### ISSUE TITLE
InvalidSessionIdError on 1.6.0

### ISSUE THREAD

**Issue by pascal-schaerli-adnovum** [Arachni/arachni#1060]
When running the scanner against [testhtml5.vulnweb.com](http://testhtml5.vulnweb.com) without any extra arguments, there was an error caused by selenium after ~12minutes.

Version:
```
Arachni 1.6.0 (ruby 2.7.5p203) [x86_64-linux]
```

OS:
```
Ubuntu 20.04.3 LTS (within docker)
```
Command:
```
./bin/arachni http://testhtml5.vulnweb.com
```

Error:
``` 
 [*] localstart.asp: Checking: http://testhtml5.vulnweb.com/login//localstart.asp
 [-] [utilities#exception_jail:428] BrowserCluster: [Selenium::WebDriver::Error::InvalidSessionIdError] invalid session id
 [-] [utilities#exception_jail:428] BrowserCluster: #0 0x55a68d0e5b33 <unknown>
 [-] [utilities#exception_jail:428] BrowserCluster: #1 0x55a68cbae56f <unknown>
 [-] [utilities#exception_jail:428] BrowserCluster: #2 0x55a68cbd739b <unknown>
 [-] [utilities#exception_jail:428] BrowserCluster: #3 0x55a68cc01fdc <unknown>
 [-] [utilities#exception_jail:428] BrowserCluster: #4 0x55a68cbffd1e <unknown>
 [-] [utilities#exception_jail:428] BrowserCluster: #5 0x55a68cbff557 <unknown>
 [-] [utilities#exception_jail:428] BrowserCluster: #6 0x55a68cb85f94 <unknown>
 [-] [utilities#exception_jail:428] BrowserCluster: #7 0x55a68cb86df0 <unknown>
 [-] [utilities#exception_jail:428] BrowserCluster: #8 0x55a68d1172fd <unknown>
 [-] [utilities#exception_jail:428] BrowserCluster: #9 0x55a68d1304bb <unknown>
 [-] [utilities#exception_jail:428] BrowserCluster: #10 0x55a68d1190d5 <unknown>
 [-] [utilities#exception_jail:428] BrowserCluster: #11 0x55a68d131145 <unknown>
 [-] [utilities#exception_jail:428] BrowserCluster: #12 0x55a68d10caaf <unknown>
 [-] [utilities#exception_jail:428] BrowserCluster: #13 0x55a68cb85b12 <unknown>
 [-] [utilities#exception_jail:428] BrowserCluster: #14 0x7f86af9400b3 <unknown>
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/response.rb:56:in `assert_ok'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/response.rb:35:in `initialize'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/selenium/webdriver/remote/typhoeus.rb:51:in `request'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/bridge.rb:588:in `execute'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/bridge.rb:194:in `close'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:192:in `close'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/browser.rb:1131:in `shutdown'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/browser_cluster/worker.rb:177:in `shutdown'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/browser_cluster.rb:308:in `block (2 levels) in shutdown'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/utilities.rb:425:in `exception_jail'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/browser_cluster.rb:308:in `block in shutdown'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/browser_cluster.rb:308:in `each'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/browser_cluster.rb:308:in `shutdown'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/framework/parts/browser.rb:73:in `shutdown_browser_cluster'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/framework/parts/state.rb:113:in `clean_up'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/framework.rb:121:in `run'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/ui/cli/framework.rb:80:in `block in run'
 [-] [utilities#exception_jail:429] BrowserCluster: 
 [-] [utilities#exception_jail:430] BrowserCluster: Parent:
 [-] [utilities#exception_jail:431] BrowserCluster: Arachni::BrowserCluster
 [-] [utilities#exception_jail:432] BrowserCluster: 
 [-] [utilities#exception_jail:433] BrowserCluster: Block:
 [-] [utilities#exception_jail:434] BrowserCluster: #<Proc:0x00007fd134175450 /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/browser_cluster.rb:308>
 [-] [utilities#exception_jail:435] BrowserCluster: 
 [-] [utilities#exception_jail:436] BrowserCluster: Caller:
 [-] [utilities#exception_jail:437] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/utilities.rb:424:in `exception_jail'
 [-] [utilities#exception_jail:437] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/browser_cluster.rb:308:in `block in shutdown'
 [-] [utilities#exception_jail:437] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/browser_cluster.rb:308:in `each'
 [-] [utilities#exception_jail:437] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/browser_cluster.rb:308:in `shutdown'
 [-] [utilities#exception_jail:437] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/framework/parts/browser.rb:73:in `shutdown_browser_cluster'
 [-] [utilities#exception_jail:437] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/framework/parts/state.rb:113:in `clean_up'
 [-] [utilities#exception_jail:437] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/framework.rb:121:in `run'
 [-] [utilities#exception_jail:437] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/ui/cli/framework.rb:80:in `block in run'
 [-] [utilities#exception_jail:438] BrowserCluster: --------------------------------------------------------------------------------
 [-] [utilities#exception_jail:428] BrowserCluster: [Selenium::WebDriver::Error::InvalidSessionIdError] invalid session id
 [-] [utilities#exception_jail:428] BrowserCluster: #0 0x55b951568b33 <unknown>
 [-] [utilities#exception_jail:428] BrowserCluster: #1 0x55b95103156f <unknown>
 [-] [utilities#exception_jail:428] BrowserCluster: #2 0x55b95105a39b <unknown>
 [-] [utilities#exception_jail:428] BrowserCluster: #3 0x55b951084fdc <unknown>
 [-] [utilities#exception_jail:428] BrowserCluster: #4 0x55b951082d1e <unknown>
 [-] [utilities#exception_jail:428] BrowserCluster: #5 0x55b951082557 <unknown>
 [-] [utilities#exception_jail:428] BrowserCluster: #6 0x55b951008f94 <unknown>
 [-] [utilities#exception_jail:428] BrowserCluster: #7 0x55b951009df0 <unknown>
 [-] [utilities#exception_jail:428] BrowserCluster: #8 0x55b95159a2fd <unknown>
 [-] [utilities#exception_jail:428] BrowserCluster: #9 0x55b9515b34bb <unknown>
 [-] [utilities#exception_jail:428] BrowserCluster: #10 0x55b95159c0d5 <unknown>
 [-] [utilities#exception_jail:428] BrowserCluster: #11 0x55b9515b4145 <unknown>
 [-] [utilities#exception_jail:428] BrowserCluster: #12 0x55b95158faaf <unknown>
 [-] [utilities#exception_jail:428] BrowserCluster: #13 0x55b951008b12 <unknown>
 [-] [utilities#exception_jail:428] BrowserCluster: #14 0x7f53ff1d80b3 <unknown>
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/response.rb:56:in `assert_ok'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/response.rb:35:in `initialize'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/selenium/webdriver/remote/typhoeus.rb:51:in `request'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/bridge.rb:588:in `execute'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/bridge.rb:194:in `close'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:192:in `close'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/browser.rb:1131:in `shutdown'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/browser_cluster/worker.rb:177:in `shutdown'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/browser_cluster.rb:308:in `block (2 levels) in shutdown'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/utilities.rb:425:in `exception_jail'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/browser_cluster.rb:308:in `block in shutdown'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/browser_cluster.rb:308:in `each'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/browser_cluster.rb:308:in `shutdown'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/framework/parts/browser.rb:73:in `shutdown_browser_cluster'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/framework/parts/state.rb:113:in `clean_up'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/framework.rb:121:in `run'
 [-] [utilities#exception_jail:428] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/ui/cli/framework.rb:80:in `block in run'
 [-] [utilities#exception_jail:429] BrowserCluster: 
 [-] [utilities#exception_jail:430] BrowserCluster: Parent:
 [-] [utilities#exception_jail:431] BrowserCluster: Arachni::BrowserCluster
 [-] [utilities#exception_jail:432] BrowserCluster: 
 [-] [utilities#exception_jail:433] BrowserCluster: Block:
 [-] [utilities#exception_jail:434] BrowserCluster: #<Proc:0x00007fd0f4063ea8 /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/browser_cluster.rb:308>
 [-] [utilities#exception_jail:435] BrowserCluster: 
 [-] [utilities#exception_jail:436] BrowserCluster: Caller:
 [-] [utilities#exception_jail:437] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/utilities.rb:424:in `exception_jail'
 [-] [utilities#exception_jail:437] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/browser_cluster.rb:308:in `block in shutdown'
 [-] [utilities#exception_jail:437] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/browser_cluster.rb:308:in `each'
 [-] [utilities#exception_jail:437] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/browser_cluster.rb:308:in `shutdown'
 [-] [utilities#exception_jail:437] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/framework/parts/browser.rb:73:in `shutdown_browser_cluster'
 [-] [utilities#exception_jail:437] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/framework/parts/state.rb:113:in `clean_up'
 [-] [utilities#exception_jail:437] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/lib/arachni/framework.rb:121:in `run'
 [-] [utilities#exception_jail:437] BrowserCluster: /home/arachniuser/arachni/.system/gems/gems/arachni-1.6.0/ui/cli/framework.rb:80:in `block in run'
 [-] [utilities#exception_jail:438] BrowserCluster: --------------------------------------------------------------------------------
```

**Comment by Zapotek** [comment]
Hello,

I haven't had much luck getting it to work inside docker, it's not a supported platform.

**Comment by Zapotek** [comment]
Ah fair enough. :)
