### ISSUE TITLE
incompatible character encodings: ASCII-8BIT and UTF-8 (Encoding::CompatibilityError)

### ISSUE THREAD

**Issue by CaosFR** [Arachni/arachni#1069]
Hi,

When I launch anachni I got this type of error. It's a fresh install on the latest Kali Linux.

```
./arachni_web
Traceback (most recent call last):
        37: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/bin/../.system/gems/bin/rackup:25:in `<main>'
        36: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/bin/../.system/gems/bin/rackup:25:in `load'
        35: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/gems/gems/rack-2.2.3/bin/rackup:5:in `<top (required)>'
        34: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/gems/gems/rack-2.2.3/lib/rack/server.rb:168:in `start'
        33: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/gems/gems/rack-2.2.3/lib/rack/server.rb:311:in `start'
        32: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/gems/gems/rack-2.2.3/lib/rack/server.rb:379:in `handle_profiling'
        31: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/gems/gems/rack-2.2.3/lib/rack/server.rb:312:in `block in start'
        30: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/gems/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
        29: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/gems/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
        28: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/gems/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
        27: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/gems/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
        26: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/gems/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
        25: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/gems/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
        24: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/gems/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
        23: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/arachni-ui-web/config.ru:3:in `block in <main>'
        22: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        21: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        20: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/arachni-ui-web/config/environment.rb:13:in `<top (required)>'
        19: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        18: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        17: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/arachni-ui-web/config/application.rb:9:in `<top (required)>'
        16: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        15: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        14: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/arachni-ui-web/config/boot.rb:3:in `<top (required)>'
        13: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        12: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        11: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/bundler/setup.rb:10:in `<top (required)>'
        10: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/bundler/ui/shell.rb:88:in `silence'
         9: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/bundler/ui/shell.rb:136:in `with_level'
         8: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/bundler/setup.rb:10:in `block in <top (required)>'
         7: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/bundler.rb:151:in `setup'
         6: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:16:in `setup'
         5: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/bundler/shared_helpers.rb:318:in `clean_load_path'
         4: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/bundler/shared_helpers.rb:318:in `reject!'
         3: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/bundler/shared_helpers.rb:320:in `block in clean_load_path'
         2: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/bundler/shared_helpers.rb:320:in `any?'
         1: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/bundler/shared_helpers.rb:320:in `block (2 levels) in clean_load_path'
/home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/bundler/shared_helpers.rb:320:in `start_with?': incompatible character encodings: ASCII-8BIT and UTF-8 (Encoding::CompatibilityError)
```
OR

```
./arachni    
Traceback (most recent call last):
        14: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/bin/../.system/arachni-ui-web/bin/arachni:27:in `<main>'
        13: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        12: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        11: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/bundler/setup.rb:10:in `<top (required)>'
        10: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/bundler/ui/shell.rb:88:in `silence'
         9: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/bundler/ui/shell.rb:136:in `with_level'
         8: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/bundler/setup.rb:10:in `block in <top (required)>'
         7: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/bundler.rb:151:in `setup'
         6: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:16:in `setup'
         5: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/bundler/shared_helpers.rb:318:in `clean_load_path'
         4: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/bundler/shared_helpers.rb:318:in `reject!'
         3: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/bundler/shared_helpers.rb:320:in `block in clean_load_path'
         2: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/bundler/shared_helpers.rb:320:in `any?'
         1: from /home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/bundler/shared_helpers.rb:320:in `block (2 levels) in clean_load_path'
/home/user1/Téléchargements/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/bundler/shared_helpers.rb:320:in `start_with?': incompatible character encodings: ASCII-8BIT and UTF-8 (Encoding::CompatibilityError)
```

I find a old issue about this problem but it's was solved in previous versions.

**Comment by Zapotek** [comment]
Can you please try running it from a directory without special characters in its path?
This doesn't look like a bug in Arachni.

**Comment by CaosFR** [comment]
Thanks it's that. Sorry for the delay.
