### ISSUE TITLE
Segmentation fault upon launch on vanilla 22.04 LTS

### ISSUE THREAD

**Issue by brettbryantgmail** [Arachni/arachni#1070]
I know the reigning advice is to update libc >= 2.31, however this is running the following:

> libc-bin/jammy,now 2.35-0ubuntu3 amd64 [installed,automatic]
> libc6/jammy,now 2.35-0ubuntu3 amd64 [installed,automatic]

Below is the segmentation fault:
> /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/ffi-1.15.5/lib/ffi/library.rb:265: [BUG] Illegal instruction at 0x00007f7ab6b3b3c0
> ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-linux]
> 
> -- Control frame information -----------------------------------------------
> c:0029 p:---- s:0133 e:000132 CFUNC  :initialize
> c:0028 p:---- s:0130 e:000129 CFUNC  :initialize
> c:0027 p:---- s:0127 e:000126 CFUNC  :new
> c:0026 p:0128 s:0119 e:000117 BLOCK  /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/ffi-1.15.5/lib/ffi/library.rb:265 [FINISH]
> c:0025 p:---- s:0113 e:000112 CFUNC  :each
> c:0024 p:0197 s:0109 e:000108 METHOD /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/ffi-1.15.5/lib/ffi/library.rb:252
> c:0023 p:0043 s:0089 e:000088 CLASS  /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/ethon-0.15.0/lib/ethon/libc.rb:17
> c:0022 p:0007 s:0086 e:000085 CLASS  /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/ethon-0.15.0/lib/ethon/libc.rb:7
> c:0021 p:0007 s:0083 e:000082 TOP    /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/ethon-0.15.0/lib/ethon/libc.rb:2 [FINISH]
> c:0020 p:---- s:0080 e:000079 CFUNC  :require
> c:0019 p:0036 s:0075 e:000074 TOP    /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/ethon-0.15.0/lib/ethon.rb:15 [FINISH]
> c:0018 p:---- s:0072 e:000071 CFUNC  :require
> c:0017 p:0011 s:0067 e:000066 TOP    /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/typhoeus-1.3.0/lib/typhoeus.rb:2 [FINISH]
> c:0016 p:---- s:0064 e:000063 CFUNC  :require
> c:0015 p:0005 s:0059 e:000058 TOP    /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/arachni-1.6.1/lib/arachni/http/client.rb:9 [FINISH]
> c:0014 p:---- s:0056 e:000055 CFUNC  :require_relative
> c:0013 p:0005 s:0051 e:000050 TOP    /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/arachni-1.6.1/lib/arachni/http.rb:9 [FINISH]
> c:0012 p:---- s:0048 e:000047 CFUNC  :require
> c:0011 p:0114 s:0043 e:000042 CLASS  /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/arachni-1.6.1/lib/arachni/framework.rb:29
> c:0010 p:0031 s:0039 e:000038 TOP    /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/arachni-1.6.1/lib/arachni/framework.rb:17 [FINISH]
> c:0009 p:---- s:0036 e:000035 CFUNC  :require_relative
> c:0008 p:0104 s:0031 e:000030 TOP    /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/arachni-1.6.1/lib/arachni.rb:97 [FINISH]
> c:0007 p:---- s:0028 e:000027 CFUNC  :require_relative
> c:0006 p:0005 s:0023 e:000022 TOP    /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/arachni-1.6.1/ui/cli/framework.rb:9 [FINISH]
> c:0005 p:---- s:0020 e:000019 CFUNC  :require_relative
> c:0004 p:0005 s:0015 e:000014 TOP    /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/arachni-1.6.1/bin/arachni:10 [FINISH]
> c:0003 p:---- s:0012 e:000011 CFUNC  :load
> c:0002 p:0157 s:0007 E:001718 EVAL   /home/user/Downloads/arachni-1.6.1-0.6.1/bin/../.system/arachni-ui-web/bin/arachni:29 [FINISH]
> c:0001 p:0000 s:0003 E:002240 (none) [FINISH]
> 
> -- Ruby level backtrace information ----------------------------------------
> /home/user/Downloads/arachni-1.6.1-0.6.1/bin/../.system/arachni-ui-web/bin/arachni:29:in `<main>'
> /home/user/Downloads/arachni-1.6.1-0.6.1/bin/../.system/arachni-ui-web/bin/arachni:29:in `load'
> /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/arachni-1.6.1/bin/arachni:10:in `<top (required)>'
> /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/arachni-1.6.1/bin/arachni:10:in `require_relative'
> /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/arachni-1.6.1/ui/cli/framework.rb:9:in `<top (required)>'
> /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/arachni-1.6.1/ui/cli/framework.rb:9:in `require_relative'
> /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/arachni-1.6.1/lib/arachni.rb:97:in `<top (required)>'
> /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/arachni-1.6.1/lib/arachni.rb:97:in `require_relative'
> /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/arachni-1.6.1/lib/arachni/framework.rb:17:in `<top (required)>'
> /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/arachni-1.6.1/lib/arachni/framework.rb:29:in `<module:Arachni>'
> /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/arachni-1.6.1/lib/arachni/framework.rb:29:in `require'
> /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/arachni-1.6.1/lib/arachni/http.rb:9:in `<top (required)>'
> /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/arachni-1.6.1/lib/arachni/http.rb:9:in `require_relative'
> /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/arachni-1.6.1/lib/arachni/http/client.rb:9:in `<top (required)>'
> /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/arachni-1.6.1/lib/arachni/http/client.rb:9:in `require'
> /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/typhoeus-1.3.0/lib/typhoeus.rb:2:in `<top (required)>'
> /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/typhoeus-1.3.0/lib/typhoeus.rb:2:in `require'
> /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/ethon-0.15.0/lib/ethon.rb:15:in `<top (required)>'
> /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/ethon-0.15.0/lib/ethon.rb:15:in `require'
> /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/ethon-0.15.0/lib/ethon/libc.rb:2:in `<top (required)>'
> /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/ethon-0.15.0/lib/ethon/libc.rb:7:in `<module:Ethon>'
> /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/ethon-0.15.0/lib/ethon/libc.rb:17:in `<module:Libc>'
> /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/ffi-1.15.5/lib/ffi/library.rb:252:in `attach_function'
> /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/ffi-1.15.5/lib/ffi/library.rb:252:in `each'
> /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/ffi-1.15.5/lib/ffi/library.rb:265:in `block in attach_function'
> /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/ffi-1.15.5/lib/ffi/library.rb:265:in `new'
> /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/ffi-1.15.5/lib/ffi/library.rb:265:in `initialize'
> /home/user/Downloads/arachni-1.6.1-0.6.1/.system/gems/gems/ffi-1.15.5/lib/ffi/library.rb:265:in `initialize'

[Full logs attached here: arachni_output.txt](https://github.com/Arachni/arachni/files/8567765/arachni_output.txt)

**Comment by Zapotek** [comment]
Can you update glibc anyways? There's a chance an update happened on the build machine as well, I may need to update the docs.

**Comment by brettbryantgmail** [comment]
To what? There’s nothing more in the package manager. Do you have a version in mind I need to update to?

**Comment by Zapotek** [comment]
My bad, I was preoccupied and didn't pay close attention.
I can't think of anything right now that could be causing this, does look like glibc but could be the other way around, too high a version?
I'll check for that and get back to you.

**Comment by afonsofsgomes** [comment]
@Zapotek I think the main problem is `ffi lib`. Check my post: #1071

**Comment by Zapotek** [comment]
@afonsofsgomes @brettbryantgmail can you please check your libffi-dev version?

    apt-cache policy libffi-dev

I'm on 3.4.2 and everything is working fine.

**Comment by brettbryantgmail** [comment]
>libffi-dev:
>  Installed: (none)
>  Candidate: 3.4.2-4
>  Version table:
>     3.4.2-4 500
>        500 http://us.archive.ubuntu.com/ubuntu jammy/main amd64 Packages

This issue should be easily reproducible in a VM with a fresh install of Ubuntu 22.04 for you to work with.

**Comment by Zapotek** [comment]
Tried that, no problem at all, it worked fine.

**Comment by lukyanovanastya** [comment]
got the same issue on VM with Ubuntu 22.04 and glibc 2.35
