### ISSUE TITLE
BUG ,can't running!

### ISSUE THREAD

**Issue by smarttang** [Arachni/arachni#1075]
```
2022-05-22 08:17:59 +0000 --------------------------------------------------------------------------------
ENV:
---
HOSTNAME: b9d6aab9167e
MY_RUBY_HOME: "/arachni/bin/../.system/usr/lib/ruby"
RUBY_VERSION: ruby-2.7.5
PWD: "/"
HOST_PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
HOME: "/arachni/bin/../.system/home/arachni"
LANG: C.UTF-8
GEM_PATH: "/arachni/bin/../.system/gems"
GEM_HOME: "/arachni/.system/gems"
TERM: xterm
CPLUS_INCLUDE_PATH: "/arachni/bin/../.system/usr/include"
LIBRARY_PATH: "/arachni/bin/../.system/usr/lib:/usr/lib:/usr/local/lib"
SHLVL: '0'
ARACHNI_FRAMEWORK_LOGDIR: "/arachni/bin/../.system/../logs/framework"
LD_LIBRARY_PATH: "/arachni/bin/../.system/usr/lib:/usr/lib:/usr/local/lib"
ARACHNI_WEBUI_LOGDIR: "/arachni/bin/../.system/../logs/webui"
PATH: "/arachni/.system/gems/bin:/arachni/bin/../.system/../bin:/arachni/bin/../.system/usr/bin:/arachni/bin/../.system/gems/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
RAILS_ENV: production
C_INCLUDE_PATH: "/arachni/bin/../.system/usr/include"
IRBRC: "/arachni/bin/../.system/usr/lib/ruby/.irbrc"
RUBYLIB: "/arachni/.system/usr/lib/ruby/site_ruby/2.7.0:/arachni/bin/../.system/usr/lib/ruby:/arachni/bin/../.system/usr/lib/ruby/site_ruby/2.7.0:/arachni/bin/../.system/usr/lib/ruby/2.7.0:/arachni/bin/../.system/usr/lib/ruby/2.7.0/x86_64-linux:/arachni/bin/../.system/usr/lib/ruby/site_ruby/2.7.0/x86_64-linux"
RACK_ENV: development
BUNDLE_GEMFILE: "/arachni/.system/arachni-ui-web/Gemfile"
BUNDLER_ORIG_BUNDLE_BIN_PATH: BUNDLER_ENVIRONMENT_PRESERVER_INTENTIONALLY_NIL
BUNDLER_ORIG_BUNDLE_GEMFILE: "/arachni/.system/arachni-ui-web/Gemfile"
BUNDLER_ORIG_BUNDLER_VERSION: BUNDLER_ENVIRONMENT_PRESERVER_INTENTIONALLY_NIL
BUNDLER_ORIG_GEM_HOME: "/arachni/bin/../.system/gems"
BUNDLER_ORIG_GEM_PATH: "/arachni/bin/../.system/gems"
BUNDLER_ORIG_MANPATH: BUNDLER_ENVIRONMENT_PRESERVER_INTENTIONALLY_NIL
BUNDLER_ORIG_PATH: "/arachni/bin/../.system/../bin:/arachni/bin/../.system/usr/bin:/arachni/bin/../.system/gems/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
BUNDLER_ORIG_RB_USER_INSTALL: BUNDLER_ENVIRONMENT_PRESERVER_INTENTIONALLY_NIL
BUNDLER_ORIG_RUBYLIB: "/arachni/bin/../.system/usr/lib/ruby:/arachni/bin/../.system/usr/lib/ruby/site_ruby/2.7.0:/arachni/bin/../.system/usr/lib/ruby/2.7.0:/arachni/bin/../.system/usr/lib/ruby/2.7.0/x86_64-linux:/arachni/bin/../.system/usr/lib/ruby/site_ruby/2.7.0/x86_64-linux"
BUNDLER_ORIG_RUBYOPT: BUNDLER_ENVIRONMENT_PRESERVER_INTENTIONALLY_NIL
BUNDLE_BIN_PATH: "/arachni/.system/gems/gems/bundler-2.3.13/exe/bundle"
BUNDLER_VERSION: 2.3.13
RUBYOPT: "-r/arachni/.system/usr/lib/ruby/site_ruby/2.7.0/bundler/setup"
MANPATH: "/arachni/.system/gems/gems/kramdown-2.4.0/man"
arachni_options: BAh7FzoIcnBjewg6EnNlcnZlcl9zb2NrZXQwOhBzZXJ2ZXJfcG9ydGkCdHw6E3NlcnZlcl9hZGRyZXNzSSIOMTI3LjAuMC4xBjoGRVQ6CmlucHV0ewk6C3ZhbHVlc3sAOhNkZWZhdWx0X3ZhbHVlc3sPSSIJbmFtZQY7CUZJIhFhcmFjaG5pX25hbWUGOwlUSSIJdXNlcgY7CUZJIhFhcmFjaG5pX3VzZXIGOwlUSSIIdXNyBjsJRkkiEWFyYWNobmlfdXNlcgY7CVRJIglwYXNzBjsJRkkiGTU1NDMhJWFyYWNobmlfc2VjcmV0BjsJVEkiCHR4dAY7CUZJIhFhcmFjaG5pX3RleHQGOwlUSSIIbnVtBjsJRkkiCDEzMgY7CVRJIgthbW91bnQGOwlGSSIIMTAwBjsJVEkiCW1haWwGOwlGSSIVYXJhY2huaUBlbWFpbC5ncgY7CVRJIgxhY2NvdW50BjsJRkkiBzEyBjsJVEkiB2lkBjsJRkkiBjEGOwlUOhV3aXRob3V0X2RlZmF1bHRzRjoKZm9yY2VGOg9kaXNwYXRjaGVyewg6F25vZGVfcGluZ19pbnRlcnZhbGYINmUxOhhpbnN0YW5jZV9wb3J0X3JhbmdlWwdpAgEEaQL//zoOcG9vbF9zaXplaQo6DmRhdGFzdG9yZXsAOg1zbmFwc2hvdHsGOg5zYXZlX3BhdGgwOgphdWRpdHsJOhVwYXJhbWV0ZXJfdmFsdWVzVDocZXhjbHVkZV92ZWN0b3JfcGF0dGVybnNbADocaW5jbHVkZV92ZWN0b3JfcGF0dGVybnNbADoTbGlua190ZW1wbGF0ZXNbADoLb3V0cHV0ewA6FGJyb3dzZXJfY2x1c3RlcnsPOhJsb2NhbF9zdG9yYWdlewA6FHNlc3Npb25fc3RvcmFnZXsAOhZ3YWl0X2Zvcl9lbGVtZW50c3sAOhR3YWl0X2Zvcl90aW1lcnNGOxJpCToQam9iX3RpbWVvdXRpQToYd29ya2VyX3RpbWVfdG9fbGl2ZWkB+joSaWdub3JlX2ltYWdlc0Y6EXNjcmVlbl93aWR0aGkCQAY6EnNjcmVlbl9oZWlnaHRpArAEOgxzZXNzaW9uewA6CWh0dHB7DjoPdXNlcl9hZ2VudEkiKU1vemlsbGEvNS4wIChHZWNrbykgQXJhY2huaS92MS42LjEuMQY7CVQ6FHJlcXVlc3RfdGltZW91dGkCIE46G3JlcXVlc3RfcmVkaXJlY3RfbGltaXRpCjoYcmVxdWVzdF9jb25jdXJyZW5jeWkPOhdyZXF1ZXN0X3F1ZXVlX3NpemVpNzoUcmVxdWVzdF9oZWFkZXJzewA6FnJlc3BvbnNlX21heF9zaXplaQMgoQc6DGNvb2tpZXN7ADoYYXV0aGVudGljYXRpb25fdHlwZUkiCWF1dG8GOwlUOgpzY29wZXsQOhpkaXJlY3RvcnlfZGVwdGhfbGltaXRpDzoZYXV0b19yZWR1bmRhbnRfcGF0aHNpFDoccmVkdW5kYW50X3BhdGhfcGF0dGVybnN7ADoUZG9tX2RlcHRoX2xpbWl0aQk6HGV4Y2x1ZGVfZmlsZV9leHRlbnNpb25zbzoIU2V0BjoKQGhhc2h9U0kiCGdpZgY7CVRUSSIIYm1wBjsJVFRJIgh0aWYGOwlUVEkiCXRpZmYGOwlUVEkiCGpwZwY7CVRUSSIJanBlZwY7CVRUSSIIanBlBjsJVFRJIgpwanBlZwY7CVRUSSIIcG5nBjsJVFRJIghpY28GOwlUVEkiCHBzZAY7CVRUSSIIeGNmBjsJVFRJIggzZG0GOwlUVEkiCG1heAY7CVRUSSIIc3ZnBjsJVFRJIghlcHMGOwlUVEkiCGRydwY7CVRUSSIHYWkGOwlUVEkiCGFzZgY7CVRUSSIHcm0GOwlUVEkiCG1wZwY7CVRUSSIJbXBlZwY7CVRUSSIIbXBlBjsJVFRJIggzZ3AGOwlUVEkiCDNnMgY7CVRUSSIIYXZpBjsJVFRJIghmbHYGOwlUVEkiCG1vdgY7CVRUSSIIbXA0BjsJVFRJIghzd2YGOwlUVEkiCHZvYgY7CVRUSSIId212BjsJVFRJIghhaWYGOwlUVEkiCG1wMwY7CVRUSSIIbXBhBjsJVFRJIgdyYQY7CVRUSSIId2F2BjsJVFRJIgh3bWEGOwlUVEkiCG1pZAY7CVRUSSIIbTRhBjsJVFRJIghvZ2cGOwlUVEkiCWZsYWMGOwlUVEkiCHppcAY7CVRUSSIJemlweAY7CVRUSSIIdGFyBjsJVFRJIgdnegY7CVRUSSIHN3oGOwlUVEkiCHJhcgY7CVRUSSIIYnoyBjsJVFRJIghiaW4GOwlUVEkiCGN1ZQY7CVRUSSIIZG1nBjsJVFRJIghpc28GOwlUVEkiCG1kZgY7CVRUSSIIdmNkBjsJVFRJIghyYXcGOwlUVEkiCGV4ZQY7CVRUSSIIYXBrBjsJVFRJIghhcHAGOwlUVEkiCGphcgY7CVRUSSIIcGtnBjsJVFRJIghkZWIGOwlUVEkiCHJwbQY7CVRUSSIIbXNpBjsJVFRJIgh0dGYGOwlUVEkiCG90ZgY7CVRUSSIJd29mZgY7CVRUSSIKd29mZjIGOwlUVEkiCGZvbgY7CVRUSSIIZm50BjsJVFRJIghjc3MGOwlUVEkiB2pzBjsJVFRJIghwZGYGOwlUVEkiCWRvY3gGOwlUVEkiCXhsc3gGOwlUVEkiCXBwdHgGOwlUVEkiCG9kdAY7CVRUSSIIb2RwBjsJVFRGOhpleGNsdWRlX3BhdGhfcGF0dGVybnNbADodZXhjbHVkZV9jb250ZW50X3BhdHRlcm5zWwA6GmluY2x1ZGVfcGF0aF9wYXR0ZXJuc1sAOhNyZXN0cmljdF9wYXRoc1sAOhFleHRlbmRfcGF0aHNbADoRdXJsX3Jld3JpdGVzewA6C2NoZWNrc1sAOg5wbGF0Zm9ybXNbADoMcGx1Z2luc3sAOgtzcGF3bnMwOhZub19maW5nZXJwcmludGluZ0Y6EmF1dGhvcml6ZWRfYnkwOgpwYXRoc3sVOglyb290SSIwL2FyYWNobmkvLnN5c3RlbS9nZW1zL2dlbXMvYXJhY2huaS0xLjYuMS4xLwY7CUY6CGdmeEkiNC9hcmFjaG5pLy5zeXN0ZW0vZ2Vtcy9nZW1zL2FyYWNobmktMS42LjEuMS9nZngvBjsJRjoPY29tcG9uZW50c0kiOy9hcmFjaG5pLy5zeXN0ZW0vZ2Vtcy9nZW1zL2FyYWNobmktMS42LjEuMS9jb21wb25lbnRzLwY7CUY6DnNuYXBzaG90c0kiOi9hcmFjaG5pLy5zeXN0ZW0vZ2Vtcy9nZW1zL2FyYWNobmktMS42LjEuMS9zbmFwc2hvdHMvBjsJRjoJbG9nc0kiLy9hcmFjaG5pL2Jpbi8uLi8uc3lzdGVtLy4uL2xvZ3MvZnJhbWV3b3JrLwY7CVQ7P0kiQi9hcmFjaG5pLy5zeXN0ZW0vZ2Vtcy9nZW1zL2FyYWNobmktMS42LjEuMS9jb21wb25lbnRzL2NoZWNrcy8GOwlGOg5yZXBvcnRlcnNJIkUvYXJhY2huaS8uc3lzdGVtL2dlbXMvZ2Vtcy9hcmFjaG5pLTEuNi4xLjEvY29tcG9uZW50cy9yZXBvcnRlcnMvBjsJRjtBSSJDL2FyYWNobmkvLnN5c3RlbS9nZW1zL2dlbXMvYXJhY2huaS0xLjYuMS4xL2NvbXBvbmVudHMvcGx1Z2lucy8GOwlGOg1zZXJ2aWNlc0kiRC9hcmFjaG5pLy5zeXN0ZW0vZ2Vtcy9nZW1zL2FyYWNobmktMS42LjEuMS9jb21wb25lbnRzL3NlcnZpY2VzLwY7CUY6FHBhdGhfZXh0cmFjdG9yc0kiSy9hcmFjaG5pLy5zeXN0ZW0vZ2Vtcy9nZW1zL2FyYWNobmktMS42LjEuMS9jb21wb25lbnRzL3BhdGhfZXh0cmFjdG9ycy8GOwlGOhNmaW5nZXJwcmludGVyc0kiSi9hcmFjaG5pLy5zeXN0ZW0vZ2Vtcy9nZW1zL2FyYWNobmktMS42LjEuMS9jb21wb25lbnRzL2ZpbmdlcnByaW50ZXJzLwY7CUY6CGxpYkkiPC9hcmFjaG5pLy5zeXN0ZW0vZ2Vtcy9nZW1zL2FyYWNobmktMS42LjEuMS9saWIvYXJhY2huaS8GOwlGOhBleGVjdXRhYmxlc0kiUi9hcmFjaG5pLy5zeXN0ZW0vZ2Vtcy9nZW1zL2FyYWNobmktMS42LjEuMS9saWIvYXJhY2huaS9wcm9jZXNzZXMvZXhlY3V0YWJsZXMvBjsJRjoMc3VwcG9ydEkiRC9hcmFjaG5pLy5zeXN0ZW0vZ2Vtcy9nZW1zL2FyYWNobmktMS42LjEuMS9saWIvYXJhY2huaS9zdXBwb3J0LwY7CUY6C21peGluc0kiSy9hcmFjaG5pLy5zeXN0ZW0vZ2Vtcy9nZW1zL2FyYWNobmktMS42LjEuMS9saWIvYXJhY2huaS9zdXBwb3J0L21peGlucy8GOwlGOgxhcmFjaG5pSSI7L2FyYWNobmkvLnN5c3RlbS9nZW1zL2dlbXMvYXJhY2huaS0xLjYuMS4xL2xpYi9hcmFjaG5pBjsJRg==
--------------------------------------------------------------------------------
OPTIONS:
---
input:
  values:
    name: arachni_name
    user: arachni_user
    usr: arachni_user
    pass: 5543!%arachni_secret
    txt: arachni_text
    num: '132'
    amount: '100'
    mail: arachni@email.gr
    account: '12'
    id: '1'
  default_values:
    name: arachni_name
    user: arachni_user
    usr: arachni_user
    pass: 5543!%arachni_secret
    txt: arachni_text
    num: '132'
    amount: '100'
    mail: arachni@email.gr
    account: '12'
    id: '1'
  without_defaults: true
  force: false
datastore:
  token: 2b004eacfdeb2f7af5e77530c2841d46
audit:
  parameter_values: true
  exclude_vector_patterns: []
  include_vector_patterns: []
  link_templates: []
  links: true
  forms: true
  cookies: true
  jsons: true
  xmls: true
  ui_forms: true
  ui_inputs: true
  nested_cookies: true
browser_cluster:
  local_storage: {}
  session_storage: {}
  wait_for_elements: {}
  wait_for_timers: false
  pool_size: 4
  job_timeout: 60
  worker_time_to_live: 250
  ignore_images: false
  screen_width: 1600
  screen_height: 1200
session: {}
http:
  user_agent: Mozilla/5.0 (Gecko) Arachni/v1.6.1.1
  request_timeout: 20000
  request_redirect_limit: 5
  request_concurrency: 10
  request_queue_size: 50
  request_headers: {}
  response_max_size: 500000
  cookies: {}
  authentication_type: auto
scope:
  directory_depth_limit: 10
  auto_redundant_paths: 15
  redundant_path_patterns: {}
  dom_depth_limit: 4
  exclude_file_extensions:
  - gif
  - bmp
  - tif
  - tiff
  - jpg
  - jpeg
  - jpe
  - pjpeg
  - png
  - ico
  - psd
  - xcf
  - 3dm
  - max
  - svg
  - eps
  - drw
  - ai
  - asf
  - rm
  - mpg
  - mpeg
  - mpe
  - 3gp
  - 3g2
  - avi
  - flv
  - mov
  - mp4
  - swf
  - vob
  - wmv
  - aif
  - mp3
  - mpa
  - ra
  - wav
  - wma
  - mid
  - m4a
  - ogg
  - flac
  - zip
  - zipx
  - tar
  - gz
  - 7z
  - rar
  - bz2
  - bin
  - cue
  - dmg
  - iso
  - mdf
  - vcd
  - raw
  - exe
  - apk
  - app
  - jar
  - pkg
  - deb
  - rpm
  - msi
  - ttf
  - otf
  - woff
  - woff2
  - fon
  - fnt
  - css
  - js
  - pdf
  - docx
  - xlsx
  - pptx
  - odt
  - odp
  exclude_path_patterns: []
  exclude_content_patterns: []
  include_path_patterns: []
  restrict_paths: []
  extend_paths: []
  url_rewrites: {}
checks:
- allowed_methods
- backdoors
- backup_directories
- backup_files
- captcha
- code_injection
- code_injection_php_input_wrapper
- code_injection_timing
- common_admin_interfaces
- common_directories
- common_files
- cookie_set_for_parent_domain
- credit_card
- csrf
- cvs_svn_users
- directory_listing
- emails
- file_inclusion
- form_upload
- hsts
- htaccess_limit
- html_objects
- http_only_cookies
- http_put
- insecure_client_access_policy
- insecure_cookies
- insecure_cors_policy
- insecure_cross_domain_policy_access
- insecure_cross_domain_policy_headers
- interesting_responses
- ldap_injection
- localstart_asp
- mixed_resource
- no_sql_injection
- no_sql_injection_differential
- origin_spoof_access_restriction_bypass
- os_cmd_injection
- os_cmd_injection_timing
- password_autocomplete
- path_traversal
- private_ip
- response_splitting
- rfi
- session_fixation
- source_code_disclosure
- sql_injection
- sql_injection_differential
- sql_injection_timing
- ssn
- trainer
- unencrypted_password_forms
- unvalidated_redirect
- unvalidated_redirect_dom
- webdav
- x_frame_options
- xpath_injection
- xss
- xss_dom
- xss_dom_script_context
- xss_event
- xss_path
- xss_script_context
- xss_tag
- xst
- xxe
platforms: []
plugins:
  autothrottle: {}
  discovery: {}
  healthmap: {}
  timing_attacks: {}
  uniformity: {}
no_fingerprinting: false
authorized_by: 
url: http://testhtml5.vulnweb.com/
--------------------------------------------------------------------------------
[2022-05-22 08:17:59 +0000] Please ensure that chromedriver and Chrome are the same version and in your PATH.
[2022-05-22 08:17:59 +0000] [Selenium::WebDriver::Error::WebDriverError] unable to connect to /arachni/bin/../.system/usr/bin/chromedriver 127.0.0.1:9515
[2022-05-22 08:17:59 +0000] /arachni/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/service_manager.rb:139:in `connect_until_stable'
[2022-05-22 08:17:59 +0000] /arachni/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/service_manager.rb:57:in `block in start'
[2022-05-22 08:17:59 +0000] /arachni/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/socket_lock.rb:41:in `locked'
[2022-05-22 08:17:59 +0000] /arachni/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/service_manager.rb:54:in `start'
[2022-05-22 08:17:59 +0000] /arachni/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/service.rb:84:in `launch'
[2022-05-22 08:17:59 +0000] /arachni/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:374:in `service_url'
[2022-05-22 08:17:59 +0000] /arachni/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:311:in `create_bridge'
[2022-05-22 08:17:59 +0000] /arachni/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:74:in `initialize'
[2022-05-22 08:17:59 +0000] /arachni/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:47:in `new'
[2022-05-22 08:17:59 +0000] /arachni/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:47:in `for'
[2022-05-22 08:17:59 +0000] /arachni/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver.rb:88:in `for'
[2022-05-22 08:17:59 +0000] /arachni/.system/gems/gems/arachni-1.6.1.1/lib/arachni/browser.rb:1100:in `selenium'
[2022-05-22 08:17:59 +0000] /arachni/.system/gems/gems/arachni-1.6.1.1/lib/arachni/browser.rb:1274:in `start_webdriver'
[2022-05-22 08:17:59 +0000] /arachni/.system/gems/gems/arachni-1.6.1.1/lib/arachni/browser.rb:192:in `initialize'
[2022-05-22 08:17:59 +0000] /arachni/.system/gems/gems/arachni-1.6.1.1/lib/arachni/browser_cluster/worker.rb:51:in `initialize'
[2022-05-22 08:17:59 +0000] /arachni/.system/gems/gems/arachni-1.6.1.1/lib/arachni/browser_cluster.rb:495:in `new'
[2022-05-22 08:17:59 +0000] /arachni/.system/gems/gems/arachni-1.6.1.1/lib/arachni/browser_cluster.rb:495:in `block in initialize_workers'
[2022-05-22 08:17:59 +0000] /arachni/.system/gems/gems/arachni-1.6.1.1/lib/arachni/browser_cluster.rb:494:in `times'
[2022-05-22 08:17:59 +0000] /arachni/.system/gems/gems/arachni-1.6.1.1/lib/arachni/browser_cluster.rb:494:in `initialize_workers'
[2022-05-22 08:17:59 +0000] /arachni/.system/gems/gems/arachni-1.6.1.1/lib/arachni/browser_cluster.rb:112:in `initialize'
[2022-05-22 08:17:59 +0000] /arachni/.system/gems/gems/arachni-1.6.1.1/lib/arachni/framework/parts/browser.rb:33:in `new'
[2022-05-22 08:17:59 +0000] /arachni/.system/gems/gems/arachni-1.6.1.1/lib/arachni/framework/parts/browser.rb:33:in `block in browser_cluster'
[2022-05-22 08:17:59 +0000] /arachni/.system/usr/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
[2022-05-22 08:17:59 +0000] /arachni/.system/usr/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
[2022-05-22 08:17:59 +0000] /arachni/.system/gems/gems/arachni-1.6.1.1/lib/arachni/framework/parts/browser.rb:28:in `browser_cluster'
[2022-05-22 08:17:59 +0000] /arachni/.system/gems/gems/arachni-1.6.1.1/lib/arachni/framework/parts/audit.rb:173:in `audit'
[2022-05-22 08:17:59 +0000] /arachni/.system/gems/gems/arachni-1.6.1.1/lib/arachni/framework.rb:117:in `block in run'
[2022-05-22 08:17:59 +0000] /arachni/.system/gems/gems/arachni-1.6.1.1/lib/arachni/utilities.rb:425:in `exception_jail'
[2022-05-22 08:17:59 +0000] /arachni/.system/gems/gems/arachni-1.6.1.1/lib/arachni/framework.rb:117:in `run'
[2022-05-22 08:17:59 +0000] /arachni/.system/gems/gems/arachni-1.6.1.1/lib/arachni/rpc/server/framework.rb:156:in `block in run'
[2022-05-22 08:17:59 +0000] 
[2022-05-22 08:17:59 +0000] Parent:
[2022-05-22 08:17:59 +0000] Arachni::RPC::Server::Framework
[2022-05-22 08:17:59 +0000] 
[2022-05-22 08:17:59 +0000] Block:
[2022-05-22 08:17:59 +0000] #<Proc:0x00007f593c053da8 /arachni/.system/gems/gems/arachni-1.6.1.1/lib/arachni/framework.rb:117>
[2022-05-22 08:17:59 +0000] 
[2022-05-22 08:17:59 +0000] Caller:
[2022-05-22 08:17:59 +0000] /arachni/.system/gems/gems/arachni-1.6.1.1/lib/arachni/utilities.rb:424:in `exception_jail'
[2022-05-22 08:17:59 +0000] /arachni/.system/gems/gems/arachni-1.6.1.1/lib/arachni/framework.rb:117:in `run'
[2022-05-22 08:17:59 +0000] /arachni/.system/gems/gems/arachni-1.6.1.1/lib/arachni/rpc/server/framework.rb:156:in `block in run'
[2022-05-22 08:17:59 +0000] --------------------------------------------------------------------------------
```

**Comment by Zapotek** [comment]
Can you please try running Arachni under your user's home dir and as a regular user?
The way you're running Arachni now could yield unpredictable results by chromedriver and Chrome.

**Comment by nextstage-brasil** [comment]
i have same problem here..

DevTools listening on ws://127.0.0.1:54667/devtools/browser/d8c3908c-4196-459c-9dc9-3f78e0bf0f9c
[0526/101107.900:ERROR:command_buffer_proxy_impl.cc(125)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
I, [2022-05-26T10:11:08.015144 #1000]  INFO -- Call: service.native_progress [127.0.0.1]

**Comment by Fellipe-A** [comment]
I'm with a similar problem, even running under home dir as a regular user.

```
[2022-05-31 00:04:08 -0300] [Timeout::Error] Request timed out: post http://127.0.0.1:9515/session
{"capabilities":{"alwaysMatch":{"browserName":"chrome","goog:chromeOptions":{"args":["--allow-running-insecure-content","--disable-web-security","--reduce-security-for-testing","--ignore-certificate-errors","--no-sandbox","--disable-plugins","--user-data-dir=/tmp/Arachni_Chrome_52880/","--proxy-server=127.0.0.1:19762","--buid=46464646","--headless"],"mobileEmulation":{"userAgent":"Mozilla/5.0 (Gecko) Arachni/v1.6.1.1"}}}}}
[2022-05-31 00:04:08 -0300] /home/infra/arachni-1.6.1.1-0.6.1.1/.system/gems/gems/arachni-1.6.1.1/lib/arachni/selenium/webdriver/remote/typhoeus.rb:48:in `request'
[2022-05-31 00:04:08 -0300] /home/infra/arachni-1.6.1.1-0.6.1.1/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
[2022-05-31 00:04:08 -0300] /home/infra/arachni-1.6.1.1-0.6.1.1/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/bridge.rb:588:in `execute'
[2022-05-31 00:04:08 -0300] /home/infra/arachni-1.6.1.1-0.6.1.1/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/bridge.rb:52:in `create_session'
[2022-05-31 00:04:08 -0300] /home/infra/arachni-1.6.1.1-0.6.1.1/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:340:in `create_bridge'
[2022-05-31 00:04:08 -0300] /home/infra/arachni-1.6.1.1-0.6.1.1/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:74:in `initialize'
[2022-05-31 00:04:08 -0300] /home/infra/arachni-1.6.1.1-0.6.1.1/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:47:in `new'
[2022-05-31 00:04:08 -0300] /home/infra/arachni-1.6.1.1-0.6.1.1/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:47:in `for'
[2022-05-31 00:04:08 -0300] /home/infra/arachni-1.6.1.1-0.6.1.1/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver.rb:88:in `for'
[2022-05-31 00:04:08 -0300] /home/infra/arachni-1.6.1.1-0.6.1.1/.system/gems/gems/arachni-1.6.1.1/lib/arachni/browser.rb:1100:in `selenium'
[2022-05-31 00:04:08 -0300] /home/infra/arachni-1.6.1.1-0.6.1.1/.system/gems/gems/arachni-1.6.1.1/lib/arachni/browser.rb:1274:in `start_webdriver'
[2022-05-31 00:04:08 -0300] /home/infra/arachni-1.6.1.1-0.6.1.1/.system/gems/gems/arachni-1.6.1.1/lib/arachni/browser.rb:192:in `initialize'
[2022-05-31 00:04:08 -0300] /home/infra/arachni-1.6.1.1-0.6.1.1/.system/gems/gems/arachni-1.6.1.1/lib/arachni/browser_cluster/worker.rb:51:in `initialize'
[2022-05-31 00:04:08 -0300] /home/infra/arachni-1.6.1.1-0.6.1.1/.system/gems/gems/arachni-1.6.1.1/lib/arachni/browser_cluster.rb:495:in `new'
[2022-05-31 00:04:08 -0300] /home/infra/arachni-1.6.1.1-0.6.1.1/.system/gems/gems/arachni-1.6.1.1/lib/arachni/browser_cluster.rb:495:in `block in initialize_workers'
[2022-05-31 00:04:08 -0300] /home/infra/arachni-1.6.1.1-0.6.1.1/.system/gems/gems/arachni-1.6.1.1/lib/arachni/browser_cluster.rb:494:in `times'
[2022-05-31 00:04:08 -0300] /home/infra/arachni-1.6.1.1-0.6.1.1/.system/gems/gems/arachni-1.6.1.1/lib/arachni/browser_cluster.rb:494:in `initialize_workers'
[2022-05-31 00:04:08 -0300] /home/infra/arachni-1.6.1.1-0.6.1.1/.system/gems/gems/arachni-1.6.1.1/lib/arachni/browser_cluster.rb:112:in `initialize'
[2022-05-31 00:04:08 -0300] /home/infra/arachni-1.6.1.1-0.6.1.1/.system/gems/gems/arachni-1.6.1.1/lib/arachni/framework/parts/browser.rb:33:in `new'
[2022-05-31 00:04:08 -0300] /home/infra/arachni-1.6.1.1-0.6.1.1/.system/gems/gems/arachni-1.6.1.1/lib/arachni/framework/parts/browser.rb:33:in `block in browser_cluster'
[2022-05-31 00:04:08 -0300] /home/infra/arachni-1.6.1.1-0.6.1.1/.system/usr/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
[2022-05-31 00:04:08 -0300] /home/infra/arachni-1.6.1.1-0.6.1.1/.system/usr/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
[2022-05-31 00:04:08 -0300] /home/infra/arachni-1.6.1.1-0.6.1.1/.system/gems/gems/arachni-1.6.1.1/lib/arachni/framework/parts/browser.rb:28:in `browser_cluster'
[2022-05-31 00:04:08 -0300] /home/infra/arachni-1.6.1.1-0.6.1.1/.system/gems/gems/arachni-1.6.1.1/lib/arachni/framework/parts/audit.rb:173:in `audit'
[2022-05-31 00:04:08 -0300] /home/infra/arachni-1.6.1.1-0.6.1.1/.system/gems/gems/arachni-1.6.1.1/lib/arachni/framework.rb:117:in `block in run'
[2022-05-31 00:04:08 -0300] /home/infra/arachni-1.6.1.1-0.6.1.1/.system/gems/gems/arachni-1.6.1.1/lib/arachni/utilities.rb:425:in `exception_jail'
[2022-05-31 00:04:08 -0300] /home/infra/arachni-1.6.1.1-0.6.1.1/.system/gems/gems/arachni-1.6.1.1/lib/arachni/framework.rb:117:in `run'
[2022-05-31 00:04:08 -0300] /home/infra/arachni-1.6.1.1-0.6.1.1/.system/gems/gems/arachni-1.6.1.1/lib/arachni/rpc/server/framework.rb:156:in `block in run'
[2022-05-31 00:04:08 -0300] 
[2022-05-31 00:04:08 -0300] Parent:
[2022-05-31 00:04:08 -0300] Arachni::RPC::Server::Framework
[2022-05-31 00:04:08 -0300] 
[2022-05-31 00:04:08 -0300] Block:
[2022-05-31 00:04:08 -0300] #<Proc:0x0000560012390e00 /home/infra/arachni-1.6.1.1-0.6.1.1/.system/gems/gems/arachni-1.6.1.1/lib/arachni/framework.rb:117>
[2022-05-31 00:04:08 -0300] 
[2022-05-31 00:04:08 -0300] Caller:
[2022-05-31 00:04:08 -0300] /home/infra/arachni-1.6.1.1-0.6.1.1/.system/gems/gems/arachni-1.6.1.1/lib/arachni/utilities.rb:424:in `exception_jail'
[2022-05-31 00:04:08 -0300] /home/infra/arachni-1.6.1.1-0.6.1.1/.system/gems/gems/arachni-1.6.1.1/lib/arachni/framework.rb:117:in `run'
[2022-05-31 00:04:08 -0300] /home/infra/arachni-1.6.1.1-0.6.1.1/.system/gems/gems/arachni-1.6.1.1/lib/arachni/rpc/server/framework.rb:156:in `block in run'
[2022-05-31 00:04:08 -0300] --------------------------------------------------------------------------------
```

**Comment by smarttang** [comment]
这个我解决了，就是镜像里缺了东西，重新打一下就行，就是缺那个pj。
