### ISSUE TITLE
problem in first time

### ISSUE THREAD

**Issue by rida2025** [Arachni/arachni#1077]
[2022-06-25 00:58:53 +0100] Please ensure that chromedriver and Chrome are the same version and in your PATH.
[2022-06-25 00:58:53 +0100] [Selenium::WebDriver::Error::SessionNotCreatedError] session not created: This version of ChromeDriver only supports Chrome version 98
Current browser version is 102.0.5005.115 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
[2022-06-25 00:58:53 +0100] Backtrace:
[2022-06-25 00:58:53 +0100] 	Ordinal0 [0x00F169A3+2582947]
[2022-06-25 00:58:53 +0100] 	Ordinal0 [0x00EAA6D1+2139857]
[2022-06-25 00:58:53 +0100] 	Ordinal0 [0x00DA3A98+1063576]
[2022-06-25 00:58:53 +0100] 	Ordinal0 [0x00DC33B8+1192888]
[2022-06-25 00:58:53 +0100] 	Ordinal0 [0x00DBF235+1176117]
[2022-06-25 00:58:53 +0100] 	Ordinal0 [0x00DBC9E1+1165793]
[2022-06-25 00:58:53 +0100] 	Ordinal0 [0x00DECFFF+1363967]
[2022-06-25 00:58:53 +0100] 	Ordinal0 [0x00DECC2A+1362986]
[2022-06-25 00:58:53 +0100] 	Ordinal0 [0x00DE8366+1344358]
[2022-06-25 00:58:53 +0100] 	Ordinal0 [0x00DC5176+1200502]
[2022-06-25 00:58:53 +0100] 	Ordinal0 [0x00DC6066+1204326]
[2022-06-25 00:58:53 +0100] 	GetHandleVerifier [0x010BBE02+1675858]
[2022-06-25 00:58:53 +0100] 	GetHandleVerifier [0x0117036C+2414524]
[2022-06-25 00:58:53 +0100] 	GetHandleVerifier [0x00FABB01+560977]
[2022-06-25 00:58:53 +0100] 	GetHandleVerifier [0x00FAA8D3+556323]
[2022-06-25 00:58:53 +0100] 	Ordinal0 [0x00EB020E+2163214]
[2022-06-25 00:58:53 +0100] 	Ordinal0 [0x00EB5078+2183288]
[2022-06-25 00:58:53 +0100] 	Ordinal0 [0x00EB51C0+2183616]
[2022-06-25 00:58:53 +0100] 	Ordinal0 [0x00EBEE1C+2223644]
[2022-06-25 00:58:53 +0100] 	BaseThreadInitThunk [0x76D3FA29+25]
[2022-06-25 00:58:53 +0100] 	RtlGetAppContainerNamedObjectPath [0x77517A9E+286]
[2022-06-25 00:58:53 +0100] 	RtlGetAppContainerNamedObjectPath [0x77517A6E+238]
[2022-06-25 00:58:53 +0100] E:/arachni-1.6.1.3-0.6.1.1-windows-x86_64/system/ruby/lib/ruby/gems/2.7.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/response.rb:56:in `assert_ok'
[2022-06-25 00:58:53 +0100] E:/arachni-1.6.1.3-0.6.1.1-windows-x86_64/system/ruby/lib/ruby/gems/2.7.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/response.rb:35:in `initialize'
[2022-06-25 00:58:53 +0100] E:/arachni-1.6.1.3-0.6.1.1-windows-x86_64/system/ruby/lib/ruby/gems/2.7.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
[2022-06-25 00:58:53 +0100] E:/arachni-1.6.1.3-0.6.1.1-windows-x86_64/system/ruby/lib/ruby/gems/2.7.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
[2022-06-25 00:58:53 +0100] E:/arachni-1.6.1.3-0.6.1.1-windows-x86_64/system/ruby/lib/ruby/gems/2.7.0/gems/arachni-1.6.1.3/lib/arachni/selenium/webdriver/remote/typhoeus.rb:51:in `request'
[2022-06-25 00:58:53 +0100] E:/arachni-1.6.1.3-0.6.1.1-windows-x86_64/system/ruby/lib/ruby/gems/2.7.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
[2022-06-25 00:58:53 +0100] E:/arachni-1.6.1.3-0.6.1.1-windows-x86_64/system/ruby/lib/ruby/gems/2.7.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/bridge.rb:588:in `execute'
[2022-06-25 00:58:53 +0100] E:/arachni-1.6.1.3-0.6.1.1-windows-x86_64/system/ruby/lib/ruby/gems/2.7.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/bridge.rb:52:in `create_session'
[2022-06-25 00:58:53 +0100] E:/arachni-1.6.1.3-0.6.1.1-windows-x86_64/system/ruby/lib/ruby/gems/2.7.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:340:in `create_bridge'
[2022-06-25 00:58:53 +0100] E:/arachni-1.6.1.3-0.6.1.1-windows-x86_64/system/ruby/lib/ruby/gems/2.7.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:74:in `initialize'
[2022-06-25 00:58:53 +0100] E:/arachni-1.6.1.3-0.6.1.1-windows-x86_64/system/ruby/lib/ruby/gems/2.7.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:47:in `new'
[2022-06-25 00:58:53 +0100] E:/arachni-1.6.1.3-0.6.1.1-windows-x86_64/system/ruby/lib/ruby/gems/2.7.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:47:in `for'
[2022-06-25 00:58:53 +0100] E:/arachni-1.6.1.3-0.6.1.1-windows-x86_64/system/ruby/lib/ruby/gems/2.7.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver.rb:88:in `for'
[2022-06-25 00:58:53 +0100] E:/arachni-1.6.1.3-0.6.1.1-windows-x86_64/system/ruby/lib/ruby/gems/2.7.0/gems/arachni-1.6.1.3/lib/arachni/browser.rb:1100:in `selenium'
[2022-06-25 00:58:53 +0100] E:/arachni-1.6.1.3-0.6.1.1-windows-x86_64/system/ruby/lib/ruby/gems/2.7.0/gems/arachni-1.6.1.3/lib/arachni/browser.rb:1274:in `start_webdriver'
[2022-06-25 00:58:53 +0100] E:/arachni-1.6.1.3-0.6.1.1-windows-x86_64/system/ruby/lib/ruby/gems/2.7.0/gems/arachni-1.6.1.3/lib/arachni/browser.rb:192:in `initialize'
[2022-06-25 00:58:53 +0100] E:/arachni-1.6.1.3-0.6.1.1-windows-x86_64/system/ruby/lib/ruby/gems/2.7.0/gems/arachni-1.6.1.3/lib/arachni/browser_cluster/worker.rb:51:in `initialize'
[2022-06-25 00:58:53 +0100] E:/arachni-1.6.1.3-0.6.1.1-windows-x86_64/system/ruby/lib/ruby/gems/2.7.0/gems/arachni-1.6.1.3/lib/arachni/browser_cluster.rb:495:in `new'
[2022-06-25 00:58:53 +0100] E:/arachni-1.6.1.3-0.6.1.1-windows-x86_64/system/ruby/lib/ruby/gems/2.7.0/gems/arachni-1.6.1.3/lib/arachni/browser_cluster.rb:495:in `block in initialize_workers'
[2022-06-25 00:58:53 +0100] E:/arachni-1.6.1.3-0.6.1.1-windows-x86_64/system/ruby/lib/ruby/gems/2.7.0/gems/arachni-1.6.1.3/lib/arachni/browser_cluster.rb:494:in `times'
[2022-06-25 00:58:53 +0100] E:/arachni-1.6.1.3-0.6.1.1-windows-x86_64/system/ruby/lib/ruby/gems/2.7.0/gems/arachni-1.6.1.3/lib/arachni/browser_cluster.rb:494:in `initialize_workers'
[2022-06-25 00:58:53 +0100] E:/arachni-1.6.1.3-0.6.1.1-windows-x86_64/system/ruby/lib/ruby/gems/2.7.0/gems/arachni-1.6.1.3/lib/arachni/browser_cluster.rb:112:in `initialize'
[2022-06-25 00:58:53 +0100] E:/arachni-1.6.1.3-0.6.1.1-windows-x86_64/system/ruby/lib/ruby/gems/2.7.0/gems/arachni-1.6.1.3/lib/arachni/framework/parts/browser.rb:33:in `new'
[2022-06-25 00:58:53 +0100] E:/arachni-1.6.1.3-0.6.1.1-windows-x86_64/system/ruby/lib/ruby/gems/2.7.0/gems/arachni-1.6.1.3/lib/arachni/framework/parts/browser.rb:33:in `block in browser_cluster'
[2022-06-25 00:58:53 +0100] E:/arachni-1.6.1.3-0.6.1.1-windows-x86_64/system/ruby/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
[2022-06-25 00:58:53 +0100] E:/arachni-1.6.1.3-0.6.1.1-windows-x86_64/system/ruby/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
[2022-06-25 00:58:53 +0100] E:/arachni-1.6.1.3-0.6.1.1-windows-x86_64/system/ruby/lib/ruby/gems/2.7.0/gems/arachni-1.6.1.3/lib/arachni/framework/parts/browser.rb:28:in `browser_cluster'
[2022-06-25 00:58:53 +0100] E:/arachni-1.6.1.3-0.6.1.1-windows-x86_64/system/ruby/lib/ruby/gems/2.7.0/gems/arachni-1.6.1.3/lib/arachni/framework/parts/audit.rb:173:in `audit'
[2022-06-25 00:58:53 +0100] E:/arachni-1.6.1.3-0.6.1.1-windows-x86_64/system/ruby/lib/ruby/gems/2.7.0/gems/arachni-1.6.1.3/lib/arachni/framework.rb:117:in `block in run'
[2022-06-25 00:58:53 +0100] E:/arachni-1.6.1.3-0.6.1.1-windows-x86_64/system/ruby/lib/ruby/gems/2.7.0/gems/arachni-1.6.1.3/lib/arachni/utilities.rb:425:in `exception_jail'
[2022-06-25 00:58:53 +0100] E:/arachni-1.6.1.3-0.6.1.1-windows-x86_64/system/ruby/lib/ruby/gems/2.7.0/gems/arachni-1.6.1.3/lib/arachni/framework.rb:117:in `run'
[2022-06-25 00:58:53 +0100] E:/arachni-1.6.1.3-0.6.1.1-windows-x86_64/system/ruby/lib/ruby/gems/2.7.0/gems/arachni-1.6.1.3/lib/arachni/rpc/server/framework.rb:156:in `block in run'
[2022-06-25 00:58:53 +0100] 
[2022-06-25 00:58:53 +0100] Parent:
[2022-06-25 00:58:53 +0100] Arachni::RPC::Server::Framework
[2022-06-25 00:58:53 +0100] 
[2022-06-25 00:58:53 +0100] Block:
[2022-06-25 00:58:53 +0100] #<Proc:0x000002327b48ef18 E:/arachni-1.6.1.3-0.6.1.1-windows-x86_64/system/ruby/lib/ruby/gems/2.7.0/gems/arachni-1.6.1.3/lib/arachni/framework.rb:117>
[2022-06-25 00:58:53 +0100] 
[2022-06-25 00:58:53 +0100] Caller:
[2022-06-25 00:58:53 +0100] E:/arachni-1.6.1.3-0.6.1.1-windows-x86_64/system/ruby/lib/ruby/gems/2.7.0/gems/arachni-1.6.1.3/lib/arachni/utilities.rb:424:in `exception_jail'
[2022-06-25 00:58:53 +0100] E:/arachni-1.6.1.3-0.6.1.1-windows-x86_64/system/ruby/lib/ruby/gems/2.7.0/gems/arachni-1.6.1.3/lib/arachni/framework.rb:117:in `run'
[2022-06-25 00:58:53 +0100] E:/arachni-1.6.1.3-0.6.1.1-windows-x86_64/system/ruby/lib/ruby/gems/2.7.0/gems/arachni-1.6.1.3/lib/arachni/rpc/server/framework.rb:156:in `block in run'
[2022-06-25 00:58:53 +0100] --------------------------------------------------------------------------------

**Comment by Aznariy** [comment]
So what exactly is your problem here? From what I can see, you will need to align the chromedriver.exe version of arachni with the version of the Chrome browser version. ??
