### ISSUE TITLE
Is arachni available for direct use under the ARM64 architecture

### ISSUE THREAD

**Issue by venuszhuliguo** [Arachni/arachni#1078]
/ # chromedriver --version
ChromeDriver 102.0.5005.61 (0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819})
/ # chromium-browser -version
Chromium 102.0.5005.61
/ # arachni http://testhtml5.vulnweb.com
Arachni - Web Application Security Scanner Framework v1.6.1.3
   Author: Tasos "Zapotek" Laskos <tasos.laskos@arachni-scanner.com>

           (With the support of the community and the Arachni Team.)

   Website:       http://arachni-scanner.com
   Documentation: http://arachni-scanner.com/wiki

 [~] No checks were specified, loading all.
 [~] No element audit options were specified, will audit links, forms, cookies, nested_cookies, UI inputs, UI forms, JSONs and XMLs.

 [*] Initializing...
 [*] Preparing plugins...
 [*] ... done.
 [*] BrowserCluster: Initializing 4 browsers...
 [-] [browser#selenium:1124] Worker: Please ensure that chromedriver and Chrome are the same version and in your PATH.
 [-] [utilities#exception_jail:428] [Selenium::WebDriver::Error::SessionNotCreatedError] session not created
from tab crashed
  (Session info: headless chrome=102.0.5005.61)
 [-] [utilities#exception_jail:428] /usr/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/response.rb:56:in `assert_ok'
 [-] [utilities#exception_jail:428] /usr/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/response.rb:35:in `initialize'
 [-] [utilities#exception_jail:428] /usr/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
 [-] [utilities#exception_jail:428] /usr/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
 [-] [utilities#exception_jail:428] /usr/lib/ruby/gems/3.1.0/gems/arachni-1.6.1.3/lib/arachni/selenium/webdriver/remote/typhoeus.rb:51:in `request'
 [-] [utilities#exception_jail:428] /usr/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
 [-] [utilities#exception_jail:428] /usr/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/bridge.rb:588:in `execute'

**Comment by Aznariy** [comment]
Hello. Did you want to run your arachni in Chromium (https://www.chromium.org/Home/) or Chrome browser (https://www.google.com/chrome/downloads/) ?
