### ISSUE TITLE
Puma issue

### ISSUE THREAD

**Issue by chrisrusso** [Arachni/arachni#1096]
Hey guys... this is almost commercial grade software already.

I'm having this issue:

= Sinatra (v2.2.0) has taken the stage on 50476 for development with backup from Puma
Puma starting in single mode...
* Puma version: 6.4.0 (ruby 2.7.4-p191) ("The Eagle of Durango")
*  Min threads: 0
*  Max threads: 5
*  Environment: development
*          PID: 31205
* Listening on http://127.0.1.1:50476
Use Ctrl-C to stop
127.0.0.1 - - [13/Oct/2023:16:10:29 -0400] "GET / HTTP/1.1" 200 11 0.0017
127.0.0.1 - - [13/Oct/2023:16:10:29 -0400] "GET /s.php HTTP/1.1" 200 2 0.0002
127.0.0.1 - - [13/Oct/2023:16:10:29 -0400] "GET /s.php HTTP/1.1" 200 2 0.0003

**An error occurred while loading ./spec/arachni/rest/server_spec.rb.
Failure/Error: require 'puma/minissl'**

NameError:
  uninitialized constant Puma::MiniSSL::OPENSSL_VERSION
# ./vendor/bundle/ruby/2.7.0/gems/puma-6.4.0/lib/puma/minissl.rb:19:in `<module:MiniSSL>'
# ./vendor/bundle/ruby/2.7.0/gems/puma-6.4.0/lib/puma/minissl.rb:14:in `<module:Puma>'
# ./vendor/bundle/ruby/2.7.0/gems/puma-6.4.0/lib/puma/minissl.rb:13:in `<top (required)>'
# ./lib/arachni/rest/server.rb:10:in `require'
# ./lib/arachni/rest/server.rb:10:in `<top (required)>'
# ./spec/arachni/rest/server_spec.rb:2:in `require'
# ./spec/arachni/rest/server_spec.rb:2:in `<top (required)>'
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

Finished in 0.00003 seconds (files took 2.59 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

/usr/bin/ruby2.7 -I/home/kali/arachni/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.2/lib:/home/kali/arachni/vendor/bundle/ruby/2.7.0/gems/rspec-support-3.12.1/lib /home/kali/arachni/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.2/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed

**Puma 6.4.0 installed. Any ideas? Thanks!**

**Comment by aborbely11** [comment]
You can fix it by downgrading puma to a version Arachni is compatible with, like ~> 4.3.12.

Open your Gemfile and lock Puma:
gem 'puma', '~> 4.3.12'

Clean and reinstall the bundle:
bundle clean --force
bundle install

Tip: Avoid testing Puma with rspec on unsupported versions

Puma 6 introduces architectural changes (especially in SSL handling), which break legacy apps relying on MiniSSL. Arachni’s web server codebase was built before those changes.
