### ISSUE TITLE
Connection refused - SSL_connect for '127.0.0.1:24336'.

### ISSUE THREAD

**Issue by ladr0n** [Arachni/arachni#534]
run in few minuts then stopped . Error log 

```
Connection refused - SSL_connect for '127.0.0.1:24336'.
/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/connection/tls.rb:66:in `connect_nonblock'
/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/connection/tls.rb:66:in `start_tls'
/opt/arachni/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/protocol.rb:23:in `on_connect'
/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/connection.rb:274:in `configure'
/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:205:in `block in connect'
/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/connection/error.rb:26:in `call'
/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/connection/error.rb:26:in `translate'
/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:200:in `connect'
/opt/arachni/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/client.rb:111:in `connect'
/opt/arachni/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/client.rb:216:in `call_async'
/opt/arachni/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/client.rb:196:in `call'
/opt/arachni/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/proxy.rb:73:in `forward'
/opt/arachni/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/proxy.rb:57:in `block in translate'
/opt/arachni/system/arachni-ui-web/app/models/scan.rb:519:in `refresh'
/opt/arachni/system/arachni-ui-web/lib/scan_manager.rb:152:in `block in refresh'
/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/iterator.rb:129:in `call'
/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/iterator.rb:129:in `block in each'
/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/iterator.rb:241:in `call'
/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/iterator.rb:241:in `block in spawn_workers'
/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/tasks/base.rb:52:in `call'
/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/tasks/base.rb:52:in `call_task'
/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/tasks/one_off.rb:23:in `call'
/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/tasks.rb:96:in `block in call'
/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/tasks.rb:96:in `each'
/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/tasks.rb:96:in `call'
/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:310:in `block in run'
/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:308:in `loop'
/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:308:in `run'
/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:350:in `block in run_in_thread'
--------------------------------------------------------------------------------
/opt/arachni/system/arachni-ui-web/app/models/scan.rb:528:in `block in refresh'
/opt/arachni/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/proxy.rb:58:in `call'
/opt/arachni/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/proxy.rb:58:in `block (2 levels) in translate'
/opt/arachni/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/client.rb:209:in `call'
/opt/arachni/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/client.rb:209:in `set_exception'
/opt/arachni/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/client.rb:218:in `block in call_async'
/opt/arachni/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/client.rb:111:in `call'
/opt/arachni/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/client.rb:111:in `connect'
/opt/arachni/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/client.rb:216:in `call_async'
/opt/arachni/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/client.rb:196:in `call'
/opt/arachni/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/proxy.rb:73:in `forward'
/opt/arachni/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/proxy.rb:57:in `block in translate'
/opt/arachni/system/arachni-ui-web/app/models/scan.rb:519:in `refresh'
/opt/arachni/system/arachni-ui-web/lib/scan_manager.rb:152:in `block in refresh'
/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/iterator.rb:129:in `call'
/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/iterator.rb:129:in `block in each'
/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/iterator.rb:241:in `call'
/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/iterator.rb:241:in `block in spawn_workers'
/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/tasks/base.rb:52:in `call'
/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/tasks/base.rb:52:in `call_task'
/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/tasks/one_off.rb:23:in `call'
/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/tasks.rb:96:in `block in call'
/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/tasks.rb:96:in `each'
/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/tasks.rb:96:in `call'
/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:310:in `block in run'
/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:308:in `loop'
/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:308:in `run'
/opt/arachni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:350:in `block in run_in_thread'
********************************************************************************
```

regards

**Comment by Zapotek** [comment]
Closing this issue due to lack of feedback and inactivity.
