### ISSUE TITLE
enable support for scanning 127.0.0.1 and localhost

### ISSUE THREAD

**Issue by dmitris** [Arachni/arachni#544]
Arachni refuses to scan test sites such as Webseclab running locally on 127.0.0.1 or localhost.  Is there a compelling reason for that?  Would it be possible to allow scanning local resources?  It would be useful to  both try Arachni on local tests as well as test initial versions of websites that are only available locally.

Arachni error for localhost or 127.0.0.1 URLs:
```
'localhost' is reserved, please use a different hostname.
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/lib/arachni/options.rb:216:in `url='
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/lib/arachni/options.rb:276:in `block in update'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/lib/arachni/options.rb:271:in `each'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/lib/arachni/options.rb:271:in `update'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/lib/arachni/rpc/server/active_options.rb:50:in `set'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/lib/arachni/rpc/server/instance.rb:583:in `scan'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/server.rb:207:in `call'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/server/handler.rb:56:in `receive_request'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/server/handler.rb:95:in `receive_object'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/protocol.rb:52:in `on_read'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/connection.rb:236:in `block in _read'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/connection/error.rb:26:in `call'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/connection/error.rb:26:in `translate'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/connection.rb:235:in `_read'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:568:in `each'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:568:in `block in process_connections'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:568:in `each'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:568:in `process_connections'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:317:in `block in run'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:308:in `loop'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:308:in `run'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/lib/arachni/rpc/server/instance.rb:152:in `initialize'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/lib/arachni/processes/executables/instance.rb:13:in `new'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/lib/arachni/processes/executables/instance.rb:13:in `<top (required)>'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/lib/arachni/processes/executables/base.rb:9:in `load'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/lib/arachni/processes/executables/base.rb:9:in `<main>'
--------------------------------------------------------------------------------
/Applications/arachni-1.0.6-0.5.6/system/arachni-ui-web/app/models/scan.rb:451:in `block in start'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/client/handler.rb:77:in `call'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/client/handler.rb:77:in `receive_response'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/client/handler.rb:137:in `receive_object'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/protocol.rb:52:in `on_read'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/connection.rb:236:in `block in _read'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/connection/error.rb:26:in `call'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/connection/error.rb:26:in `translate'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/connection.rb:235:in `_read'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:568:in `each'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:568:in `block in process_connections'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:568:in `each'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:568:in `process_connections'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:317:in `block in run'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:308:in `loop'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:308:in `run'
/Applications/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:350:in `block in run_in_thread'
********************************************************************************
```

**Comment by Zapotek** [comment]
You can scan local resources, just not by `127.0.0.1` or `localhost`. You can use `127.0.0.2` or the IP address of some other interface.

Cheers

**Comment by georgiamilton** [comment]
When i try eth0 ip or 127.0.0.2 it does not work the same as localhost so how can i fix this?
