### ISSUE TITLE
Some error when importing scan into Arachni Web

### ISSUE THREAD

**Issue by sbehrens** [Arachni/arachni#548]
Hello,

I had a scan that was taking a few hours to finish.  After terminating the scan, I tried to upload the report to Arachni web.  I get the following error:

```
TP/1.1" 304 - 0.0893
#<TypeError: can't cast Regexp to text>
[
    [  0] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/quoting.rb:81:in `type_cast'",
    [  1] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/connection_adapters/sqlite3_adapter.rb:261:in `type_cast'",
    [  2] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/connection_adapters/sqlite3_adapter.rb:295:in `block in exec_query'",
    [  3] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/connection_adapters/sqlite3_adapter.rb:294:in `map'",
    [  4] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/connection_adapters/sqlite3_adapter.rb:294:in `exec_query'",
    [  5] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:68:in `exec_insert'",
    [  6] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:95:in `insert'",
    [  7] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'",
    [  8] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/relation.rb:64:in `insert'",
    [  9] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/persistence.rb:503:in `_create_record'",
    [ 10] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/attribute_methods/dirty.rb:87:in `_create_record'",
    [ 11] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/callbacks.rb:306:in `block in _create_record'",
    [ 12] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:113:in `call'",
    [ 13] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:113:in `call'",
    [ 14] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'",
    [ 15] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `call'",
    [ 16] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'",
    [ 17] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `call'",
    [ 18] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'",
    [ 19] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `call'",
    [ 20] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `run_callbacks'",
    [ 21] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/callbacks.rb:306:in `_create_record'",
    [ 22] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/timestamp.rb:57:in `_create_record'",
    [ 23] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/persistence.rb:483:in `create_or_update'",
    [ 24] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/callbacks.rb:302:in `block in create_or_update'",
    [ 25] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:113:in `call'",
    [ 26] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:113:in `call'",
    [ 27] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'",
    [ 28] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'",
    [ 29] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'",
    [ 30] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'",
    [ 31] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'",
    [ 32] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'",
    [ 33] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'",
    [ 34] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `call'",
    [ 35] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `run_callbacks'",
    [ 36] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/callbacks.rb:302:in `create_or_update'",
    [ 37] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/persistence.rb:103:in `save'",
    [ 38] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/validations.rb:51:in `save'",
    [ 39] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/attribute_methods/dirty.rb:21:in `save'",
    [ 40] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:268:in `block (2 levels) in save'",
    [ 41] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'",
    [ 42] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:199:in `transaction'",
    [ 43] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:208:in `transaction'",
    [ 44] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'",
    [ 45] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:268:in `block in save'",
    [ 46] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:283:in `rollback_active_record_state!'",
    [ 47] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:267:in `save'",
    [ 48] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/autosave_association.rb:423:in `save_belongs_to_association'",
    [ 49] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/autosave_association.rb:203:in `block in add_autosave_association_callbacks'",
    [ 50] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/autosave_association.rb:157:in `instance_eval'",
    [ 51] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/autosave_association.rb:157:in `block in define_non_cyclic_method'",
    [ 52] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:424:in `block in make_lambda'",
    [ 53] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:160:in `call'",
    [ 54] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:160:in `block in halting'",
    [ 55] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'",
    [ 56] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'",
    [ 57] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `call'",
    [ 58] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `run_callbacks'",
    [ 59] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/callbacks.rb:302:in `create_or_update'",
    [ 60] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/persistence.rb:103:in `save'",
    [ 61] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/validations.rb:51:in `save'",
    [ 62] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/attribute_methods/dirty.rb:21:in `save'",
    [ 63] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:268:in `block (2 levels) in save'",
    [ 64] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'",
    [ 65] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'",
    [ 66] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'",
    [ 67] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'",
    [ 68] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:208:in `transaction'",
    [ 69] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'",
    [ 70] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:268:in `block in save'",
    [ 71] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:283:in `rollback_active_record_state!'",
    [ 72] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/transactions.rb:267:in `save'",
    [ 73] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/arachni-ui-web/app/models/scan.rb:651:in `create_report'",
    [ 74] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/arachni-ui-web/app/models/scan.rb:634:in `import'",
    [ 75] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/arachni-ui-web/app/controllers/scans_controller.rb:182:in `import'",
    [ 76] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/actionpack-4.1.8/lib/action_controller/metal/implicit_render.rb:4:in `send_action'",
    [ 77] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/actionpack-4.1.8/lib/abstract_controller/base.rb:189:in `process_action'",
    [ 78] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/actionpack-4.1.8/lib/action_controller/metal/rendering.rb:10:in `process_action'",
    [ 79] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/actionpack-4.1.8/lib/abstract_controller/callbacks.rb:20:in `block in process_action'",
    [ 80] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:113:in `call'",
    [ 81] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:113:in `call'",
    [ 82] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'",
    [ 83] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:149:in `call'",
    [ 84] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'",
    [ 85] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:149:in `call'",
    [ 86] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'",
    [ 87] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:149:in `call'",
    [ 88] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'",
    [ 89] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'",
    [ 90] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'",
    [ 91] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:229:in `call'",
    [ 92] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:229:in `block in halting'",
    [ 93] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'",
    [ 94] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'",
    [ 95] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'",
    [ 96] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'",
    [ 97] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `call'",
    [ 98] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `run_callbacks'",
    [ 99] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/actionpack-4.1.8/lib/abstract_controller/callbacks.rb:19:in `process_action'",
    [100] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/actionpack-4.1.8/lib/action_controller/metal/rescue.rb:29:in `process_action'",
    [101] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/actionpack-4.1.8/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'",
    [102] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/notifications.rb:159:in `block in instrument'",
    [103] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'",
    [104] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/notifications.rb:159:in `instrument'",
    [105] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/actionpack-4.1.8/lib/action_controller/metal/instrumentation.rb:30:in `process_action'",
    [106] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/actionpack-4.1.8/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'",
    [107] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/railties/controller_runtime.rb:18:in `process_action'",
    [108] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/actionpack-4.1.8/lib/abstract_controller/base.rb:136:in `process'",
    [109] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/actionview-4.1.8/lib/action_view/rendering.rb:30:in `process'",
    [110] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/actionpack-4.1.8/lib/action_controller/metal.rb:196:in `dispatch'",
    [111] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/actionpack-4.1.8/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'",
    [112] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/actionpack-4.1.8/lib/action_controller/metal.rb:232:in `block in action'",
    [113] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:82:in `call'",
    [114] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'",
    [115] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:50:in `call'",
    [116] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/actionpack-4.1.8/lib/action_dispatch/journey/router.rb:73:in `block in call'",
    [117] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/actionpack-4.1.8/lib/action_dispatch/journey/router.rb:59:in `each'",
    [118] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/actionpack-4.1.8/lib/action_dispatch/journey/router.rb:59:in `call'",
    [119] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:678:in `call'",
    [120] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'",
    [121] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'",
    [122] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'",
    [123] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'",
    [124] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/rack-1.5.2/lib/rack/conditionalget.rb:35:in `call'",
    [125] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'",
    [126] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/actionpack-4.1.8/lib/action_dispatch/middleware/params_parser.rb:27:in `call'",
    [127] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/actionpack-4.1.8/lib/action_dispatch/middleware/flash.rb:254:in `call'",
    [128] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'",
    [129] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'",
    [130] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/actionpack-4.1.8/lib/action_dispatch/middleware/cookies.rb:560:in `call'",
    [131] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/query_cache.rb:36:in `call'",
    [132] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'",
    [133] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/actionpack-4.1.8/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'",
    [134] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:82:in `run_callbacks'",
    [135] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/actionpack-4.1.8/lib/action_dispatch/middleware/callbacks.rb:27:in `call'",
    [136] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/actionpack-4.1.8/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'",
    [137] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/actionpack-4.1.8/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'",
    [138] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/actionpack-4.1.8/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'",
    [139] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/railties-4.1.8/lib/rails/rack/logger.rb:38:in `call_app'",
    [140] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/railties-4.1.8/lib/rails/rack/logger.rb:22:in `call'",
    [141] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/actionpack-4.1.8/lib/action_dispatch/middleware/request_id.rb:21:in `call'",
    [142] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'",
    [143] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'",
    [144] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/activesupport-4.1.8/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'",
    [145] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/actionpack-4.1.8/lib/action_dispatch/middleware/static.rb:84:in `call'",
    [146] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'",
    [147] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/railties-4.1.8/lib/rails/engine.rb:514:in `call'",
    [148] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/railties-4.1.8/lib/rails/application.rb:144:in `call'",
    [149] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/railties-4.1.8/lib/rails/railtie.rb:194:in `public_send'",
    [150] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/railties-4.1.8/lib/rails/railtie.rb:194:in `method_missing'",
    [151] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/rack-1.5.2/lib/rack/lint.rb:49:in `_call'",
    [152] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/rack-1.5.2/lib/rack/lint.rb:37:in `call'",
    [153] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/rack-1.5.2/lib/rack/showexceptions.rb:24:in `call'",
    [154] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/rack-1.5.2/lib/rack/commonlogger.rb:33:in `call'",
    [155] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/rack-1.5.2/lib/rack/chunked.rb:43:in `call'",
    [156] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/rack-1.5.2/lib/rack/content_length.rb:14:in `call'",
    [157] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/thin-1.6.3/lib/thin/connection.rb:86:in `block in pre_process'",
    [158] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/thin-1.6.3/lib/thin/connection.rb:84:in `catch'",
    [159] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/thin-1.6.3/lib/thin/connection.rb:84:in `pre_process'",
    [160] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/thin-1.6.3/lib/thin/connection.rb:53:in `process'",
    [161] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/thin-1.6.3/lib/thin/connection.rb:39:in `receive_data'",
    [162] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'",
    [163] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'",
    [164] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/thin-1.6.3/lib/thin/backends/base.rb:73:in `start'",
    [165] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/thin-1.6.3/lib/thin/server.rb:162:in `start'",
    [166] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/rack-1.5.2/lib/rack/handler/thin.rb:16:in `run'",
    [167] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/rack-1.5.2/lib/rack/server.rb:264:in `start'",
    [168] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/rack-1.5.2/lib/rack/server.rb:141:in `start'",
    [169] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/rack-1.5.2/bin/rackup:4:in `<top (required)>'",
    [170] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/bin/../system/gems/bin/rackup:23:in `load'",
    [171] "/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/bin/../system/gems/bin/rackup:23:in `<main>'"
]
```

Is there anyway I can retrieve the scan results?

**Comment by Zapotek** [comment]
This will be fixed in v1.1 which changes the way the WebUI stores the report in the DB.
You can still retrieve the results with the `arachni_reporter` executable though.

Cheers
