### ISSUE TITLE
Script crashed

### ISSUE THREAD

**Issue by Cleveridge** [Arachni/arachni#549]
While running Arachni_web a script crashed and forced me to reboot my computer.
After the reboot the scan showed the following errors:
```
Connection refused - SSL_connect for '127.0.0.1:33646'.
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/connection/tls.rb:66:in `connect_nonblock'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/connection/tls.rb:66:in `start_tls'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/protocol.rb:23:in `on_connect'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/connection.rb:274:in `configure'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:205:in `block in connect'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/connection/error.rb:26:in `call'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/connection/error.rb:26:in `translate'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:200:in `connect'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/client.rb:111:in `connect'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/client.rb:216:in `call_async'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/client.rb:196:in `call'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/proxy.rb:73:in `forward'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/proxy.rb:57:in `block in translate'
/root/Downloads/arachni-1.0.6-0.5.6/system/arachni-ui-web/app/models/scan.rb:519:in `refresh'
/root/Downloads/arachni-1.0.6-0.5.6/system/arachni-ui-web/lib/scan_manager.rb:152:in `block in refresh'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/iterator.rb:129:in `call'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/iterator.rb:129:in `block in each'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/iterator.rb:241:in `call'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/iterator.rb:241:in `block in spawn_workers'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/tasks/base.rb:52:in `call'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/tasks/base.rb:52:in `call_task'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/tasks/one_off.rb:23:in `call'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/tasks.rb:96:in `block in call'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/tasks.rb:96:in `each'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/tasks.rb:96:in `call'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:310:in `block in run'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:308:in `loop'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:308:in `run'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:350:in `block in run_in_thread'
--------------------------------------------------------------------------------
/root/Downloads/arachni-1.0.6-0.5.6/system/arachni-ui-web/app/models/scan.rb:528:in `block in refresh'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/proxy.rb:58:in `call'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/proxy.rb:58:in `block (2 levels) in translate'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/client.rb:209:in `call'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/client.rb:209:in `set_exception'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/client.rb:218:in `block in call_async'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/client.rb:111:in `call'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/client.rb:111:in `connect'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/client.rb:216:in `call_async'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/client.rb:196:in `call'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/proxy.rb:73:in `forward'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/proxy.rb:57:in `block in translate'
/root/Downloads/arachni-1.0.6-0.5.6/system/arachni-ui-web/app/models/scan.rb:519:in `refresh'
/root/Downloads/arachni-1.0.6-0.5.6/system/arachni-ui-web/lib/scan_manager.rb:152:in `block in refresh'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/iterator.rb:129:in `call'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/iterator.rb:129:in `block in each'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/iterator.rb:241:in `call'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/iterator.rb:241:in `block in spawn_workers'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/tasks/base.rb:52:in `call'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/tasks/base.rb:52:in `call_task'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/tasks/one_off.rb:23:in `call'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/tasks.rb:96:in `block in call'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/tasks.rb:96:in `each'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/tasks.rb:96:in `call'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:310:in `block in run'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:308:in `loop'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:308:in `run'
/root/Downloads/arachni-1.0.6-0.5.6/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:350:in `block in run_in_thread'
********************************************************************************
```
I was running a scan against an up to date wordpress website and I had the same issue with another wordpress website yesterday

The gui said it was scanning a css page of a template and after I while I got the pop up a script in
```
assets/application-c587a62573c1a152991bc30f01da0ce7.js:3
```
crashed.

**Comment by Zapotek** [comment]
This is a WebUI issue and doesn't have anything to do with the scan, could I trouble you to post it at https://github.com/Arachni/arachni-ui-web/issues ?

**Comment by Cleveridge** [comment]
No problem at all... done
