### ISSUE TITLE
WebUI in Windows : The program issued a command but the command length is incorrect. (24)

### ISSUE THREAD

**Issue by cybernot** [Arachni/arachni#551]
I saw the blog post encouraging people to try to windows version and tried the web ui. However, when I try to start a scan through the webui (or command line) I get errors (see below). I have to say that I removed the "RAILS_ENV=production" prefix from the command. Could this be the problem ?

On a side note, you should update the tutorial to use "del Gemfile.lock" instead of "rm Gemfile.lock"

[2015-02-20 15:59:29 -0500] [ChildProcess::Error] The program issued a command but the command length is incorrect. (24)
[2015-02-20 15:59:29 -0500] C:/jruby-1.7.18/lib/ruby/gems/shared/gems/childprocess-0.5.3/lib/childprocess/windows/lib.rb:385:in `check_error'
[2015-02-20 15:59:29 -0500] C:/jruby-1.7.18/lib/ruby/gems/shared/gems/childprocess-0.5.3/lib/childprocess/windows/process.rb:114:in `initialize'
[2015-02-20 15:59:29 -0500] C:/jruby-1.7.18/lib/ruby/gems/shared/gems/childprocess-0.5.3/lib/childprocess/windows/process.rb:72:in `launch_process'
[2015-02-20 15:59:29 -0500] C:/jruby-1.7.18/lib/ruby/gems/shared/gems/childprocess-0.5.3/lib/childprocess/abstract_process.rb:82:in `start'
[2015-02-20 15:59:29 -0500] C:/jruby-1.7.18/lib/ruby/gems/shared/bundler/gems/arachni-039a57b251e3/lib/arachni/browser.rb:1077:in `spawn_phantomjs'
[2015-02-20 15:59:29 -0500] org/jruby/RubyProc.java:271:in `call'
[2015-02-20 15:59:29 -0500] C:/jruby-1.7.18/lib/ruby/gems/shared/bundler/gems/arachni-039a57b251e3/lib/arachni/browser.rb:1019:in `with_timeout'
[2015-02-20 15:59:29 -0500] org/jruby/ext/timeout/Timeout.java:126:in `timeout'
[2015-02-20 15:59:29 -0500] C:/jruby-1.7.18/lib/ruby/gems/shared/bundler/gems/arachni-039a57b251e3/lib/arachni/browser.rb:1018:in `with_timeout'
[2015-02-20 15:59:29 -0500] C:/jruby-1.7.18/lib/ruby/gems/shared/bundler/gems/arachni-039a57b251e3/lib/arachni/browser.rb:1060:in `spawn_phantomjs'
[2015-02-20 15:59:29 -0500] org/jruby/RubyFixnum.java:280:in `times'
[2015-02-20 15:59:29 -0500] C:/jruby-1.7.18/lib/ruby/gems/shared/bundler/gems/arachni-039a57b251e3/lib/arachni/browser.rb:1053:in `spawn_phantomjs'
[2015-02-20 15:59:29 -0500] C:/jruby-1.7.18/lib/ruby/gems/shared/bundler/gems/arachni-039a57b251e3/lib/arachni/browser.rb:1037:in `spawn_browser'
[2015-02-20 15:59:29 -0500] C:/jruby-1.7.18/lib/ruby/gems/shared/bundler/gems/arachni-039a57b251e3/lib/arachni/browser.rb:944:in `selenium'
[2015-02-20 15:59:29 -0500] C:/jruby-1.7.18/lib/ruby/gems/shared/bundler/gems/arachni-039a57b251e3/lib/arachni/browser.rb:155:in `initialize'
[2015-02-20 15:59:29 -0500] C:/jruby-1.7.18/lib/ruby/gems/shared/bundler/gems/arachni-039a57b251e3/lib/arachni/session.rb:378:in `refresh_browser'
[2015-02-20 15:59:29 -0500] C:/jruby-1.7.18/lib/ruby/gems/shared/bundler/gems/arachni-039a57b251e3/lib/arachni/session.rb:228:in `login'
[2015-02-20 15:59:29 -0500] C:/jruby-1.7.18/lib/ruby/gems/shared/bundler/gems/arachni-039a57b251e3/components/plugins/autologin.rb:40:in `run'
[2015-02-20 15:59:29 -0500] C:/jruby-1.7.18/lib/ruby/gems/shared/bundler/gems/arachni-039a57b251e3/lib/arachni/plugin/manager.rb:75:in `run'
[2015-02-20 15:59:29 -0500] org/jruby/RubyProc.java:271:in `call'
[2015-02-20 15:59:29 -0500] C:/jruby-1.7.18/lib/ruby/gems/shared/bundler/gems/arachni-039a57b251e3/lib/arachni/utilities.rb:400:in `exception_jail'
[2015-02-20 15:59:29 -0500] C:/jruby-1.7.18/lib/ruby/gems/shared/bundler/gems/arachni-039a57b251e3/lib/arachni/plugin/manager.rb:67:in `run'
[2015-02-20 15:59:29 -0500] 
[2015-02-20 15:59:29 -0500] Parent:
[2015-02-20 15:59:29 -0500] Arachni::RPC::Server::Plugin::Manager
[2015-02-20 15:59:29 -0500] 
[2015-02-20 15:59:29 -0500] Block:
[2015-02-20 15:59:29 -0500] #<Proc:0x4734e161@C:/jruby-1.7.18/lib/ruby/gems/shared/bundler/gems/arachni-039a57b251e3/lib/arachni/plugin/manager.rb:67>
[2015-02-20 15:59:29 -0500] 
[2015-02-20 15:59:29 -0500] Caller:
[2015-02-20 15:59:29 -0500] C:/jruby-1.7.18/lib/ruby/gems/shared/bundler/gems/arachni-039a57b251e3/lib/arachni/plugin/manager.rb:67:in `run'
[2015-02-20 15:59:29 -0500] --------------------------------------------------------------------------------

**Comment by Zapotek** [comment]
The fact that you didn't set the `RAILS_ENV` variable can indeed be the issue.
Also, didn't you run this from the Git bash?

**Comment by Zapotek** [comment]
Closing due to lack of feedback.
