### ISSUE TITLE
error when using Arachni ,Connection refused - SSL_connect for '0.0.0.0:42929'

### ISSUE THREAD

**Issue by sampr0** [Arachni/arachni#567]
when using Arachni ,I saw the errors as flows:
using the Remote scan but it report error like 

```
Connection refused - SSL_connect for '0.0.0.0:42929'.
/root/Desktop/scan/archni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/connection/tls.rb:66:in `connect_nonblock'
/root/Desktop/scan/archni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/connection/tls.rb:66:in `start_tls'
/root/Desktop/scan/archni/system/gems/gems/arachni-rpc-0.2.1.1/lib/arachni/rpc/protocol.rb:23:in `on_connect'
/root/Desktop/scan/archni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor/connection.rb:274:in `configure'
/root/Desktop/scan/archni/system/gems/gems/arachni-reactor-0.1.0.beta5/lib/arachni/reactor.rb:205:in `block in connect'
```

Could you help em to solve the problem,thank you !

**Comment by Zapotek** [comment]
Is there a chance the the scanner was killed by the OS due to lack of RAM or something?
What does `dmesg` say?

**Comment by Zapotek** [comment]
Closing due to lack of feedback.
