### ISSUE TITLE
Error when converting to XML

### ISSUE THREAD

**Issue by sbehrens** [Arachni/arachni#571]
Trying to convert a report to XML for Threadfix, getting the following error with version v1.0.6:

```
[-] [NoMethodError] undefined method `round' for nil:NilClass
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/components/reporters/xml.rb:210:in `block (2 levels) in add_page'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/nokogiri-1.6.2.1/lib/nokogiri/xml/builder.rb:391:in `call'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/nokogiri-1.6.2.1/lib/nokogiri/xml/builder.rb:391:in `insert'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/nokogiri-1.6.2.1/lib/nokogiri/xml/builder.rb:375:in `method_missing'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/components/reporters/xml.rb:206:in `block in add_page'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/nokogiri-1.6.2.1/lib/nokogiri/xml/builder.rb:391:in `call'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/nokogiri-1.6.2.1/lib/nokogiri/xml/builder.rb:391:in `insert'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/nokogiri-1.6.2.1/lib/nokogiri/xml/builder.rb:375:in `method_missing'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/components/reporters/xml.rb:190:in `add_page'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/components/reporters/xml.rb:112:in `block (8 levels) in run'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/nokogiri-1.6.2.1/lib/nokogiri/xml/builder.rb:391:in `call'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/nokogiri-1.6.2.1/lib/nokogiri/xml/builder.rb:391:in `insert'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/nokogiri-1.6.2.1/lib/nokogiri/xml/builder.rb:375:in `method_missing'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/components/reporters/xml.rb:85:in `block (7 levels) in run'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/components/reporters/xml.rb:84:in `each'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/components/reporters/xml.rb:84:in `block (6 levels) in run'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/nokogiri-1.6.2.1/lib/nokogiri/xml/builder.rb:391:in `call'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/nokogiri-1.6.2.1/lib/nokogiri/xml/builder.rb:391:in `insert'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/nokogiri-1.6.2.1/lib/nokogiri/xml/builder.rb:375:in `method_missing'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/components/reporters/xml.rb:83:in `block (5 levels) in run'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/nokogiri-1.6.2.1/lib/nokogiri/xml/builder.rb:391:in `call'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/nokogiri-1.6.2.1/lib/nokogiri/xml/builder.rb:391:in `insert'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/nokogiri-1.6.2.1/lib/nokogiri/xml/builder.rb:375:in `method_missing'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/components/reporters/xml.rb:40:in `block (4 levels) in run'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/components/reporters/xml.rb:39:in `each'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/components/reporters/xml.rb:39:in `block (3 levels) in run'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/nokogiri-1.6.2.1/lib/nokogiri/xml/builder.rb:391:in `call'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/nokogiri-1.6.2.1/lib/nokogiri/xml/builder.rb:391:in `insert'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/nokogiri-1.6.2.1/lib/nokogiri/xml/builder.rb:375:in `method_missing'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/components/reporters/xml.rb:38:in `block (2 levels) in run'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/nokogiri-1.6.2.1/lib/nokogiri/xml/builder.rb:391:in `call'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/nokogiri-1.6.2.1/lib/nokogiri/xml/builder.rb:391:in `insert'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/nokogiri-1.6.2.1/lib/nokogiri/xml/builder.rb:375:in `method_missing'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/components/reporters/xml.rb:23:in `block in run'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/nokogiri-1.6.2.1/lib/nokogiri/xml/builder.rb:293:in `initialize'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/components/reporters/xml.rb:22:in `new'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/components/reporters/xml.rb:22:in `run'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/lib/arachni/reporter/manager.rb:34:in `tap'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/lib/arachni/reporter/manager.rb:34:in `block in run'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/lib/arachni/utilities.rb:395:in `call'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/lib/arachni/utilities.rb:395:in `exception_jail'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/lib/arachni/reporter/manager.rb:33:in `run'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/ui/cli/reporter.rb:43:in `block in run'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/ui/cli/reporter.rb:42:in `each'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/ui/cli/reporter.rb:42:in `run'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/ui/cli/reporter.rb:26:in `initialize'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/bin/arachni_reporter:12:in `new'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/bin/arachni_reporter:12:in `<top (required)>'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/bin/../system/arachni-ui-web/bin/arachni_reporter:16:in `load'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/bin/../system/arachni-ui-web/bin/arachni_reporter:16:in `<main>'
 [-]
 [-] Parent:
 [-] Arachni::Reporter::Manager
 [-]
 [-] Block:
 [-] #<Proc:0x007fa249aa1d18@/Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/lib/arachni/reporter/manager.rb:33>
 [-]
 [-] Caller:
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/lib/arachni/utilities.rb:395:in `exception_jail'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/lib/arachni/reporter/manager.rb:33:in `run'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/ui/cli/reporter.rb:43:in `block in run'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/ui/cli/reporter.rb:42:in `each'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/ui/cli/reporter.rb:42:in `run'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/ui/cli/reporter.rb:26:in `initialize'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/bin/arachni_reporter:12:in `new'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/bin/arachni_reporter:12:in `<top (required)>'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/bin/../system/arachni-ui-web/bin/arachni_reporter:16:in `load'
 [-] /Users/sbehrens/arachni/arachni-1.0.6-0.5.6/bin/../system/arachni-ui-web/bin/arachni_reporter:16:in `<main>'
 [-] --------------------------------------------------------------------------------
```

**Comment by sbehrens** [comment]
Also, this command returns a Status code of '0' when it should return non-zero status code because of the error.

**Comment by Zapotek** [comment]
This issue has been fixed in the nightlies, will look into the status code.

Cheers

**Comment by Zapotek** [comment]
I don't want to mess with the error handling code of the components so close before the v1.1 release so I've put that on my list for the next version and I'll close this ticket since the original issue has been resolved.
