### ISSUE TITLE
Can not respawn the browser

### ISSUE THREAD

**Issue by jvoisin** [Arachni/arachni#573]
I was playing with arachni on [mutilidae]( http://www.irongeek.com/i.php?page=mutillidae/mutillidae-deliberately-vulnerable-php-owasp-top-10 ), when suddenly:
```

2015-04-07 15:32:53 +0200 --------------------------------------------------------------------------------
ENV:
---
CPLUS_INCLUDE_PATH: "/home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/bin/../system/usr/include"
XDG_VTNR: '7'
LC_PAPER: fr_FR.UTF-8
LC_ADDRESS: fr_FR.UTF-8
XDG_SESSION_ID: c2
XDG_GREETER_DATA_DIR: "/var/lib/lightdm-data/jvoisin"
rvm_bin_path: "/home/jvoisin/.rvm/bin"
LC_MONETARY: fr_FR.UTF-8
TERMINATOR_UUID: urn:uuid:d7d4139e-8a3c-4017-b674-c5b0a55bcc72
SESSION: xubuntu
GEM_HOME: "/home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/system/gems"
GPG_AGENT_INFO: "/run/user/1000/keyring-Zcf426/gpg:0:1"
GLADE_PIXMAP_PATH: ":"
TERM: xterm-256color
XDG_MENU_PREFIX: xfce-
SHELL: "/bin/zsh"
GTK2_RC_FILES: "/home/jvoisin/.gtkrc-2.0"
IRBRC: "/home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/bin/../system/usr/lib/ruby/.irbrc"
LIBRARY_PATH: "/home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/bin/../system/usr/lib"
PERL5LIB: "/home/jvoisin/perl5/lib/perl5"
WINDOWID: '88080387'
LC_NUMERIC: fr_FR.UTF-8
UPSTART_SESSION: unix:abstract=/com/ubuntu/upstart-session/1000/2630
GNOME_KEYRING_CONTROL: "/run/user/1000/keyring-Zcf426"
PERL_MB_OPT: --install_base "/home/jvoisin/perl5"
MY_RUBY_HOME: "/home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/bin/../system/usr/lib/ruby"
vcs_info_msg_1_: ''
USER: jvoisin
LD_LIBRARY_PATH: "/home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/bin/../system/usr/lib"
LS_COLORS: 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:'
LC_TELEPHONE: fr_FR.UTF-8
DEBEMAIL: jvo@nbs-system.com
_system_type: Linux
GLADE_MODULE_PATH: ":"
XDG_SESSION_PATH: "/org/freedesktop/DisplayManager/Session0"
XDG_SEAT_PATH: "/org/freedesktop/DisplayManager/Seat0"
rvm_path: "/home/jvoisin/.rvm"
SSH_AUTH_SOCK: "/run/user/1000/keyring-Zcf426/ssh"
DEFAULTS_PATH: "/usr/share/gconf/xubuntu.default.path"
SESSION_MANAGER: local/laptop-jvoisin:@/tmp/.ICE-unix/2994,unix/laptop-jvoisin:/tmp/.ICE-unix/2994
XDG_CONFIG_DIRS: "/etc/xdg/xdg-xubuntu:/usr/share/upstart/xdg:/etc/xdg:/etc/xdg"
rvm_prefix: "/home/jvoisin"
DESKTOP_SESSION: xubuntu
PATH: "/home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/system/gems/bin:/home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/bin/../system/../bin:/home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/bin/../system/usr/bin:/home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/bin/../system/gems/bin:/home/jvoisin/perl5/bin:/home/jvoisin/.rvm/gems/ruby-2.1.5/bin:/home/jvoisin/.rvm/gems/ruby-2.1.5@global/bin:/home/jvoisin/.rvm/rubies/ruby-2.1.5/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/jvoisin/.rvm/bin"
C_INCLUDE_PATH: "/home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/bin/../system/usr/include"
LC_IDENTIFICATION: fr_FR.UTF-8
XDG_SESSION_TYPE: x11
PWD: "/home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev"
JOB: dbus
ARACHNI_WEBUI_LOGDIR: "/home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/bin/../system/logs/webui"
vcs_info_msg_0_: ''
EDITOR: vim
GNOME_KEYRING_PID: '2617'
LANG: en_US.UTF-8
GDM_LANG: en_US
MANDATORY_PATH: "/usr/share/gconf/xubuntu.mandatory.path"
TZ: Europe/Paris
LC_MEASUREMENT: fr_FR.UTF-8
ARACHNI_FRAMEWORK_LOGDIR: "/home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/bin/../system/logs/framework"
_system_arch: x86_64
IM_CONFIG_PHASE: '1'
GCC_COLORS: '1'
_system_version: '14.10'
GDMSESSION: xubuntu
SESSIONTYPE: ''
rvm_version: 1.26.10 (latest)
SHLVL: '1'
HOME: "/home/jvoisin"
XDG_SEAT: seat0
LANGUAGE: en_US
RAILS_ENV: production
DYLD_LIBRARY_PATH: "/home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/bin/../system/usr/lib"
UPSTART_INSTANCE: ''
PERL_LOCAL_LIB_ROOT: "/home/jvoisin/perl5"
UPSTART_EVENTS: started xsession
XDG_SESSION_DESKTOP: xubuntu
LOGNAME: jvoisin
DBUS_SESSION_BUS_ADDRESS: unix:abstract=/tmp/dbus-AUVKS05a9A
XDG_DATA_DIRS: "/usr/share/xubuntu:/usr/share/xfce4:/usr/local/share/:/usr/share/:/usr/share"
GEM_PATH: "/home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/bin/../system/gems"
GOPATH: "/opt/go"
TEXTDOMAIN: im-config
INSTANCE: ''
UPSTART_JOB: startxfce4
XDG_RUNTIME_DIR: "/run/user/1000"
DISPLAY: ":0.0"
GLADE_CATALOG_PATH: ":"
XDG_CURRENT_DESKTOP: XFCE
RUBYLIB: "/home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/system/gems/gems/bundler-1.9.2/lib:/home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/bin/../system/usr/lib/ruby:/home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/bin/../system/usr/lib/ruby/site_ruby/2.2.0:/home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/bin/../system/usr/lib/ruby/2.2.0:/home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/bin/../system/usr/lib/ruby/2.2.0/x86_64-linux:/home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/bin/../system/usr/lib/ruby/site_ruby/2.2.0/x86_64-linux"
LC_TIME: fr_FR.UTF-8
RUBY_VERSION: ruby-2.2.1
PERL_MM_OPT: INSTALL_BASE=/home/jvoisin/perl5
_system_name: Ubuntu
TEXTDOMAINDIR: "/usr/share/locale/"
LC_NAME: fr_FR.UTF-8
XAUTHORITY: "/home/jvoisin/.Xauthority"
COLORTERM: gnome-terminal
RACK_ENV: development
BUNDLE_GEMFILE: "/home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/system/arachni-ui-web/Gemfile"
_ORIGINAL_GEM_PATH: "/home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/bin/../system/gems"
BUNDLE_BIN_PATH: "/home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/system/gems/gems/bundler-1.9.2/bin/bundle"
RUBYOPT: "-rbundler/setup"
MANPATH: "/home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/system/gems/gems/kramdown-1.4.1/man"
BUNDLE_ORIG_MANPATH: "/home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/system/gems/gems/kramdown-1.4.1/man"
--------------------------------------------------------------------------------
OPTIONS:
---
session: {}
scope:
  redundant_path_patterns: {}
  dom_depth_limit: 5
  exclude_path_patterns: []
  exclude_content_patterns: []
  include_path_patterns: []
  restrict_paths: []
  extend_paths: []
  url_rewrites: {}
input:
  values:
    "(?i-mx:name)": arachni_name
    "(?i-mx:user)": arachni_user
    "(?i-mx:usr)": arachni_user
    "(?i-mx:pass)": 5543!%arachni_secret
    "(?i-mx:txt)": arachni_text
    "(?i-mx:num)": '132'
    "(?i-mx:amount)": '100'
    "(?i-mx:mail)": arachni@email.gr
    "(?i-mx:account)": '12'
    "(?i-mx:id)": '1'
  default_values:
    "(?i-mx:name)": arachni_name
    "(?i-mx:user)": arachni_user
    "(?i-mx:usr)": arachni_user
    "(?i-mx:pass)": 5543!%arachni_secret
    "(?i-mx:txt)": arachni_text
    "(?i-mx:num)": '132'
    "(?i-mx:amount)": '100'
    "(?i-mx:mail)": arachni@email.gr
    "(?i-mx:account)": '12'
    "(?i-mx:id)": '1'
  without_defaults: true
  force: false
browser_cluster:
  pool_size: 6
  job_timeout: 15
  worker_time_to_live: 100
  ignore_images: false
  screen_width: 1600
  screen_height: 1200
http:
  user_agent: Arachni/v2.0dev
  request_timeout: 10000
  request_redirect_limit: 5
  request_concurrency: 20
  request_queue_size: 500
  request_headers: {}
  response_max_size: 500000
  cookies: {}
audit:
  parameter_values: true
  exclude_vector_patterns: []
  include_vector_patterns: []
  link_templates: []
  links: true
  forms: true
  cookies: true
datastore:
  token: b6dad195a330c939012d49148cf73b33
checks:
- allowed_methods
- backdoors
- backup_directories
- backup_files
- captcha
- code_injection
- code_injection_php_input_wrapper
- code_injection_timing
- common_directories
- common_files
- cookie_set_for_parent_domain
- credit_card
- csrf
- cvs_svn_users
- directory_listing
- emails
- file_inclusion
- form_upload
- hsts
- htaccess_limit
- html_objects
- http_only_cookies
- http_put
- insecure_client_access_policy
- insecure_cookies
- insecure_cors_policy
- insecure_cross_domain_policy_access
- insecure_cross_domain_policy_headers
- interesting_responses
- ldap_injection
- localstart_asp
- mixed_resource
- no_sql_injection
- no_sql_injection_differential
- origin_spoof_access_restriction_bypass
- os_cmd_injection
- os_cmd_injection_timing
- password_autocomplete
- path_traversal
- private_ip
- response_splitting
- rfi
- session_fixation
- source_code_disclosure
- sql_injection
- sql_injection_differential
- sql_injection_timing
- ssn
- trainer
- unencrypted_password_forms
- unvalidated_redirect
- unvalidated_redirect_dom
- webdav
- x_frame_options
- xpath_injection
- xss
- xss_dom
- xss_dom_inputs
- xss_dom_script_context
- xss_event
- xss_path
- xss_script_context
- xss_tag
- xst
- xxe
platforms: []
plugins:
  autothrottle: {}
  discovery: {}
  healthmap: {}
  timing_attacks: {}
  uniformity: {}
no_fingerprinting: false
authorized_by: 
url: http://192.168.56.101/mutillidae/
--------------------------------------------------------------------------------
[2015-04-07 15:32:56 +0200] Could not spawn browser process.
[2015-04-07 15:32:56 +0200] Fontconfig error: Cannot load default config file

[2015-04-07 15:32:56 +0200] Could not respawn the browser, will try again at the next job. (Could not start the browser process.)
[2015-04-07 15:32:57 +0200] [NoMethodError] undefined method `cookies' for nil:NilClass
[2015-04-07 15:32:57 +0200] /home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-b652ef6bbce3/lib/arachni/browser_cluster/worker.rb:106:in `run_job'
[2015-04-07 15:32:57 +0200] /home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-b652ef6bbce3/lib/arachni/browser_cluster/worker.rb:233:in `block (3 levels) in start'
[2015-04-07 15:32:57 +0200] /home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-b652ef6bbce3/lib/arachni/utilities.rb:400:in `call'
[2015-04-07 15:32:57 +0200] /home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-b652ef6bbce3/lib/arachni/browser_cluster/worker.rb:233:in `block (2 levels) in start'
[2015-04-07 15:32:57 +0200] /home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-b652ef6bbce3/lib/arachni/utilities.rb:400:in `call'
[2015-04-07 15:32:57 +0200] /home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-b652ef6bbce3/lib/arachni/utilities.rb:400:in `exception_jail'
[2015-04-07 15:32:57 +0200] /home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-b652ef6bbce3/lib/arachni/browser_cluster/worker.rb:231:in `block in start'
[2015-04-07 15:32:57 +0200] 
[2015-04-07 15:32:57 +0200] Parent:
[2015-04-07 15:32:57 +0200] Arachni::BrowserCluster::Worker
[2015-04-07 15:32:57 +0200] 
[2015-04-07 15:32:57 +0200] Block:
[2015-04-07 15:32:57 +0200] #<Proc:0x00000002eb52b0@/home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-b652ef6bbce3/lib/arachni/browser_cluster/worker.rb:233>
[2015-04-07 15:32:57 +0200] 
[2015-04-07 15:32:57 +0200] Caller:
[2015-04-07 15:32:57 +0200] /home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-b652ef6bbce3/lib/arachni/utilities.rb:400:in `exception_jail'
[2015-04-07 15:32:57 +0200] /home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-b652ef6bbce3/lib/arachni/browser_cluster/worker.rb:233:in `block (2 levels) in start'
[2015-04-07 15:32:57 +0200] /home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-b652ef6bbce3/lib/arachni/utilities.rb:400:in `call'
[2015-04-07 15:32:57 +0200] /home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-b652ef6bbce3/lib/arachni/utilities.rb:400:in `exception_jail'
[2015-04-07 15:32:57 +0200] /home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-b652ef6bbce3/lib/arachni/browser_cluster/worker.rb:231:in `block in start'
[2015-04-07 15:32:57 +0200] --------------------------------------------------------------------------------
[2015-04-07 15:33:01 +0200] Could not spawn browser process.
[2015-04-07 15:33:01 +0200] Fontconfig error: Cannot load default config file

[2015-04-07 15:33:01 +0200] Could not respawn the browser, will try again at the next job. (Could not start the browser process.)
[2015-04-07 15:33:01 +0200] [NoMethodError] undefined method `cookies' for nil:NilClass
[2015-04-07 15:33:01 +0200] /home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-b652ef6bbce3/lib/arachni/browser_cluster/worker.rb:106:in `run_job'
[2015-04-07 15:33:01 +0200] /home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-b652ef6bbce3/lib/arachni/browser_cluster/worker.rb:233:in `block (3 levels) in start'
[2015-04-07 15:33:01 +0200] /home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-b652ef6bbce3/lib/arachni/utilities.rb:400:in `call'
[2015-04-07 15:33:01 +0200] /home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-b652ef6bbce3/lib/arachni/utilities.rb:400:in `exception_jail'
[2015-04-07 15:33:01 +0200] /home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-b652ef6bbce3/lib/arachni/browser_cluster/worker.rb:233:in `block (2 levels) in start'
[2015-04-07 15:33:01 +0200] /home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-b652ef6bbce3/lib/arachni/utilities.rb:400:in `call'
[2015-04-07 15:33:01 +0200] /home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-b652ef6bbce3/lib/arachni/utilities.rb:400:in `exception_jail'
[2015-04-07 15:33:01 +0200] /home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-b652ef6bbce3/lib/arachni/browser_cluster/worker.rb:231:in `block in start'
[2015-04-07 15:33:01 +0200] 
[2015-04-07 15:33:01 +0200] Parent:
[2015-04-07 15:33:01 +0200] Arachni::BrowserCluster::Worker
[2015-04-07 15:33:01 +0200] 
[2015-04-07 15:33:01 +0200] Block:
[2015-04-07 15:33:01 +0200] #<Proc:0x007f27292c2430@/home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-b652ef6bbce3/lib/arachni/browser_cluster/worker.rb:233>
[2015-04-07 15:33:01 +0200] 
[2015-04-07 15:33:01 +0200] Caller:
[2015-04-07 15:33:01 +0200] /home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-b652ef6bbce3/lib/arachni/utilities.rb:400:in `exception_jail'
[2015-04-07 15:33:01 +0200] /home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-b652ef6bbce3/lib/arachni/browser_cluster/worker.rb:233:in `block (2 levels) in start'
[2015-04-07 15:33:01 +0200] /home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-b652ef6bbce3/lib/arachni/utilities.rb:400:in `call'
[2015-04-07 15:33:01 +0200] /home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-b652ef6bbce3/lib/arachni/utilities.rb:400:in `exception_jail'
[2015-04-07 15:33:01 +0200] /home/jvoisin/bench/scanners/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-b652ef6bbce3/lib/arachni/browser_cluster/worker.rb:231:in `block in start'
[2015-04-07 15:33:01 +0200] --------------------------------------------------------------------------------
```

**Comment by Zapotek** [comment]
Could you retry after increasing the max open file limit please?

**Comment by jvoisin** [comment]
It seems to fix the issue; at least, I can't reproduce it anymore.

**Comment by Zapotek** [comment]
Cool, let me know if it reappears.
