### ISSUE TITLE
Timeout has been reached, shutting down. never completes

### ISSUE THREAD

**Issue by sbehrens** [Arachni/arachni#587]
Hello,

When I run a scan and a timeout is reached, I see this message:

```
[*] Harvesting HTTP responses...
 [~] Depending on server responsiveness and network conditions this may take a while.
 [-] Timeout has been reached, shutting down.
```

I can generate a report but I cannot suspend the scan, I just see the message:

```
[~] Status: Suspending
```

Any ideas?

**Comment by Zapotek** [comment]
Can you please show me the CLI?

**Comment by sbehrens** [comment]
Here is a snippet from the log, took about 2 hours to hit this error:

```
[2015-05-18 11:19:21 -0700] BrowserCluster Worker#70324596558080: [Errno::EMFILE] Too many open files @ rb_sysopen - /Users/sbehrens/testing/arachni-2.0dev-1.0dev/bin/../system/logs/framework/error-74997.log
[2015-05-18 11:19:21 -0700] BrowserCluster Worker#70324596558080: /Users/sbehrens/testing/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-32c8ee7f6ec0/ui/cli/output.rb:77:in `initialize'
[2015-05-18 11:19:22 -0700] BrowserCluster Worker#70324596558080: /Users/sbehrens/testing/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-32c8ee7f6ec0/ui/cli/output.rb:77:in `open'
[2015-05-18 11:19:22 -0700] BrowserCluster Worker#70324596558080: /Users/sbehrens/testing/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-32c8ee7f6ec0/ui/cli/output.rb:77:in `error_log_fd'
[2015-05-18 11:19:22 -0700] BrowserCluster Worker#70324596558080: /Users/sbehrens/testing/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-32c8ee7f6ec0/ui/cli/output.rb:118:in `block in log_error'
[2015-05-18 11:19:22 -0700] BrowserCluster Worker#70324596558080: /Users/sbehrens/testing/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-32c8ee7f6ec0/ui/cli/output.rb:117:in `each'
[2015-05-18 11:19:22 -0700] BrowserCluster Worker#70324596558080: /Users/sbehrens/testing/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-32c8ee7f6ec0/ui/cli/output.rb:117:in `log_error'
[2015-05-18 11:19:22 -0700] BrowserCluster Worker#70324596558080: /Users/sbehrens/testing/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-32c8ee7f6ec0/ui/cli/output.rb:95:in `print_error'
[2015-05-18 11:19:22 -0700] BrowserCluster Worker#70324596558080: /Users/sbehrens/testing/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-32c8ee7f6ec0/ui/cli/output.rb:106:in `print_exception'
[2015-05-18 11:19:22 -0700] BrowserCluster Worker#70324596558080: /Users/sbehrens/testing/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-32c8ee7f6ec0/lib/arachni/utilities.rb:403:in `rescue in exception_jail'
[2015-05-18 11:19:22 -0700] BrowserCluster Worker#70324596558080: /Users/sbehrens/testing/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-32c8ee7f6ec0/lib/arachni/utilities.rb:400:in `exception_jail'
[2015-05-18 11:19:22 -0700] BrowserCluster Worker#70324596558080: /Users/sbehrens/testing/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-32c8ee7f6ec0/lib/arachni/browser_cluster/worker.rb:233:in `block (2 levels) in start'
[2015-05-18 11:19:22 -0700] BrowserCluster Worker#70324596558080: /Users/sbehrens/testing/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-32c8ee7f6ec0/lib/arachni/utilities.rb:400:in `call'
[2015-05-18 11:19:22 -0700] BrowserCluster Worker#70324596558080: /Users/sbehrens/testing/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-32c8ee7f6ec0/lib/arachni/utilities.rb:400:in `exception_jail'
[2015-05-18 11:19:22 -0700] BrowserCluster Worker#70324596558080: /Users/sbehrens/testing/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-32c8ee7f6ec0/lib/arachni/browser_cluster/worker.rb:231:in `block in start'
[2015-05-18 11:19:22 -0700] BrowserCluster Worker#70324596558080:
[2015-05-18 11:19:22 -0700] BrowserCluster Worker#70324596558080: Parent:
[2015-05-18 11:19:22 -0700] BrowserCluster Worker#70324596558080: Arachni::BrowserCluster::Worker
[2015-05-18 11:19:22 -0700] BrowserCluster Worker#70324596558080:
[2015-05-18 11:19:22 -0700] BrowserCluster Worker#70324596558080: Block:
[2015-05-18 11:19:22 -0700] BrowserCluster Worker#70324596558080: #<Proc:0x007feb71202c40@/Users/sbehrens/testing/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-32c8ee7f6ec0/lib/arachni/browser_cluster/worker.rb:231>
"~/testing/arachni-2.0dev-1.0dev/bin/../system/logs/framework/error-74997.log" 58L, 9955C
[2015-05-18 11:19:27 -0700] BrowserCluster Worker#70324596558080: /Users/sbehrens/testing/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-32c8ee7f6ec0/lib/arachni/browser_cluster/worker.rb:88:in `run_job'
[2015-05-18 11:19:27 -0700] BrowserCluster Worker#70324596558080: /Users/sbehrens/testing/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-32c8ee7f6ec0/lib/arachni/browser_cluster/worker.rb:233:in `block (3 levels) in start'
[2015-05-18 11:19:27 -0700] BrowserCluster Worker#70324596558080: /Users/sbehrens/testing/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-32c8ee7f6ec0/lib/arachni/utilities.rb:400:in `call'
[2015-05-18 11:19:27 -0700] BrowserCluster Worker#70324596558080: /Users/sbehrens/testing/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-32c8ee7f6ec0/lib/arachni/utilities.rb:400:in `exception_jail'
[2015-05-18 11:19:27 -0700] BrowserCluster Worker#70324596558080: /Users/sbehrens/testing/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-32c8ee7f6ec0/lib/arachni/browser_cluster/worker.rb:233:in `block (2 levels) in start'
[2015-05-18 11:19:27 -0700] BrowserCluster Worker#70324596558080: /Users/sbehrens/testing/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-32c8ee7f6ec0/lib/arachni/utilities.rb:400:in `call'
[2015-05-18 11:19:27 -0700] BrowserCluster Worker#70324596558080: /Users/sbehrens/testing/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-32c8ee7f6ec0/lib/arachni/utilities.rb:400:in `exception_jail'
[2015-05-18 11:19:27 -0700] BrowserCluster Worker#70324596558080: /Users/sbehrens/testing/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-32c8ee7f6ec0/lib/arachni/browser_cluster/worker.rb:231:in `block in start'
[2015-05-18 11:19:27 -0700] BrowserCluster Worker#70324596558080:
[2015-05-18 11:19:27 -0700] BrowserCluster Worker#70324596558080: Parent:
[2015-05-18 11:19:27 -0700] BrowserCluster Worker#70324596558080: Arachni::BrowserCluster::Worker
[2015-05-18 11:19:27 -0700] BrowserCluster Worker#70324596558080:
[2015-05-18 11:19:27 -0700] BrowserCluster Worker#70324596558080: Block:
[2015-05-18 11:19:27 -0700] BrowserCluster Worker#70324596558080: #<Proc:0x007feb6db14ee0@/Users/sbehrens/testing/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-32c8ee7f6ec0/lib/arachni/browser_cluster/worker.rb:233>
[2015-05-18 11:19:27 -0700] BrowserCluster Worker#70324596558080:
[2015-05-18 11:19:27 -0700] BrowserCluster Worker#70324596558080: Caller:
[2015-05-18 11:19:27 -0700] BrowserCluster Worker#70324596558080: /Users/sbehrens/testing/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-32c8ee7f6ec0/lib/arachni/utilities.rb:400:in `exception_jail'
[2015-05-18 11:19:27 -0700] BrowserCluster Worker#70324596558080: /Users/sbehrens/testing/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-32c8ee7f6ec0/lib/arachni/browser_cluster/worker.rb:233:in `block (2 levels) in start'
[2015-05-18 11:19:27 -0700] BrowserCluster Worker#70324596558080: /Users/sbehrens/testing/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-32c8ee7f6ec0/lib/arachni/utilities.rb:400:in `call'
[2015-05-18 11:19:27 -0700] BrowserCluster Worker#70324596558080: /Users/sbehrens/testing/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-32c8ee7f6ec0/lib/arachni/utilities.rb:400:in `exception_jail'
[2015-05-18 11:19:27 -0700] BrowserCluster Worker#70324596558080: /Users/sbehrens/testing/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-32c8ee7f6ec0/lib/arachni/browser_cluster/worker.rb:231:in `block in start'
[2015-05-18 11:19:27 -0700] BrowserCluster Worker#70324596558080: --------------------------------------------------------------------------------
[2015-05-18 11:53:14 -0700] Timeout has been reached, shutting down.
```

Here is my CLI:

```
./arachni --profile-load-filepath default.afp --report-save-path /tmp/3a411e067ad77d415218e573f887aa35.ar --plugin=autologin:url=https://www.redacted.com/globallogin,parameters='email=tester@redacted.com&password=redacted',check=. --session-check-url=http://www.redacted.com/Redacted --session-check-pattern=SignOut --scope-exclude-pattern=SignOut   --timeout 02:00:00 --http-request-redirect-limit 6 --http-user-agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:32.0) Gecko/20100101 Firefox/32.0" --scope-directory-depth-limit 4 --scope-page-limit 350  https://www.redacted.com/youraccount
```

default.afp just removes a few checks and has some auto-redundant config options.

**Comment by Zapotek** [comment]
You'll need to increase your maximum open files limit (`ulimit`) to fix this error.
As for suspending after a timeout, looking into it.

**Comment by sbehrens** [comment]
Cool, Ill set the ulimit higher and retry.

**Comment by Zapotek** [comment]
I'm confused, you didn't specify `--timeout-suspend`, did you try to manually suspend after the `--timeout` was reached and the system was in the process of shutting down?
You can't do that.

As for the error, I added some error handling. The log will not be written in those cases but at least the system won't crash.

**Comment by sbehrens** [comment]
When timeout was reached the program never exited.  it just said timeout.
I tried to ctrl+c but that didn't do anything either

**Comment by Zapotek** [comment]
If that was after the `Errno::EMFILE` error I can see that happening, it would have messed with the browser cluster.
You shouldn't have been able to try and suspend though, will look into the interface.
