### ISSUE TITLE
Unable complete test 

### ISSUE THREAD

**Issue by BabuVelu** [Arachni/arachni#599]
Support,

After long running the test  I got bellow error message.

System info:

OS : Ubuntu
Ram - 8G.B
CPU - 2 Core CPU

```
2015-06-26 09:12:47 +0000 --------------------------------------------------------------------------------
ENV:
---
CPLUS_INCLUDE_PATH: "/paas/arachni-1.1-0.5.7/bin/../system/usr/include"
GEM_HOME: "/paas/arachni-1.1-0.5.7/system/gems"
TERM: screen
SHELL: "/bin/bash"
IRBRC: "/paas/arachni-1.1-0.5.7/bin/../system/usr/lib/ruby/.irbrc"
LIBRARY_PATH: "/paas/arachni-1.1-0.5.7/bin/../system/usr/lib"
MY_RUBY_HOME: "/paas/arachni-1.1-0.5.7/bin/../system/usr/lib/ruby"
SECURITY_MONKEY_SETTINGS: "/usr/local/src/security_monkey/env-config/config-deploy.py"
USER: root
LD_LIBRARY_PATH: "/paas/arachni-1.1-0.5.7/bin/../system/usr/lib"
LS_COLORS: 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:'
SUDO_USER: balaji
SUDO_UID: '1001'
TERMCAP: "SC|screen|VT 100/ANSI X3.64 virtual terminal:\\\n\t:DO=\\E[%dB:LE=\\E[%dD:RI=\\E[%dC:UP=\\E[%dA:bs:bt=\\E[Z:\\\n\t:cd=\\E[J:ce=\\E[K:cl=\\E[H\\E[J:cm=\\E[%i%d;%dH:ct=\\E[3g:\\\n\t:do=^J:nd=\\E[C:pt:rc=\\E8:rs=\\Ec:sc=\\E7:st=\\EH:up=\\EM:\\\n\t:le=^H:bl=^G:cr=^M:it#8:ho=\\E[H:nw=\\EE:ta=^I:is=\\E)0:\\\n\t:li#33:co#209:am:xn:xv:LP:sr=\\EM:al=\\E[L:AL=\\E[%dL:\\\n\t:cs=\\E[%i%d;%dr:dl=\\E[M:DL=\\E[%dM:dc=\\E[P:DC=\\E[%dP:\\\n\t:im=\\E[4h:ei=\\E[4l:mi:IC=\\E[%d@:ks=\\E[?1h\\E=:\\\n\t:ke=\\E[?1l\\E>:vi=\\E[?25l:ve=\\E[34h\\E[?25h:vs=\\E[34l:\\\n\t:ti=\\E[?1049h:te=\\E[?1049l:us=\\E[4m:ue=\\E[24m:so=\\E[3m:\\\n\t:se=\\E[23m:mb=\\E[5m:md=\\E[1m:mr=\\E[7m:me=\\E[m:ms:\\\n\t:Co#8:pa#64:AF=\\E[3%dm:AB=\\E[4%dm:op=\\E[39;49m:AX:\\\n\t:vb=\\Eg:G0:as=\\E(0:ae=\\E(B:\\\n\t:ac=\\140\\140aaffggjjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~..--++,,hhII00:\\\n\t:po=\\E[5i:pf=\\E[4i:Km=\\E[M:k0=\\E[10~:k1=\\EOP:k2=\\EOQ:\\\n\t:k3=\\EOR:k4=\\EOS:k5=\\E[15~:k6=\\E[17~:k7=\\E[18~:\\\n\t:k8=\\E[19~:k9=\\E[20~:k;=\\E[21~:F1=\\E[23~:F2=\\E[24~:\\\n\t:F3=\\E[1;2P:F4=\\E[1;2Q:F5=\\E[1;2R:F6=\\E[1;2S:\\\n\t:F7=\\E[15;2~:F8=\\E[17;2~:F9=\\E[18;2~:FA=\\E[19;2~:kb=\x7F:\\\n\t:K2=\\EOE:kB=\\E[Z:kF=\\E[1;2B:kR=\\E[1;2A:*4=\\E[3;2~:\\\n\t:*7=\\E[1;2F:#2=\\E[1;2H:#3=\\E[2;2~:#4=\\E[1;2D:%c=\\E[6;2~:\\\n\t:%e=\\E[5;2~:%i=\\E[1;2C:kh=\\E[1~:@1=\\E[1~:kH=\\E[4~:\\\n\t:@7=\\E[4~:kN=\\E[6~:kP=\\E[5~:kI=\\E[2~:kD=\\E[3~:ku=\\EOA:\\\n\t:kd=\\EOB:kr=\\EOC:kl=\\EOD:km:"
USERNAME: root
MAIL: "/var/mail/root"
PATH: "/paas/arachni-1.1-0.5.7/system/gems/bin:/paas/arachni-1.1-0.5.7/bin/../system/../bin:/paas/arachni-1.1-0.5.7/bin/../system/usr/bin:/paas/arachni-1.1-0.5.7/bin/../system/gems/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
STY: 1466.pts-0.tpaas-ss
C_INCLUDE_PATH: "/paas/arachni-1.1-0.5.7/bin/../system/usr/include"
PWD: "/paas/arachni-1.1-0.5.7/bin"
ARACHNI_WEBUI_LOGDIR: "/paas/arachni-1.1-0.5.7/bin/../system/logs/webui"
LANG: en_US.UTF-8
ARACHNI_FRAMEWORK_LOGDIR: "/paas/arachni-1.1-0.5.7/bin/../system/logs/framework"
SHLVL: '2'
SUDO_COMMAND: "/bin/bash"
HOME: "/root"
RAILS_ENV: production
DYLD_LIBRARY_PATH: "/paas/arachni-1.1-0.5.7/bin/../system/usr/lib"
LOGNAME: root
WINDOW: '0'
GEM_PATH: "/paas/arachni-1.1-0.5.7/bin/../system/gems"
LESSOPEN: "| /usr/bin/lesspipe %s"
SUDO_GID: '1001'
RUBYLIB: "/paas/arachni-1.1-0.5.7/system/gems/gems/bundler-1.9.5/lib:/paas/arachni-1.1-0.5.7/bin/../system/usr/lib/ruby:/paas/arachni-1.1-0.5.7/bin/../system/usr/lib/ruby/site_ruby/2.2.0:/paas/arachni-1.1-0.5.7/bin/../system/usr/lib/ruby/2.2.0:/paas/arachni-1.1-0.5.7/bin/../system/usr/lib/ruby/2.2.0/x86_64-linux:/paas/arachni-1.1-0.5.7/bin/../system/usr/lib/ruby/site_ruby/2.2.0/x86_64-linux"
RUBY_VERSION: ruby-2.2.2
LESSCLOSE: "/usr/bin/lesspipe %s %s"
RACK_ENV: development
BUNDLE_GEMFILE: "/paas/arachni-1.1-0.5.7/system/arachni-ui-web/Gemfile"
_ORIGINAL_GEM_PATH: "/paas/arachni-1.1-0.5.7/bin/../system/gems"
BUNDLE_BIN_PATH: "/paas/arachni-1.1-0.5.7/system/gems/gems/bundler-1.9.5/bin/bundle"
RUBYOPT: "-rbundler/setup"
MANPATH: "/paas/arachni-1.1-0.5.7/system/gems/gems/kramdown-1.4.1/man"
BUNDLE_ORIG_MANPATH: "/paas/arachni-1.1-0.5.7/system/gems/gems/kramdown-1.4.1/man"
--------------------------------------------------------------------------------
OPTIONS:
---
session: {}
datastore:
  token: 16b01ae1866aa57251fb634b4bb6c6a9
input:
  values:
    "(?i-mx:name)": arachni_name
    "(?i-mx:user)": arachni_user
    "(?i-mx:usr)": arachni_user
    "(?i-mx:pass)": 5543!%arachni_secret
    "(?i-mx:txt)": arachni_text
    "(?i-mx:num)": '132'
    "(?i-mx:amount)": '100'
    "(?i-mx:mail)": arachni@email.gr
    "(?i-mx:account)": '12'
    "(?i-mx:id)": '1'
  default_values:
    "(?i-mx:name)": arachni_name
    "(?i-mx:user)": arachni_user
    "(?i-mx:usr)": arachni_user
    "(?i-mx:pass)": 5543!%arachni_secret
    "(?i-mx:txt)": arachni_text
    "(?i-mx:num)": '132'
    "(?i-mx:amount)": '100'
    "(?i-mx:mail)": arachni@email.gr
    "(?i-mx:account)": '12'
    "(?i-mx:id)": '1'
  without_defaults: true
  force: false
scope:
  redundant_path_patterns: {}
  dom_depth_limit: 5
  exclude_path_patterns: []
  exclude_content_patterns: []
  include_path_patterns: []
  restrict_paths: []
  extend_paths: []
  url_rewrites: {}
browser_cluster:
  pool_size: 6
  job_timeout: 15
  worker_time_to_live: 100
  ignore_images: false
  screen_width: 1600
  screen_height: 1200
http:
  user_agent: Arachni/v1.1
  request_timeout: 10000
  request_redirect_limit: 5
  request_concurrency: 20
  request_queue_size: 500
  request_headers: {}
  response_max_size: 500000
  cookies: {}
audit:
  parameter_values: true
  exclude_vector_patterns: []
  include_vector_patterns: []
  link_templates: []
  links: true
  forms: true
  cookies: true
  jsons: true
  xmls: true
checks:
- allowed_methods
- backdoors
- backup_directories
- backup_files
- captcha
- code_injection
- code_injection_php_input_wrapper
- code_injection_timing
- common_directories
- common_files
- cookie_set_for_parent_domain
- credit_card
- csrf
- cvs_svn_users
- directory_listing
- emails
- file_inclusion
- form_upload
- hsts
- htaccess_limit
- html_objects
- http_only_cookies
- http_put
- insecure_client_access_policy
- insecure_cookies
- insecure_cors_policy
- insecure_cross_domain_policy_access
- insecure_cross_domain_policy_headers
- interesting_responses
- ldap_injection
- localstart_asp
- mixed_resource
- no_sql_injection
- no_sql_injection_differential
- origin_spoof_access_restriction_bypass
- os_cmd_injection
- os_cmd_injection_timing
- password_autocomplete
- path_traversal
- private_ip
- response_splitting
- rfi
- session_fixation
- source_code_disclosure
- sql_injection
- sql_injection_differential
- sql_injection_timing
- ssn
- trainer
- unencrypted_password_forms
- unvalidated_redirect
- unvalidated_redirect_dom
- webdav
- x_frame_options
- xpath_injection
- xss
- xss_dom
- xss_dom_inputs
- xss_dom_script_context
- xss_event
- xss_path
- xss_script_context
- xss_tag
- xst
- xxe
platforms: []
plugins:
  autothrottle: {}
  discovery: {}
  healthmap: {}
  timing_attacks: {}
  uniformity: {}
no_fingerprinting: false
authorized_by: 
url: https://identity-dev1.trimble.com/trimble-identity/identity
--------------------------------------------------------------------------------
[2015-06-26 09:12:47 +0000] [NoMethodError] undefined method `master' for nil:NilClass
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/browser_cluster/job.rb:104:in `save_result'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/browser_cluster/jobs/resource_exploration/event_trigger.rb:32:in `block in run'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/support/mixins/observable.rb:76:in `call'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/support/mixins/observable.rb:76:in `block (3 levels) in notify_observers'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/utilities.rb:400:in `call'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/utilities.rb:400:in `exception_jail'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/support/mixins/observable.rb:76:in `block (2 levels) in notify_observers'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/support/mixins/observable.rb:75:in `each'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/support/mixins/observable.rb:75:in `block in notify_observers'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/support/mixins/observable.rb:74:in `notify_observers'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/support/mixins/observable.rb:42:in `block (2 levels) in advertise'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/browser.rb:1454:in `capture'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/browser.rb:1309:in `request_handler'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/browser.rb:144:in `block (3 levels) in initialize'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/utilities.rb:400:in `call'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/utilities.rb:400:in `exception_jail'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/browser.rb:144:in `block (2 levels) in initialize'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/browser.rb:144:in `block in initialize'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/http/proxy_server.rb:245:in `call'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/http/proxy_server.rb:245:in `perform_proxy_request'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/http/proxy_server.rb:123:in `do_POST'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/usr/lib/ruby/2.2.0/webrick/httpproxy.rb:117:in `proxy_service'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/http/proxy_server.rb:217:in `call'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/http/proxy_server.rb:217:in `service'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/usr/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/usr/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
[2015-06-26 09:12:47 +0000] 
[2015-06-26 09:12:47 +0000] Parent:
[2015-06-26 09:12:47 +0000] Arachni::BrowserCluster::Worker
[2015-06-26 09:12:47 +0000] 
[2015-06-26 09:12:47 +0000] Block:
[2015-06-26 09:12:47 +0000] #<Proc:0x007fb5761dc968@/paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/support/mixins/observable.rb:76>
[2015-06-26 09:12:47 +0000] 
[2015-06-26 09:12:47 +0000] Caller:
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/utilities.rb:400:in `exception_jail'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/support/mixins/observable.rb:76:in `block (2 levels) in notify_observers'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/support/mixins/observable.rb:75:in `each'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/support/mixins/observable.rb:75:in `block in notify_observers'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/support/mixins/observable.rb:74:in `notify_observers'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/support/mixins/observable.rb:42:in `block (2 levels) in advertise'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/browser.rb:1454:in `capture'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/browser.rb:1309:in `request_handler'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/browser.rb:144:in `block (3 levels) in initialize'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/utilities.rb:400:in `call'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/utilities.rb:400:in `exception_jail'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/browser.rb:144:in `block (2 levels) in initialize'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/browser.rb:144:in `block in initialize'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/http/proxy_server.rb:245:in `call'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/http/proxy_server.rb:245:in `perform_proxy_request'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/http/proxy_server.rb:123:in `do_POST'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/usr/lib/ruby/2.2.0/webrick/httpproxy.rb:117:in `proxy_service'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/http/proxy_server.rb:217:in `call'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/http/proxy_server.rb:217:in `service'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/usr/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
[2015-06-26 09:12:47 +0000] /paas/arachni-1.1-0.5.7/system/usr/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
[2015-06-26 09:12:47 +0000] --------------------------------------------------------------------------------
```

**Comment by Zapotek** [comment]
Hello,

What do you mean by "unable to complete test"?
Did the system crash? If it did it wasn't because of this error.

Cheers

**Comment by BabuVelu** [comment]
Hello,

Yes. Unable to complete the test. 
![screen shot 2015-06-30 at 4 14 45 pm](https://cloud.githubusercontent.com/assets/13116834/8429225/455a62fa-1f43-11e5-8c69-610c25118ca6.png)

**Comment by Zapotek** [comment]
I don't think you're right, it says right there that the scan completed fine.

**Comment by BabuVelu** [comment]
Yes, you are right. The scan completed.
