### ISSUE TITLE
Why there is always a problem like this?(arachni)

### ISSUE THREAD

**Issue by linux-info** [Arachni/arachni#607]
```
2015-07-27 01:18:22 +0800 --------------------------------------------------------------------------------
ENV:
---
SSH_AGENT_PID: '3716'
CLUTTER_IM_MODULE: xim
GEM_HOME: "/usr/share/arachni/system/gems"
GPG_AGENT_INFO: "/root/.cache/keyring-AU1U4F/gpg:0:1"
TERM: xterm
SHELL: "/bin/bash"
XDG_SESSION_COOKIE: c05cac21bc83e788e05a741155b1dddd-1437930822.533218-2065414133
IRBRC: "/usr/share/arachni/bin/../system/usr/lib/ruby/.irbrc"
WINDOWID: '60817412'
GNOME_KEYRING_CONTROL: "/root/.cache/keyring-AU1U4F"
MY_RUBY_HOME: "/usr/share/arachni/bin/../system/usr/lib/ruby"
USER: root
LD_LIBRARY_PATH: "/usr/share/arachni/bin/../system/usr/lib"
LS_COLORS: 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:'
SSH_AUTH_SOCK: "/root/.cache/keyring-AU1U4F/ssh"
SESSION_MANAGER: local/kali:@/tmp/.ICE-unix/3608,unix/kali:/tmp/.ICE-unix/3608
USERNAME: root
PATH: "/usr/share/arachni/system/gems/bin:/usr/share/arachni/bin/../system/../bin:/usr/share/arachni/bin/../system/usr/bin:/usr/share/arachni/bin/../system/gems/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
DESKTOP_SESSION: default
QT_IM_MODULE: xim
PWD: "/usr/share/arachni/bin"
XMODIFIERS: "@im=SCIM"
ARACHNI_WEBUI_LOGDIR: "/usr/share/arachni/bin/../system/logs/webui"
GNOME_KEYRING_PID: '3590'
LANG: en_US.UTF-8
GDM_LANG: en_US.UTF-8
ARACHNI_FRAMEWORK_LOGDIR: "/usr/share/arachni/bin/../system/logs/framework"
GDMSESSION: default
SHLVL: '2'
HOME: "/root"
RAILS_ENV: production
GNOME_DESKTOP_SESSION_ID: this-is-deprecated
DYLD_LIBRARY_PATH: "/usr/share/arachni/bin/../system/usr/lib:"
LOGNAME: root
GEM_PATH: "/usr/share/arachni/bin/../system/gems"
QT4_IM_MODULE: xim
XDG_DATA_DIRS: "/usr/share/gnome:/usr/local/share/:/usr/share/"
DBUS_SESSION_BUS_ADDRESS: unix:abstract=/tmp/dbus-G8V4Ati6qE,guid=e751874bf00ee11cd784fb0f55b51548
WINDOWPATH: '7'
TEXTDOMAIN: im-config
DISPLAY: ":0.0"
GTK_IM_MODULE: scim
RUBYLIB: "/usr/share/arachni/system/gems/gems/bundler-1.7.8/lib:/usr/share/arachni/bin/../system/usr/lib/ruby:/usr/share/arachni/bin/../system/usr/lib/ruby/site_ruby/2.1.0:/usr/share/arachni/bin/../system/usr/lib/ruby/2.1.0:/usr/share/arachni/bin/../system/usr/lib/ruby/2.1.0/x86_64-linux:/usr/share/arachni/bin/../system/usr/lib/ruby/site_ruby/2.1.0/x86_64-linux"
RUBY_VERSION: ruby-2.1.5
TEXTDOMAINDIR: "/usr/share/locale/"
COLORTERM: gnome-terminal
XAUTHORITY: "/var/run/gdm3/auth-for-root-znTjKr/database"
RACK_ENV: development
BUNDLE_GEMFILE: "/usr/share/arachni/system/arachni-ui-web/Gemfile"
_ORIGINAL_GEM_PATH: "/usr/share/arachni/bin/../system/gems"
BUNDLE_BIN_PATH: "/usr/share/arachni/system/gems/gems/bundler-1.7.8/bin/bundle"
RUBYOPT: "-rbundler/setup"
MANPATH: "/usr/share/arachni/system/gems/gems/kramdown-1.4.1/man"
BUNDLE_ORIG_MANPATH: "/usr/share/arachni/system/gems/gems/kramdown-1.4.1/man"
--------------------------------------------------------------------------------
OPTIONS:
---
http:
  user_agent: Arachni/v1.0.6
  request_timeout: 50000
  request_redirect_limit: 5
  request_concurrency: 20
  request_queue_size: 500
  request_headers: {}
  cookies: {}
session: {}
browser_cluster:
  pool_size: 6
  job_timeout: 120
  worker_time_to_live: 100
  ignore_images: false
  screen_width: 1600
  screen_height: 1200
audit:
  exclude_vector_patterns: []
  include_vector_patterns: []
  link_templates: []
  links: true
  forms: true
  cookies: true
datastore:
  token: 1aede9c08b539b2cd8a310a82b6ff82b
input:
  values:
    "(?i-mx:name)": arachni_name
    "(?i-mx:user)": arachni_user
    "(?i-mx:usr)": arachni_user
    "(?i-mx:pass)": 5543!%arachni_secret
    "(?i-mx:txt)": arachni_text
    "(?i-mx:num)": '132'
    "(?i-mx:amount)": '100'
    "(?i-mx:mail)": arachni@email.gr
    "(?i-mx:account)": '12'
    "(?i-mx:id)": '1'
  default_values:
    "(?i-mx:name)": arachni_name
    "(?i-mx:user)": arachni_user
    "(?i-mx:usr)": arachni_user
    "(?i-mx:pass)": 5543!%arachni_secret
    "(?i-mx:txt)": arachni_text
    "(?i-mx:num)": '132'
    "(?i-mx:amount)": '100'
    "(?i-mx:mail)": arachni@email.gr
    "(?i-mx:account)": '12'
    "(?i-mx:id)": '1'
  without_defaults: true
  force: false
scope:
  redundant_path_patterns: {}
  dom_depth_limit: 10
  exclude_path_patterns: []
  exclude_content_patterns: []
  include_path_patterns: []
  restrict_paths: []
  extend_paths: []
  url_rewrites: {}
checks:
- sql_injection
- sql_injection_differential
- sql_injection_timing
platforms: []
plugins:
  autothrottle: {}
  discovery: {}
  healthmap: {}
  timing_attacks: {}
  uniformity: {}
no_fingerprinting: false
authorized_by: 
url: http://www.cnhxcc.com.cn/
--------------------------------------------------------------------------------
[2015-07-27 01:18:22 +0800] [NoMethodError] undefined method `marquee' for #<Watir::Browser:0x000000054fe0e8>
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser/element_locator.rb:68:in `locate'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser.rb:573:in `fire_event'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser.rb:535:in `trigger_event'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser_cluster/jobs/resource_exploration/event_trigger.rb:35:in `run'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser_cluster/job.rb:88:in `configure_and_run'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser_cluster/worker.rb:92:in `block (2 levels) in run_job'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/utilities.rb:395:in `call'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/utilities.rb:395:in `exception_jail'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser_cluster/worker.rb:90:in `block in run_job'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser.rb:949:in `call'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser.rb:949:in `block in with_timeout'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/usr/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/usr/lib/ruby/2.1.0/timeout.rb:35:in `block in catch'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/usr/lib/ruby/2.1.0/timeout.rb:35:in `catch'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/usr/lib/ruby/2.1.0/timeout.rb:35:in `catch'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/usr/lib/ruby/2.1.0/timeout.rb:106:in `timeout'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser.rb:948:in `with_timeout'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser_cluster/worker.rb:89:in `run_job'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser_cluster/worker.rb:229:in `block (3 levels) in start'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/utilities.rb:395:in `call'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/utilities.rb:395:in `exception_jail'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser_cluster/worker.rb:229:in `block (2 levels) in start'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/utilities.rb:395:in `call'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/utilities.rb:395:in `exception_jail'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser_cluster/worker.rb:227:in `block in start'
[2015-07-27 01:18:22 +0800] 
[2015-07-27 01:18:22 +0800] Parent:
[2015-07-27 01:18:22 +0800] Arachni::BrowserCluster::Worker
[2015-07-27 01:18:22 +0800] 
[2015-07-27 01:18:22 +0800] Block:
[2015-07-27 01:18:22 +0800] #<Proc:0x00000004f61338@/usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser_cluster/worker.rb:90>
[2015-07-27 01:18:22 +0800] 
[2015-07-27 01:18:22 +0800] Caller:
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/utilities.rb:395:in `exception_jail'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser_cluster/worker.rb:90:in `block in run_job'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser.rb:949:in `call'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser.rb:949:in `block in with_timeout'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/usr/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/usr/lib/ruby/2.1.0/timeout.rb:35:in `block in catch'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/usr/lib/ruby/2.1.0/timeout.rb:35:in `catch'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/usr/lib/ruby/2.1.0/timeout.rb:35:in `catch'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/usr/lib/ruby/2.1.0/timeout.rb:106:in `timeout'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser.rb:948:in `with_timeout'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser_cluster/worker.rb:89:in `run_job'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser_cluster/worker.rb:229:in `block (3 levels) in start'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/utilities.rb:395:in `call'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/utilities.rb:395:in `exception_jail'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser_cluster/worker.rb:229:in `block (2 levels) in start'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/utilities.rb:395:in `call'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/utilities.rb:395:in `exception_jail'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser_cluster/worker.rb:227:in `block in start'
[2015-07-27 01:18:22 +0800] --------------------------------------------------------------------------------
[2015-07-27 01:18:22 +0800] [NoMethodError] undefined method `marquee' for #<Watir::Browser:0x000000054fe0e8>
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser/element_locator.rb:68:in `locate'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser.rb:573:in `fire_event'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser.rb:535:in `trigger_event'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser_cluster/jobs/resource_exploration/event_trigger.rb:35:in `run'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser_cluster/job.rb:88:in `configure_and_run'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser_cluster/worker.rb:92:in `block (2 levels) in run_job'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/utilities.rb:395:in `call'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/utilities.rb:395:in `exception_jail'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser_cluster/worker.rb:90:in `block in run_job'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser.rb:949:in `call'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser.rb:949:in `block in with_timeout'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/usr/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/usr/lib/ruby/2.1.0/timeout.rb:35:in `block in catch'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/usr/lib/ruby/2.1.0/timeout.rb:35:in `catch'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/usr/lib/ruby/2.1.0/timeout.rb:35:in `catch'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/usr/lib/ruby/2.1.0/timeout.rb:106:in `timeout'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser.rb:948:in `with_timeout'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser_cluster/worker.rb:89:in `run_job'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser_cluster/worker.rb:229:in `block (3 levels) in start'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/utilities.rb:395:in `call'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/utilities.rb:395:in `exception_jail'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser_cluster/worker.rb:229:in `block (2 levels) in start'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/utilities.rb:395:in `call'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/utilities.rb:395:in `exception_jail'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser_cluster/worker.rb:227:in `block in start'
[2015-07-27 01:18:22 +0800] 
[2015-07-27 01:18:22 +0800] Parent:
[2015-07-27 01:18:22 +0800] Arachni::BrowserCluster::Worker
[2015-07-27 01:18:22 +0800] 
[2015-07-27 01:18:22 +0800] Block:
[2015-07-27 01:18:22 +0800] #<Proc:0x00000003feba48@/usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser_cluster/worker.rb:90>
[2015-07-27 01:18:22 +0800] 
[2015-07-27 01:18:22 +0800] Caller:
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/utilities.rb:395:in `exception_jail'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser_cluster/worker.rb:90:in `block in run_job'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser.rb:949:in `call'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser.rb:949:in `block in with_timeout'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/usr/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/usr/lib/ruby/2.1.0/timeout.rb:35:in `block in catch'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/usr/lib/ruby/2.1.0/timeout.rb:35:in `catch'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/usr/lib/ruby/2.1.0/timeout.rb:35:in `catch'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/usr/lib/ruby/2.1.0/timeout.rb:106:in `timeout'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser.rb:948:in `with_timeout'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser_cluster/worker.rb:89:in `run_job'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser_cluster/worker.rb:229:in `block (3 levels) in start'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/utilities.rb:395:in `call'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/utilities.rb:395:in `exception_jail'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser_cluster/worker.rb:229:in `block (2 levels) in start'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/utilities.rb:395:in `call'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/utilities.rb:395:in `exception_jail'
[2015-07-27 01:18:22 +0800] /usr/share/arachni/system/gems/gems/arachni-1.0.6/lib/arachni/browser_cluster/worker.rb:227:in `block in start'
[2015-07-27 01:18:22 +0800] --------------------------------------------------------------------------------
```

**Comment by Zapotek** [comment]
You're a few version behind, this issue has been fixed for a while.
Can you please [download](http://www.arachni-scanner.com/download/) the latest version and retry?

Cheers

**Comment by linux-info** [comment]
thanks you

在 2015-07-27 06:53:41，"Tasos Laskos" <notifications@github.com> 写道：


You're a few version behind, this issue has been fixed for a while.
Can you please download the latest version and retry?

Cheers

**Comment by linux-info** [comment]
i install it like this : apt-get install arachni

在 2015-07-27 06:53:41，"Tasos Laskos" <notifications@github.com> 写道：


You're a few version behind, this issue has been fixed for a while.
Can you please download the latest version and retry?

Cheers

**Comment by Zapotek** [comment]
I only provide the official packages available from the official website, I've no control over what distributions provide.
