### ISSUE TITLE
OSX Installation Issues: dyld: Library not loaded: /Users/zapotek/arachni-build-dir/arachni/system/usr/lib/libruby.2.2.0.dylib

### ISSUE THREAD

**Issue by bom-d-van** [Arachni/arachni#619]
![image](https://cloud.githubusercontent.com/assets/459505/10248317/3aabad5c-6951-11e5-81b7-f451451b8129.png)

**Comment by Zapotek** [comment]
OK, that's strange it kept the path at the time of packaging, instead of calculating it during runtime.
Looking into it.

**Comment by Zapotek** [comment]
Any chance I can see the whole thing?
Preferably as text?

**Comment by bom-d-van** [comment]
I just download and unarchive it. Didn't do anything special.

╭─ ~/Downloads/arachni-1.2.1-0.5.7.1 ‹go1.5.1› <2015-10-02 22:10:55>
╰─$ ls bin
arachni                     arachni_rpc                 arachni_web
        arachni_web_script
arachni_console             arachni_rpcd
 arachni_web_change_password arachni_web_task
arachni_multi               arachni_rpcd_monitor
 arachni_web_create_user     readlink_f.sh
arachni_reporter            arachni_script              arachni_web_import
arachni_restore             arachni_shell
arachni_web_scan_import
╭─ ~/Downloads/arachni-1.2.1-0.5.7.1 ‹go1.5.1› <2015-10-02 22:10:58>
╰─$ bin/arachni_web
dyld: Library not loaded:
/Users/zapotek/arachni-build-dir/arachni/system/usr/lib/libruby.2.2.0.dylib
  Referenced from:
/Users/bom_d_van/Downloads/arachni-1.2.1-0.5.7.1/bin/../system/usr/bin/ruby
  Reason: image not found
[1]    49876 trace trap  bin/arachni_web

[image: Inline image 1]

On Fri, Oct 2, 2015 at 10:08 PM, Tasos Laskos <notifications@github.com>
wrote:

> Any chance I can see the whole thing?
> Preferably as text?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Arachni/arachni/issues/619#issuecomment-145031538>.
>



-- 
Van Hu
Go Developer at The Plant

**Comment by Zapotek** [comment]
I show the end of an exception's output in your screenshot, it could be useful.
Also, are the [nightlies](http://downloads.arachni-scanner.com/nightlies/) giving you the same problem?

**Comment by bom-d-van** [comment]
Do you mean this:

```
╭─ ~/Downloads/arachni-1.2.1-0.5.7.1 ‹go1.5.1› <2015-10-02 21:57:18>
╰─$ arachni
/Users/bom_d_van/Downloads/arachni-1.2.1-0.5.7.1/system/gems/gems/ffi-1.9.6/lib/ffi/library.rb:133:in `block in ffi_lib': Could not open library 'libcurl': dlopen(libcurl, 10): image not found. (LoadError)
Could not open library 'libcurl.dylib': dlopen(libcurl.dylib, 10): Symbol not found: _sqlite3_intarray_bind
  Referenced from: /System/Library/Frameworks/CoreData.framework/Versions/A/CoreData
  Expected in: /Users/bom_d_van/Downloads/arachni-1.2.1-0.5.7.1/bin/../system/usr/lib/libsqlite3.dylib
 in /System/Library/Frameworks/CoreData.framework/Versions/A/CoreData.
Could not open library 'libcurl.so.4': dlopen(libcurl.so.4, 10): image not found.
Could not open library 'libcurl.so.4.dylib': dlopen(libcurl.so.4.dylib, 10): image not found
	from /Users/bom_d_van/Downloads/arachni-1.2.1-0.5.7.1/system/gems/gems/ffi-1.9.6/lib/ffi/library.rb:100:in `map'
	from /Users/bom_d_van/Downloads/arachni-1.2.1-0.5.7.1/system/gems/gems/ffi-1.9.6/lib/ffi/library.rb:100:in `ffi_lib'
	from /Users/bom_d_van/Downloads/arachni-1.2.1-0.5.7.1/system/gems/gems/ethon-0.7.4/lib/ethon/curls/settings.rb:6:in `<module:Curl>'
	from /Users/bom_d_van/Downloads/arachni-1.2.1-0.5.7.1/system/gems/gems/ethon-0.7.4/lib/ethon/curls/settings.rb:2:in `<module:Ethon>'
	from /Users/bom_d_van/Downloads/arachni-1.2.1-0.5.7.1/system/gems/gems/ethon-0.7.4/lib/ethon/curls/settings.rb:1:in `<top (required)>'
	from /Users/bom_d_van/Downloads/arachni-1.2.1-0.5.7.1/system/gems/gems/ethon-0.7.4/lib/ethon/curl.rb:27:in `require'
	from /Users/bom_d_van/Downloads/arachni-1.2.1-0.5.7.1/system/gems/gems/ethon-0.7.4/lib/ethon/curl.rb:27:in `<module:Curl>'
	from /Users/bom_d_van/Downloads/arachni-1.2.1-0.5.7.1/system/gems/gems/ethon-0.7.4/lib/ethon/curl.rb:13:in `<module:Ethon>'
	from /Users/bom_d_van/Downloads/arachni-1.2.1-0.5.7.1/system/gems/gems/ethon-0.7.4/lib/ethon/curl.rb:8:in `<top (required)>'
	from /Users/bom_d_van/Downloads/arachni-1.2.1-0.5.7.1/system/gems/gems/ethon-0.7.4/lib/ethon.rb:11:in `require'
	from /Users/bom_d_van/Downloads/arachni-1.2.1-0.5.7.1/system/gems/gems/ethon-0.7.4/lib/ethon.rb:11:in `<top (required)>'
	from /Users/bom_d_van/Downloads/arachni-1.2.1-0.5.7.1/system/gems/gems/typhoeus-0.6.9/lib/typhoeus.rb:2:in `require'
	from /Users/bom_d_van/Downloads/arachni-1.2.1-0.5.7.1/system/gems/gems/typhoeus-0.6.9/lib/typhoeus.rb:2:in `<top (required)>'
	from /Users/bom_d_van/Downloads/arachni-1.2.1-0.5.7.1/system/gems/gems/arachni-1.2.1/lib/arachni/http/client.rb:9:in `require'
	from /Users/bom_d_van/Downloads/arachni-1.2.1-0.5.7.1/system/gems/gems/arachni-1.2.1/lib/arachni/http/client.rb:9:in `<top (required)>'
	from /Users/bom_d_van/Downloads/arachni-1.2.1-0.5.7.1/system/gems/gems/arachni-1.2.1/lib/arachni/http.rb:9:in `require_relative'
	from /Users/bom_d_van/Downloads/arachni-1.2.1-0.5.7.1/system/gems/gems/arachni-1.2.1/lib/arachni/http.rb:9:in `<top (required)>'
	from /Users/bom_d_van/Downloads/arachni-1.2.1-0.5.7.1/system/gems/gems/arachni-1.2.1/lib/arachni/framework.rb:32:in `require'
	from /Users/bom_d_van/Downloads/arachni-1.2.1-0.5.7.1/system/gems/gems/arachni-1.2.1/lib/arachni/framework.rb:32:in `<module:Arachni>'
	from /Users/bom_d_van/Downloads/arachni-1.2.1-0.5.7.1/system/gems/gems/arachni-1.2.1/lib/arachni/framework.rb:20:in `<top (required)>'
	from /Users/bom_d_van/Downloads/arachni-1.2.1-0.5.7.1/system/gems/gems/arachni-1.2.1/lib/arachni.rb:58:in `require_relative'
	from /Users/bom_d_van/Downloads/arachni-1.2.1-0.5.7.1/system/gems/gems/arachni-1.2.1/lib/arachni.rb:58:in `<top (required)>'
	from /Users/bom_d_van/Downloads/arachni-1.2.1-0.5.7.1/system/gems/gems/arachni-1.2.1/ui/cli/framework.rb:9:in `require_relative'
	from /Users/bom_d_van/Downloads/arachni-1.2.1-0.5.7.1/system/gems/gems/arachni-1.2.1/ui/cli/framework.rb:9:in `<top (required)>'
	from /Users/bom_d_van/Downloads/arachni-1.2.1-0.5.7.1/system/gems/gems/arachni-1.2.1/bin/arachni:10:in `require_relative'
	from /Users/bom_d_van/Downloads/arachni-1.2.1-0.5.7.1/system/gems/gems/arachni-1.2.1/bin/arachni:10:in `<top (required)>'
	from /Users/bom_d_van/Downloads/arachni-1.2.1-0.5.7.1/bin/../system/arachni-ui-web/bin/arachni:16:in `load'
	from /Users/bom_d_van/Downloads/arachni-1.2.1-0.5.7.1/bin/../system/arachni-ui-web/bin/arachni:16:in `<main>'
```

**Comment by Zapotek** [comment]
Yep, thank you.

**Comment by Zapotek** [comment]
I forgot to ask, which OSX version are you using?

**Comment by bom-d-van** [comment]
El Captain Version 10.11

**Comment by Zapotek** [comment]
I see, I haven't tried that one yet, didn't even know it was out tbh.
Lucky you opened this issue now, I was preparing the next release, it would have been really embarrassing pushing a broken package.

Upgrading to 10.11 now, I'll keep you posted on my progress.

Cheers

**Comment by bom-d-van** [comment]
Thanks.

**Comment by Zapotek** [comment]
I'm assuming the [nightlies](http://downloads.arachni-scanner.com/nightlies/) gave you the same trouble right?

**Comment by Zapotek** [comment]
I guess the path of that lib is always hardcoded, but I'm setting `DYLD_LIBRARY_PATH` which should have taken precedence.
For some reason that doesn't work for 10.11.

Not 100% on the above, I'm still looking.

**Comment by Zapotek** [comment]
Crap, I was right, this is a new security feature for 10.11; you can't export `DYLD_LIBRARY_PATH` to subshells. 
I think I solved it by setting `DYLD_FALLBACK_LIBRARY_PATH` instead, but there's another issue in the library that handles a big chunk of extensions: https://github.com/ffi/ffi/issues/461

El Capitan seems to be causing problems all around, I can't do much but wait for the FFI issue for now.

**Comment by colinmo** [comment]
I've managed to get it working by setting `DYLD_FALLBACK_LIBRARY_PATH` as you state, then symlinking `system/usr/lib/libsqlite3.dylib` to my Mac OS install at `/usr/lib`, and _then_ creating a `/Users/zapotek/...` directory symlinked to my arachni directory as per the next error for `libcrypto`

It's ugly and unpleasant (and documented to be removed as soon as the base code is repaired), but I've got incoming code I need to hammer and I'd like arachni to be around to do it.

**Comment by Zapotek** [comment]
@colinmo I'm not sure that I would trust this workaround but if it works for you then that's fair enough.

For the time being I've just configured the packages to notify that OSX 10.11 is not supported and exit.
Once the FFI issue get's resolved things should get back to normal.

**Comment by Zapotek** [comment]
I sorted out the OSX issues, the [nightlies](http://downloads.arachni-scanner.com/nightlies/) should now work on >= 10.9.

**Comment by colinmo** [comment]
Thanks. Oddly even with the new version (downloaded from nightlies), it still looks for files under /Users/zapotek/. 

$ bin/arachni_web
/Users/[redacted]/Applications/arachni-2.0dev-1.0dev/system/usr/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(/Users/[redacted]/Applications/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/x86_64-darwin13/digest/sha1.bundle, 9): Library not loaded: /Users/zapotek/arachni-build-dir/arachni/system/usr/lib/libcrypto.1.0.0.dylib (LoadError)

**Comment by Zapotek** [comment]
Does `./bin/arachni` work for you?

**Comment by Zapotek** [comment]
I think I fixed it, should be the last one.

Uploading nightlies now but I would appreciate it if you verified it for me by replacing the `arachni_web` contents with:

```bash
#!/usr/bin/env bash

source "$(dirname $0)/readlink_f.sh"
source "$(dirname "$(readlink_f "${0}")")"/../system/setenv

# PhantomJS cache is under $HOME/.qws/ and each version may affect it differently,
# so each package needs its own $HOME.
export HOME="$env_root/home/arachni"

exec ruby $GEM_PATH/bin/rackup $env_root/arachni-ui-web/config.ru "$@"
```

Let me know how it works.

**Comment by Zapotek** [comment]
@colinmo Don't mind the previous comment, fresh OSX nightlies are up, give them a try please.

**Comment by colinmo** [comment]
Downloading now, will update.

**Comment by colinmo** [comment]
Downloaded, installed, executed arachni_web and it all appears to be working. Thanks!

**Comment by Zapotek** [comment]
Yay, closing this sucker.

Thanks for the feedback guys.

**Comment by ethicalhack3r** [comment]
Got the error below which I think is related to this issue using nightlies (arachni-2.0dev-1.0dev-darwin-x86_64.tar.gz Jan 17) on OS X 10.11.2 using Ruby 2.3.0p0 (RVM).

```
/Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/bundler/gems/ffi-2b19a7dde1c2/lib/ffi/library.rb:133:in `block in ffi_lib': Could not open library 'c': dlopen(c, 5): image not found. (LoadError)
Could not open library 'libc.dylib': dlopen(libc.dylib, 5): image not found
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/bundler/gems/ffi-2b19a7dde1c2/lib/ffi/library.rb:100:in `map'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/bundler/gems/ffi-2b19a7dde1c2/lib/ffi/library.rb:100:in `ffi_lib'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/ethon-0.8.1/lib/ethon/libc.rb:8:in `<module:Libc>'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/ethon-0.8.1/lib/ethon/libc.rb:6:in `<module:Ethon>'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/ethon-0.8.1/lib/ethon/libc.rb:1:in `<top (required)>'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/ethon-0.8.1/lib/ethon.rb:14:in `<top (required)>'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/typhoeus-1.0.1/lib/typhoeus.rb:2:in `<top (required)>'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-17bf15655fab/lib/arachni/http/client.rb:9:in `<top (required)>'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-17bf15655fab/lib/arachni/http.rb:9:in `require_relative'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-17bf15655fab/lib/arachni/http.rb:9:in `<top (required)>'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-17bf15655fab/lib/arachni/framework.rb:29:in `<module:Arachni>'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-17bf15655fab/lib/arachni/framework.rb:17:in `<top (required)>'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-17bf15655fab/lib/arachni.rb:95:in `require_relative'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-17bf15655fab/lib/arachni.rb:95:in `<top (required)>'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `block (2 levels) in require'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/arachni-ui-web/config/application.rb:15:in `<top (required)>'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/usr/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/usr/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/arachni-ui-web/config/environment.rb:13:in `<top (required)>'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/usr/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/usr/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/arachni-ui-web/config.ru:3:in `block in <main>'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/arachni-ui-web/config.ru:in `new'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/arachni-ui-web/config.ru:in `<main>'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/rack-1.6.4/lib/rack/server.rb:272:in `start'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/rack-1.6.4/lib/rack/server.rb:147:in `start'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/gems/rack-1.6.4/bin/rackup:4:in `<top (required)>'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/bin/../system/gems/bin/rackup:23:in `load'
	from /Users/ryan/Tools/arachni-2.0dev-1.0dev/bin/../system/gems/bin/rackup:23:in `<main>'
```

It was solved by following the instructions posted here https://github.com/ffi/ffi/issues/461#issuecomment-149253757

The instructions are to edit ```vim /Users/ryan/Tools/arachni-2.0dev-1.0dev/system/gems/bundler/gems/ffi-2b19a7dde1c2/lib/ffi/library.rb```

Change line 81 ```LIBC``` constant to ```'/usr/lib/libc.dylib'```:

```LIBC = '/usr/lib/libc.dylib'```

Then everything worked.

**Comment by Zapotek** [comment]
I've been using a special branch of FFI which had resolved this issue, not sure why it appeared again.
Looking into it.

**Comment by Trovador237** [comment]
Hello there, I got an error trying to run arachni_web 

~/Desktop/arachni-1.4-0.5.10/bin# ./arachni_web
./arachni_web: line 10: /root/Desktop/arachni-1.4-0.5.10/bin/../system/usr/bin/ruby: No such file or directory

Not sure what to do, I think is something that is not finding the path of ruby but not sure, I'm currently using a virtual version of Kali 2.0. Any help will be thank.

**Comment by Zapotek** [comment]
Did you do anything to the package after extracting it?

**Comment by mohankallepalli** [comment]
mohankallepalli@localhost:~$ cd arachni-1.4-0.5.10/bin/
mohankallepalli@localhost:~/arachni-1.4-0.5.10/bin$ ./arachni -h
./arachni: line 10: /home/mohankallepalli/arachni-1.4-0.5.10/bin/../system/usr/bin/ruby: **No such file or directory**

**Same error** with "Linux localhost 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux". Any solution?

**Comment by Zapotek** [comment]
@mohankallepalli Are you sure you downloaded the right package for your architecture?
