### ISSUE TITLE
undefined method ssl_key

### ISSUE THREAD

**Issue by Dutchy-** [Arachni/arachni#623]
I am trying to run arachni on Kali Linux, and I'm getting the following error when trying to use an ssl certificate:

```
root@kali:~/arachni# /var/lib/gems/2.1.0/bin/arachni --http-ssl-key ~/path/to/file.pem --http-ssl-key-pass 'my.password1' https://my.target.com
WARN: Unresolved specs during Gem::Specification.reset:
      rack (>= 0)
      ffi (>= 1.0.11, >= 1.3.0, ~> 1.0)
      mail (>= 2.0)
      selenium-webdriver (>= 2.18.0)
      loofah (~> 2.0.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/var/lib/gems/2.1.0/gems/arachni-1.3/lib/arachni/version.rb:12: warning: already initialized constant Arachni::VERSION
/root/arachni/lib/arachni/version.rb:12: warning: previous definition of VERSION was here
Arachni - Web Application Security Scanner Framework v1.3
   Author: Tasos "Zapotek" Laskos <tasos.laskos@arachni-scanner.com>

           (With the support of the community and the Arachni Team.)

   Website:       http://arachni-scanner.com
   Documentation: http://arachni-scanner.com/wiki


 [-] --http-ssl-key: [NoMethodError] undefined method `ssl_key=' for #<Arachni::OptionGroups::HTTP:0x00000002a55378>
root@kali:~/arachni# /var/lib/gems/2.1.0/bin/arachni -v
WARN: Unresolved specs during Gem::Specification.reset:
      rack (>= 0)
      ffi (>= 1.0.11, >= 1.3.0, ~> 1.0)
      mail (>= 2.0)
      selenium-webdriver (>= 2.18.0)
      loofah (~> 2.0.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/var/lib/gems/2.1.0/gems/arachni-1.3/lib/arachni/version.rb:12: warning: already initialized constant Arachni::VERSION
/root/arachni/lib/arachni/version.rb:12: warning: previous definition of VERSION was here
Arachni - Web Application Security Scanner Framework v1.3
   Author: Tasos "Zapotek" Laskos <tasos.laskos@arachni-scanner.com>

           (With the support of the community and the Arachni Team.)

   Website:       http://arachni-scanner.com
   Documentation: http://arachni-scanner.com/wiki


Arachni 1.3 (ruby 2.1.5p273) [x86_64-linux-gnu]
root@kali:~/arachni# arachni --http-ssl-key ~/path/to/file.pem --http-ssl-key-pass 'my.password1' https://my.target.com
Arachni - Web Application Security Scanner Framework v1.2.1
   Author: Tasos "Zapotek" Laskos <tasos.laskos@arachni-scanner.com>

           (With the support of the community and the Arachni Team.)

   Website:       http://arachni-scanner.com
   Documentation: http://arachni-scanner.com/wiki


/usr/share/arachni/ui/cli/framework/option_parser.rb:360:in `block in http': undefined method `ssl_key=' for #<Arachni::OptionGroups::HTTP:0x00000002bc16f8> (NoMethodError)
	from /usr/lib/ruby/2.1.0/optparse.rb:1359:in `call'
	from /usr/lib/ruby/2.1.0/optparse.rb:1359:in `block in parse_in_order'
	from /usr/lib/ruby/2.1.0/optparse.rb:1346:in `catch'
	from /usr/lib/ruby/2.1.0/optparse.rb:1346:in `parse_in_order'
	from /usr/lib/ruby/2.1.0/optparse.rb:1340:in `order!'
	from /usr/lib/ruby/2.1.0/optparse.rb:1432:in `permute!'
	from /usr/lib/ruby/2.1.0/optparse.rb:1454:in `parse!'
	from /usr/share/arachni/ui/cli/option_parser.rb:66:in `parse'
	from /usr/share/arachni/ui/cli/framework.rb:398:in `parse_options'
	from /usr/share/arachni/ui/cli/framework.rb:32:in `initialize'
	from ./arachni:12:in `new'
	from ./arachni:12:in `<main>'
root@kali:~/arachni# arachni -v
Arachni - Web Application Security Scanner Framework v1.2.1
   Author: Tasos "Zapotek" Laskos <tasos.laskos@arachni-scanner.com>

           (With the support of the community and the Arachni Team.)

   Website:       http://arachni-scanner.com
   Documentation: http://arachni-scanner.com/wiki


Arachni 1.2.1 (ruby 2.1.5p273) [x86_64-linux-gnu]
```

Above shows both version 1.2.1 from the Kali Linux repositories and version 1.3 from source. I'm not sure if I'm doing something wrong or not, but I suspect it might be some mismatch with the libraries used?

**Comment by Zapotek** [comment]
The mismatches are due to the fact that you were running Arachni directly from the source (seems like versions are mixed) instead of the packages.
The error is due to a typo in the option parser, I was trying to set an option that doesn't exist, my bad.

I'll push a fix today.

**Comment by Zapotek** [comment]
Released: http://www.arachni-scanner.com/download/
