### ISSUE TITLE
[NoMethodError] undefined method `print_debug_exception' for #<Arachni::Element::Form:0x00000002e53650>

### ISSUE THREAD

**Issue by danc86** [Arachni/arachni#654]
Using arachni-1.3.2-0.5.9, running a scan through the web UI. Scan crashed after 2 hours 20 minutes with the following error:

```
[2016-01-06 13:12:23 +1000] [NoMethodError] undefined method `print_debug_exception' for #<Arachni::Element::Form:0x00000002e53650>
[2016-01-06 13:12:23 +1000] /home/dcallagh/arachni/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/element/capabilities/with_dom.rb:27:in `rescue in dom'
[2016-01-06 13:12:23 +1000] /home/dcallagh/arachni/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/element/capabilities/with_dom.rb:24:in `dom'
[2016-01-06 13:12:23 +1000] /home/dcallagh/arachni/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/element/form/capabilities/with_dom.rb:24:in `dom'
[2016-01-06 13:12:23 +1000] /home/dcallagh/arachni/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/check/auditor.rb:104:in `each'
[2016-01-06 13:12:23 +1000] /home/dcallagh/arachni/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/check/auditor.rb:104:in `find'
[2016-01-06 13:12:23 +1000] /home/dcallagh/arachni/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/check/auditor.rb:104:in `block in check?'
[2016-01-06 13:12:23 +1000] /home/dcallagh/arachni/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/check/auditor.rb:134:in `call'
[2016-01-06 13:12:23 +1000] /home/dcallagh/arachni/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/check/auditor.rb:134:in `block in check?'
[2016-01-06 13:12:23 +1000] /home/dcallagh/arachni/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/check/auditor.rb:130:in `each'
[2016-01-06 13:12:23 +1000] /home/dcallagh/arachni/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/check/auditor.rb:130:in `check?'
[2016-01-06 13:12:23 +1000] /home/dcallagh/arachni/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework/parts/browser.rb:132:in `block in schedule_dom_metadata_application'
[2016-01-06 13:12:23 +1000] /home/dcallagh/arachni/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework/parts/browser.rb:132:in `each'
[2016-01-06 13:12:23 +1000] /home/dcallagh/arachni/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework/parts/browser.rb:132:in `find'
[2016-01-06 13:12:23 +1000] /home/dcallagh/arachni/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework/parts/browser.rb:132:in `schedule_dom_metadata_application'
[2016-01-06 13:12:23 +1000] /home/dcallagh/arachni/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework/parts/browser.rb:115:in `perform_browser_analysis'
[2016-01-06 13:12:23 +1000] /home/dcallagh/arachni/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/rpc/server/framework/multi_instance.rb:207:in `perform_browser_analysis'
[2016-01-06 13:12:23 +1000] /home/dcallagh/arachni/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework/parts/audit.rb:117:in `audit_page'
[2016-01-06 13:12:23 +1000] /home/dcallagh/arachni/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework/parts/audit.rb:217:in `audit_queues'
[2016-01-06 13:12:23 +1000] /home/dcallagh/arachni/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/rpc/server/framework/multi_instance.rb:222:in `audit_queues'
[2016-01-06 13:12:23 +1000] /home/dcallagh/arachni/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework/parts/audit.rb:191:in `block in audit'
[2016-01-06 13:12:23 +1000] /home/dcallagh/arachni/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework/parts/audit.rb:171:in `loop'
[2016-01-06 13:12:23 +1000] /home/dcallagh/arachni/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework/parts/audit.rb:171:in `audit'
[2016-01-06 13:12:23 +1000] /home/dcallagh/arachni/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework.rb:120:in `block in run'
[2016-01-06 13:12:23 +1000] /home/dcallagh/arachni/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/utilities.rb:408:in `call'
[2016-01-06 13:12:23 +1000] /home/dcallagh/arachni/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/utilities.rb:408:in `exception_jail'
[2016-01-06 13:12:23 +1000] /home/dcallagh/arachni/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework.rb:120:in `run'
[2016-01-06 13:12:23 +1000] /home/dcallagh/arachni/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/rpc/server/framework.rb:154:in `block in run'
[2016-01-06 13:12:23 +1000] 
[2016-01-06 13:12:23 +1000] Parent:
[2016-01-06 13:12:23 +1000] Arachni::RPC::Server::Framework
[2016-01-06 13:12:23 +1000] 
[2016-01-06 13:12:23 +1000] Block:
[2016-01-06 13:12:23 +1000] #<Proc:0x00000002cf6690@/home/dcallagh/arachni/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework.rb:120>
[2016-01-06 13:12:23 +1000] 
[2016-01-06 13:12:23 +1000] Caller:
[2016-01-06 13:12:23 +1000] /home/dcallagh/arachni/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/utilities.rb:408:in `exception_jail'
[2016-01-06 13:12:23 +1000] /home/dcallagh/arachni/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework.rb:120:in `run'
[2016-01-06 13:12:23 +1000] /home/dcallagh/arachni/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/rpc/server/framework.rb:154:in `block in run'
[2016-01-06 13:12:23 +1000] --------------------------------------------------------------------------------
```

**Comment by Zapotek** [comment]
Hello, I think this issue has already been resolved, can you please try the [nightlies](http://downloads.arachni-scanner.com/nightlies/)?
