### ISSUE TITLE
Timeout never triggered

### ISSUE THREAD

**Issue by sbehrens** [Arachni/arachni#655]
Hi Tasos,

Timeouts aren't working anymore, see screenshot below (set timeout to 3 minutes scan ran for over an hour).  I tried a few different timeout settings and observed similar behavior:

![](http://snag.gy/DQZyW.jpg)

**Comment by Zapotek** [comment]
Is this in the nightly or stable?

**Comment by sbehrens** [comment]
Fyi the log file contains the following:

```
[2016-01-11 18:05:45 +0000] Timeout has been reached, shutting down.
[2016-01-11 18:18:16 +0000] Error in Arachni::Checks::FileInclusion: invalid byte sequence in US-ASCII
[2016-01-11 18:18:16 +0000] /apps/monterey/monterey/plugins/monterey-arachni/arachni/arachni/system/gems/bundler/gems/arachni-d0a69444add0/components/checks/active/file_inclusion.rb:60:in `split'
[2016-01-11 18:18:16 +0000] /apps/monterey/monterey/plugins/monterey-arachni/arachni/arachni/system/gems/bundler/gems/arachni-d0a69444add0/components/checks/active/file_inclusion.rb:60:in `block in options'
[2016-01-11 18:18:16 +0000] /apps/monterey/monterey/plugins/monterey-arachni/arachni/arachni/system/gems/bundler/gems/arachni-d0a69444add0/lib/arachni/element/capabilities/auditable.rb:366:in `call'
[2016-01-11 18:18:16 +0000] /apps/monterey/monterey/plugins/monterey-arachni/arachni/arachni/system/gems/bundler/gems/arachni-d0a69444add0/lib/arachni/element/capabilities/auditable.rb:366:in `block in audit_single'
[2016-01-11 18:18:16 +0000] /apps/monterey/monterey/plugins/monterey-arachni/arachni/arachni/system/gems/bundler/gems/arachni-d0a69444add0/lib/arachni/element/capabilities/mutable.rb:371:in `yield_if_unique'
[2016-01-11 18:18:16 +0000] /apps/monterey/monterey/plugins/monterey-arachni/arachni/arachni/system/gems/bundler/gems/arachni-d0a69444add0/lib/arachni/element/capabilities/mutable.rb:361:in `create_and_yield_if_unique'
[2016-01-11 18:18:16 +0000] /apps/monterey/monterey/plugins/mo
```
Looks like the timeout was triggered but didn't result in the scan terminating.

**Comment by sbehrens** [comment]
This was in a nightly build from a few weeks ago, not exactly sure which nightly.

**Comment by sbehrens** [comment]
Have you seen this issue in the current nightlies?

**Comment by Zapotek** [comment]
No, I did a test run and couldn't reproduce it.
I didn't get a chance to dig deeper, I was working on a different issue until a few ours ago.

**Comment by Zapotek** [comment]
Can you paste the entire configuration please?
You can send it over privately if you prefer.

**Comment by sbehrens** [comment]
I wasn't able to reproduce the bug with the latest nightly, so I'm going to close this as fixed.  Thanks Tasos!
