### ISSUE TITLE
[ArgumentError] unknown encoding name - uft-8

### ISSUE THREAD

**Issue by ashrav** [Arachni/arachni#661]
Scan is aborting and giving error message:

```
[2016-01-19 03:00:27 -0500] [ArgumentError] unknown encoding name - uft-8
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node.rb:615:in `find'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node.rb:615:in `serialize'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node.rb:774:in `to_format'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node.rb:630:in `to_html'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/element/form.rb:294:in `from_node'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/element/form.rb:279:in `block in from_document'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:187:in `block in each'
```

**Comment by Zapotek** [comment]
Can you show me the entire error message please?

**Comment by Zapotek** [comment]
Also, does this issue appear in the [nightlies](http://downloads.arachni-scanner.com/nightlies/)?

**Comment by ashrav** [comment]
I didn't try nightlies yet, I will try it later... below is the complete error (I masked some parts):
2016-01-19 03:00:27 -0500 --------------------------------------------------------------------------------
ENV:
---
CPLUS_INCLUDE_PATH: "/home/xxx/tools/arachni-1.3.2-0.5.9/bin/../system/usr/include"
XDG_SESSION_ID: '25'
GEM_HOME: "/home/xxx/tools/arachni-1.3.2-0.5.9/system/gems"
SHELL: "/bin/bash"
TERM: xterm
IRBRC: "/home/xxx/tools/arachni-1.3.2-0.5.9/bin/../system/usr/lib/ruby/.irbrc"
SSH_CLIENT: 85.108.144.154 62405 22
LIBRARY_PATH: "/home/xxx/tools/arachni-1.3.2-0.5.9/bin/../system/usr/lib"
MY_RUBY_HOME: "/home/xxx/tools/arachni-1.3.2-0.5.9/bin/../system/usr/lib/ruby"
SSH_TTY: "/dev/pts/0"
USER: root
LD_LIBRARY_PATH: "/home/xxx/tools/arachni-1.3.2-0.5.9/bin/../system/usr/lib"
LS_COLORS: 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:'
PATH: "/home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/bin:/home/xxx/tools/arachni-1.3.2-0.5.9/bin/../system/../bin:/home/xxx/tools/arachni-1.3.2-0.5.9/bin/../system/usr/bin:/home/xxx/tools/arachni-1.3.2-0.5.9/bin/../system/gems/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
MAIL: "/var/mail/root"
C_INCLUDE_PATH: "/home/xxx/tools/arachni-1.3.2-0.5.9/bin/../system/usr/include"
PWD: "/home/xxx/tools/arachni-1.3.2-0.5.9/bin"
ARACHNI_WEBUI_LOGDIR: "/home/xxx/tools/arachni-1.3.2-0.5.9/bin/../system/logs/webui"
LANG: en_US.UTF-8
ARACHNI_FRAMEWORK_LOGDIR: "/home/xxx/tools/arachni-1.3.2-0.5.9/bin/../system/logs/framework"
HOME: "/home/xxx/tools/arachni-1.3.2-0.5.9/bin/../system/home/arachni"
SHLVL: '1'
RAILS_ENV: production
DYLD_LIBRARY_PATH: "/home/xxx/tools/arachni-1.3.2-0.5.9/bin/../system/usr/lib"
LOGNAME: root
GEM_PATH: "/home/xxx/tools/arachni-1.3.2-0.5.9/bin/../system/gems"
SSH_CONNECTION: 85.108.144.154 62405 104.236.52.48 22
LESSOPEN: "| /usr/bin/lesspipe %s"
DISPLAY: localhost:10.0
XDG_RUNTIME_DIR: "/run/user/0"
RUBYLIB: "/home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/bundler-1.10.6/lib:/home/xxx/tools/arachni-1.3.2-0.5.9/bin/../system/usr/lib/ruby:/home/xxx/tools/arachni-1.3.2-0.5.9/bin/../system/usr/lib/ruby/site_ruby/2.2.0:/home/xxx/tools/arachni-1.3.2-0.5.9/bin/../system/usr/lib/ruby/2.2.0:/home/xxx/tools/arachni-1.3.2-0.5.9/bin/../system/usr/lib/ruby/2.2.0/x86_64-linux:/home/xxx/tools/arachni-1.3.2-0.5.9/bin/../system/usr/lib/ruby/site_ruby/2.2.0/x86_64-linux"
RUBY_VERSION: ruby-2.2.2
LESSCLOSE: "/usr/bin/lesspipe %s %s"
RACK_ENV: development
BUNDLE_GEMFILE: "/home/xxx/tools/arachni-1.3.2-0.5.9/system/arachni-ui-web/Gemfile"
_ORIGINAL_GEM_PATH: "/home/xxx/tools/arachni-1.3.2-0.5.9/bin/../system/gems"
BUNDLE_BIN_PATH: "/home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/bundler-1.10.6/bin/bundle"
RUBYOPT: "-rbundler/setup"
MANPATH: "/home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/kramdown-1.4.1/man"
BUNDLE_ORIG_MANPATH: "/home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/kramdown-1.4.1/man"
--------------------------------------------------------------------------------
OPTIONS:
---
browser_cluster:
  local_storage: {}
  wait_for_elements: {}
  pool_size: 6
  job_timeout: 25
  worker_time_to_live: 100
  ignore_images: false
  screen_width: 1600
  screen_height: 1200
http:
  user_agent: Arachni/v1.3.2
  request_timeout: 10000
  request_redirect_limit: 5
  request_concurrency: 20
  request_queue_size: 100
  request_headers: {}
  response_max_size: 500000
  cookies: {}
scope:
  redundant_path_patterns: {}
  dom_depth_limit: 5
  exclude_path_patterns: []
  exclude_content_patterns: []
  include_path_patterns: []
  restrict_paths: []
  extend_paths: []
  url_rewrites: {}
input:
  values:
    "(?i-mx:name)": arachni_name
    "(?i-mx:user)": arachni_user
    "(?i-mx:usr)": arachni_user
    "(?i-mx:pass)": 5543!%arachni_secret
    "(?i-mx:txt)": arachni_text
    "(?i-mx:num)": '132'
    "(?i-mx:amount)": '100'
    "(?i-mx:mail)": arachni@email.gr
    "(?i-mx:account)": '12'
    "(?i-mx:id)": '1'
  default_values:
    "(?i-mx:name)": arachni_name
    "(?i-mx:user)": arachni_user
    "(?i-mx:usr)": arachni_user
    "(?i-mx:pass)": 5543!%arachni_secret
    "(?i-mx:txt)": arachni_text
    "(?i-mx:num)": '132'
    "(?i-mx:amount)": '100'
    "(?i-mx:mail)": arachni@email.gr
    "(?i-mx:account)": '12'
    "(?i-mx:id)": '1'
  without_defaults: true
  force: false
audit:
  parameter_values: true
  exclude_vector_patterns: []
  include_vector_patterns: []
  link_templates: []
  links: true
  forms: true
  cookies: true
  jsons: true
  xmls: true
  ui_forms: true
  ui_inputs: true
datastore:
  token: d53d5016e9ef74e5108a2ea16e73b65f
session: {}
checks:
- allowed_methods
- backdoors
- backup_directories
- backup_files
- captcha
- code_injection
- code_injection_php_input_wrapper
- code_injection_timing
- common_admin_interfaces
- common_directories
- common_files
- cookie_set_for_parent_domain
- credit_card
- csrf
- cvs_svn_users
- directory_listing
- emails
- file_inclusion
- form_upload
- hsts
- htaccess_limit
- html_objects
- http_only_cookies
- http_put
- insecure_client_access_policy
- insecure_cookies
- insecure_cors_policy
- insecure_cross_domain_policy_access
- insecure_cross_domain_policy_headers
- interesting_responses
- ldap_injection
- localstart_asp
- mixed_resource
- no_sql_injection
- no_sql_injection_differential
- origin_spoof_access_restriction_bypass
- os_cmd_injection
- os_cmd_injection_timing
- password_autocomplete
- path_traversal
- private_ip
- response_splitting
- rfi
- session_fixation
- source_code_disclosure
- sql_injection
- sql_injection_differential
- sql_injection_timing
- ssn
- trainer
- unencrypted_password_forms
- unvalidated_redirect
- unvalidated_redirect_dom
- webdav
- x_frame_options
- xpath_injection
- xss
- xss_dom
- xss_dom_script_context
- xss_event
- xss_path
- xss_script_context
- xss_tag
- xst
- xxe
platforms: []
plugins:
  autothrottle: {}
  discovery: {}
  healthmap: {}
  timing_attacks: {}
  uniformity: {}
no_fingerprinting: false
authorized_by: 
url: https://www.somewebsite.com.tr/
--------------------------------------------------------------------------------
[2016-01-19 03:00:27 -0500] [ArgumentError] unknown encoding name - uft-8
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node.rb:615:in `find'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node.rb:615:in `serialize'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node.rb:774:in `to_format'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node.rb:630:in `to_html'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/element/form.rb:294:in `from_node'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/element/form.rb:279:in `block in from_document'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:187:in `block in each'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:186:in `upto'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:186:in `each'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/element/form.rb:278:in `map'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/element/form.rb:278:in `from_document'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/parser.rb:165:in `forms'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/page.rb:287:in `block (2 levels) in <class:Page>'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/element_filter.rb:173:in `block in update_from_page'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/element_filter.rb:173:in `map'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/element_filter.rb:173:in `update_from_page'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/trainer.rb:104:in `page='
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/trainer.rb:40:in `block in initialize'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/support/mixins/observable.rb:78:in `call'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/support/mixins/observable.rb:78:in `block (3 levels) in notify_observers'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/utilities.rb:408:in `call'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/utilities.rb:408:in `exception_jail'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/support/mixins/observable.rb:78:in `block (2 levels) in notify_observers'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/support/mixins/observable.rb:77:in `each'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/support/mixins/observable.rb:77:in `block in notify_observers'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/support/mixins/observable.rb:76:in `notify_observers'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/support/mixins/observable.rb:44:in `block (2 levels) in advertise'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework/parts/audit.rb:109:in `audit_page'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework/parts/audit.rb:217:in `audit_queues'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/rpc/server/framework/multi_instance.rb:222:in `audit_queues'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework/parts/audit.rb:191:in `block in audit'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework/parts/audit.rb:171:in `loop'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework/parts/audit.rb:171:in `audit'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework.rb:120:in `block in run'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/utilities.rb:408:in `call'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/utilities.rb:408:in `exception_jail'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework.rb:120:in `run'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/rpc/server/framework.rb:154:in `block in run'
[2016-01-19 03:00:27 -0500] 
[2016-01-19 03:00:27 -0500] Parent:
[2016-01-19 03:00:27 -0500] Arachni::RPC::Server::Framework
[2016-01-19 03:00:27 -0500] 
[2016-01-19 03:00:27 -0500] Block:
[2016-01-19 03:00:27 -0500] #<Proc:0x000000047e00f0@/home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/support/mixins/observable.rb:78>
[2016-01-19 03:00:27 -0500] 
[2016-01-19 03:00:27 -0500] Caller:
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/utilities.rb:408:in `exception_jail'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/support/mixins/observable.rb:78:in `block (2 levels) in notify_observers'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/support/mixins/observable.rb:77:in `each'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/support/mixins/observable.rb:77:in `block in notify_observers'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/support/mixins/observable.rb:76:in `notify_observers'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/support/mixins/observable.rb:44:in `block (2 levels) in advertise'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework/parts/audit.rb:109:in `audit_page'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework/parts/audit.rb:217:in `audit_queues'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/rpc/server/framework/multi_instance.rb:222:in `audit_queues'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework/parts/audit.rb:191:in `block in audit'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework/parts/audit.rb:171:in `loop'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework/parts/audit.rb:171:in `audit'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework.rb:120:in `block in run'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/utilities.rb:408:in `call'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/utilities.rb:408:in `exception_jail'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework.rb:120:in `run'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/rpc/server/framework.rb:154:in `block in run'
[2016-01-19 03:00:27 -0500] --------------------------------------------------------------------------------
[2016-01-19 03:00:27 -0500] [ArgumentError] unknown encoding name - uft-8
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node.rb:615:in `find'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node.rb:615:in `serialize'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node.rb:774:in `to_format'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node.rb:630:in `to_html'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/element/form.rb:294:in `from_node'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/element/form.rb:279:in `block in from_document'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:187:in `block in each'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:186:in `upto'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:186:in `each'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/element/form.rb:278:in `map'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/element/form.rb:278:in `from_document'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/parser.rb:165:in `forms'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/page.rb:287:in `block (2 levels) in <class:Page>'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/check/auditor.rb:104:in `block in check?'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/check/auditor.rb:134:in `call'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/check/auditor.rb:134:in `block in check?'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/check/auditor.rb:130:in `each'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/check/auditor.rb:130:in `check?'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework/parts/browser.rb:132:in `block in schedule_dom_metadata_application'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework/parts/browser.rb:132:in `each'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework/parts/browser.rb:132:in `find'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework/parts/browser.rb:132:in `schedule_dom_metadata_application'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework/parts/browser.rb:115:in `perform_browser_analysis'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/rpc/server/framework/multi_instance.rb:207:in `perform_browser_analysis'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework/parts/audit.rb:117:in `audit_page'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework/parts/audit.rb:217:in `audit_queues'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/rpc/server/framework/multi_instance.rb:222:in `audit_queues'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework/parts/audit.rb:191:in `block in audit'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework/parts/audit.rb:171:in `loop'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework/parts/audit.rb:171:in `audit'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework.rb:120:in `block in run'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/utilities.rb:408:in `call'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/utilities.rb:408:in `exception_jail'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework.rb:120:in `run'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/rpc/server/framework.rb:154:in `block in run'
[2016-01-19 03:00:27 -0500] 
[2016-01-19 03:00:27 -0500] Parent:
[2016-01-19 03:00:27 -0500] Arachni::RPC::Server::Framework
[2016-01-19 03:00:27 -0500] 
[2016-01-19 03:00:27 -0500] Block:
[2016-01-19 03:00:27 -0500] #<Proc:0x00000004413f58@/home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework.rb:120>
[2016-01-19 03:00:27 -0500] 
[2016-01-19 03:00:27 -0500] Caller:
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/utilities.rb:408:in `exception_jail'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/framework.rb:120:in `run'
[2016-01-19 03:00:27 -0500] /home/xxx/tools/arachni-1.3.2-0.5.9/system/gems/gems/arachni-1.3.2/lib/arachni/rpc/server/framework.rb:154:in `block in run'
[2016-01-19 03:00:27 -0500] --------------------------------------------------------------------------------

**Comment by Zapotek** [comment]
This is strange, there's a typo somewhere but it's not in Arachni and I can't find it in the dependency either -- `uft-8` should have been `utf-8`.
Any chance you can send me the URL of page that causes this issue?
You can do so privately if you wish: tasos.laskos@arachni-scanner.com

**Comment by ashrav** [comment]
I sent it, please let me know if there is a workaround

**Comment by Zapotek** [comment]
The page includes this:

```html
<meta http-equiv="Content-Type" content="text/html; charset=uft-8" />
```

However, the HTML parser shouldn't just explode when something like this happens so I'll forward the issue to the maintainers.

Thanks for the feedback.

**Comment by Zapotek** [comment]
After digging a bit deeper, I found that a sanitization in Arachni that was supposed to fix those issues at a higher level wasn't working properly.

I'm making sure that my fix doesn't break anything else and after that I'll be uploading fresh nightlies.

**Comment by ashrav** [comment]
alright thanks, I will test it again when nightlies is ready

**Comment by Zapotek** [comment]
Sorry it took so long, nightlies are up and the issue has been resolved.

Cheers
