### ISSUE TITLE
[Errno::EMFILE] Too many open files

### ISSUE THREAD

**Issue by corelanc0d3r** [Arachni/arachni#669]
Hi,

I have tried to run the latest version of arachni on OSX (El Capitan) and noticed the following error when running a default scan:

````
[2016-02-09 08:36:21 +0100] --------------------------------------------------------------------------------
[2016-02-09 08:36:21 +0100] [Errno::EMFILE] Too many open files - socket(2) for "127.0.0.1" port 51278
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/net/http.rb:879:in `initialize'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/net/http.rb:879:in `open'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/timeout.rb:98:in `call'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/timeout.rb:98:in `timeout'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/net/http.rb:878:in `connect'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/net/http.rb:852:in `start'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/net/http.rb:1375:in `request'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/selenium-webdriver-2.51.0/lib/selenium/webdriver/remote/http/default.rb:107:in `response_for'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/selenium-webdriver-2.51.0/lib/selenium/webdriver/remote/http/default.rb:58:in `request'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/selenium-webdriver-2.51.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/selenium-webdriver-2.51.0/lib/selenium/webdriver/remote/bridge.rb:645:in `raw_execute'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/selenium-webdriver-2.51.0/lib/selenium/webdriver/remote/bridge.rb:623:in `execute'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/selenium-webdriver-2.51.0/lib/selenium/webdriver/remote/bridge.rb:234:in `getWindowHandles'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/selenium-webdriver-2.51.0/lib/selenium/webdriver/common/driver.rb:194:in `window_handles'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:1471:in `ensure_open_window'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:362:in `goto'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/page/dom.rb:150:in `restore'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:280:in `load'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster/jobs/dom_exploration/event_trigger.rb:34:in `run'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster/job.rb:105:in `configure_and_run'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster/worker.rb:87:in `block (2 levels) in run_job'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `call'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `exception_jail'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster/worker.rb:85:in `block in run_job'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:1245:in `call'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:1245:in `block in with_timeout'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/timeout.rb:32:in `block in catch'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/timeout.rb:32:in `catch'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/timeout.rb:32:in `catch'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/timeout.rb:103:in `timeout'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:1244:in `with_timeout'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster/worker.rb:84:in `run_job'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster/worker.rb:215:in `block (3 levels) in start'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `call'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `exception_jail'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster/worker.rb:215:in `block (2 levels) in start'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `call'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `exception_jail'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster/worker.rb:213:in `block in start'
[2016-02-09 08:36:21 +0100] 
[2016-02-09 08:36:21 +0100] Parent:
[2016-02-09 08:36:21 +0100] Arachni::BrowserCluster::Worker
[2016-02-09 08:36:21 +0100] 
[2016-02-09 08:36:21 +0100] Block:
[2016-02-09 08:36:21 +0100] #<Proc:0x007ff23d215b88@/Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster/worker.rb:85>
[2016-02-09 08:36:21 +0100] 
[2016-02-09 08:36:21 +0100] Caller:
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `exception_jail'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster/worker.rb:85:in `block in run_job'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:1245:in `call'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:1245:in `block in with_timeout'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/timeout.rb:32:in `block in catch'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/timeout.rb:32:in `catch'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/timeout.rb:32:in `catch'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/timeout.rb:103:in `timeout'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:1244:in `with_timeout'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster/worker.rb:84:in `run_job'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster/worker.rb:215:in `block (3 levels) in start'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `call'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `exception_jail'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster/worker.rb:215:in `block (2 levels) in start'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `call'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `exception_jail'
[2016-02-09 08:36:21 +0100] /Users/corelanc0d3r/pentest/web/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster/worker.rb:213:in `block in start'
```

**Comment by Zapotek** [comment]
I think that you need to increase the maximum open files limit for your system.
Can you please show me the output of `ulimit -a`?

**Comment by corelanc0d3r** [comment]
sure
````core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 256
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 709
virtual memory          (kbytes, -v) unlimited
```

**Comment by Zapotek** [comment]
Yeah that's what I figured, 256 looks pretty low, setting it to something like 1024 should fix the issue.

**Comment by corelanc0d3r** [comment]
it probably does.  Would checking the current ulimit value & reporting potential low value be an option?

**Comment by Zapotek** [comment]
I've thought of that but there's no good place to put that check, if it's at startup then the warning will immediately disappear following the scan messages.

Besides, "Errno::EMFILE too many open files" is a system error and the solution is just a simple Google search away.

**Comment by corelanc0d3r** [comment]
you could put the warning in the gui. If the default "open files" value is low by default, I'm sure others will run into the same issue as me.  I am not a big fan of having to google for stuff before I can run a tool, but ok, it's your call.

**Comment by Zapotek** [comment]
Fair enough, if it turns out to be a remotely common occurrence then I'll have to figure something out.
I've only gotten a handful of these reports in 6 or so years and it greatly depends on the webapp that is being scanned.

Could be that some new code may trigger this more frequently, enough to warrant the addition of global UI-specific sanity checks, I'll have to run more tests on OSX to make sure.
