### ISSUE TITLE
This scan has the logged the following errors

### ISSUE THREAD

**Issue by ihacku** [Arachni/arachni#676]
```

2016-02-18 14:56:06 +0800 --------------------------------------------------------------------------------
ENV:
---
CPLUS_INCLUDE_PATH: "/root/arachni-1.4-0.5.10/bin/../system/usr/include"
XDG_SESSION_ID: '10495'
HOSTNAME: localhost.localdomain
GEM_HOME: "/root/arachni-1.4-0.5.10/system/gems"
TERM: screen
SHELL: "/bin/bash"
HISTSIZE: '1000'
IRBRC: "/root/arachni-1.4-0.5.10/bin/../system/usr/lib/ruby/.irbrc"
LIBRARY_PATH: "/root/arachni-1.4-0.5.10/bin/../system/usr/lib:/usr/lib:/usr/local/lib"
MY_RUBY_HOME: "/root/arachni-1.4-0.5.10/bin/../system/usr/lib/ruby"
USER: root
LD_LIBRARY_PATH: "/root/arachni-1.4-0.5.10/bin/../system/usr/lib:/usr/lib:/usr/local/lib"
LS_COLORS: 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:'
TERMCAP: "SC|screen|VT 100/ANSI X3.64 virtual terminal:\\\n\t:DO=\\E[%dB:LE=\\E[%dD:RI=\\E[%dC:UP=\\E[%dA:bs:bt=\\E[Z:\\\n\t:cd=\\E[J:ce=\\E[K:cl=\\E[H\\E[J:cm=\\E[%i%d;%dH:ct=\\E[3g:\\\n\t:do=^J:nd=\\E[C:pt:rc=\\E8:rs=\\Ec:sc=\\E7:st=\\EH:up=\\EM:\\\n\t:le=^H:bl=^G:cr=^M:it#8:ho=\\E[H:nw=\\EE:ta=^I:is=\\E)0:\\\n\t:li#40:co#189:am:xn:xv:LP:sr=\\EM:al=\\E[L:AL=\\E[%dL:\\\n\t:cs=\\E[%i%d;%dr:dl=\\E[M:DL=\\E[%dM:dc=\\E[P:DC=\\E[%dP:\\\n\t:im=\\E[4h:ei=\\E[4l:mi:IC=\\E[%d@:ks=\\E[?1h\\E=:\\\n\t:ke=\\E[?1l\\E>:vi=\\E[?25l:ve=\\E[34h\\E[?25h:vs=\\E[34l:\\\n\t:ti=\\E[?1049h:te=\\E[?1049l:us=\\E[4m:ue=\\E[24m:so=\\E[3m:\\\n\t:se=\\E[23m:mb=\\E[5m:md=\\E[1m:mr=\\E[7m:me=\\E[m:ms:\\\n\t:Co#8:pa#64:AF=\\E[3%dm:AB=\\E[4%dm:op=\\E[39;49m:AX:\\\n\t:vb=\\Eg:G0:as=\\E(0:ae=\\E(B:\\\n\t:ac=\\140\\140aaffggjjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~..--++,,hhII00:\\\n\t:po=\\E[5i:pf=\\E[4i:Km=\\E[M:k0=\\E[10~:k1=\\EOP:k2=\\EOQ:\\\n\t:k3=\\EOR:k4=\\EOS:k5=\\E[15~:k6=\\E[17~:k7=\\E[18~:\\\n\t:k8=\\E[19~:k9=\\E[20~:k;=\\E[21~:F1=\\E[23~:F2=\\E[24~:\\\n\t:F3=\\E[1;2P:F4=\\E[1;2Q:F5=\\E[1;2R:F6=\\E[1;2S:\\\n\t:F7=\\E[15;2~:F8=\\E[17;2~:F9=\\E[18;2~:FA=\\E[19;2~:kb=\x7F:\\\n\t:K2=\\EOE:kB=\\E[Z:kF=\\E[1;2B:kR=\\E[1;2A:*4=\\E[3;2~:\\\n\t:*7=\\E[1;2F:#2=\\E[1;2H:#3=\\E[2;2~:#4=\\E[1;2D:%c=\\E[6;2~:\\\n\t:%e=\\E[5;2~:%i=\\E[1;2C:kh=\\E[1~:@1=\\E[1~:kH=\\E[4~:\\\n\t:@7=\\E[4~:kN=\\E[6~:kP=\\E[5~:kI=\\E[2~:kD=\\E[3~:ku=\\EOA:\\\n\t:kd=\\EOB:kr=\\EOC:kl=\\EOD:km:"
MAIL: "/var/spool/mail/root"
PATH: "/root/arachni-1.4-0.5.10/system/gems/bin:/root/arachni-1.4-0.5.10/bin/../system/../bin:/root/arachni-1.4-0.5.10/bin/../system/usr/bin:/root/arachni-1.4-0.5.10/bin/../system/gems/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin"
STY: 26872.pts-0.localhost
C_INCLUDE_PATH: "/root/arachni-1.4-0.5.10/bin/../system/usr/include"
PWD: "/root/arachni-1.4-0.5.10/bin"
ARACHNI_WEBUI_LOGDIR: "/root/arachni-1.4-0.5.10/bin/../system/logs/webui"
LANG: en_US.UTF-8
ARACHNI_FRAMEWORK_LOGDIR: "/root/arachni-1.4-0.5.10/bin/../system/logs/framework"
HISTCONTROL: ignoredups
SHLVL: '2'
HOME: "/root/arachni-1.4-0.5.10/bin/../system/home/arachni"
RAILS_ENV: production
DYLD_LIBRARY_PATH: "/root/arachni-1.4-0.5.10/bin/../system/usr/lib:/usr/lib:/usr/local/lib"
LOGNAME: root
WINDOW: '0'
GEM_PATH: "/root/arachni-1.4-0.5.10/bin/../system/gems"
LESSOPEN: "||/usr/bin/lesspipe.sh %s"
RUBYLIB: "/root/arachni-1.4-0.5.10/system/gems/gems/bundler-1.11.2/lib:/root/arachni-1.4-0.5.10/bin/../system/usr/lib/ruby:/root/arachni-1.4-0.5.10/bin/../system/usr/lib/ruby/site_ruby/2.2.0:/root/arachni-1.4-0.5.10/bin/../system/usr/lib/ruby/2.2.0:/root/arachni-1.4-0.5.10/bin/../system/usr/lib/ruby/2.2.0/x86_64-linux:/root/arachni-1.4-0.5.10/bin/../system/usr/lib/ruby/site_ruby/2.2.0/x86_64-linux"
RUBY_VERSION: ruby-2.2.3
HISTTIMEFORMAT: "%F %T # "
RACK_ENV: development
BUNDLE_GEMFILE: "/root/arachni-1.4-0.5.10/system/arachni-ui-web/Gemfile"
_ORIGINAL_GEM_PATH: "/root/arachni-1.4-0.5.10/bin/../system/gems"
BUNDLE_BIN_PATH: "/root/arachni-1.4-0.5.10/system/gems/gems/bundler-1.11.2/exe/bundle"
RUBYOPT: "-rbundler/setup"
MANPATH: "/root/arachni-1.4-0.5.10/system/gems/gems/kramdown-1.4.1/man"
BUNDLE_ORIG_MANPATH: "/root/arachni-1.4-0.5.10/system/gems/gems/kramdown-1.4.1/man"
--------------------------------------------------------------------------------
OPTIONS:
---
datastore:
  token: a91176a6aab993fe3a0eea57140ea4fb
browser_cluster:
  local_storage: {}
  wait_for_elements: {}
  pool_size: 6
  job_timeout: 25
  worker_time_to_live: 100
  ignore_images: false
  screen_width: 1600
  screen_height: 1200
scope:
  redundant_path_patterns: {}
  dom_depth_limit: 5
  exclude_file_extensions: []
  exclude_path_patterns: []
  exclude_content_patterns: []
  include_path_patterns: []
  restrict_paths: []
  extend_paths: []
  url_rewrites: {}
audit:
  parameter_values: true
  exclude_vector_patterns: []
  include_vector_patterns: []
  link_templates: []
  links: true
  forms: true
  cookies: true
  jsons: true
  xmls: true
  ui_forms: true
  ui_inputs: true
input:
  values:
    name: arachni_name
    user: arachni_user
    usr: arachni_user
    pass: 5543!%arachni_secret
    txt: arachni_text
    num: '132'
    amount: '100'
    mail: arachni@email.gr
    account: '12'
    id: '1'
  default_values:
    name: arachni_name
    user: arachni_user
    usr: arachni_user
    pass: 5543!%arachni_secret
    txt: arachni_text
    num: '132'
    amount: '100'
    mail: arachni@email.gr
    account: '12'
    id: '1'
  without_defaults: true
  force: false
http:
  user_agent: Arachni/v1.4
  request_timeout: 10000
  request_redirect_limit: 5
  request_concurrency: 20
  request_queue_size: 100
  request_headers: {}
  response_max_size: 500000
  cookies: {}
session: {}
checks:
- sql_injection
- sql_injection_differential
- sql_injection_timing
platforms: []
plugins:
  autothrottle: {}
  discovery: {}
  healthmap: {}
  timing_attacks: {}
  uniformity: {}
no_fingerprinting: false
authorized_by: 
url: http://m.ly.com/
--------------------------------------------------------------------------------
[2016-02-18 14:56:06 +0800] [HTTP: 0] http://m.ly.com/youlun/json/cruisecommonjson.html?topicId=255&moduleId=766&lid=48
[2016-02-18 14:56:06 +0800] [operation_timedout] Timeout was reached
[2016-02-18 15:04:07 +0800] [Net::OpenTimeout] execution expired
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:1116:in `sleep'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:1116:in `wait_for_timers'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:413:in `wait_till_ready'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:374:in `block in goto'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/page/dom/transition.rb:151:in `call'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/page/dom/transition.rb:151:in `start'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/page/dom/transition.rb:106:in `initialize'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:366:in `new'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:366:in `goto'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/page/dom.rb:150:in `restore'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:280:in `load'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster/jobs/dom_exploration/event_trigger.rb:34:in `run'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster/job.rb:105:in `configure_and_run'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster/worker.rb:87:in `block (2 levels) in run_job'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `call'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `exception_jail'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster/worker.rb:85:in `block in run_job'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:1245:in `call'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:1245:in `block in with_timeout'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/timeout.rb:32:in `block in catch'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/timeout.rb:32:in `catch'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/timeout.rb:32:in `catch'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/timeout.rb:103:in `timeout'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:1244:in `with_timeout'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster/worker.rb:84:in `run_job'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster/worker.rb:215:in `block (3 levels) in start'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `call'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `exception_jail'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster/worker.rb:215:in `block (2 levels) in start'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `call'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `exception_jail'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster/worker.rb:213:in `block in start'
[2016-02-18 15:04:07 +0800] 
[2016-02-18 15:04:07 +0800] Parent:
[2016-02-18 15:04:07 +0800] Arachni::BrowserCluster::Worker
[2016-02-18 15:04:07 +0800] 
[2016-02-18 15:04:07 +0800] Block:
[2016-02-18 15:04:07 +0800] #<Proc:0x007fef11f71888@/root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster/worker.rb:85>
[2016-02-18 15:04:07 +0800] 
[2016-02-18 15:04:07 +0800] Caller:
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `exception_jail'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster/worker.rb:85:in `block in run_job'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:1245:in `call'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:1245:in `block in with_timeout'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/timeout.rb:32:in `block in catch'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/timeout.rb:32:in `catch'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/timeout.rb:32:in `catch'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/timeout.rb:103:in `timeout'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:1244:in `with_timeout'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster/worker.rb:84:in `run_job'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster/worker.rb:215:in `block (3 levels) in start'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `call'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `exception_jail'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster/worker.rb:215:in `block (2 levels) in start'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `call'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `exception_jail'
[2016-02-18 15:04:07 +0800] /root/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster/worker.rb:213:in `block in start'
[2016-02-18 15:04:07 +0800] --------------------------------------------------------------------------------

```

**Comment by Zapotek** [comment]
Timeout errors can occur depending on the networking conditions, no need for concern.
