### ISSUE TITLE
Error arachni whit proxychains

### ISSUE THREAD

**Issue by lgcambero** [Arachni/arachni#677]
I'm trying to use Arachni with proxychains but I have the following error, you'll know that you should or should I go about it?

```
root@kali:~/Desktop/arachni-1.4-0.5.10/bin# proxychains ./arachni http://www.scanme.nmap.org
ProxyChains-3.1 (http://proxychains.sf.net)
|DNS-response|: kali does not exist
Arachni - Web Application Security Scanner Framework v1.4
   Author: Tasos "Zapotek" Laskos <tasos.laskos@arachni-scanner.com>

           (With the support of the community and the Arachni Team.)

   Website:       http://arachni-scanner.com
   Documentation: http://arachni-scanner.com/wiki


 [~] No checks were specified, loading all.
 [~] No element audit options were specified, will audit links, forms, cookies, UI inputs, UI forms, JSONs and XMLs.

 [*] Initializing...
 [*] Preparing plugins...
 [*] ... done.
 [*] BrowserCluster: Initializing 6 browsers...
|S-chain|-<>-127.0.0.1:9050-<><>-127.0.0.1:65390-<--timeout
 [-] [utilities#exception_jail:428] [Errno::ECONNREFUSED] Connection refused - connect(2) for "127.0.0.1" port 65390
 [-] [utilities#exception_jail:428] /root/Desktop/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/net/http.rb:879:in `initialize'
 [-] [utilities#exception_jail:428] /root/Desktop/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/net/http.rb:879:in `open'
 [-] [utilities#exception_jail:428] /root/Desktop/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
 [-] [utilities#exception_jail:428] /root/Desktop/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
 [-] [utilities#exception_jail:428] /root/Desktop/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/timeout.rb:98:in `call'
 [-] [utilities#exception_jail:428] /root/Desktop/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/timeout.rb:98:in `timeout'
 [-] [utilities#exception_jail:428] /root/Desktop/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/net/http.rb:878:in `connect'
 [-] [utilities#exception_jail:428] /root/Desktop/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
 [-] [utilities#exception_jail:428] /root/Desktop/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/net/http.rb:852:in `start'
 [-] [utilities#exception_jail:428] /root/Desktop/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/net/http.rb:1375:in `request'
 [-] [utilities#exception_jail:428] /root/Desktop/arachni-1.4-0.5.10/system/gems/gems/selenium-webdriver-2.51.0/lib/selenium/webdriver/remote/http/default.rb:107:in `response_for'
 [-] [utilities#exception_jail:428] /root/Desktop/arachni-1.4-0.5.10/system/gems/gems/selenium-webdriver-2.51.0/lib/selenium/webdriver/remote/http/default.rb:58:in `request'
 [-] [utilities#exception_jail:428] /root/Desktop/arachni-1.4-0.5.10/system/gems/gems/selenium-webdriver-2.51.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
 [-] [utilities#exception_jail:428] /root/Desktop/arachni-1.4-0.5.10/system/gems/gems/selenium-webdriver-2.51.0/lib/selenium/webdriver/remote/bridge.rb:645:in `raw_execute'
 [-] [utilities#exception_jail:428] /root/Desktop/arachni-1.4-0.5.10/system/gems/gems/selenium-webdriver-2.51.0/lib/selenium/webdriver/remote/bridge.rb:123:in `create_session'
 [-] [utilities#exception_jail:428] /root/Desktop/arachni-1.4-0.5.10/system/gems/gems/selenium-webdriver-2.51.0/lib/selenium/webdriver/remote/bridge.rb:87:in `initialize'
 [-] [utilities#exception_jail:428] /root/Desktop/arachni-1.4-0.5.10/system/gems/gems/selenium-webdriver-2.51.0/lib/selenium/webdriver/common/driver.rb:59:in `new'
 [-] [utilities#exception_jail:428] /root/Desktop/arachni-1.4-0.5.10/system/gems/gems/selenium-webdriver-2.51.0/lib/selenium/webdriver/common/driver.rb:59:in `for'
 [-] [utilities#exception_jail:428] /root/Desktop/arachni-1.4-0.5.10/system/gems/gems/selenium-webdriver-2.51.0/lib/selenium/webdriver.rb:86:in `for'
 [-] [utilities#exception_jail:428] /root/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:1159:in `selenium'
 [-] [utilities#exception_jail:428] /root/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:197:in `initialize'
 [-] [utilities#exception_jail:428] /root/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster/worker.rb:52:in `initialize'
 [-] [utilities#exception_jail:428] /root/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster.rb:477:in `new'
 [-] [utilities#exception_jail:428] /root/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster.rb:477:in `block in initialize_workers'
 [-] [utilities#exception_jail:428] /root/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster.rb:476:in `times'
 [-] [utilities#exception_jail:428] /root/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster.rb:476:in `initialize_workers'
 [-] [utilities#exception_jail:428] /root/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster.rb:119:in `initialize'
 [-] [utilities#exception_jail:428] /root/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework/parts/browser.rb:33:in `new'
 [-] [utilities#exception_jail:428] /root/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework/parts/browser.rb:33:in `block in browser_cluster'
 [-] [utilities#exception_jail:428] /root/Desktop/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
 [-] [utilities#exception_jail:428] /root/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework/parts/browser.rb:28:in `browser_cluster'
 [-] [utilities#exception_jail:428] /root/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework/parts/audit.rb:173:in `audit'
 [-] [utilities#exception_jail:428] /root/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework.rb:117:in `block in run'
 [-] [utilities#exception_jail:428] /root/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `call'
 [-] [utilities#exception_jail:428] /root/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `exception_jail'
 [-] [utilities#exception_jail:428] /root/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework.rb:117:in `run'
 [-] [utilities#exception_jail:428] /root/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/ui/cli/framework.rb:63:in `block in run'
 [-] [utilities#exception_jail:429] 
 [-] [utilities#exception_jail:430] Parent:
 [-] [utilities#exception_jail:431] Arachni::Framework
 [-] [utilities#exception_jail:432] 
 [-] [utilities#exception_jail:433] Block:
 [-] [utilities#exception_jail:434] #<Proc:0x00000003c7e518@/root/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework.rb:117>
 [-] [utilities#exception_jail:435] 
 [-] [utilities#exception_jail:436] Caller:
 [-] [utilities#exception_jail:437] /root/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `exception_jail'
 [-] [utilities#exception_jail:437] /root/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework.rb:117:in `run'
 [-] [utilities#exception_jail:437] /root/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/ui/cli/framework.rb:63:in `block in run'
 [-] [utilities#exception_jail:438] --------------------------------------------------------------------------------
```

**Comment by Zapotek** [comment]
Hello,

Arachni uses socket IO and HTTP for many of its internal operations, you can't hijack all connections with something like proxychains.

If you'd like to run Arachni through a proxy you should use the `--http-proxy` option.

Cheers
