### ISSUE TITLE
Proxy error

### ISSUE THREAD

**Issue by diegoesc** [Arachni/arachni#688]
I got an error <TypeError: no implicit conversion of String into Hash>, when browsing my site with plugin=proxy option, and request an (api) url with not supported method (json response was: {"Message":"The requested resource does not support http method 'GET'."})
Thanks!

**Comment by Zapotek** [comment]
Do you get an actual error from Arachni or is this something the application returns in these cases?
Does the same thing happen when not using the proxy?

This just looks like normal behavior to me.

**Comment by diegoesc** [comment]
It seems an error from Arachni, but the request method is POST not GET. To clarify the issue let me show you what happens when I browse the site after using the following command:
/bin/arachni https://... --checks - --plugin=proxy --browser-cluster-pool-size 0

...

 [*] Proxy: Requesting https://.../api/userpreferences/preferences
#<TypeError: no implicit conversion of String into Hash>
[
    [0] "/root/Desktop/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-84fae8ed9d19/lib/arachni/element/json.rb:46:in `merge'",
    [1] "/root/Desktop/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-84fae8ed9d19/lib/arachni/element/json.rb:46:in `initialize'",
    [2] "/root/Desktop/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-84fae8ed9d19/lib/arachni/element/json.rb:118:in `new'",
    [3] "/root/Desktop/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-84fae8ed9d19/lib/arachni/element/json.rb:118:in `from_request'",
    [4] "/root/Desktop/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-84fae8ed9d19/components/plugins/proxy.rb:394:in `update_forms'",
    [5] "/root/Desktop/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-84fae8ed9d19/components/plugins/proxy.rb:382:in `response_handler'",
    [6] "/root/Desktop/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-84fae8ed9d19/lib/arachni/http/proxy_server/connection.rb:142:in `call'",
    [7] "/root/Desktop/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-84fae8ed9d19/lib/arachni/http/proxy_server/connection.rb:142:in `handle_response'",
    [8] "/root/Desktop/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-84fae8ed9d19/lib/arachni/http/proxy_server/connection.rb:122:in `block in handle_request'"
]
#<NoMethodError: undefined method `forms' for #<Array:0xaf20ff8>>
[
    [0] "/root/Desktop/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-84fae8ed9d19/components/plugins/proxy.rb:384:in `response_handler'",
    [1] "/root/Desktop/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-84fae8ed9d19/lib/arachni/http/proxy_server/connection.rb:142:in `call'",
    [2] "/root/Desktop/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-84fae8ed9d19/lib/arachni/http/proxy_server/connection.rb:142:in `handle_response'",
    [3] "/root/Desktop/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-84fae8ed9d19/lib/arachni/http/proxy_server/connection.rb:122:in `block in handle_request'"
]

The normal response (of the above url) via POST, with no proxy, is the following:
{"ErrorCode":0,"Message":null,"Content":{"UserName":"test","PageRecords":10,"Timezone":1},"Success":true,"TotalRecords":0,"HaveDuplicates":false,"LastUpdated":"0001-01-01T00:00:00"}
And the "Request payload" is: "undefined"

Using Arachni 2.0dev-1.0dev (3/14)

Thanks!

**Comment by Zapotek** [comment]
Yeah that needs fixing, could you send me the real URLs and the steps to get to that resource via [e-mail](mailto:tasos.laskos@gmail.com) so that I can reproduce this?

**Comment by Zapotek** [comment]
Nightlies are up and they should fix the problem, although without being able to reproduce your particular issue I'm just guessing.
