### ISSUE TITLE
Double Cookies Bug Using Autologin Script

### ISSUE THREAD

**Issue by sbehrens** [Arachni/arachni#700]
Hi Tasos,

I am having issues logging into netflix.com using the autologin plugin.  It worked for a while but is now having issues, here is some verbose output from the plugin:

```
[!] [browser#spawn_phantomjs:1284] Browser: PhantomJS is ready.
[!] [session#login_from_configuration:326] Session: Logging in via configuration.
[!] [session#login_from_configuration:329] Session: Logging in using browser.
[!] [session#login_from_configuration:334] Session: Grabbing page at: https://www.netflix.com/globallogin
[!] [session#login_from_configuration:344] Session: Got page with URL https://www.netflix.com/globallogin
[!] [session#login_from_configuration:360] Session: Found login form: form:post:https://www.netflix.com/globallogin:-141964720793868947:4606983592342835654
[!] [session#login_from_configuration:377] Session: Updated form inputs: {"authURL"=>"1461010434626.1cR0zdZOXb/0YmJjfEYeKweMBlg=", "email"=>"redacted@redacted.com", "password"=>"REDACTED", "RememberMe"=>"", "login-form-contBtn"=>""}
[!] [session#login_from_configuration:381] Session: Submitting form.
[!] [page/dom#restore:172] Browser: Could not load snapshot by URL (https://www.netflix.com/globallogin), will load by replaying transitions.
[!] [session#login_from_configuration:383] Session: Form submitted.
[!] [session#logged_in?:285] Session: Performing login check.
[!] [session#logged_in?:291] Session: Login check done: false
[!] [session#logged_in?:294] Session:
```

It is unclear to me why it cannot log in but i'm not having any issues authenticating using the test account via a browser or curl so unsure what the issue is.  Does the log file tell you something may be going on?

**Comment by Zapotek** [comment]
Hey Scott,

That doesn't tell me much but I'll try to reproduce it tomorrow.
In the meantime, you can try increasing the debug level which will show you the session check response.

Cheers

**Comment by sbehrens** [comment]
Im on a remote server and when i raise the debug level from 2 to 3, the debug file is now 0.  i tried a few times but it only logs if debug < 3.

**Comment by sbehrens** [comment]
Hi Tasos,

I have identified the bug and can reproduce it.  While proxying during login, cookies that are sent are not being updated instead the cookies are being appended too (meaning we send 2 cookies with the same names but different values).  

Autologin plugin POST /login (already has 2 session cookies)
Server responds with the same 2 session cookies with different values
Autologin plugin follows 302 redirect but appends the 2 cookies onto the Cookie string (so now we are sending 2 cookies with same name)
App reads the first pair of cookies (which are the old ones) and thinks you are logged out.

**Comment by Zapotek** [comment]
Thanks man. :)

**Comment by sbehrens** [comment]
If it would be helpful I can send you the Burpsuite logs with the double cookies but it seems pretty easy to reproduce on netflix.com using the autologin script.

**Comment by Zapotek** [comment]
Better send them over so that I'll have something to compare my result to.

**Comment by Zapotek** [comment]
A few annotations about which cookies are messed up would help too.

In the meantime I've reproduced it and looking for the bug.

**Comment by Zapotek** [comment]
Nevermind, found the issues, sorting it out now.

**Comment by Zapotek** [comment]
Fixed it, running the test suite now to make sure I didn't break anything and then I'll push nightlies.

**Comment by sbehrens** [comment]
Thanks Tasos please let me know when it's ready to try out.

**Comment by Zapotek** [comment]
Uploading right now.

**Comment by Zapotek** [comment]
Nightlies are up. :)

**Comment by sbehrens** [comment]
Tested, new exception:

```
[-] [utilities#exception_jail:428] Session: [Selenium::WebDriver::Error::NoSuchElementError] Error Message => 'Unable to find element with css selector 'form[class="login-form"][action="/login"][method="post"][data-arachni-id="1073277187"]''
 caused by Request => {"headers":{"Accept":"application/json","Accept-Encoding":"gzip;q=1.0,deflate;q=0.6,identity;q=0.3","Connection":"close","Content-Length":"129","Content-Type":"application/json; charset=utf-8","Host":"127.0.0.1:59193","User-Agent":"Ruby"},"httpVersion":"1.1","method":"POST","post":"{\"using\":\"css selector\",\"value\":\"form[class=\\\"login-form\\\"][action=\\\"/login\\\"][method=\\\"post\\\"][data-arachni-id=\\\"1073277187\\\"]\"}","url":"/element","urlParsed":{"anchor":"","query":"","file":"element","directory":"/","path":"/element","relative":"/element","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/element","queryKey":{},"chunks":["element"]},"urlOriginal":"/session/8a08da80-0746-11e6-b5dd-03b0bcede433/element"} (SessionReqHand)
 [-] [utilities#exception_jail:428] Session: /private/tmp/arachni/system/gems/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/response.rb:70:in `assert_ok'
 [-] [utilities#exception_jail:428] Session: /private/tmp/arachni/system/gems/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
 [-] [utilities#exception_jail:428] Session: /private/tmp/arachni/system/gems/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/http/common.rb:78:in `new'
 [-] [utilities#exception_jail:428] Session: /private/tmp/arachni/system/gems/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/http/common.rb:78:in `create_response'
 [-] [utilities#exception_jail:428] Session: /private/tmp/arachni/system/gems/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/http/default.rb:90:in `request'
 [-] [utilities#exception_jail:428] Session: /private/tmp/arachni/system/gems/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
 [-] [utilities#exception_jail:428] Session: /private/tmp/arachni/system/gems/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/bridge.rb:649:in `raw_execute'
 [-] [utilities#exception_jail:428] Session: /private/tmp/arachni/system/gems/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/bridge.rb:627:in `execute'
 [-] [utilities#exception_jail:428] Session: /private/tmp/arachni/system/gems/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/bridge.rb:596:in `find_element_by'
 [-] [utilities#exception_jail:428] Session: /private/tmp/arachni/system/gems/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/common/search_context.rb:61:in `find_element'
 [-] [utilities#exception_jail:428] Session: /private/tmp/arachni/system/gems/bundler/gems/arachni-6698254a8698/lib/arachni/browser/element_locator.rb:70:in `locate'
 [-] [utilities#exception_jail:428] Session: /private/tmp/arachni/system/gems/bundler/gems/arachni-6698254a8698/lib/arachni/element/dom/capabilities/locatable.rb:22:in `locate'
 [-] [utilities#exception_jail:428] Session: /private/tmp/arachni/system/gems/bundler/gems/arachni-6698254a8698/lib/arachni/element/form/dom.rb:39:in `trigger'
 [-] [utilities#exception_jail:428] Session: /private/tmp/arachni/system/gems/bundler/gems/arachni-6698254a8698/lib/arachni/element/dom/capabilities/submittable.rb:26:in `block in submit'
 [-] [utilities#exception_jail:428] Session: /private/tmp/arachni/system/gems/bundler/gems/arachni-6698254a8698/lib/arachni/session.rb:260:in `call'
 [-] [utilities#exception_jail:428] Session: /private/tmp/arachni/system/gems/bundler/gems/arachni-6698254a8698/lib/arachni/session.rb:260:in `with_browser'
 [-] [utilities#exception_jail:428] Session: /private/tmp/arachni/system/gems/bundler/gems/arachni-6698254a8698/lib/arachni/element/dom/capabilities/auditable.rb:18:in `with_browser'
 [-] [utilities#exception_jail:428] Session: /private/tmp/arachni/system/gems/bundler/gems/arachni-6698254a8698/lib/arachni/element/dom/capabilities/submittable.rb:21:in `submit'
 [-] [utilities#exception_jail:428] Session: /private/tmp/arachni/system/gems/bundler/gems/arachni-6698254a8698/lib/arachni/session.rb:399:in `login_from_configuration'
 [-] [utilities#exception_jail:428] Session: /private/tmp/arachni/system/gems/bundler/gems/arachni-6698254a8698/lib/arachni/session.rb:245:in `block in login'
 [-] [utilities#exception_jail:428] Session: /private/tmp/arachni/system/gems/bundler/gems/arachni-6698254a8698/lib/arachni/utilities.rb:425:in `call'
 [-] [utilities#exception_jail:428] Session: /private/tmp/arachni/system/gems/bundler/gems/arachni-6698254a8698/lib/arachni/utilities.rb:425:in `exception_jail'
 [-] [utilities#exception_jail:428] Session: /private/tmp/arachni/system/gems/bundler/gems/arachni-6698254a8698/lib/arachni/session.rb:244:in `login'
 [-] [utilities#exception_jail:428] Session: /private/tmp/arachni/system/gems/bundler/gems/arachni-6698254a8698/components/plugins/autologin.rb:37:in `prepare'
 [-] [utilities#exception_jail:428] Session: /private/tmp/arachni/system/gems/bundler/gems/arachni-6698254a8698/lib/arachni/plugin/manager.rb:69:in `block (2 levels) in run'
 [-] [utilities#exception_jail:428] Session: /private/tmp/arachni/system/gems/bundler/gems/arachni-6698254a8698/lib/arachni/utilities.rb:425:in `call'
 [-] [utilities#exception_jail:428] Session: /private/tmp/arachni/system/gems/bundler/gems/arachni-6698254a8698/lib/arachni/utilities.rb:425:in `exception_jail'
 [-] [utilities#exception_jail:428] Session: /private/tmp/arachni/system/gems/bundler/gems/arachni-6698254a8698/lib/arachni/plugin/manager.rb:68:in `block in run'
 [-] [utilities#exception_jail:428] Session: /private/tmp/arachni/system/gems/bundler/gems/arachni-6698254a8698/lib/arachni/plugin/manager.rb:65:in `each'
 [-] [utilities#exception_jail:428] Session: /private/tmp/arachni/system/gems/bundler/gems/arachni-6698254a8698/lib/arachni/plugin/manager.rb:65:in `run'
 [-] [utilities#exception_jail:428] Session: /private/tmp/arachni/system/gems/bundler/gems/arachni-6698254a8698/lib/arachni/framework/parts/state.rb:348:in `prepare'
 [-] [utilities#exception_jail:428] Session: /private/tmp/arachni/system/gems/bundler/gems/arachni-6698254a8698/lib/arachni/framework.rb:110:in `run'
 [-] [utilities#exception_jail:428] Session: /private/tmp/arachni/system/gems/bundler/gems/arachni-6698254a8698/ui/cli/framework.rb:63:in `block in run'
 [-] [utilities#exception_jail:429] Session:
 [-] [utilities#exception_jail:430] Session: Parent:
 [-] [utilities#exception_jail:431] Session: Arachni::Session
 [-] [utilities#exception_jail:432] Session:
 [-] [utilities#exception_jail:433] Session: Block:
 [-] [utilities#exception_jail:434] Session: #<Proc:0x007fea1ed416c8@/private/tmp/arachni/system/gems/bundler/gems/arachni-6698254a8698/lib/arachni/session.rb:244>
 [-] [utilities#exception_jail:435] Session:
 [-] [utilities#exception_jail:436] Session: Caller:
 [-] [utilities#exception_jail:437] Session: /private/tmp/arachni/system/gems/bundler/gems/arachni-6698254a8698/lib/arachni/utilities.rb:425:in `exception_jail'
 [-] [utilities#exception_jail:437] Session: /private/tmp/arachni/system/gems/bundler/gems/arachni-6698254a8698/lib/arachni/session.rb:244:in `login'
 [-] [utilities#exception_jail:437] Session: /private/tmp/arachni/system/gems/bundler/gems/arachni-6698254a8698/components/plugins/autologin.rb:37:in `prepare'
 [-] [utilities#exception_jail:437] Session: /private/tmp/arachni/system/gems/bundler/gems/arachni-6698254a8698/lib/arachni/plugin/manager.rb:69:in `block (2 levels) in run'
 [-] [utilities#exception_jail:437] Session: /private/tmp/arachni/system/gems/bundler/gems/arachni-6698254a8698/lib/arachni/utilities.rb:425:in `call'
 [-] [utilities#exception_jail:437] Session: /private/tmp/arachni/system/gems/bundler/gems/arachni-6698254a8698/lib/arachni/utilities.rb:425:in `exception_jail'
 [-] [utilities#exception_jail:437] Session: /private/tmp/arachni/system/gems/bundler/gems/arachni-6698254a8698/lib/arachni/plugin/manager.rb:68:in `block in run'
 [-] [utilities#exception_jail:437] Session: /private/tmp/arachni/system/gems/bundler/gems/arachni-6698254a8698/lib/arachni/plugin/manager.rb:65:in `each'
 [-] [utilities#exception_jail:437] Session: /private/tmp/arachni/system/gems/bundler/gems/arachni-6698254a8698/lib/arachni/plugin/manager.rb:65:in `run'
 [-] [utilities#exception_jail:437] Session: /private/tmp/arachni/system/gems/bundler/gems/arachni-6698254a8698/lib/arachni/framework/parts/state.rb:348:in `prepare'
 [-] [utilities#exception_jail:437] Session: /private/tmp/arachni/system/gems/bundler/gems/arachni-6698254a8698/lib/arachni/framework.rb:110:in `run'
 [-] [utilities#exception_jail:437] Session: /private/tmp/arachni/system/gems/bundler/gems/arachni-6698254a8698/ui/cli/framework.rb:63:in `block in run'
 [-] [utilities#exception_jail:438] Session: --------------------------------------------------------------------------------
 [-] [utilities#exception_jail:428] [Selenium::WebDriver::Error::NoSuchElementError] Error Message => 'Unable to find element with css selector 'form[class="login-form"][action="/login"][method="post"][data-arachni-id="1073277187"]''
 caused by Request => {"headers":{"Accept":"application/json","Accept-Encoding":"gzip;q=1.0,deflate;q=0.6,identity;q=0.3","Connection":"close","Content-Length":"129","Content-Type":"application/json; charset=utf-8","Host":"127.0.0.1:59193","User-Agent":"Ruby"},"httpVersion":"1.1","method":"POST","post":"{\"using\":\"css selector\",\"value\":\"form[class=\\\"login-form\\\"][action=\\\"/login\\\"][method=\\\"post\\\"][data-arachni-id=\\\"1073277187\\\"]\"}","url":"/element","urlParsed":{"anchor":"","query":"","file":"element","directory":"/","path":"/element","relative":"/element","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/element","queryKey":{},"chunks":["element"]},"urlOriginal":"/session/8a08da80-0746-11e6-b5dd-03b0bcede433/element"} (SessionReqHand)
```

**Comment by sbehrens** [comment]
I used a different login endpoint and observed the same double cookie bug on that endpoint, see screenshot

![image](https://cloud.githubusercontent.com/assets/688589/14692566/edbf7e4c-070c-11e6-8ab5-256466ec416a.png)

You will see NetflixId and SecureNetflixId are set twice instead of it's value being overwritten during login.

**Comment by Zapotek** [comment]
Does the login work though?

**Comment by Zapotek** [comment]
The login worked for em consistently but I think I missed an entry point for the cookies, fixing and will upload nightlies.

**Comment by Zapotek** [comment]
Well, this is embarrassing, I made a typo during my fix, I was setting the domain attribute in `Set-Cookie` as `Domain: host` rather than `Domain=host`.
The fact that it was working for a while was weird though.

**Comment by Zapotek** [comment]
Having some networking issue that don't let me build the packages, will let you know once I manage to upload them.

**Comment by Zapotek** [comment]
Ok, now they should work properly.

**Comment by sbehrens** [comment]
Resolved, thanks!

**Comment by sbehrens** [comment]
Hey Tasos, did the fix also go into the Linux branch?  It's working fine for me on my laptop (OSX) but I'm still not able to auth using an AWS ubuntu box.

**Comment by Zapotek** [comment]
Yeah, all packages have the same code.
Maybe an env or whitelisting issue?

**Comment by sbehrens** [comment]
Totally my side, sorry!

**Comment by sbehrens** [comment]
Thanks again for the help.
