### ISSUE TITLE
Arachni_reporter is failing 

### ISSUE THREAD

**Issue by dnyrop** [Arachni/arachni#701]
When I run a scan like this: `arachni http://www.testfire.net      --timeout=00:01:00`  (timeout can be left out with the same result) the resulting .afr report can't be converted into an xml file like this: 
`arachni_reporter www.testfire.net\ 2016-04-20\ 16_46_44\ +0000.afr --reporter=xml:outfile=testfire.xml`

This error is returned:
```
[-] [utilities#exception_jail:428] [ArgumentError] string contains null byte
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/node.rb:127:in `set'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/node.rb:127:in `[]='
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/document.rb:98:in `block (2 levels) in create_element'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/document.rb:92:in `each'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/document.rb:92:in `block in create_element'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/document.rb:89:in `each'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/document.rb:89:in `create_element'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/builder.rb:359:in `method_missing'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/components/reporters/xml.rb:188:in `block (2 levels) in add_inputs'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/components/reporters/xml.rb:187:in `each'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/components/reporters/xml.rb:187:in `block in add_inputs'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/builder.rb:391:in `call'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/builder.rb:391:in `insert'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/builder.rb:375:in `method_missing'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/components/reporters/xml.rb:186:in `add_inputs'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/components/reporters/xml.rb:88:in `block (6 levels) in run'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/builder.rb:391:in `call'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/builder.rb:391:in `insert'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/builder.rb:375:in `method_missing'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/components/reporters/xml.rb:65:in `block (5 levels) in run'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/builder.rb:391:in `call'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/builder.rb:391:in `insert'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/builder.rb:375:in `method_missing'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/components/reporters/xml.rb:39:in `block (4 levels) in run'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/components/reporters/xml.rb:38:in `each'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/components/reporters/xml.rb:38:in `block (3 levels) in run'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/builder.rb:391:in `call'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/builder.rb:391:in `insert'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/builder.rb:375:in `method_missing'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/components/reporters/xml.rb:37:in `block (2 levels) in run'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/builder.rb:391:in `call'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/builder.rb:391:in `insert'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/builder.rb:375:in `method_missing'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/components/reporters/xml.rb:22:in `block in run'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/builder.rb:293:in `initialize'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/components/reporters/xml.rb:21:in `new'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/components/reporters/xml.rb:21:in `run'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/reporter/manager.rb:34:in `tap'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/reporter/manager.rb:34:in `block in run'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `call'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `exception_jail'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/reporter/manager.rb:33:in `run'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/ui/cli/reporter.rb:43:in `block in run'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/ui/cli/reporter.rb:42:in `each'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/ui/cli/reporter.rb:42:in `run'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/ui/cli/reporter.rb:25:in `initialize'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/bin/arachni_reporter:12:in `new'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/bin/arachni_reporter:12:in `<top (required)>'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/bin/../system/arachni-ui-web/bin/arachni_reporter:16:in `load'
 [-] [utilities#exception_jail:428] /usr/local/arachni-1.4-0.5.10/bin/../system/arachni-ui-web/bin/arachni_reporter:16:in `<main>'
 [-] [utilities#exception_jail:429] 
 [-] [utilities#exception_jail:430] Parent:
 [-] [utilities#exception_jail:431] Arachni::Reporter::Manager
 [-] [utilities#exception_jail:432] 
 [-] [utilities#exception_jail:433] Block:
 [-] [utilities#exception_jail:434] #<Proc:0x0000000409d2e8@/usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/reporter/manager.rb:33>
 [-] [utilities#exception_jail:435] 
 [-] [utilities#exception_jail:436] Caller:
 [-] [utilities#exception_jail:437] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `exception_jail'
 [-] [utilities#exception_jail:437] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/reporter/manager.rb:33:in `run'
 [-] [utilities#exception_jail:437] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/ui/cli/reporter.rb:43:in `block in run'
 [-] [utilities#exception_jail:437] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/ui/cli/reporter.rb:42:in `each'
 [-] [utilities#exception_jail:437] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/ui/cli/reporter.rb:42:in `run'
 [-] [utilities#exception_jail:437] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/ui/cli/reporter.rb:25:in `initialize'
 [-] [utilities#exception_jail:437] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/bin/arachni_reporter:12:in `new'
 [-] [utilities#exception_jail:437] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/bin/arachni_reporter:12:in `<top (required)>'
 [-] [utilities#exception_jail:437] /usr/local/arachni-1.4-0.5.10/bin/../system/arachni-ui-web/bin/arachni_reporter:16:in `load'
 [-] [utilities#exception_jail:437] /usr/local/arachni-1.4-0.5.10/bin/../system/arachni-ui-web/bin/arachni_reporter:16:in `<main>'
 [-] [utilities#exception_jail:438] --------------------------------------------------------------------------------
 [-] [ui/cli/reporter#run:47] [ArgumentError] string contains null byte
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/node.rb:127:in `set'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/node.rb:127:in `[]='
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/document.rb:98:in `block (2 levels) in create_element'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/document.rb:92:in `each'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/document.rb:92:in `block in create_element'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/document.rb:89:in `each'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/document.rb:89:in `create_element'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/builder.rb:359:in `method_missing'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/components/reporters/xml.rb:188:in `block (2 levels) in add_inputs'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/components/reporters/xml.rb:187:in `each'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/components/reporters/xml.rb:187:in `block in add_inputs'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/builder.rb:391:in `call'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/builder.rb:391:in `insert'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/builder.rb:375:in `method_missing'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/components/reporters/xml.rb:186:in `add_inputs'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/components/reporters/xml.rb:88:in `block (6 levels) in run'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/builder.rb:391:in `call'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/builder.rb:391:in `insert'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/builder.rb:375:in `method_missing'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/components/reporters/xml.rb:65:in `block (5 levels) in run'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/builder.rb:391:in `call'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/builder.rb:391:in `insert'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/builder.rb:375:in `method_missing'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/components/reporters/xml.rb:39:in `block (4 levels) in run'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/components/reporters/xml.rb:38:in `each'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/components/reporters/xml.rb:38:in `block (3 levels) in run'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/builder.rb:391:in `call'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/builder.rb:391:in `insert'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/builder.rb:375:in `method_missing'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/components/reporters/xml.rb:37:in `block (2 levels) in run'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/builder.rb:391:in `call'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/builder.rb:391:in `insert'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/builder.rb:375:in `method_missing'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/components/reporters/xml.rb:22:in `block in run'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/nokogiri-1.6.8.rc2/lib/nokogiri/xml/builder.rb:293:in `initialize'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/components/reporters/xml.rb:21:in `new'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/components/reporters/xml.rb:21:in `run'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/reporter/manager.rb:34:in `tap'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/reporter/manager.rb:34:in `block in run'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `call'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `exception_jail'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/reporter/manager.rb:33:in `run'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/ui/cli/reporter.rb:43:in `block in run'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/ui/cli/reporter.rb:42:in `each'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/ui/cli/reporter.rb:42:in `run'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/ui/cli/reporter.rb:25:in `initialize'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/bin/arachni_reporter:12:in `new'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/bin/arachni_reporter:12:in `<top (required)>'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/bin/../system/arachni-ui-web/bin/arachni_reporter:16:in `load'
 [-] [ui/cli/reporter#run:47] /usr/local/arachni-1.4-0.5.10/bin/../system/arachni-ui-web/bin/arachni_reporter:16:in `<main>'
```

**Comment by Zapotek** [comment]
This turned out to be a limitation of the XML parser, it doesn't encode null-bytes and the encoded ones are silently stripped.
This error started to get raised by an upgraded version of that dependency, previously the nulls were silently ignored.
If you try the nightlies the error will go away, but so will the null characters which can be vital in properly describing the vulnerability.

I'll work on replacing them with placeholders (something like `[NULL]`) so that at least you'll know that a null-byte is meant to be placed at that position.

**Comment by dnyrop** [comment]
Wow, very quick response :)
I'll try the nightlies.

**Comment by Zapotek** [comment]
Nightlies are up and include the null placeholder substitution thing.

**Comment by TiredOfProgramming** [comment]
I'm getting the same when running a report batch file in VSTS

XML: Null bytes have been replaced with: [ARACHNI_NULL]
