### ISSUE TITLE
spawn_phantomjs:1337] Browser: base.rb:3:in `load': undefined class/module Set (ArgumentError)

### ISSUE THREAD

**Issue by mgeeky** [Arachni/arachni#725]
Hello there.

I've installed my Arachni 1.4 via Kali repos (apt-get install) and found out that it is unable to launch PhantomJS browser driver, as shown in below output. I've been trying to replace default instance of PhantomJS with the one coming from Kali repos, but without any success. 

```
$ /usr/bin/arachni --session-check-url="/dashboard" --session-check-pattern="Wyloguj" --scope-exclude-pattern="/wylogowac-sie" --plugin=autologin:url=https://www.some-website.pl/login_check,parameters="username=some-login&password=some-password&submit=",check="logout|logoff|lylog|witaj|welcome|hello" --output-verbose --output-debug=4 --scope-exclude-file-extensions js,jpg,jpeg,png,gif,bmp,woff,tiff,css,less,pdf,doc,docx,xls,xlsx,rtf,swf --scope-exclude-binaries --scope-auto-redundant=4 --audit-links --audit-forms --audit-cookies --audit-headers --http-user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0" --browser-cluster-ignore-images --checks=*,-backup_files,-backup_directories --plugin=metrics --plugin=waf_detector --plugin=discovery --report-save-path="/root/work/some-project/" --snapshot-save-path="/root/work/some-project/" https://www.some-website.pl

Arachni - Web Application Security Scanner Framework v1.4
   Author: Tasos "Zapotek" Laskos <tasos.laskos@arachni-scanner.com>

           (With the support of the community and the Arachni Team.)

   Website:       http://arachni-scanner.com
   Documentation: http://arachni-scanner.com/wiki


 [*] Initializing...
 [*] Preparing plugins...
 [*] AutoLogin: Logging in, please wait.
 [!!] [http/proxy_server#start_async:50] ProxyServer: Starting
 [!!] [http/proxy_server#start_async:63] ProxyServer: Started
 [!] [browser#spawn_phantomjs:1277] Browser: Spawning PhantomJS...
 [!] [browser#spawn_phantomjs:1290] Browser: Attempt #0, chose port number 19754
 [!] [browser#spawn_phantomjs:1294] Browser: Spawning process: /usr/local/bin/phantomjs
 [!] [browser#spawn_phantomjs:1315] Browser: Process spawned, waiting for it to boot-up...
 [!] [browser#spawn_phantomjs:1333] Browser: Spawn timed-out.
 [!] [browser#spawn_phantomjs:1337] Browser: /usr/share/arachni/lib/arachni/processes/executables/base.rb:3:in `load': undefined class/module Set (ArgumentError)
	from /usr/share/arachni/lib/arachni/processes/executables/base.rb:3:in `<main>'

 [!] [browser#spawn_phantomjs:1345] Browser: Killing process.
 [!] [browser#spawn_phantomjs:1290] Browser: Attempt #1, chose port number 11053
 [!] [browser#spawn_phantomjs:1294] Browser: Spawning process: /usr/local/bin/phantomjs
 [!] [browser#spawn_phantomjs:1315] Browser: Process spawned, waiting for it to boot-up...
 [!] [browser#spawn_phantomjs:1333] Browser: Spawn timed-out.
 [!] [browser#spawn_phantomjs:1337] Browser: /usr/share/arachni/lib/arachni/processes/executables/base.rb:3:in `load': undefined class/module Set (ArgumentError)
	from /usr/share/arachni/lib/arachni/processes/executables/base.rb:3:in `<main>'

 [!] [browser#spawn_phantomjs:1345] Browser: Killing process.
 [!] [browser#spawn_phantomjs:1290] Browser: Attempt #2, chose port number 2169
 [!] [browser#spawn_phantomjs:1294] Browser: Spawning process: /usr/local/bin/phantomjs
 [!] [browser#spawn_phantomjs:1315] Browser: Process spawned, waiting for it to boot-up...
 [!] [browser#spawn_phantomjs:1333] Browser: Spawn timed-out.
 [!] [browser#spawn_phantomjs:1337] Browser: /usr/share/arachni/lib/arachni/processes/executables/base.rb:3:in `load': undefined class/module Set (ArgumentError)
	from /usr/share/arachni/lib/arachni/processes/executables/base.rb:3:in `<main>'

```

Any ideas what to do next, what to test?

Thanks in advance.

**Comment by Zapotek** [comment]
Please try the [nightlies](http://downloads.arachni-scanner.com/nightlies/), they include the fix.

Cheers
