### ISSUE TITLE
[NoMethodError] undefined method `strip' for nil:NilClass

### ISSUE THREAD

**Issue by bararchy** [Arachni/arachni#733]
Getting this crash while scanning a specific page

```
 [-] [utilities#exception_jail:428] Client: [NoMethodError] undefined method `strip' for nil:NilClass
 [-] [utilities#exception_jail:428] Client: /usr/lib/ruby/gems/2.3.0/gems/typhoeus-1.0.1/lib/typhoeus/response/header.rb:48:in `process_line'
 [-] [utilities#exception_jail:428] Client: /usr/lib/ruby/gems/2.3.0/gems/typhoeus-1.0.1/lib/typhoeus/response/header.rb:36:in `block in parse'
 [-] [utilities#exception_jail:428] Client: /usr/lib/ruby/gems/2.3.0/gems/typhoeus-1.0.1/lib/typhoeus/response/header.rb:34:in `each'
 [-] [utilities#exception_jail:428] Client: /usr/lib/ruby/gems/2.3.0/gems/typhoeus-1.0.1/lib/typhoeus/response/header.rb:34:in `parse'
 [-] [utilities#exception_jail:428] Client: /usr/lib/ruby/gems/2.3.0/gems/typhoeus-1.0.1/lib/typhoeus/response/header.rb:19:in `initialize'
 [-] [utilities#exception_jail:428] Client: /usr/lib/ruby/gems/2.3.0/gems/typhoeus-1.0.1/lib/typhoeus/response/informations.rb:226:in `new'
 [-] [utilities#exception_jail:428] Client: /usr/lib/ruby/gems/2.3.0/gems/typhoeus-1.0.1/lib/typhoeus/response/informations.rb:226:in `headers'
 [-] [utilities#exception_jail:428] Client: /home/unshadow/Desktop/git-projects/arachni/lib/arachni/http/response.rb:254:in `from_typhoeus'
 [-] [utilities#exception_jail:428] Client: /home/unshadow/Desktop/git-projects/arachni/lib/arachni/http/request.rb:473:in `block in to_typhoeus'
 [-] [utilities#exception_jail:428] Client: /usr/lib/ruby/gems/2.3.0/gems/typhoeus-1.0.1/lib/typhoeus/request/callbacks.rb:128:in `block in execute_callbacks'
 [-] [utilities#exception_jail:428] Client: /usr/lib/ruby/gems/2.3.0/gems/typhoeus-1.0.1/lib/typhoeus/request/callbacks.rb:127:in `each'
 [-] [utilities#exception_jail:428] Client: /usr/lib/ruby/gems/2.3.0/gems/typhoeus-1.0.1/lib/typhoeus/request/callbacks.rb:127:in `execute_callbacks'
 [-] [utilities#exception_jail:428] Client: /usr/lib/ruby/gems/2.3.0/gems/typhoeus-1.0.1/lib/typhoeus/request/operations.rb:35:in `finish'
 [-] [utilities#exception_jail:428] Client: /usr/lib/ruby/gems/2.3.0/gems/typhoeus-1.0.1/lib/typhoeus/easy_factory.rb:159:in `block in set_callback'
 [-] [utilities#exception_jail:428] Client: /usr/lib/ruby/gems/2.3.0/gems/ethon-0.9.0/lib/ethon/easy/response_callbacks.rb:65:in `block in complete'
 [-] [utilities#exception_jail:428] Client: /usr/lib/ruby/gems/2.3.0/gems/ethon-0.9.0/lib/ethon/easy/response_callbacks.rb:65:in `each'
 [-] [utilities#exception_jail:428] Client: /usr/lib/ruby/gems/2.3.0/gems/ethon-0.9.0/lib/ethon/easy/response_callbacks.rb:65:in `complete'
 [-] [utilities#exception_jail:428] Client: /usr/lib/ruby/gems/2.3.0/gems/ethon-0.9.0/lib/ethon/multi/operations.rb:151:in `check'
 [-] [utilities#exception_jail:428] Client: /usr/lib/ruby/gems/2.3.0/gems/ethon-0.9.0/lib/ethon/multi/operations.rb:164:in `run'
 [-] [utilities#exception_jail:428] Client: /usr/lib/ruby/gems/2.3.0/gems/ethon-0.9.0/lib/ethon/multi/operations.rb:43:in `perform'
 [-] [utilities#exception_jail:428] Client: /usr/lib/ruby/gems/2.3.0/gems/typhoeus-1.0.1/lib/typhoeus/hydra/runnable.rb:15:in `run'
 [-] [utilities#exception_jail:428] Client: /usr/lib/ruby/gems/2.3.0/gems/typhoeus-1.0.1/lib/typhoeus/hydra/memoizable.rb:51:in `run'
 [-] [utilities#exception_jail:428] Client: /home/unshadow/Desktop/git-projects/arachni/lib/arachni/http/client.rb:610:in `block in client_run'
 [-] [utilities#exception_jail:428] Client: /home/unshadow/Desktop/git-projects/arachni/lib/arachni/utilities.rb:425:in `exception_jail'
 [-] [utilities#exception_jail:428] Client: /home/unshadow/Desktop/git-projects/arachni/lib/arachni/http/client.rb:610:in `client_run'
 [-] [utilities#exception_jail:428] Client: /home/unshadow/Desktop/git-projects/arachni/lib/arachni/http/client.rb:492:in `run_and_update_statistics'
 [-] [utilities#exception_jail:428] Client: /home/unshadow/Desktop/git-projects/arachni/lib/arachni/http/client.rb:221:in `block in run'
 [-] [utilities#exception_jail:428] Client: /home/unshadow/Desktop/git-projects/arachni/lib/arachni/utilities.rb:425:in `exception_jail'
 [-] [utilities#exception_jail:428] Client: /home/unshadow/Desktop/git-projects/arachni/lib/arachni/http/client.rb:217:in `run'
 [-] [utilities#exception_jail:428] Client: /home/unshadow/Desktop/git-projects/arachni/lib/arachni/framework/parts/audit.rb:236:in `harvest_http_responses'
 [-] [utilities#exception_jail:428] Client: /home/unshadow/Desktop/git-projects/arachni/lib/arachni/framework/parts/check.rb:59:in `run_checks'
 [-] [utilities#exception_jail:428] Client: /home/unshadow/Desktop/git-projects/arachni/lib/arachni/framework/parts/audit.rb:137:in `audit_page'
 [-] [utilities#exception_jail:428] Client: /home/unshadow/Desktop/git-projects/arachni/lib/arachni/framework/parts/audit.rb:223:in `audit_queues'
 [-] [utilities#exception_jail:428] Client: /home/unshadow/Desktop/git-projects/arachni/lib/arachni/framework/parts/audit.rb:197:in `block in audit'
 [-] [utilities#exception_jail:428] Client: /home/unshadow/Desktop/git-projects/arachni/lib/arachni/framework/parts/audit.rb:177:in `loop'
 [-] [utilities#exception_jail:428] Client: /home/unshadow/Desktop/git-projects/arachni/lib/arachni/framework/parts/audit.rb:177:in `audit'
 [-] [utilities#exception_jail:428] Client: /home/unshadow/Desktop/git-projects/arachni/lib/arachni/framework.rb:117:in `block in run'
 [-] [utilities#exception_jail:428] Client: /home/unshadow/Desktop/git-projects/arachni/lib/arachni/utilities.rb:425:in `exception_jail'
 [-] [utilities#exception_jail:428] Client: /home/unshadow/Desktop/git-projects/arachni/lib/arachni/framework.rb:117:in `run'
 [-] [utilities#exception_jail:428] Client: /home/unshadow/Desktop/git-projects/arachni/ui/cli/framework.rb:63:in `block in run'
 [-] [utilities#exception_jail:429] Client: 
 [-] [utilities#exception_jail:430] Client: Parent:
 [-] [utilities#exception_jail:431] Client: Arachni::HTTP::Client
 [-] [utilities#exception_jail:432] Client: 
 [-] [utilities#exception_jail:433] Client: Block:
 [-] [utilities#exception_jail:434] Client: #<Proc:0x00000002ef6738@/home/unshadow/Desktop/git-projects/arachni/lib/arachni/http/client.rb:610>
 [-] [utilities#exception_jail:435] Client: 
 [-] [utilities#exception_jail:436] Client: Caller:
 [-] [utilities#exception_jail:437] Client: /home/unshadow/Desktop/git-projects/arachni/lib/arachni/utilities.rb:425:in `exception_jail'
 [-] [utilities#exception_jail:437] Client: /home/unshadow/Desktop/git-projects/arachni/lib/arachni/http/client.rb:610:in `client_run'
 [-] [utilities#exception_jail:437] Client: /home/unshadow/Desktop/git-projects/arachni/lib/arachni/http/client.rb:492:in `run_and_update_statistics'
 [-] [utilities#exception_jail:437] Client: /home/unshadow/Desktop/git-projects/arachni/lib/arachni/http/client.rb:221:in `block in run'
 [-] [utilities#exception_jail:437] Client: /home/unshadow/Desktop/git-projects/arachni/lib/arachni/utilities.rb:425:in `exception_jail'
 [-] [utilities#exception_jail:437] Client: /home/unshadow/Desktop/git-projects/arachni/lib/arachni/http/client.rb:217:in `run'
 [-] [utilities#exception_jail:437] Client: /home/unshadow/Desktop/git-projects/arachni/lib/arachni/framework/parts/audit.rb:236:in `harvest_http_responses'
 [-] [utilities#exception_jail:437] Client: /home/unshadow/Desktop/git-projects/arachni/lib/arachni/framework/parts/check.rb:59:in `run_checks'
 [-] [utilities#exception_jail:437] Client: /home/unshadow/Desktop/git-projects/arachni/lib/arachni/framework/parts/audit.rb:137:in `audit_page'
 [-] [utilities#exception_jail:437] Client: /home/unshadow/Desktop/git-projects/arachni/lib/arachni/framework/parts/audit.rb:223:in `audit_queues'
 [-] [utilities#exception_jail:437] Client: /home/unshadow/Desktop/git-projects/arachni/lib/arachni/framework/parts/audit.rb:197:in `block in audit'
 [-] [utilities#exception_jail:437] Client: /home/unshadow/Desktop/git-projects/arachni/lib/arachni/framework/parts/audit.rb:177:in `loop'
 [-] [utilities#exception_jail:437] Client: /home/unshadow/Desktop/git-projects/arachni/lib/arachni/framework/parts/audit.rb:177:in `audit'
 [-] [utilities#exception_jail:437] Client: /home/unshadow/Desktop/git-projects/arachni/lib/arachni/framework.rb:117:in `block in run'
 [-] [utilities#exception_jail:437] Client: /home/unshadow/Desktop/git-projects/arachni/lib/arachni/utilities.rb:425:in `exception_jail'
 [-] [utilities#exception_jail:437] Client: /home/unshadow/Desktop/git-projects/arachni/lib/arachni/framework.rb:117:in `run'
 [-] [utilities#exception_jail:437] Client: /home/unshadow/Desktop/git-projects/arachni/ui/cli/framework.rb:63:in `block in run'
 [-] [utilities#exception_jail:438] Client: --------------------------------------------------------------------------------

```

**Comment by Zapotek** [comment]
This looks like a bug in a dependency caused by a malformed header.
Any chance I can have a look at that page to see what's going on?
You can send over that info [in private](mailto:tasos.laskos@arachni-scanner.com) if you prefer.

**Comment by bararchy** [comment]
Sent you a private mail :) thanks

**Comment by Zapotek** [comment]
Can you also send the exact config you used please?

**Comment by Zapotek** [comment]
Upstream PR: https://github.com/typhoeus/typhoeus/pull/526

**Comment by Zapotek** [comment]
Pushing nightlies with updated dependency, will let you know once they're up.

**Comment by Zapotek** [comment]
[Nightlies](http://downloads.arachni-scanner.com/nightlies/) are up.
