### ISSUE TITLE
Issue with Proxy plugin

### ISSUE THREAD

**Issue by taesiri** [Arachni/arachni#738]
Hi,

I have an issue with Proxy plugin. when I use Arachni's proxy to explore the target website, after few minutes (requests), Proxy panel showing an error message. (by accessing http://arachni.proxy/panel).

In generated error file there is line telling that `[RuntimeError] can't add a new key into hash during iteration`

here is the error message showing in proxy panel:

```
["(erb):3:in `get_binding'", "/home/mreza/arachni/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/erb.rb:863:in `eval'", "/home/mreza/arachni/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/erb.rb:863:in `result'", "/home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bbf0715dd0a5/components/plugins/proxy/template_scope.rb:105:in `erb'", "(erb):64:in `get_binding'", "/home/mreza/arachni/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/erb.rb:863:in `eval'", "/home/mreza/arachni/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/erb.rb:863:in `result'", "/home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bbf0715dd0a5/components/plugins/proxy/template_scope.rb:105:in `erb'", "/home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bbf0715dd0a5/components/plugins/proxy.rb:437:in `erb'", "/home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bbf0715dd0a5/components/plugins/proxy.rb:201:in `request_handler'", "/home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bbf0715dd0a5/lib/arachni/http/proxy_server/connection.rb:119:in `call'", "/home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bbf0715dd0a5/lib/arachni/http/proxy_server/connection.rb:119:in `handle_request'", "/home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bbf0715dd0a5/lib/arachni/http/proxy_server/connection.rb:85:in `block (3 levels) in initialize'"]
```

and this is the generted error log file :

```

2016-06-19 22:10:25 +0430 --------------------------------------------------------------------------------
ENV:
---
CPLUS_INCLUDE_PATH: "/home/mreza/arachni/arachni-2.0dev-1.0dev/bin/../system/usr/include"
XDG_SESSION_ID: '33'
GEM_HOME: "/home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems"
TERM: screen
SHELL: "/bin/bash"
IRBRC: "/home/mreza/arachni/arachni-2.0dev-1.0dev/bin/../system/usr/lib/ruby/.irbrc"
SSH_CLIENT: 89.41.41.75 49268 22
LIBRARY_PATH: "/home/mreza/arachni/arachni-2.0dev-1.0dev/bin/../system/usr/lib:/usr/lib:/usr/local/lib"
MY_RUBY_HOME: "/home/mreza/arachni/arachni-2.0dev-1.0dev/bin/../system/usr/lib/ruby"
SSH_TTY: "/dev/pts/0"
USER: mreza
LD_LIBRARY_PATH: "/home/mreza/arachni/arachni-2.0dev-1.0dev/bin/../system/usr/lib:/usr/lib:/usr/local/lib"
LS_COLORS: 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
TMUX: "/tmp/tmux-1000/default,1191,0"
MAIL: "/var/mail/mreza"
PATH: "/home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/bin:/home/mreza/arachni/arachni-2.0dev-1.0dev/bin/../system/../bin:/home/mreza/arachni/arachni-2.0dev-1.0dev/bin/../system/usr/bin:/home/mreza/arachni/arachni-2.0dev-1.0dev/bin/../system/gems/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
C_INCLUDE_PATH: "/home/mreza/arachni/arachni-2.0dev-1.0dev/bin/../system/usr/include"
PWD: "/home/mreza/arachni/arachni-2.0dev-1.0dev/bin"
ARACHNI_WEBUI_LOGDIR: "/home/mreza/arachni/arachni-2.0dev-1.0dev/bin/../system/logs/webui"
LANG: en_US.UTF-8
ARACHNI_FRAMEWORK_LOGDIR: "/home/mreza/arachni/arachni-2.0dev-1.0dev/bin/../system/logs/framework"
TMUX_PANE: "%0"
SHLVL: '2'
HOME: "/home/mreza/arachni/arachni-2.0dev-1.0dev/bin/../system/home/arachni"
LANGUAGE: en_US:en
RAILS_ENV: production
DYLD_LIBRARY_PATH: "/home/mreza/arachni/arachni-2.0dev-1.0dev/bin/../system/usr/lib:/usr/lib:/usr/local/lib"
LOGNAME: mreza
GEM_PATH: "/home/mreza/arachni/arachni-2.0dev-1.0dev/bin/../system/gems"
SSH_CONNECTION: 89.41.41.75 49268 213.233.171.167 22
LESSOPEN: "| /usr/bin/lesspipe %s"
XDG_RUNTIME_DIR: "/run/user/1000"
RUBYLIB: "/home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/gems/bundler-1.12.5/lib:/home/mreza/arachni/arachni-2.0dev-1.0dev/bin/../system/usr/lib/ruby:/home/mreza/arachni/arachni-2.0dev-1.0dev/bin/../system/usr/lib/ruby/site_ruby/2.2.0:/home/mreza/arachni/arachni-2.0dev-1.0dev/bin/../system/usr/lib/ruby/2.2.0:/home/mreza/arachni/arachni-2.0dev-1.0dev/bin/../system/usr/lib/ruby/2.2.0/x86_64-linux:/home/mreza/arachni/arachni-2.0dev-1.0dev/bin/../system/usr/lib/ruby/site_ruby/2.2.0/x86_64-linux"
RUBY_VERSION: ruby-2.2.3
LESSCLOSE: "/usr/bin/lesspipe %s %s"
RACK_ENV: development
BUNDLE_GEMFILE: "/home/mreza/arachni/arachni-2.0dev-1.0dev/system/arachni-ui-web/Gemfile"
BUNDLE_ORIG_PATH: "/home/mreza/arachni/arachni-2.0dev-1.0dev/bin/../system/../bin:/home/mreza/arachni/arachni-2.0dev-1.0dev/bin/../system/usr/bin:/home/mreza/arachni/arachni-2.0dev-1.0dev/bin/../system/gems/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin"
BUNDLE_ORIG_GEM_PATH: "/home/mreza/arachni/arachni-2.0dev-1.0dev/bin/../system/gems"
BUNDLE_BIN_PATH: "/home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/gems/bundler-1.12.5/exe/bundle"
RUBYOPT: "-rbundler/setup"
MANPATH: "/home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/gems/kramdown-1.4.1/man"
BUNDLE_ORIG_MANPATH: "/home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/gems/kramdown-1.4.1/man"
--------------------------------------------------------------------------------
OPTIONS:
---
session: {}
browser_cluster:
  local_storage: {}
  wait_for_elements: {}
  pool_size: 6
  job_timeout: 25
  worker_time_to_live: 100
  ignore_images: false
  screen_width: 1600
  screen_height: 1200
audit:
  parameter_values: true
  exclude_vector_patterns: []
  include_vector_patterns: []
  link_templates: []
  links: true
  forms: true
  cookies: true
  headers: false
  with_both_http_methods: false
  cookies_extensively: false
  jsons: true
  xmls: true
  ui_forms: true
  ui_inputs: true
input:
  values:
    "(?i-mx:name)": arachni_name
    "(?i-mx:user)": arachni_user
    "(?i-mx:usr)": arachni_user
    "(?i-mx:pass)": 5543!%arachni_secret
    "(?i-mx:txt)": arachni_text
    "(?i-mx:num)": '132'
    "(?i-mx:amount)": '100'
    "(?i-mx:mail)": arachni@email.gr
    "(?i-mx:account)": '12'
    "(?i-mx:id)": '1'
  default_values:
    name: arachni_name
    user: arachni_user
    usr: arachni_user
    pass: 5543!%arachni_secret
    txt: arachni_text
    num: '132'
    amount: '100'
    mail: arachni@email.gr
    account: '12'
    id: '1'
  without_defaults: true
  force: false
http:
  user_agent: Arachni/v2.0dev
  request_timeout: 10000
  request_redirect_limit: 5
  request_concurrency: 20
  request_queue_size: 100
  request_headers: {}
  response_max_size: 500000
  cookies: {}
  authentication_type: auto
datastore:
  token: 5f8bebb841d545a34fe852bad3e857dd
scope:
  redundant_path_patterns: {}
  dom_depth_limit: 5
  exclude_file_extensions:
  - "[]"
  exclude_path_patterns: []
  exclude_content_patterns: []
  include_path_patterns: []
  restrict_paths: []
  extend_paths: []
  url_rewrites: {}
  include_subdomains: false
  exclude_binaries: false
  https_only: false
checks:
- code_injection
- code_injection_php_input_wrapper
- code_injection_timing
- csrf
- file_inclusion
- ldap_injection
- no_sql_injection
- no_sql_injection_differential
- os_cmd_injection
- os_cmd_injection_timing
- path_traversal
- response_splitting
- rfi
- session_fixation
- source_code_disclosure
- sql_injection
- sql_injection_differential
- sql_injection_timing
- trainer
- unvalidated_redirect
- unvalidated_redirect_dom
- xpath_injection
- xss
- xss_dom
- xss_dom_script_context
- xss_event
- xss_path
- xss_script_context
- xss_tag
- xxe
- allowed_methods
- backdoors
- backup_directories
- backup_files
- captcha
- common_admin_interfaces
- common_directories
- common_files
- cookie_set_for_parent_domain
- credit_card
- cvs_svn_users
- directory_listing
- emails
- form_upload
- hsts
- htaccess_limit
- html_objects
- http_only_cookies
- http_put
- insecure_client_access_policy
- insecure_cookies
- insecure_cors_policy
- insecure_cross_domain_policy_access
- insecure_cross_domain_policy_headers
- interesting_responses
- localstart_asp
- mixed_resource
- origin_spoof_access_restriction_bypass
- password_autocomplete
- private_ip
- ssn
- unencrypted_password_forms
- webdav
- x_frame_options
- xst
platforms: []
plugins:
  autothrottle: 
  discovery: 
  healthmap: 
  proxy:
    port: '8282'
    bind_address: 127.0.0.1
    session_token: ''
    timeout: '20000'
  timing_attacks: 
  uniformity: 
no_fingerprinting: false
authorized_by: 
url: http://vulnhost/
--------------------------------------------------------------------------------
[2016-06-19 22:10:25 +0430] [RuntimeError] can't add a new key into hash during iteration
[2016-06-19 22:10:25 +0430] /home/mreza/arachni/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/set.rb:290:in `add'
[2016-06-19 22:10:25 +0430] /home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bbf0715dd0a5/components/plugins/proxy.rb:389:in `response_handler'
[2016-06-19 22:10:25 +0430] /home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bbf0715dd0a5/lib/arachni/http/proxy_server/connection.rb:162:in `call'
[2016-06-19 22:10:25 +0430] /home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bbf0715dd0a5/lib/arachni/http/proxy_server/connection.rb:162:in `handle_response'
[2016-06-19 22:10:25 +0430] /home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bbf0715dd0a5/lib/arachni/http/proxy_server/connection.rb:143:in `block in handle_request'
[2016-06-19 22:10:25 +0430] /home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/tasks/base.rb:52:in `call'
[2016-06-19 22:10:25 +0430] /home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/tasks/base.rb:52:in `call_task'
[2016-06-19 22:10:25 +0430] /home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/tasks/one_off.rb:23:in `call'
[2016-06-19 22:10:25 +0430] /home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/tasks.rb:96:in `block in call'
[2016-06-19 22:10:25 +0430] /home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/tasks.rb:96:in `each'
[2016-06-19 22:10:25 +0430] /home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/tasks.rb:96:in `call'
[2016-06-19 22:10:25 +0430] /home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:309:in `block in run'
[2016-06-19 22:10:25 +0430] /home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:307:in `loop'
[2016-06-19 22:10:25 +0430] /home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:307:in `run'
[2016-06-19 22:10:25 +0430] /home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:349:in `block in run_in_thread'
[2016-06-19 22:11:36 +0430] [RuntimeError] can't add a new key into hash during iteration
[2016-06-19 22:11:36 +0430] /home/mreza/arachni/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/set.rb:290:in `add'
[2016-06-19 22:11:36 +0430] /home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bbf0715dd0a5/components/plugins/proxy.rb:389:in `response_handler'
[2016-06-19 22:11:36 +0430] /home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bbf0715dd0a5/lib/arachni/http/proxy_server/connection.rb:162:in `call'
[2016-06-19 22:11:36 +0430] /home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bbf0715dd0a5/lib/arachni/http/proxy_server/connection.rb:162:in `handle_response'
[2016-06-19 22:11:36 +0430] /home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bbf0715dd0a5/lib/arachni/http/proxy_server/connection.rb:143:in `block in handle_request'
[2016-06-19 22:11:36 +0430] /home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/tasks/base.rb:52:in `call'
[2016-06-19 22:11:36 +0430] /home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/tasks/base.rb:52:in `call_task'
[2016-06-19 22:11:36 +0430] /home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/tasks/one_off.rb:23:in `call'
[2016-06-19 22:11:36 +0430] /home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/tasks.rb:96:in `block in call'
[2016-06-19 22:11:36 +0430] /home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/tasks.rb:96:in `each'
[2016-06-19 22:11:36 +0430] /home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/tasks.rb:96:in `call'
[2016-06-19 22:11:36 +0430] /home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:309:in `block in run'
[2016-06-19 22:11:36 +0430] /home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:307:in `loop'
[2016-06-19 22:11:36 +0430] /home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:307:in `run'
[2016-06-19 22:11:36 +0430] /home/mreza/arachni/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:349:in `block in run_in_thread'


```

How can i solve this issue?

**Comment by Zapotek** [comment]
Fix is in the [nightlies](http://downloads.arachni-scanner.com/nightlies/).

**Comment by taesiri** [comment]
It seems like proxy still have some issues. with latest builds, I'm getting the following error in some cases:

```
["(erb):62:in `concat'", "(erb):62:in `block (3 levels) in get_binding'", "(erb):60:in `each'", "(erb):60:in `block (2 levels) in get_binding'", "(erb):56:in `each'", "(erb):56:in `block in get_binding'", "(erb):2:in `each'", "(erb):2:in `with_index'", "(erb):2:in `get_binding'", "/home/mreza/new_aug_arachni/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/erb.rb:863:in `eval'", "/home/mreza/new_aug_arachni/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/erb.rb:863:in `result'", "/home/mreza/new_aug_arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-8ba4ea8bb4e2/components/plugins/proxy/template_scope.rb:105:in `erb'", "/home/mreza/new_aug_arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-8ba4ea8bb4e2/components/plugins/proxy/template_scope.rb:110:in `render'", "(erb):16:in `get_binding'", "/home/mreza/new_aug_arachni/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/erb.rb:863:in `eval'", "/home/mreza/new_aug_arachni/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/erb.rb:863:in `result'", "/home/mreza/new_aug_arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-8ba4ea8bb4e2/components/plugins/proxy/template_scope.rb:105:in `erb'", "/home/mreza/new_aug_arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-8ba4ea8bb4e2/components/plugins/proxy/template_scope.rb:110:in `render'", "(erb):8:in `get_binding'", "/home/mreza/new_aug_arachni/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/erb.rb:863:in `eval'", "/home/mreza/new_aug_arachni/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/erb.rb:863:in `result'", "/home/mreza/new_aug_arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-8ba4ea8bb4e2/components/plugins/proxy/template_scope.rb:105:in `erb'", "(erb):64:in `get_binding'", "/home/mreza/new_aug_arachni/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/erb.rb:863:in `eval'", "/home/mreza/new_aug_arachni/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/erb.rb:863:in `result'", "/home/mreza/new_aug_arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-8ba4ea8bb4e2/components/plugins/proxy/template_scope.rb:105:in `erb'", "/home/mreza/new_aug_arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-8ba4ea8bb4e2/components/plugins/proxy.rb:449:in `erb'", "/home/mreza/new_aug_arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-8ba4ea8bb4e2/components/plugins/proxy.rb:205:in `request_handler'", "/home/mreza/new_aug_arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-8ba4ea8bb4e2/lib/arachni/http/proxy_server/connection.rb:119:in `call'", "/home/mreza/new_aug_arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-8ba4ea8bb4e2/lib/arachni/http/proxy_server/connection.rb:119:in `handle_request'", "/home/mreza/new_aug_arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-8ba4ea8bb4e2/lib/arachni/http/proxy_server/connection.rb:85:in `block (3 levels) in initialize'"]
```

**Comment by Zapotek** [comment]
Reproduction steps?

**Comment by taesiri** [comment]
When I login into a website. there is only one website that i have this issue with.

**Comment by Zapotek** [comment]
An actual test case would help, but if you can't give out more details the extra error logging I added may help pinpoint the issue.
Pushing nightlies now.

**Comment by taesiri** [comment]
I can send more details in private. what is your email address?

**Comment by Zapotek** [comment]
tasos.laskos@arachni-scanner.com

**Comment by Zapotek** [comment]
Fixed and pushing nightlies.
