### ISSUE TITLE
Scan fails to complete

### ISSUE THREAD

**Issue by k0z1can** [Arachni/arachni#754]
Hello Tasos,

When running a scan it fails to fully complete. The time value for running does not change and the scan has to be aborted. Below is an snipit of the error encountered:

```
Connection closed [Connection refused - connect(2) for 127.0.0.1:62013]
--------------------------------------------------------------------------------
/root/arachni-1.4-0.5.10/system/arachni-ui-web/app/models/scan.rb:312:in `block in abort'
/root/arachni-1.4-0.5.10/system/gems/gems/arachni-rpc-0.2.1.3/lib/arachni/rpc/proxy.rb:58:in `call'
/root/arachni-1.4-0.5.10/system/gems/gems/arachni-rpc-0.2.1.3/lib/arachni/rpc/proxy.rb:58:in `block (2 levels) in translate'
/root/arachni-1.4-0.5.10/system/gems/gems/arachni-rpc-0.2.1.3/lib/arachni/rpc/client/handler.rb:100:in `call'
/root/arachni-1.4-0.5.10/system/gems/gems/arachni-rpc-0.2.1.3/lib/arachni/rpc/client/handler.rb:100:in `on_close'
/root/arachni-1.4-0.5.10/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection.rb:179:in `close'
/root/arachni-1.4-0.5.10/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection.rb:246:in `rescue in _connect'
/root/arachni-1.4-0.5.10/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection.rb:230:in `_connect'
/root/arachni-1.4-0.5.10/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection/tls.rb:82:in `block in _connect'
/root/arachni-1.4-0.5.10/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection/error.rb:26:in `call'
/root/arachni-1.4-0.5.10/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection/error.rb:26:in `translate'
/root/arachni-1.4-0.5.10/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection/tls.rb:81:in `_connect'
/root/arachni-1.4-0.5.10/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection.rb:284:in `_write'
/root/arachni-1.4-0.5.10/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection/tls.rb:104:in `_write'
/root/arachni-1.4-0.5.10/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:574:in `each'
/root/arachni-1.4-0.5.10/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:574:in `block in process_connections'
/root/arachni-1.4-0.5.10/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:574:in `each'
/root/arachni-1.4-0.5.10/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:574:in `process_connections'
/root/arachni-1.4-0.5.10/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:316:in `block in run'
/root/arachni-1.4-0.5.10/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:307:in `loop'
/root/arachni-1.4-0.5.10/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:307:in `run'
/root/arachni-1.4-0.5.10/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:349:in `block in run_in_thread'
********************************************************************************
```

Is there something I overlooked?

Thank you for your assistance,
Andrew

**Comment by Zapotek** [comment]
It looks like communication with the scanner is lost.
Can you try using the CLI with the same configuration and see if the scan completes?

**Comment by Zapotek** [comment]
Any updates on this?

**Comment by k0z1can** [comment]
Hello Tasos,

Worked like a top from the command line. Rebooted since and the webui seems to be fine now. 


Thank you,
K0z1Can
