### ISSUE TITLE
Could not start browser process (specifics seem different to all previous browser issues)

### ISSUE THREAD

**Issue by jyting** [Arachni/arachni#766]
Hi,

Tried to get Arachni working today on a local web app, and ran into issues, as it couldn't launch the browser. This is from the web-ui, but I get exactly the same error using the cli version.

I get the following trace:

> [2016-08-18 17:54:24 +1000] [Arachni::Browser::Error::Spawn] Could not start the browser process.
[2016-08-18 17:54:24 +1000] /home/justinting/programs/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:1268:in `spawn_browser'
[2016-08-18 17:54:24 +1000] /home/justinting/programs/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:1164:in `selenium'
[2016-08-18 17:54:24 +1000] /home/justinting/programs/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:197:in `initialize'
[2016-08-18 17:54:24 +1000] /home/justinting/programs/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster/worker.rb:52:in `initialize'
[2016-08-18 17:54:24 +1000] /home/justinting/programs/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster.rb:477:in `new'
[2016-08-18 17:54:24 +1000] /home/justinting/programs/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster.rb:477:in `block in initialize_workers'
[2016-08-18 17:54:24 +1000] /home/justinting/programs/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster.rb:476:in `times'
[2016-08-18 17:54:24 +1000] /home/justinting/programs/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster.rb:476:in `initialize_workers'
[2016-08-18 17:54:24 +1000] /home/justinting/programs/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster.rb:119:in `initialize'
[2016-08-18 17:54:24 +1000] /home/justinting/programs/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework/parts/browser.rb:33:in `new'
[2016-08-18 17:54:24 +1000] /home/justinting/programs/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework/parts/browser.rb:33:in `block in browser_cluster'
[2016-08-18 17:54:24 +1000] /home/justinting/programs/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
[2016-08-18 17:54:24 +1000] /home/justinting/programs/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework/parts/browser.rb:28:in `browser_cluster'
[2016-08-18 17:54:24 +1000] /home/justinting/programs/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework/parts/audit.rb:173:in `audit'
[2016-08-18 17:54:24 +1000] /home/justinting/programs/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework.rb:117:in `block in run'
[2016-08-18 17:54:24 +1000] /home/justinting/programs/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `call'
[2016-08-18 17:54:24 +1000] /home/justinting/programs/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `exception_jail'
[2016-08-18 17:54:24 +1000] /home/justinting/programs/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework.rb:117:in `run'
[2016-08-18 17:54:24 +1000] /home/justinting/programs/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/rpc/server/framework.rb:156:in `block in run'
[2016-08-18 17:54:24 +1000] 
[2016-08-18 17:54:24 +1000] Parent:
[2016-08-18 17:54:24 +1000] Arachni::RPC::Server::Framework
[2016-08-18 17:54:24 +1000] 
[2016-08-18 17:54:24 +1000] Block:
[2016-08-18 17:54:24 +1000] #<Proc:0x00000004a51848@/home/justinting/programs/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework.rb:117>
[2016-08-18 17:54:24 +1000] 
[2016-08-18 17:54:24 +1000] Caller:
[2016-08-18 17:54:24 +1000] /home/justinting/programs/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `exception_jail'
[2016-08-18 17:54:24 +1000] /home/justinting/programs/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework.rb:117:in `run'
[2016-08-18 17:54:24 +1000] /home/justinting/programs/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/rpc/server/framework.rb:156:in `block in run'

Any help would be greatly appreciated.

**Comment by Zapotek** [comment]
Can you retry with the [nightlies](http://downloads.arachni-scanner.com/nightlies/) please?

**Comment by Zapotek** [comment]
Any update on this? Did you try the nightly?

**Comment by jyting** [comment]
Hi Zapotek,

Just got around to testing it with the latest nightly today - the issue doesn't come up with this issue, thanks for pointing me in the right direction!

**Comment by Zapotek** [comment]
No problem.
