### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by dizainorg** [Arachni/arachni#773]
Hi!

I have tried to run arachni-1.4-0.5.10 (and arachni-2.0dev-1.0dev) on OS X (El Capitan 10.11.6 (15G1004)) and noticed the following error when running a scan:

```
--------------------------------------------------------------------------------
[2016-09-15 17:57:08 +0300] [Errno::EMFILE] Too many open files @ rb_sysopen - /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-15e02381d75c/lib/arachni/http/proxy_server/ssl-interceptor-cakey.pem
[2016-09-15 17:57:08 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-15e02381d75c/lib/arachni/http/proxy_server/ssl_interceptor.rb:46:in `read'
[2016-09-15 17:57:08 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-15e02381d75c/lib/arachni/http/proxy_server/ssl_interceptor.rb:46:in `start_tls'
[2016-09-15 17:57:08 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-15e02381d75c/lib/arachni/http/proxy_server/ssl_interceptor.rb:30:in `on_connect'
[2016-09-15 17:57:08 +0300] [Errno::EMFILE] Too many open files @ rb_sysopen - /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-15e02381d75c/lib/arachni/http/proxy_server/ssl-interceptor-cacert.pem
[2016-09-15 17:57:08 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-15e02381d75c/lib/arachni/http/proxy_server/ssl_interceptor.rb:45:in `read'
[2016-09-15 17:57:08 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-15e02381d75c/lib/arachni/http/proxy_server/ssl_interceptor.rb:45:in `start_tls'
[2016-09-15 17:57:08 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection.rb:218:in `configure'
[2016-09-15 17:57:08 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:268:in `block in listen'
[2016-09-15 17:57:08 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection/error.rb:26:in `call'
[2016-09-15 17:57:08 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection/error.rb:26:in `translate'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:263:in `listen'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-15e02381d75c/lib/arachni/http/proxy_server/connection.rb:274:in `start_interceptor'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-15e02381d75c/lib/arachni/http/proxy_server/connection.rb:118:in `handle_connect'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-15e02381d75c/lib/arachni/http/proxy_server/connection.rb:61:in `block in initialize'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-15e02381d75c/lib/arachni/http/proxy_server/connection.rb:264:in `call'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-15e02381d75c/lib/arachni/http/proxy_server/connection.rb:264:in `<<'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-15e02381d75c/lib/arachni/http/proxy_server/connection.rb:264:in `on_read'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection.rb:261:in `block in _read'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection/error.rb:26:in `call'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection/error.rb:26:in `translate'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection.rb:260:in `_read'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:574:in `each'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:574:in `block in process_connections'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:574:in `each'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:574:in `process_connections'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:316:in `block in run'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:307:in `loop'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:307:in `run'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:349:in `block in run_in_thread'
[2016-09-15 17:57:09 +0300] [Errno::EMFILE] Too many open files - accept(2)
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection.rb:333:in `accept_nonblock'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection.rb:333:in `socket_accept'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection.rb:192:in `accept'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection.rb:258:in `_read'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:574:in `each'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:574:in `block in process_connections'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:574:in `each'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:574:in `process_connections'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:316:in `block in run'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:307:in `loop'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:307:in `run'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:349:in `block in run_in_thread'
[2016-09-15 17:57:09 +0300] [Errno::EMFILE] Too many open files - accept(2)
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection/tls.rb:146:in `accept_nonblock'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection/tls.rb:146:in `block in socket_accept'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection/error.rb:26:in `call'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection/error.rb:26:in `translate'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection/tls.rb:145:in `socket_accept'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection.rb:192:in `accept'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection.rb:258:in `_read'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection/tls.rb:115:in `_read'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:574:in `each'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:574:in `block in process_connections'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:574:in `each'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:574:in `process_connections'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:316:in `block in run'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:307:in `loop'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:307:in `run'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:349:in `block in run_in_thread'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-15e02381d75c/lib/arachni/http/proxy_server/ssl_interceptor.rb:30:in `on_connect'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection.rb:218:in `configure'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:268:in `block in listen'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection/error.rb:26:in `call'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection/error.rb:26:in `translate'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:263:in `listen'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-15e02381d75c/lib/arachni/http/proxy_server/connection.rb:274:in `start_interceptor'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-15e02381d75c/lib/arachni/http/proxy_server/connection.rb:118:in `handle_connect'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-15e02381d75c/lib/arachni/http/proxy_server/connection.rb:61:in `block in initialize'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-15e02381d75c/lib/arachni/http/proxy_server/connection.rb:264:in `call'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-15e02381d75c/lib/arachni/http/proxy_server/connection.rb:264:in `<<'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-15e02381d75c/lib/arachni/http/proxy_server/connection.rb:264:in `on_read'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection.rb:261:in `block in _read'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection/error.rb:26:in `call'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection/error.rb:26:in `translate'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection.rb:260:in `_read'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:574:in `each'
[2016-09-15 17:57:09 +0300] /Users/mac/Downloads/arachni-2.0dev-1.0dev/system/gems/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:574:in `block in process_connections'
...
```

Some info

```
iMac-Mac:~ mac$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 709
virtual memory          (kbytes, -v) unlimited
```

**Comment by Zapotek** [comment]
The open files limit on OSX is on the low side (1024), if you increase it the issue will go away.
You don't need to be niggardly either, even 10 times the existing limit won't usually have any negative consequences.
