### ISSUE TITLE
[Arachni::Browser::Error::Spawn] Could not start the browser process.

### ISSUE THREAD

**Issue by TommyJ1994** [Arachni/arachni#783]
- Tried a scan of a localhost site. 
- Tested with admin and regular user. 
- Running on Linux Mint 18, i7 and 16GB of RAM.
- Tried limiting browser cluster to 1.

```
2016-10-10 21:29:23 +0100 --------------------------------------------------------------------------------
ENV:
---
CPLUS_INCLUDE_PATH: "/home/tjackman/Desktop/arachni-1.4-0.5.10/bin/../system/usr/include"
XDG_VTNR: '8'
MANPATH: "/home/tjackman/Desktop/arachni-1.4-0.5.10/system/gems/gems/kramdown-1.4.1/man:/home/tjackman/.nvm/v0.10.46/share/man:/usr/local/man:/usr/local/share/man:/usr/share/man:/usr/lib/jvm/java-8-oracle/man:/home/tjackman/.rvm/man"
XDG_SESSION_ID: c1
SSH_AGENT_PID: '2115'
TERMINATOR_UUID: urn:uuid:e00dd7b0-9d22-407e-9901-d94cb077aa2c
IBUS_DISABLE_SNOOPER: '1'
QT_STYLE_OVERRIDE: gtk
GIO_LAUNCHED_DESKTOP_FILE_PID: '11829'
GEM_HOME: "/home/tjackman/Desktop/arachni-1.4-0.5.10/system/gems"
NVM_CD_FLAGS: ''
MM_NOTTTY: '1'
TERM: xterm
SHELL: "/usr/bin/fish"
XDG_SESSION_COOKIE: 4603ef0b0eb640e2836974a04d12e5ab-1476086023.189038-1166214192
OMF_CONFIG: "/home/tjackman/.config/omf"
IRBRC: "/home/tjackman/Desktop/arachni-1.4-0.5.10/bin/../system/usr/lib/ruby/.irbrc"
DERBY_HOME: "/usr/lib/jvm/java-8-oracle/db"
LIBRARY_PATH: "/home/tjackman/Desktop/arachni-1.4-0.5.10/bin/../system/usr/lib:/usr/lib:/usr/local/lib"
QT_LINUX_ACCESSIBILITY_ALWAYS_ON: '1'
NVM_PATH: "/home/tjackman/.nvm/v0.10.46/lib/node"
GJS_DEBUG_OUTPUT: stderr
WINDOWID: '115343364'
MY_RUBY_HOME: "/home/tjackman/Desktop/arachni-1.4-0.5.10/bin/../system/usr/lib/ruby"
GJS_DEBUG_TOPICS: JS ERROR;JS LOG
GTK_MODULES: gail:atk-bridge
USER: tjackman
NVM_DIR: "/home/tjackman/.nvm"
QT_ACCESSIBILITY: '1'
LD_LIBRARY_PATH: "/home/tjackman/Desktop/arachni-1.4-0.5.10/bin/../system/usr/lib:/usr/lib:/usr/local/lib"
SSH_AUTH_SOCK: "/run/user/1000/keyring/ssh"
USERNAME: tjackman
SESSION_MANAGER: local/redhat:@/tmp/.ICE-unix/1883,unix/redhat:/tmp/.ICE-unix/1883
DEFAULTS_PATH: "/usr/share/gconf/cinnamon.default.path"
GIO_LAUNCHED_DESKTOP_FILE: "/usr/share/applications/Thunar-folder-handler.desktop"
XDG_CONFIG_DIRS: "/etc/xdg/xdg-cinnamon:/etc/xdg"
PATH: "/home/tjackman/Desktop/arachni-1.4-0.5.10/system/gems/bin:/home/tjackman/Desktop/arachni-1.4-0.5.10/bin/../system/../bin:/home/tjackman/Desktop/arachni-1.4-0.5.10/bin/../system/usr/bin:/home/tjackman/Desktop/arachni-1.4-0.5.10/bin/../system/gems/bin:/home/tjackman/.nvm/v0.10.46/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/tjackman/.rvm/bin"
DESKTOP_SESSION: cinnamon
C_INCLUDE_PATH: "/home/tjackman/Desktop/arachni-1.4-0.5.10/bin/../system/usr/include"
NVM_NODEJS_ORG_MIRROR: https://nodejs.org/dist
GDM_XSERVER_LOCATION: local
PWD: "/home/tjackman/Desktop/arachni-1.4-0.5.10/bin"
JAVA_HOME: "/usr/lib/jvm/java-8-oracle"
ARACHNI_WEBUI_LOGDIR: "/home/tjackman/Desktop/arachni-1.4-0.5.10/bin/../system/logs/webui"
LANG: en_IE.UTF-8
MANDATORY_PATH: "/usr/share/gconf/cinnamon.mandatory.path"
ARACHNI_FRAMEWORK_LOGDIR: "/home/tjackman/Desktop/arachni-1.4-0.5.10/bin/../system/logs/framework"
MDM_XSERVER_LOCATION: local
GDMSESSION: cinnamon
CINNAMON_VERSION: 3.0.7
XDG_SEAT: seat0
SHLVL: '1'
HOME: "/home/tjackman/Desktop/arachni-1.4-0.5.10/bin/../system/home/arachni"
RAILS_ENV: production
OMF_PATH: "/home/tjackman/.local/share/omf"
GNOME_DESKTOP_SESSION_ID: this-is-deprecated
DYLD_LIBRARY_PATH: "/home/tjackman/Desktop/arachni-1.4-0.5.10/bin/../system/usr/lib:/usr/lib:/usr/local/lib"
GTK_OVERLAY_SCROLLING: '1'
CHROME_WRAPPER: "/opt/google/chrome/google-chrome"
XDG_SESSION_DESKTOP: cinnamon
LOGNAME: tjackman
GEM_PATH: "/home/tjackman/Desktop/arachni-1.4-0.5.10/bin/../system/gems"
XDG_DATA_DIRS: "/usr/share/cinnamon:/usr/share/gnome:/usr/local/share/:/usr/share/:/usr/share/mdm/"
J2SDKDIR: "/usr/lib/jvm/java-8-oracle"
DBUS_SESSION_BUS_ADDRESS: unix:abstract=/tmp/dbus-hoIlANIBIM,guid=3555f6e933cc9f2c5495cc9357fb4907
NVM_BIN: "/home/tjackman/.nvm/v0.10.46/bin"
NVM_IOJS_ORG_MIRROR: https://iojs.org/dist
MDMSESSION: cinnamon
CHROME_VERSION_EXTRA: stable
WINDOWPATH: '8'
XDG_RUNTIME_DIR: "/run/user/1000"
DISPLAY: ":0.0"
MDM_LANG: en_IE.UTF-8
XDG_CURRENT_DESKTOP: X-Cinnamon
J2REDIR: "/usr/lib/jvm/java-8-oracle/jre"
RUBYLIB: "/home/tjackman/Desktop/arachni-1.4-0.5.10/system/gems/gems/bundler-1.11.2/lib:/home/tjackman/Desktop/arachni-1.4-0.5.10/bin/../system/usr/lib/ruby:/home/tjackman/Desktop/arachni-1.4-0.5.10/bin/../system/usr/lib/ruby/site_ruby/2.2.0:/home/tjackman/Desktop/arachni-1.4-0.5.10/bin/../system/usr/lib/ruby/2.2.0:/home/tjackman/Desktop/arachni-1.4-0.5.10/bin/../system/usr/lib/ruby/2.2.0/x86_64-linux:/home/tjackman/Desktop/arachni-1.4-0.5.10/bin/../system/usr/lib/ruby/site_ruby/2.2.0/x86_64-linux"
RUBY_VERSION: ruby-2.2.3
XAUTHORITY: "/home/tjackman/.Xauthority"
COLORTERM: gnome-terminal
RACK_ENV: development
BUNDLE_GEMFILE: "/home/tjackman/Desktop/arachni-1.4-0.5.10/system/arachni-ui-web/Gemfile"
_ORIGINAL_GEM_PATH: "/home/tjackman/Desktop/arachni-1.4-0.5.10/bin/../system/gems"
BUNDLE_BIN_PATH: "/home/tjackman/Desktop/arachni-1.4-0.5.10/system/gems/gems/bundler-1.11.2/exe/bundle"
RUBYOPT: "-rbundler/setup"
BUNDLE_ORIG_MANPATH: "/home/tjackman/Desktop/arachni-1.4-0.5.10/system/gems/gems/kramdown-1.4.1/man:/home/tjackman/.nvm/v0.10.46/share/man:/usr/local/man:/usr/local/share/man:/usr/share/man:/usr/lib/jvm/java-8-oracle/man:/home/tjackman/.rvm/man"
--------------------------------------------------------------------------------
OPTIONS:
---
audit:
  parameter_values: true
  exclude_vector_patterns: []
  include_vector_patterns: []
  link_templates: []
  links: true
  forms: true
  cookies: true
  jsons: true
  xmls: true
  ui_forms: true
  ui_inputs: true
  headers: false
  with_both_http_methods: false
  cookies_extensively: false
session: {}
scope:
  redundant_path_patterns: {}
  dom_depth_limit: 5
  exclude_file_extensions: []
  exclude_path_patterns: []
  exclude_content_patterns: []
  include_path_patterns: []
  restrict_paths: []
  extend_paths: []
  url_rewrites: {}
  include_subdomains: false
  exclude_binaries: false
  https_only: false
datastore:
  token: 9896f40e8bc02da56bb859b3d0f8deb9
http:
  user_agent: Arachni/v1.4
  request_timeout: 10000
  request_redirect_limit: 5
  request_concurrency: 20
  request_queue_size: 100
  request_headers: {}
  response_max_size: 500000
  cookies: {}
input:
  values:
    "(?i-mx:name)": arachni_name
    "(?i-mx:user)": arachni_user
    "(?i-mx:usr)": arachni_user
    "(?i-mx:pass)": 5543!%arachni_secret
    "(?i-mx:txt)": arachni_text
    "(?i-mx:num)": '132'
    "(?i-mx:amount)": '100'
    "(?i-mx:mail)": arachni@email.gr
    "(?i-mx:account)": '12'
    "(?i-mx:id)": '1'
  default_values:
    name: arachni_name
    user: arachni_user
    usr: arachni_user
    pass: 5543!%arachni_secret
    txt: arachni_text
    num: '132'
    amount: '100'
    mail: arachni@email.gr
    account: '12'
    id: '1'
  without_defaults: true
  force: false
browser_cluster:
  local_storage: {}
  wait_for_elements: {}
  pool_size: 1
  job_timeout: 25
  worker_time_to_live: 100
  ignore_images: false
  screen_width: 1600
  screen_height: 1200
checks:
- code_injection
- code_injection_php_input_wrapper
- code_injection_timing
- csrf
- file_inclusion
- ldap_injection
- no_sql_injection
- no_sql_injection_differential
- os_cmd_injection
- os_cmd_injection_timing
- path_traversal
- response_splitting
- rfi
- session_fixation
- source_code_disclosure
- sql_injection
- sql_injection_differential
- sql_injection_timing
- trainer
- unvalidated_redirect
- unvalidated_redirect_dom
- xpath_injection
- xss
- xss_dom
- xss_dom_script_context
- xss_event
- xss_path
- xss_script_context
- xss_tag
- xxe
- allowed_methods
- backdoors
- backup_directories
- backup_files
- captcha
- common_admin_interfaces
- common_directories
- common_files
- cookie_set_for_parent_domain
- credit_card
- cvs_svn_users
- directory_listing
- emails
- form_upload
- hsts
- htaccess_limit
- html_objects
- http_only_cookies
- http_put
- insecure_client_access_policy
- insecure_cookies
- insecure_cors_policy
- insecure_cross_domain_policy_access
- insecure_cross_domain_policy_headers
- interesting_responses
- localstart_asp
- mixed_resource
- origin_spoof_access_restriction_bypass
- password_autocomplete
- private_ip
- ssn
- unencrypted_password_forms
- webdav
- x_frame_options
- xst
platforms: []
plugins:
  autothrottle: 
  discovery: 
  healthmap: 
  timing_attacks: 
  uniformity: 
no_fingerprinting: false
authorized_by: 
url: https://testing.x.me/
--------------------------------------------------------------------------------
[2016-10-10 21:29:23 +0100] Could not spawn browser process.
[2016-10-10 21:29:23 +0100] 14677: Started
PID: 14680
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working
14677: Working

[2016-10-10 21:29:23 +0100] [Arachni::Browser::Error::Spawn] Could not start the browser process.
[2016-10-10 21:29:23 +0100] /home/tjackman/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:1268:in `spawn_browser'
[2016-10-10 21:29:23 +0100] /home/tjackman/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:1164:in `selenium'
[2016-10-10 21:29:23 +0100] /home/tjackman/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:197:in `initialize'
[2016-10-10 21:29:23 +0100] /home/tjackman/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster/worker.rb:52:in `initialize'
[2016-10-10 21:29:23 +0100] /home/tjackman/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster.rb:477:in `new'
[2016-10-10 21:29:23 +0100] /home/tjackman/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster.rb:477:in `block in initialize_workers'
[2016-10-10 21:29:23 +0100] /home/tjackman/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster.rb:476:in `times'
[2016-10-10 21:29:23 +0100] /home/tjackman/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster.rb:476:in `initialize_workers'
[2016-10-10 21:29:23 +0100] /home/tjackman/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster.rb:119:in `initialize'
[2016-10-10 21:29:23 +0100] /home/tjackman/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework/parts/browser.rb:33:in `new'
[2016-10-10 21:29:23 +0100] /home/tjackman/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework/parts/browser.rb:33:in `block in browser_cluster'
[2016-10-10 21:29:23 +0100] /home/tjackman/Desktop/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
[2016-10-10 21:29:23 +0100] /home/tjackman/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework/parts/browser.rb:28:in `browser_cluster'
[2016-10-10 21:29:23 +0100] /home/tjackman/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework/parts/audit.rb:173:in `audit'
[2016-10-10 21:29:23 +0100] /home/tjackman/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework.rb:117:in `block in run'
[2016-10-10 21:29:23 +0100] /home/tjackman/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `call'
[2016-10-10 21:29:23 +0100] /home/tjackman/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `exception_jail'
[2016-10-10 21:29:23 +0100] /home/tjackman/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework.rb:117:in `run'
[2016-10-10 21:29:23 +0100] /home/tjackman/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/rpc/server/framework.rb:156:in `block in run'
[2016-10-10 21:29:23 +0100] 
[2016-10-10 21:29:23 +0100] Parent:
[2016-10-10 21:29:23 +0100] Arachni::RPC::Server::Framework
[2016-10-10 21:29:23 +0100] 
[2016-10-10 21:29:23 +0100] Block:
[2016-10-10 21:29:23 +0100] #<Proc:0x00000003b1db10@/home/tjackman/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework.rb:117>
[2016-10-10 21:29:23 +0100] 
[2016-10-10 21:29:23 +0100] Caller:
[2016-10-10 21:29:23 +0100] /home/tjackman/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `exception_jail'
[2016-10-10 21:29:23 +0100] /home/tjackman/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework.rb:117:in `run'
[2016-10-10 21:29:23 +0100] /home/tjackman/Desktop/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/rpc/server/framework.rb:156:in `block in run'
[2016-10-10 21:29:23 +0100] --------------------------------------------------------------------------------

```

**Comment by Zapotek** [comment]
I believe this issue has been resolved in the [nightlies](http://downloads.arachni-scanner.com/nightlies/), can you please give them a try?

**Comment by TommyJ1994** [comment]
@Zapotek Thanks, downloading now. Will report back.

**Comment by TommyJ1994** [comment]
@Zapotek Works a treat, thanks!

**Comment by hahwul** [comment]
@Zapotek 
Hi 
I have same problem on Arachni REST API(version 1.5.1-0.5.12 / browser cluster = 1)
```json
"message" : [
  "initialising browser cluster."
]
```
Is there a way to fix it without upgrading?
plz reply me
 
thank you :)
