### ISSUE TITLE
Login Script wont start

### ISSUE THREAD

**Issue by moku23** [Arachni/arachni#793]
Here my problem in log

> 2016-11-04 12:16:51 -0400] Session: [utilities#exception_jail:428][Selenium::WebDriver::Error::WebDriverError] unable to obtain stable firefox connection in 60 seconds (127.0.0.1:7055)
[2016-11-04 12:16:51 -0400] Session: [utilities#exception_jail:428]/home/ubuntu/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/components/plugins/login_script.rb:29:in `eval'
[2016-11-04 12:16:51 -0400] Session: [utilities#exception_jail:428]/home/ubuntu/arachni-1.4-0.5.10/system/gems/gems/selenium-webdriver-2.51.0/lib/selenium/webdriver/firefox/launcher.rb:55:in `block in launch'
[2016-11-04 12:16:51 -0400] Session: [utilities#exception_jail:428]/home/ubuntu/arachni-1.4-0.5.10/system/gems/gems/selenium-webdriver-2.51.0/lib/selenium/webdriver/common/socket_lock.rb:43:in `locked'
[2016-11-04 12:16:51 -0400] Session: [utilities#exception_jail:428]/home/ubuntu/arachni-1.4-0.5.10/system/gems/gems/selenium-webdriver-2.51.0/lib/selenium/webdriver/firefox/launcher.rb:51:in `launch'
[2016-11-04 12:16:51 -0400] Session: [utilities#exception_jail:428]/home/ubuntu/arachni-1.4-0.5.10/system/gems/gems/selenium-webdriver-2.51.0/lib/selenium/webdriver/firefox/bridge.rb:43:in `initialize'
[2016-11-04 12:16:51 -0400] Session: [utilities#exception_jail:428]/home/ubuntu/arachni-1.4-0.5.10/system/gems/gems/selenium-webdriver-2.51.0/lib/selenium/webdriver/common/driver.rb:53:in `new'

**Comment by Zapotek** [comment]
You can't use a different browser to login, you need to use the bundled browser/watir instance made available to the login script via the `browser` variable.
