### ISSUE TITLE
scan Failed to open TCP connection to 127.0.0.1:55778 

### ISSUE THREAD

**Issue by sundod** [Arachni/arachni#799]
```
[2016-11-18 16:01:45 +0800] [Errno::ECONNREFUSED] Failed to open TCP connection to 127.0.0.1:55778 (Connection refused - connect(2) for "127.0.0.1" port 55778)
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect'
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/2.3.0/net/http.rb:879:in `block in connect'
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/2.3.0/net/http.rb:878:in `connect'
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/2.3.0/net/http.rb:852:in `start'
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/2.3.0/net/http.rb:1398:in `request'
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/default.rb:103:in `response_for'
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/default.rb:57:in `request'
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/bridge.rb:653:in `raw_execute'
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/bridge.rb:124:in `create_session'
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/bridge.rb:88:in `initialize'
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/common/driver.rb:57:in `new'
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/common/driver.rb:57:in `for'
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver.rb:82:in `for'
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/gems/2.3.0/bundler/gems/arachni-73f4189eee17/lib/arachni/browser.rb:1088:in `selenium'
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/gems/2.3.0/bundler/gems/arachni-73f4189eee17/lib/arachni/browser.rb:1316:in `start_webdriver'
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/gems/2.3.0/bundler/gems/arachni-73f4189eee17/lib/arachni/browser.rb:187:in `initialize'
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/gems/2.3.0/bundler/gems/arachni-73f4189eee17/lib/arachni/browser_cluster/worker.rb:51:in `initialize'
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/gems/2.3.0/bundler/gems/arachni-73f4189eee17/lib/arachni/browser_cluster.rb:495:in `new'
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/gems/2.3.0/bundler/gems/arachni-73f4189eee17/lib/arachni/browser_cluster.rb:495:in `block in initialize_workers'
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/gems/2.3.0/bundler/gems/arachni-73f4189eee17/lib/arachni/browser_cluster.rb:494:in `times'
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/gems/2.3.0/bundler/gems/arachni-73f4189eee17/lib/arachni/browser_cluster.rb:494:in `initialize_workers'
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/gems/2.3.0/bundler/gems/arachni-73f4189eee17/lib/arachni/browser_cluster.rb:112:in `initialize'
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/gems/2.3.0/bundler/gems/arachni-73f4189eee17/lib/arachni/framework/parts/browser.rb:33:in `new'
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/gems/2.3.0/bundler/gems/arachni-73f4189eee17/lib/arachni/framework/parts/browser.rb:33:in `block in browser_cluster'
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/gems/2.3.0/bundler/gems/arachni-73f4189eee17/lib/arachni/framework/parts/browser.rb:28:in `browser_cluster'
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/gems/2.3.0/bundler/gems/arachni-73f4189eee17/lib/arachni/framework/parts/audit.rb:173:in `audit'
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/gems/2.3.0/bundler/gems/arachni-73f4189eee17/lib/arachni/framework.rb:117:in `block in run'
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/gems/2.3.0/bundler/gems/arachni-73f4189eee17/lib/arachni/utilities.rb:425:in `exception_jail'
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/gems/2.3.0/bundler/gems/arachni-73f4189eee17/lib/arachni/framework.rb:117:in `run'
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/gems/2.3.0/bundler/gems/arachni-73f4189eee17/lib/arachni/rpc/server/framework.rb:156:in `block in run'
[2016-11-18 16:01:45 +0800] 
[2016-11-18 16:01:45 +0800] Parent:
[2016-11-18 16:01:45 +0800] Arachni::RPC::Server::Framework
[2016-11-18 16:01:45 +0800] 
[2016-11-18 16:01:45 +0800] Block:
[2016-11-18 16:01:45 +0800] #<Proc:0x007fb97cafcd90@/usr/local/lib/ruby/gems/2.3.0/bundler/gems/arachni-73f4189eee17/lib/arachni/framework.rb:117>
[2016-11-18 16:01:45 +0800] 
[2016-11-18 16:01:45 +0800] Caller:
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/gems/2.3.0/bundler/gems/arachni-73f4189eee17/lib/arachni/utilities.rb:425:in `exception_jail'
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/gems/2.3.0/bundler/gems/arachni-73f4189eee17/lib/arachni/framework.rb:117:in `run'
[2016-11-18 16:01:45 +0800] /usr/local/lib/ruby/gems/2.3.0/bundler/gems/arachni-73f4189eee17/lib/arachni/rpc/server/framework.rb:156:in `block in run'
```

**Comment by Zapotek** [comment]
Does this happen when you use the packages rather than the gem?

**Comment by Zapotek** [comment]
Closing due to lack of feedback and because the scan was ran in a foreign env.
