### ISSUE TITLE
Could not start the browser process

### ISSUE THREAD

**Issue by SuperSuperSuperSuper5** [Arachni/arachni#811]
Dear developers:

I am first using this method and it raise me a error:

```
[2016-12-21 10:57:46 +0800] [Arachni::Browser::Error::Spawn] Could not start the browser process.
[2016-12-21 10:57:46 +0800] /home/hero/Downloads/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:1268:in `spawn_browser'
[2016-12-21 10:57:46 +0800] /home/hero/Downloads/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:1164:in `selenium'
[2016-12-21 10:57:46 +0800] /home/hero/Downloads/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:197:in `initialize'
[2016-12-21 10:57:46 +0800] /home/hero/Downloads/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster/worker.rb:52:in `initialize'
[2016-12-21 10:57:46 +0800] /home/hero/Downloads/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster.rb:477:in `new'
[2016-12-21 10:57:46 +0800] /home/hero/Downloads/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster.rb:477:in `block in initialize_workers'
[2016-12-21 10:57:46 +0800] /home/hero/Downloads/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster.rb:476:in `times'
[2016-12-21 10:57:46 +0800] /home/hero/Downloads/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster.rb:476:in `initialize_workers'
[2016-12-21 10:57:46 +0800] /home/hero/Downloads/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster.rb:119:in `initialize'
[2016-12-21 10:57:46 +0800] /home/hero/Downloads/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework/parts/browser.rb:33:in `new'
[2016-12-21 10:57:46 +0800] /home/hero/Downloads/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework/parts/browser.rb:33:in `block in browser_cluster'
[2016-12-21 10:57:46 +0800] /home/hero/Downloads/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
[2016-12-21 10:57:46 +0800] /home/hero/Downloads/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework/parts/browser.rb:28:in `browser_cluster'
[2016-12-21 10:57:46 +0800] /home/hero/Downloads/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework/parts/audit.rb:173:in `audit'
[2016-12-21 10:57:46 +0800] /home/hero/Downloads/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework.rb:117:in `block in run'
[2016-12-21 10:57:46 +0800] /home/hero/Downloads/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `call'
[2016-12-21 10:57:46 +0800] /home/hero/Downloads/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `exception_jail'
[2016-12-21 10:57:46 +0800] /home/hero/Downloads/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework.rb:117:in `run'
[2016-12-21 10:57:46 +0800] /home/hero/Downloads/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/rpc/server/framework.rb:156:in `block in run'
[2016-12-21 10:57:46 +0800] 
[2016-12-21 10:57:46 +0800] Parent:
[2016-12-21 10:57:46 +0800] Arachni::RPC::Server::Framework
[2016-12-21 10:57:46 +0800] 
[2016-12-21 10:57:46 +0800] Block:
[2016-12-21 10:57:46 +0800] #<Proc:0x0000000571c1b8@/home/hero/Downloads/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework.rb:117>
[2016-12-21 10:57:46 +0800] 
[2016-12-21 10:57:46 +0800] Caller:
[2016-12-21 10:57:46 +0800] /home/hero/Downloads/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `exception_jail'
[2016-12-21 10:57:46 +0800] /home/hero/Downloads/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework.rb:117:in `run'
[2016-12-21 10:57:46 +0800] /home/hero/Downloads/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/rpc/server/framework.rb:156:in `block in run'
[2016-12-21 10:57:46 +0800] --------------------------------------------------------------------------------
```
 Thx

**Comment by Zapotek** [comment]
Hello,

This issue has been fixed in the [nightlies](http://downloads.arachni-scanner.com/nightlies/).

Cheers
