### ISSUE TITLE
Too many open files during checks

### ISSUE THREAD

**Issue by brandonprry** [Arachni/arachni#815]
Running latest experimental branch on OS X.

```
$ git log | head -n1
commit 2438e975e2c5a571b514608f19ea0b5009eddacd
$
```

Not sure the exact cause, but these stack traces are printed often. I know it says too many open files, but only Arachni is complaining about too many open files. Arguments used when running the scan were ```--checks xss*,sql*``` and ```--http-user-agent```.

```
[*] XSS in script context: Analyzing response #837 for form input 'task' pointing to: 'https://example.com'
 [-] [http/proxy_server#start_async:70] ProxyServer: [Errno::EMFILE] Too many open files - accept(2)
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/socket.rb:1308:in `__accept_nonblock'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/socket.rb:1308:in `accept_nonblock'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor/connection/tls.rb:146:in `block in socket_accept'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor/connection/error.rb:26:in `translate'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor/connection/tls.rb:145:in `socket_accept'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor/connection.rb:192:in `accept'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor/connection.rb:258:in `_read'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor/connection/tls.rb:115:in `_read'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor.rb:574:in `each'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor.rb:574:in `block in process_connections'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor.rb:574:in `each'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor.rb:574:in `process_connections'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor.rb:316:in `block in run'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor.rb:307:in `loop'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor.rb:307:in `run'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor.rb:349:in `block in run_in_thread'
 [-] [http/proxy_server#start_async:70] ProxyServer: [Errno::EMFILE] Too many open files - accept(2)
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/socket.rb:1308:in `__accept_nonblock'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/socket.rb:1308:in `accept_nonblock'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor/connection/tls.rb:146:in `block in socket_accept'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor/connection/error.rb:26:in `translate'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor/connection/tls.rb:145:in `socket_accept'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor/connection.rb:192:in `accept'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor/connection.rb:258:in `_read'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor/connection/tls.rb:115:in `_read'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor.rb:574:in `each'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor.rb:574:in `block in process_connections'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor.rb:574:in `each'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor.rb:574:in `process_connections'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor.rb:316:in `block in run'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor.rb:307:in `loop'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor.rb:307:in `run'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor.rb:349:in `block in run_in_thread'
 [-] [http/proxy_server#start_async:70] ProxyServer: [Errno::EMFILE] Too many open files - accept(2)
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/socket.rb:1308:in `__accept_nonblock'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/socket.rb:1308:in `accept_nonblock'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor/connection/tls.rb:146:in `block in socket_accept'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor/connection/error.rb:26:in `translate'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor/connection/tls.rb:145:in `socket_accept'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor/connection.rb:192:in `accept'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor/connection.rb:258:in `_read'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor/connection/tls.rb:115:in `_read'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor.rb:574:in `each'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor.rb:574:in `block in process_connections'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor.rb:574:in `each'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor.rb:574:in `process_connections'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor.rb:316:in `block in run'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor.rb:307:in `loop'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor.rb:307:in `run'
 [-] [http/proxy_server#start_async:70] ProxyServer: /Users/bperry/.rvm/gems/ruby-2.3.1/bundler/gems/arachni-reactor-5be03a86b3d6/lib/arachni/reactor.rb:349:in `block in run_in_thread'
```

**Comment by brandonprry** [comment]
This only seems to work when scanning a particular host. Another host with the same args does not do this. Trying to nail it down.

**Comment by Zapotek** [comment]
The OS is actually complaining about there being too many open files, try increasing your `ulimit`.
Also, just for curiosity's sake, can you please paste the output of `ulimit -a`?

**Comment by brandonprry** [comment]
Nothing special, whatever is default on OS X. I had actually just rebooted so it shouldn't have been doing anything heavy.

```
$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 256
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 709
virtual memory          (kbytes, -v) unlimited
$
```

Still able to repro it with the specific host I am scanning (can't go into much detail about the specific host though unfortunately...)

**Comment by Zapotek** [comment]
The OSX defaults are way too conservative, if you increase the open files limit the issue will go away.
