### ISSUE TITLE
Archni Update Scan Issue

### ISSUE THREAD

**Issue by florian-eichelberger** [Arachni/arachni#822]
Hi 

I am doing a quick test of Arachni v1.4 WebGui 0.5.10 and stumbled across the following issue when updating the info of a finished scan: (I was actually not updating anything, just clicking Save") All the settings are default settings.

```
Started GET "/navigation" for ::1 at 2017-01-09 16:33:42 +0100
Processing by HomeController#navigation as HTML
  Rendered layouts/_navigation.html.erb (20.8ms)
Completed 200 OK in 23ms (Views: 18.8ms | ActiveRecord: 2.4ms)
Started GET "/scans/4.js?action=show&amp;controller=scans&amp;format=js&amp;id=4&amp;overview=false&amp;scan_id=4&amp;tab=all" for ::1 at 2017-01-09 16:33:42 +0100
Processing by ScansController#show as JS
  Parameters: {"amp"=>nil, "id"=>"4", "overview"=>"false", "scan_id"=>"4", "tab"=>"all"}
  Rendered comments/_list.html.erb (0.6ms)
  Rendered issues/_table_tabs.html.erb (0.1ms)
  Rendered issues/_table.html.erb (15.2ms)
  Rendered scans/_revisions_nav_list.html.erb (3.8ms)
  Rendered shared/_share_form.html.erb (3.5ms)
  Rendered scans/_scan_sidebar.html.erb (10.6ms)
  Rendered scans/_show_inactive.html.erb (3.5ms)
  Rendered scans/_scan.js.erb (36.6ms)
Completed 200 OK in 47ms (Views: 35.0ms | ActiveRecord: 2.4ms)
Started GET "/scans/4/edit" for ::1 at 2017-01-09 16:33:44 +0100
Processing by ScansController#edit as HTML
  Parameters: {"id"=>"4"}
  Rendered scans/_form.html.erb (7.0ms)
  Rendered scans/edit.html.erb within layouts/application (7.3ms)
  Rendered layouts/_navigation.html.erb (15.3ms)
  Rendered layouts/_breadcrumbs.html.erb (0.1ms)
  Rendered layouts/_messages.html.erb (0.1ms)
Completed 200 OK in 34ms (Views: 21.6ms | ActiveRecord: 3.0ms)
Started GET "/navigation" for ::1 at 2017-01-09 16:33:45 +0100
Processing by HomeController#navigation as HTML
  Rendered layouts/_navigation.html.erb (17.6ms)
Completed 200 OK in 19ms (Views: 16.1ms | ActiveRecord: 2.0ms)
ScanManager#keep_schedule
ScanManager#refresh
DispatcherManager#refresh
Started GET "/navigation" for ::1 at 2017-01-09 16:33:50 +0100
Processing by HomeController#navigation as HTML
  Rendered layouts/_navigation.html.erb (20.0ms)
Completed 200 OK in 22ms (Views: 18.0ms | ActiveRecord: 2.4ms)
ScanManager#keep_schedule
ScanManager#refresh
DispatcherManager#refresh
Started PATCH "/scans/4" for ::1 at 2017-01-09 16:33:52 +0100
Processing by ScansController#update as HTML
  Parameters: {"utf8"=>"\u2713", "authenticity_token"=>"ZCxqpfdsX7SRR1mIOURdRehAfCnEZfJAxezjjaNd+V5QxvP4ZiMtD+cU5XXXj8EqcYJkoQepRk8K5UemS8lvng==", "scan"=>{"description"=>"", "user_ids"=>[""], "type"=>"direct"}, "commit"=>"Save", "id"=>"4"}
Completed 500 Internal Server Error in 20ms (ActiveRecord: 3.4ms)

ArgumentError (When assigning attributes, you must pass a hash as an argument.):
  app/controllers/scans_controller.rb:231:in `block in update'
  app/controllers/scans_controller.rb:229:in `update'
```

**Comment by Zapotek** [comment]
The issue has been fixed and will be in the nightlies in a few hours.

In the future, please open issues related to the WebUI at: https://github.com/Arachni/arachni-ui-web/issues

Cheers
