### ISSUE TITLE
issue in scan ./arachni_web 

### ISSUE THREAD

**Issue by rodolfovile** [Arachni/arachni#827]
```
2017-01-14 14:41:52 -0300 --------------------------------------------------------------------------------
ENV:
---
CPLUS_INCLUDE_PATH: "/home/vmteste/Documents/arachni-1.4-0.5.10/bin/../system/usr/include"
XDG_VTNR: '7'
LC_PAPER: pt_BR.UTF-8
XDG_SESSION_ID: c2
LC_ADDRESS: pt_BR.UTF-8
SSH_AGENT_PID: '1413'
XDG_GREETER_DATA_DIR: "/var/lib/lightdm-data/vmteste"
LC_MONETARY: pt_BR.UTF-8
SAL_USE_VCLPLUGIN: gtk
GEM_HOME: "/home/vmteste/Documents/arachni-1.4-0.5.10/system/gems"
XDG_MENU_PREFIX: lxde-
SHELL: "/bin/bash"
TERM: xterm
IRBRC: "/home/vmteste/Documents/arachni-1.4-0.5.10/bin/../system/usr/lib/ruby/.irbrc"
LIBRARY_PATH: "/home/vmteste/Documents/arachni-1.4-0.5.10/bin/../system/usr/lib:/usr/lib:/usr/local/lib"
QT_LINUX_ACCESSIBILITY_ALWAYS_ON: '1'
LC_NUMERIC: pt_BR.UTF-8
MY_RUBY_HOME: "/home/vmteste/Documents/arachni-1.4-0.5.10/bin/../system/usr/lib/ruby"
USER: vmteste
LD_LIBRARY_PATH: "/home/vmteste/Documents/arachni-1.4-0.5.10/bin/../system/usr/lib:/usr/lib:/usr/local/lib"
LC_TELEPHONE: pt_BR.UTF-8
QT_ACCESSIBILITY: '1'
LS_COLORS: 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
XDG_SESSION_PATH: "/org/freedesktop/DisplayManager/Session0"
XDG_SEAT_PATH: "/org/freedesktop/DisplayManager/Seat0"
SSH_AUTH_SOCK: "/tmp/ssh-IjAxMatuPXUY/agent.1352"
XDG_CONFIG_DIRS: "/etc/xdg/lubuntu:/etc/xdg/xdg-Lubuntu:/etc/xdg"
DESKTOP_SESSION: Lubuntu
PATH: "/home/vmteste/Documents/arachni-1.4-0.5.10/system/gems/bin:/home/vmteste/Documents/arachni-1.4-0.5.10/bin/../system/../bin:/home/vmteste/Documents/arachni-1.4-0.5.10/bin/../system/usr/bin:/home/vmteste/Documents/arachni-1.4-0.5.10/bin/../system/gems/bin:/home/vmteste/bin:/home/vmteste/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
QT_QPA_PLATFORMTHEME: lxqt
C_INCLUDE_PATH: "/home/vmteste/Documents/arachni-1.4-0.5.10/bin/../system/usr/include"
LC_IDENTIFICATION: pt_BR.UTF-8
PWD: "/home/vmteste/Documents/arachni-1.4-0.5.10/bin"
XDG_SESSION_TYPE: x11
ARACHNI_WEBUI_LOGDIR: "/home/vmteste/Documents/arachni-1.4-0.5.10/bin/../system/logs/webui"
LANG: en_US.UTF-8
GDM_LANG: en_US
LC_MEASUREMENT: pt_BR.UTF-8
ARACHNI_FRAMEWORK_LOGDIR: "/home/vmteste/Documents/arachni-1.4-0.5.10/bin/../system/logs/framework"
GDMSESSION: Lubuntu
QT_PLATFORM_PLUGIN: lxqt
_LXSESSION_PID: '1352'
SHLVL: '1'
HOME: "/home/vmteste/Documents/arachni-1.4-0.5.10/bin/../system/home/arachni"
XDG_SEAT: seat0
LANGUAGE: en_US
XDG_CONFIG_HOME: "/home/vmteste/.config"
RAILS_ENV: production
DYLD_LIBRARY_PATH: "/home/vmteste/Documents/arachni-1.4-0.5.10/bin/../system/usr/lib:/usr/lib:/usr/local/lib"
LOGNAME: vmteste
XDG_SESSION_DESKTOP: Lubuntu
GEM_PATH: "/home/vmteste/Documents/arachni-1.4-0.5.10/bin/../system/gems"
LC_CTYPE: pt_BR.UTF-8
DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
XDG_DATA_DIRS: "/etc/xdg/lubuntu:/usr/local/share:/usr/share:/usr/share/gdm:/var/lib/menu-xdg:/usr/share/Lubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop"
LESSOPEN: "| /usr/bin/lesspipe %s"
DISPLAY: ":0"
XDG_RUNTIME_DIR: "/run/user/1000"
XDG_CURRENT_DESKTOP: LXDE
RUBYLIB: "/home/vmteste/Documents/arachni-1.4-0.5.10/system/gems/gems/bundler-1.11.2/lib:/home/vmteste/Documents/arachni-1.4-0.5.10/bin/../system/usr/lib/ruby:/home/vmteste/Documents/arachni-1.4-0.5.10/bin/../system/usr/lib/ruby/site_ruby/2.2.0:/home/vmteste/Documents/arachni-1.4-0.5.10/bin/../system/usr/lib/ruby/2.2.0:/home/vmteste/Documents/arachni-1.4-0.5.10/bin/../system/usr/lib/ruby/2.2.0/x86_64-linux:/home/vmteste/Documents/arachni-1.4-0.5.10/bin/../system/usr/lib/ruby/site_ruby/2.2.0/x86_64-linux"
RUBY_VERSION: ruby-2.2.3
LC_TIME: pt_BR.UTF-8
LESSCLOSE: "/usr/bin/lesspipe %s %s"
LC_NAME: pt_BR.UTF-8
XAUTHORITY: "/home/vmteste/.Xauthority"
RACK_ENV: development
BUNDLE_GEMFILE: "/home/vmteste/Documents/arachni-1.4-0.5.10/system/arachni-ui-web/Gemfile"
_ORIGINAL_GEM_PATH: "/home/vmteste/Documents/arachni-1.4-0.5.10/bin/../system/gems"
BUNDLE_BIN_PATH: "/home/vmteste/Documents/arachni-1.4-0.5.10/system/gems/gems/bundler-1.11.2/exe/bundle"
RUBYOPT: "-rbundler/setup"
MANPATH: "/home/vmteste/Documents/arachni-1.4-0.5.10/system/gems/gems/kramdown-1.4.1/man"
BUNDLE_ORIG_MANPATH: "/home/vmteste/Documents/arachni-1.4-0.5.10/system/gems/gems/kramdown-1.4.1/man"
--------------------------------------------------------------------------------
OPTIONS:
---
datastore:
  token: a46b8000fb559f84618407e76d952448
http:
  user_agent: Arachni/v1.4
  request_timeout: 10000
  request_redirect_limit: 5
  request_concurrency: 20
  request_queue_size: 100
  request_headers: {}
  response_max_size: 500000
  cookies: {}
browser_cluster:
  local_storage: {}
  wait_for_elements: {}
  pool_size: 6
  job_timeout: 25
  worker_time_to_live: 100
  ignore_images: false
  screen_width: 1600
  screen_height: 1200
input:
  values:
    name: arachni_name
    user: arachni_user
    usr: arachni_user
    pass: 5543!%arachni_secret
    txt: arachni_text
    num: '132'
    amount: '100'
    mail: arachni@email.gr
    account: '12'
    id: '1'
  default_values:
    name: arachni_name
    user: arachni_user
    usr: arachni_user
    pass: 5543!%arachni_secret
    txt: arachni_text
    num: '132'
    amount: '100'
    mail: arachni@email.gr
    account: '12'
    id: '1'
  without_defaults: true
  force: false
scope:
  redundant_path_patterns: {}
  dom_depth_limit: 5
  exclude_file_extensions: []
  exclude_path_patterns: []
  exclude_content_patterns: []
  include_path_patterns: []
  restrict_paths: []
  extend_paths: []
  url_rewrites: {}
audit:
  parameter_values: true
  exclude_vector_patterns: []
  include_vector_patterns: []
  link_templates: []
  links: true
  forms: true
  cookies: true
  jsons: true
  xmls: true
  ui_forms: true
  ui_inputs: true
session: {}
checks:
- xss
- xss_path
- xss_tag
- xss_script_context
- xss_event
- xss_dom
- xss_dom_script_context
platforms: []
plugins:
  autothrottle: {}
  discovery: {}
  healthmap: {}
  timing_attacks: {}
  uniformity: {}
no_fingerprinting: false
authorized_by: 
url: http://www.site.com/nossos-clientes/?lista=pub
--------------------------------------------------------------------------------
[2017-01-14 14:41:52 -0300] Could not spawn browser process.
[2017-01-14 14:41:52 -0300] 18416: Started
PID: 18419
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working
18416: Working

[2017-01-14 14:41:52 -0300] [Arachni::Browser::Error::Spawn] Could not start the browser process.
[2017-01-14 14:41:52 -0300] /home/vmteste/Documents/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:1268:in `spawn_browser'
[2017-01-14 14:41:52 -0300] /home/vmteste/Documents/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:1164:in `selenium'
[2017-01-14 14:41:52 -0300] /home/vmteste/Documents/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:197:in `initialize'
[2017-01-14 14:41:52 -0300] /home/vmteste/Documents/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster/worker.rb:52:in `initialize'
[2017-01-14 14:41:52 -0300] /home/vmteste/Documents/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster.rb:477:in `new'
[2017-01-14 14:41:52 -0300] /home/vmteste/Documents/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster.rb:477:in `block in initialize_workers'
[2017-01-14 14:41:52 -0300] /home/vmteste/Documents/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster.rb:476:in `times'
[2017-01-14 14:41:52 -0300] /home/vmteste/Documents/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster.rb:476:in `initialize_workers'
[2017-01-14 14:41:52 -0300] /home/vmteste/Documents/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster.rb:119:in `initialize'
[2017-01-14 14:41:52 -0300] /home/vmteste/Documents/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework/parts/browser.rb:33:in `new'
[2017-01-14 14:41:52 -0300] /home/vmteste/Documents/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework/parts/browser.rb:33:in `block in browser_cluster'
[2017-01-14 14:41:52 -0300] /home/vmteste/Documents/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
[2017-01-14 14:41:52 -0300] /home/vmteste/Documents/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework/parts/browser.rb:28:in `browser_cluster'
[2017-01-14 14:41:52 -0300] /home/vmteste/Documents/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework/parts/audit.rb:173:in `audit'
[2017-01-14 14:41:52 -0300] /home/vmteste/Documents/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework.rb:117:in `block in run'
[2017-01-14 14:41:52 -0300] /home/vmteste/Documents/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `call'
[2017-01-14 14:41:52 -0300] /home/vmteste/Documents/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `exception_jail'
[2017-01-14 14:41:52 -0300] /home/vmteste/Documents/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework.rb:117:in `run'
[2017-01-14 14:41:52 -0300] /home/vmteste/Documents/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/rpc/server/framework.rb:156:in `block in run'
[2017-01-14 14:41:52 -0300] 
[2017-01-14 14:41:52 -0300] Parent:
[2017-01-14 14:41:52 -0300] Arachni::RPC::Server::Framework
[2017-01-14 14:41:52 -0300] 
[2017-01-14 14:41:52 -0300] Block:
[2017-01-14 14:41:52 -0300] #<Proc:0x00000004d92f98@/home/vmteste/Documents/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework.rb:117>
[2017-01-14 14:41:52 -0300] 
[2017-01-14 14:41:52 -0300] Caller:
[2017-01-14 14:41:52 -0300] /home/vmteste/Documents/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `exception_jail'
[2017-01-14 14:41:52 -0300] /home/vmteste/Documents/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework.rb:117:in `run'
[2017-01-14 14:41:52 -0300] /home/vmteste/Documents/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/rpc/server/framework.rb:156:in `block in run'
[2017-01-14 14:41:52 -0300] --------------------------------------------------------------------------------
```

**Comment by Zapotek** [comment]
This issue has been resolved in the [nighlties](http://downloads.arachni-scanner.com/nightlies/).
