### ISSUE TITLE
bug ? report

### ISSUE THREAD

**Issue by hktalent** [Arachni/arachni#846]
# 1 kali linux
# 2 error msg
```
root@kali:/usr/share/arachni# ./bin/arachni http://erp.yinhai.com:8082
Arachni - Web Application Security Scanner Framework v1.5
   Author: Tasos "Zapotek" Laskos <tasos.laskos@arachni-scanner.com>

           (With the support of the community and the Arachni Team.)

   Website:       http://arachni-scanner.com
   Documentation: http://arachni-scanner.com/wiki


 [~] No checks were specified, loading all.
 [~] No element audit options were specified, will audit links, forms, cookies, UI inputs, UI forms, JSONs and XMLs.

 [*] Initializing...
 [*] Preparing plugins...
 [*] ... done.
 [-] [utilities#exception_jail:428] [Selenium::WebDriver::Error::WebDriverError] Unable to find phantomjs executable.
 [-] [utilities#exception_jail:428] /usr/share/arachni/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/phantomjs.rb:38:in `path'
 [-] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/browser.rb:148:in `executable'
 [-] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/browser.rb:142:in `has_executable?'
 [-] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/framework/parts/browser.rb:50:in `host_has_browser?'
 [-] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/framework/parts/browser.rb:65:in `use_browsers?'
 [-] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/framework/parts/browser.rb:24:in `browser_cluster'
 [-] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/framework/parts/audit.rb:173:in `audit'
 [-] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/framework.rb:117:in `block in run'
 [-] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/utilities.rb:425:in `exception_jail'
 [-] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/framework.rb:117:in `run'
 [-] [utilities#exception_jail:428] /usr/share/arachni/ui/cli/framework.rb:80:in `block in run'
 [-] [utilities#exception_jail:429] 
 [-] [utilities#exception_jail:430] Parent:
 [-] [utilities#exception_jail:431] Arachni::Framework
 [-] [utilities#exception_jail:432] 
 [-] [utilities#exception_jail:433] Block:
 [-] [utilities#exception_jail:434] #<Proc:0x00559671a99f18@/usr/share/arachni/lib/arachni/framework.rb:117>
 [-] [utilities#exception_jail:435] 
 [-] [utilities#exception_jail:436] Caller:
 [-] [utilities#exception_jail:437] /usr/share/arachni/lib/arachni/utilities.rb:425:in `exception_jail'
 [-] [utilities#exception_jail:437] /usr/share/arachni/lib/arachni/framework.rb:117:in `run'
 [-] [utilities#exception_jail:437] /usr/share/arachni/ui/cli/framework.rb:80:in `block in run'
 [-] [utilities#exception_jail:438] --------------------------------------------------------------------------------


================================================================================


 [+] Web Application Security Report - Arachni Framework

 [~] Report generated on: 2017-03-06 17:35:42 +0800
 [~] Report false positives at: http://github.com/Arachni/arachni/issues

 [+] System settings:
 [~] ---------------
 [~] Version:           1.5
 [~] Seed:              2a2dee69f99a83b1cb3074086c221b09
 [~] Audit started on:  2017-03-06 17:35:41 +0800
 [~] Audit finished on: 2017-03-06 17:35:41 +0800
 [~] Runtime:           00:00:00

 [~] URL:        http://erp.yinhai.com:8082/
 [~] User agent: Arachni/v1.5

 [*] Audited elements: 
 [~] * Links
 [~] * Forms
 [~] * Cookies
 [~] * XMLs
 [~] * JSONs
 [~] * UI inputs
 [~] * UI forms

 [*] Checks: xxe, xss_tag, code_injection_timing, code_injection_php_input_wrapper, sql_injection_timing, sql_injection_differential, ldap_injection, code_injection, os_cmd_injection, no_sql_injection, xss_dom_script_context, session_fixation, xss_script_context, csrf, xss_dom, unvalidated_redirect, source_code_disclosure, xss_event, path_traversal, xss, trainer, xss_path, os_cmd_injection_timing, response_splitting, file_inclusion, unvalidated_redirect_dom, xpath_injection, rfi, no_sql_injection_differential, sql_injection, origin_spoof_access_restriction_bypass, insecure_cross_domain_policy_headers, backdoors, http_put, backup_files, common_admin_interfaces, private_ip, form_upload, insecure_cookies, hsts, cvs_svn_users, html_objects, cookie_set_for_parent_domain, captcha, insecure_cors_policy, password_autocomplete, ssn, credit_card, mixed_resource, unencrypted_password_forms, http_only_cookies, x_frame_options, emails, insecure_client_access_policy, allowed_methods, interesting_responses, common_files, localstart_asp, htaccess_limit, xst, common_directories, webdav, backup_directories, insecure_cross_domain_policy_access, directory_listing

 [~] ===========================

 [+] 0 issues were detected.


 [~] Report saved at: /usr/share/arachni/erp.yinhai.com 2017-03-06 17_35_41 +0800.afr [0.0MB]
 [~] The scan has logged errors: /usr/share/arachni/logs/error-2337.log

 [~] Audited 0 page snapshots.

 [~] Duration: 00:00:00
 [~] Processed 0/0 HTTP requests.
 [~] -- 0.0 requests/second.
 [~] Processed 0/0 browser jobs.
 [~] -- 0.0 second/job.

 [~] Burst response time sum     0.0 seconds
 [~] Burst response count        0
 [~] Burst average response time 0.0 seconds
 [~] Burst average               0.0 requests/second
 [~] Timed-out requests          0
 [~] Original max concurrency    20
 [~] Throttled max concurrency   20
```
# 3 usr/share/arachni/logs/error-2337.log
```
root@kali:/usr/share/arachni# cat /usr/share/arachni/logs/error-2337.log

2017-03-06 17:35:41 +0800 --------------------------------------------------------------------------------
ENV:
---
LS_COLORS: 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
SSH_CONNECTION: 192.168.28.47 57056 192.168.10.243 22
LANG: zh_CN.UTF-8
NODE_PATH: "/opt/soft/node-v7.2.0-linux-x64/lib/node_modules"
NODE_HOME: "/opt/soft/node-v7.2.0-linux-x64"
SSH_AUTH_SOCK: "/tmp/ssh-KfJg4ZFOTw/agent.2284"
XDG_SESSION_ID: '39212'
USER: root
PWD: "/usr/share/arachni"
HOME: "/root"
SSH_CLIENT: 192.168.28.47 57056 22
SSH_TTY: "/dev/pts/2"
MAIL: "/var/mail/root"
TERM: xterm
SHELL: "/bin/bash"
SHLVL: '1'
LOGNAME: root
DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/0/bus
XDG_RUNTIME_DIR: "/run/user/0"
PATH: "/usr/share/arachni/vendor/bundle/ruby/2.3.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/soft/node-v7.2.0-linux-x64/bin"
_: "./bin/arachni"
OLDPWD: "/root"
BUNDLER_ORIG_PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/soft/node-v7.2.0-linux-x64/bin"
GEM_PATH: ''
GEM_HOME: "/usr/share/arachni/vendor/bundle/ruby/2.3.0"
BUNDLE_BIN_PATH: "/usr/lib/ruby/exe/bundle"
BUNDLE_GEMFILE: "/usr/share/arachni/Gemfile"
BUNDLER_VERSION: 1.13.6
RUBYOPT: "-rbundler/setup"
MANPATH: "/usr/share/arachni/vendor/bundle/ruby/2.3.0/gems/kramdown-1.4.1/man"
--------------------------------------------------------------------------------
OPTIONS:
---
datastore:
  report_path: 
input:
  values: {}
  default_values:
    name: arachni_name
    user: arachni_user
    usr: arachni_user
    pass: 5543!%arachni_secret
    txt: arachni_text
    num: '132'
    amount: '100'
    mail: arachni@email.gr
    account: '12'
    id: '1'
  without_defaults: false
  force: false
http:
  user_agent: Arachni/v1.5
  request_timeout: 10000
  request_redirect_limit: 5
  request_concurrency: 20
  request_queue_size: 100
  request_headers: {}
  response_max_size: 500000
  cookies: {}
  authentication_type: auto
audit:
  parameter_values: true
  exclude_vector_patterns: []
  include_vector_patterns: []
  link_templates: []
  links: true
  forms: true
  cookies: true
  ui_inputs: true
  ui_forms: true
  jsons: true
  xmls: true
session: {}
browser_cluster:
  local_storage: {}
  wait_for_elements: {}
  pool_size: 6
  job_timeout: 10
  worker_time_to_live: 100
  ignore_images: false
  screen_width: 1600
  screen_height: 1200
scope:
  redundant_path_patterns: {}
  dom_depth_limit: 5
  exclude_file_extensions: []
  exclude_path_patterns: []
  exclude_content_patterns: []
  include_path_patterns: []
  restrict_paths: []
  extend_paths: []
  url_rewrites: {}
checks:
- xxe
- xss_tag
- code_injection_timing
- code_injection_php_input_wrapper
- sql_injection_timing
- sql_injection_differential
- ldap_injection
- code_injection
- os_cmd_injection
- no_sql_injection
- xss_dom_script_context
- session_fixation
- xss_script_context
- csrf
- xss_dom
- unvalidated_redirect
- source_code_disclosure
- xss_event
- path_traversal
- xss
- trainer
- xss_path
- os_cmd_injection_timing
- response_splitting
- file_inclusion
- unvalidated_redirect_dom
- xpath_injection
- rfi
- no_sql_injection_differential
- sql_injection
- origin_spoof_access_restriction_bypass
- insecure_cross_domain_policy_headers
- backdoors
- http_put
- backup_files
- common_admin_interfaces
- private_ip
- form_upload
- insecure_cookies
- hsts
- cvs_svn_users
- html_objects
- cookie_set_for_parent_domain
- captcha
- insecure_cors_policy
- password_autocomplete
- ssn
- credit_card
- mixed_resource
- unencrypted_password_forms
- http_only_cookies
- x_frame_options
- emails
- insecure_client_access_policy
- allowed_methods
- interesting_responses
- common_files
- localstart_asp
- htaccess_limit
- xst
- common_directories
- webdav
- backup_directories
- insecure_cross_domain_policy_access
- directory_listing
platforms: []
plugins: {}
no_fingerprinting: false
authorized_by: 
url: http://erp.yinhai.com:8082/
--------------------------------------------------------------------------------
[2017-03-06 17:35:41 +0800] [utilities#exception_jail:428] [Selenium::WebDriver::Error::WebDriverError] Unable to find phantomjs executable.
[2017-03-06 17:35:41 +0800] [utilities#exception_jail:428] /usr/share/arachni/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/phantomjs.rb:38:in `path'
[2017-03-06 17:35:41 +0800] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/browser.rb:148:in `executable'
[2017-03-06 17:35:41 +0800] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/browser.rb:142:in `has_executable?'
[2017-03-06 17:35:41 +0800] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/framework/parts/browser.rb:50:in `host_has_browser?'
[2017-03-06 17:35:41 +0800] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/framework/parts/browser.rb:65:in `use_browsers?'
[2017-03-06 17:35:41 +0800] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/framework/parts/browser.rb:24:in `browser_cluster'
[2017-03-06 17:35:41 +0800] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/framework/parts/audit.rb:173:in `audit'
[2017-03-06 17:35:41 +0800] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/framework.rb:117:in `block in run'
[2017-03-06 17:35:41 +0800] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/utilities.rb:425:in `exception_jail'
[2017-03-06 17:35:41 +0800] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/framework.rb:117:in `run'
[2017-03-06 17:35:41 +0800] [utilities#exception_jail:428] /usr/share/arachni/ui/cli/framework.rb:80:in `block in run'
[2017-03-06 17:35:41 +0800] [utilities#exception_jail:429] 
[2017-03-06 17:35:41 +0800] [utilities#exception_jail:430] Parent:
[2017-03-06 17:35:41 +0800] [utilities#exception_jail:431] Arachni::Framework
[2017-03-06 17:35:41 +0800] [utilities#exception_jail:432] 
[2017-03-06 17:35:41 +0800] [utilities#exception_jail:433] Block:
[2017-03-06 17:35:41 +0800] [utilities#exception_jail:434] #<Proc:0x00559671a99f18@/usr/share/arachni/lib/arachni/framework.rb:117>
[2017-03-06 17:35:41 +0800] [utilities#exception_jail:435] 
[2017-03-06 17:35:41 +0800] [utilities#exception_jail:436] Caller:
[2017-03-06 17:35:41 +0800] [utilities#exception_jail:437] /usr/share/arachni/lib/arachni/utilities.rb:425:in `exception_jail'
[2017-03-06 17:35:41 +0800] [utilities#exception_jail:437] /usr/share/arachni/lib/arachni/framework.rb:117:in `run'
[2017-03-06 17:35:41 +0800] [utilities#exception_jail:437] /usr/share/arachni/ui/cli/framework.rb:80:in `block in run'
[2017-03-06 17:35:41 +0800] [utilities#exception_jail:438] --------------------------------------------------------------------------------
```

**Comment by Zapotek** [comment]
Please use one of the provided packages: http://www.arachni-scanner.com/download/

**Comment by hktalent** [comment]
@Zapotek  thank you
