### ISSUE TITLE
"Failed to open TCP connection to 127.0.0.1:<port>" on Docker

### ISSUE THREAD

**Issue by ErwinJanssen** [Arachni/arachni#866]
I'm trying to run a Arachni scan from a Docker container (kalilinux/kali-linux-docker as base image). When running `arachni http://<target_ip>`, it doesn't go past ` [*] BrowserCluster: Initializing 6 browsers...` and after 10 minutes it aborts and gives the following trace:

```
 [*] BrowserCluster: Initializing 6 browsers...
 [-] [utilities#exception_jail:428] [Errno::ECONNREFUSED] Failed to open TCP connection to 127.0.0.1:43385 (Connection refused - connect(2) for "127.0.0.1" port 43385)
 [-] [utilities#exception_jail:428] /usr/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect'
 [-] [utilities#exception_jail:428] /usr/lib/ruby/2.3.0/net/http.rb:879:in `block in connect'
 [-] [utilities#exception_jail:428] /usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
 [-] [utilities#exception_jail:428] /usr/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
 [-] [utilities#exception_jail:428] /usr/lib/ruby/2.3.0/net/http.rb:878:in `connect'
 [-] [utilities#exception_jail:428] /usr/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
 [-] [utilities#exception_jail:428] /usr/lib/ruby/2.3.0/net/http.rb:852:in `start'
 [-] [utilities#exception_jail:428] /usr/lib/ruby/2.3.0/net/http.rb:1398:in `request'
 [-] [utilities#exception_jail:428] /usr/share/arachni/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/default.rb:103:in `response_for'
 [-] [utilities#exception_jail:428] /usr/share/arachni/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/default.rb:57:in `request'
 [-] [utilities#exception_jail:428] /usr/share/arachni/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
 [-] [utilities#exception_jail:428] /usr/share/arachni/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/bridge.rb:653:in `raw_execute'
 [-] [utilities#exception_jail:428] /usr/share/arachni/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/bridge.rb:124:in `create_session'
 [-] [utilities#exception_jail:428] /usr/share/arachni/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/bridge.rb:88:in `initialize'
 [-] [utilities#exception_jail:428] /usr/share/arachni/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/common/driver.rb:57:in `new'
 [-] [utilities#exception_jail:428] /usr/share/arachni/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/common/driver.rb:57:in `for'
 [-] [utilities#exception_jail:428] /usr/share/arachni/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver.rb:82:in `for'
 [-] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/browser.rb:1109:in `selenium'
 [-] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/browser.rb:1337:in `start_webdriver'
 [-] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/browser.rb:187:in `initialize'
 [-] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/browser_cluster/worker.rb:51:in `initialize'
 [-] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/browser_cluster.rb:495:in `new'
 [-] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/browser_cluster.rb:495:in `block in initialize_workers'
 [-] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/browser_cluster.rb:494:in `times'
 [-] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/browser_cluster.rb:494:in `initialize_workers'
 [-] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/browser_cluster.rb:112:in `initialize'
 [-] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/framework/parts/browser.rb:33:in `new'
 [-] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/framework/parts/browser.rb:33:in `block in browser_cluster'
 [-] [utilities#exception_jail:428] /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
 [-] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/framework/parts/browser.rb:28:in `browser_cluster'
 [-] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/framework/parts/audit.rb:173:in `audit'
 [-] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/framework.rb:117:in `block in run'
 [-] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/utilities.rb:425:in `exception_jail'
 [-] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/framework.rb:117:in `run'
 [-] [utilities#exception_jail:428] /usr/share/arachni/ui/cli/framework.rb:80:in `block in run'
 [-] [utilities#exception_jail:429] 
 [-] [utilities#exception_jail:430] Parent:
 [-] [utilities#exception_jail:431] Arachni::Framework
 [-] [utilities#exception_jail:432] 
 [-] [utilities#exception_jail:433] Block:
 [-] [utilities#exception_jail:434] #<Proc:0x005612192d0308@/usr/share/arachni/lib/arachni/framework.rb:117>
 [-] [utilities#exception_jail:435] 
 [-] [utilities#exception_jail:436] Caller:
 [-] [utilities#exception_jail:437] /usr/share/arachni/lib/arachni/utilities.rb:425:in `exception_jail'
 [-] [utilities#exception_jail:437] /usr/share/arachni/lib/arachni/framework.rb:117:in `run'
 [-] [utilities#exception_jail:437] /usr/share/arachni/ui/cli/framework.rb:80:in `block in run'
 [-] [utilities#exception_jail:438] --------------------------------------------------------------------------------
```

Is this a known problem that has a workaround / fix?

**Comment by Zapotek** [comment]
Sorry, I don't know what's going on, I can only support the provided [packages](http://www.arachni-scanner.com/download/).
I hope that you understand that if you choose to setup your own environment (or use a 3rd party's env as the case may be in Kali) then the situation is out of my hands.

On the bright side, you can download and use the official packages and they should work fine pretty much anywhere.

Cheers

**Comment by ErwinJanssen** [comment]
When I download and run the package you provide on your website inside the docker container, it *does* work! Since your package is so easy to install, I will use that instead of the one provided by Kali. Thanks!
