### ISSUE TITLE
[Arachni::RPC::Exceptions::ConnectionError] Connection closed [Connection refused - connect(2) for 127.0.0.1:15886]

### ISSUE THREAD

**Issue by NitescuLucian** [Arachni/arachni#869]
Arachni hosted in Azure VM. But I recive this at scan

```
[Arachni::RPC::Exceptions::ConnectionError] Connection closed [Connection refused - connect(2) for 127.0.0.1:15886]
--------------------------------------------------------------------------------
/root/arachni-1.5.1-0.5.12/system/arachni-ui-web/app/models/scan.rb:528:in `block in refresh'
/root/arachni-1.5.1-0.5.12/system/gems/gems/arachni-rpc-0.2.1.4/lib/arachni/rpc/proxy.rb:58:in `call'
/root/arachni-1.5.1-0.5.12/system/gems/gems/arachni-rpc-0.2.1.4/lib/arachni/rpc/proxy.rb:58:in `block (2 levels) in translate'
/root/arachni-1.5.1-0.5.12/system/gems/gems/arachni-rpc-0.2.1.4/lib/arachni/rpc/client/handler.rb:100:in `call'
/root/arachni-1.5.1-0.5.12/system/gems/gems/arachni-rpc-0.2.1.4/lib/arachni/rpc/client/handler.rb:100:in `on_close'
/root/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/connection.rb:179:in `close'
/root/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/connection.rb:246:in `rescue in _connect'
/root/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/connection.rb:230:in `_connect'
/root/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/connection/tls.rb:82:in `block in _connect'
/root/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/connection/error.rb:26:in `call'
/root/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/connection/error.rb:26:in `translate'
/root/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/connection/tls.rb:81:in `_connect'
/root/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/connection.rb:284:in `_write'
/root/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/connection/tls.rb:104:in `_write'
/root/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:574:in `each'
/root/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:574:in `block in process_connections'
/root/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:574:in `each'
/root/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:574:in `process_connections'
/root/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:316:in `block in run'
/root/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:307:in `loop'
/root/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:307:in `run'
/root/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:349:in `block in run_in_thread'
********************************************************************************
```

**Comment by Zapotek** [comment]
Sounds to me like the OS is killing the process, probably due to low RAM.
What does `dmesg` say and how much RAM does the machine have?

**Comment by NitescuLucian** [comment]
I was able to track this problem as a RAM issue. I had 0.75 GB.
