### ISSUE TITLE
Problems with Webdriver on startup

### ISSUE THREAD

**Issue by deflexor** [Arachni/arachni#872]
Here is startup log with `--debug-output=3`
Arachni 1.5.1 (ruby 2.3.1p112) [x86_64-linux-gnu]

```
Arachni - Web Application Security Scanner Framework v1.5.1
   Author: Tasos "Zapotek" Laskos <tasos.laskos@arachni-scanner.com>

           (With the support of the community and the Arachni Team.)

   Website:       http://arachni-scanner.com
   Documentation: http://arachni-scanner.com/wiki


 [~] No element audit options were specified, will audit links, forms, cookies, UI inputs, UI forms, JSONs and XMLs.

 [*] Initializing...
 [*] Preparing plugins...
 [*] ... done.
 [*] BrowserCluster: Initializing 1 browsers...
 [2017-04-13 12:44:47 +0300 - 0.0] [!!] [browser#start_webdriver:1336] Worker: Starting WebDriver...
 [2017-04-13 12:44:47 +0300 - 0.0] [!] [browser#spawn_phantomjs:1227] Worker: Spawning PhantomJS...
 [2017-04-13 12:44:47 +0300 - 0.0] [!] [browser#start_proxy:1318] Worker: Booting up...
 [2017-04-13 12:44:47 +0300 - 0.0] [!!] [browser#start_proxy:1320] Worker: Starting proxy...
 [2017-04-13 12:44:47 +0300 - 0.0] [!!] [http/proxy_server#start_async:61] ProxyServer: Starting...
 [2017-04-13 12:44:47 +0300 - 0.1] [!!] [http/proxy_server#start_async:78] ProxyServer: ...started at: http://127.0.0.1:24479
 [2017-04-13 12:44:47 +0300 - 0.1] [!!] [browser#start_proxy:1332] Worker: ... started proxy at: http://127.0.0.1:24479
 [2017-04-13 12:44:47 +0300 - 0.0] [!!] [browser#spawn_phantomjs:1242] Worker: Attempt #0, chose port number 54185
 [2017-04-13 12:44:47 +0300 - 0.0] [!!] [browser#spawn_phantomjs:1246] Worker: Spawning process: /usr/bin/phantomjs
 [2017-04-13 12:44:47 +0300 - 0.0] [!!] [browser#spawn_phantomjs:1267] Worker: Process spawned, waiting for WebDriver server...
 [2017-04-13 12:45:47 +0300 - 60.1] [!] [browser#spawn_phantomjs:1285] Worker: Spawn timed-out.
 [2017-04-13 12:45:47 +0300 - 60.0] [!!] [browser#spawn_phantomjs:1289] Worker: /var/lib/gems/2.3.0/gems/arachni-1.5.1/lib/arachni/processes/executables/base.rb:3:in `load': undefined class/module Set (ArgumentError)
	from /var/lib/gems/2.3.0/gems/arachni-1.5.1/lib/arachni/processes/executables/base.rb:3:in `<main>'

 [2017-04-13 12:45:47 +0300 - 0.0] [!!] [browser#spawn_phantomjs:1297] Worker: Killing process.
 [2017-04-13 12:45:47 +0300 - 0.0] [!] [browser_cluster/worker#shutdown:162] Worker: Shutting down (wait: true) ...
 [2017-04-13 12:45:47 +0300 - 0.0] [!!] [browser_cluster/worker#shutdown:175] Worker: Waiting for done signal...
 [2017-04-13 12:45:47 +0300 - 0.0] [!!] [browser_cluster/worker#shutdown:171] Worker: Signaling done.
 [2017-04-13 12:45:47 +0300 - 0.0] [!!] [browser_cluster/worker#shutdown:179] Worker: ...done.
 [2017-04-13 12:45:47 +0300 - 0.0] [!!] [browser_cluster/worker#shutdown:181] Worker: Waiting for kill check...
 [2017-04-13 12:45:47 +0300 - 0.0] [!!] [browser_cluster/worker#shutdown:183] Worker: ...done.
 [2017-04-13 12:45:47 +0300 - 0.0] [!!] [browser_cluster/worker#shutdown:191] Worker: Calling parent shutdown...
 [2017-04-13 12:45:47 +0300 - 0.0] [!] [browser#shutdown:378] Worker: Shutting down...
 [2017-04-13 12:45:47 +0300 - 0.0] [!!] [browser#shutdown:380] Worker: Killing process.
 [2017-04-13 12:45:47 +0300 - 0.0] [!!] [browser#shutdown:389] Worker: Shutting down proxy...
 [2017-04-13 12:45:47 +0300 - 60.0] [!!] [http/proxy_server#shutdown:95] ProxyServer: Shutting down...
 [2017-04-13 12:45:47 +0300 - 0.0] [!!!] [http/proxy_server/connection#on_close:221] Connection: Closed because: [NilClass] 
 [2017-04-13 12:45:47 +0300 - 0.0] [!!] [http/proxy_server#shutdown:102] ProxyServer: ...shutdown.
 [2017-04-13 12:45:47 +0300 - 0.0] [!!] [browser#shutdown:391] Worker: ...done.
 [2017-04-13 12:45:47 +0300 - 0.0] [!] [browser#shutdown:401] Worker: ...shutdown complete.
 [2017-04-13 12:45:47 +0300 - 0.0] [!!] [browser_cluster/worker#shutdown:193] Worker: ...done.
 [2017-04-13 12:45:47 +0300 - 0.0] [!] [browser_cluster/worker#shutdown:195] Worker: ...shutdown complete.
 [2017-04-13 12:45:47 +0300 - 0.0] [!] [browser#start_proxy:1318] Worker: Booting up...
 [2017-04-13 12:45:47 +0300 - 0.0] [!!] [browser#start_proxy:1320] Worker: Starting proxy...
 [2017-04-13 12:45:47 +0300 - 0.0] [!!] [http/proxy_server#start_async:61] ProxyServer: Starting...
 [2017-04-13 12:45:47 +0300 - 0.1] [!!] [http/proxy_server#start_async:78] ProxyServer: ...started at: http://127.0.0.1:24117
 [2017-04-13 12:45:47 +0300 - 0.1] [!!] [browser#start_proxy:1332] Worker: ... started proxy at: http://127.0.0.1:24117
 [2017-04-13 12:45:47 +0300 - 0.0] [!!] [browser#spawn_phantomjs:1242] Worker: Attempt #1, chose port number 8820
 [2017-04-13 12:45:47 +0300 - 0.0] [!!] [browser#spawn_phantomjs:1246] Worker: Spawning process: /usr/bin/phantomjs
 [2017-04-13 12:45:47 +0300 - 0.0] [!!] [browser#spawn_phantomjs:1267] Worker: Process spawned, waiting for WebDriver server...
```

**Comment by Zapotek** [comment]
Please use the officially provided [packages](http://www.arachni-scanner.com/download/).
