### ISSUE TITLE
Cannot be executed while running as an RPC server.

### ISSUE THREAD

**Issue by bossadvisors** [Arachni/arachni#876]
Hello, developers.

I encountered this error "Cannot be executed while running as an RPC server." several times on my first scan after the installation of Arachni.

Note: I run Arachni in docker containers. if that matters.

Thanks.

```
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/processes/executables/base.rb:50:in `<main>'
[2017-04-20 00:16:50 +0000] 
[2017-04-20 00:16:50 +0000] Parent:
[2017-04-20 00:16:50 +0000] Arachni::Session
[2017-04-20 00:16:50 +0000] Block:
[2017-04-20 00:16:50 +0000] #<Proc:0x000000030ee608@/opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/session.rb:244>
[2017-04-20 00:16:50 +0000] Caller:
[2017-04-20 00:16:50 +0000] --------------------------------------------------------------------------------
[2017-04-20 00:16:50 +0000] Arachni::RPC::Server::Plugin::Manager
[2017-04-20 00:16:50 +0000] #<Proc:0x000000032d52c8@/opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/plugin/manager.rb:68>
[2017-04-20 00:16:50 +0000] Cannot be executed while running as an RPC server.
[2017-04-20 00:16:50 +0000] #<Proc:0x000000030ee608@/opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/session.rb:244>
[2017-04-20 00:16:50 +0000] 
[2017-04-20 00:16:50 +0000] Caller:
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/utilities.rb:425:in `exception_jail'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/session.rb:244:in `login'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/components/plugins/autologin.rb:37:in `prepare'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/plugin/manager.rb:69:in `block (2 levels) in run'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/utilities.rb:425:in `call'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/plugin/manager.rb:68:in `block in run'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/plugin/manager.rb:65:in `each'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/plugin/manager.rb:65:in `run'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/framework/parts/state.rb:348:in `prepare'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/rpc/server/framework.rb:257:in `prepare'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/rpc/server/framework.rb:148:in `run'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/rpc/server/instance.rb:594:in `block in scan'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:95:in `call'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:95:in `block in each'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:119:in `call'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:119:in `block (2 levels) in each'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/rpc/server/instance.rb:606:in `call'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/rpc/server/instance.rb:606:in `block (2 levels) in scan'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/rpc/server/framework/master.rb:88:in `call'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/rpc/server/framework/master.rb:88:in `block (2 levels) in enslave'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-rpc-0.2.1.4/lib/arachni/rpc/client/handler.rb:77:in `call'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-rpc-0.2.1.4/lib/arachni/rpc/client/handler.rb:77:in `receive_response'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-rpc-0.2.1.4/lib/arachni/rpc/client/handler.rb:137:in `receive_object'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-rpc-0.2.1.4/lib/arachni/rpc/protocol.rb:52:in `on_read'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/connection.rb:261:in `block in _read'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/connection/error.rb:26:in `call'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/connection/error.rb:26:in `translate'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/connection.rb:260:in `_read'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/connection/tls.rb:115:in `_read'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:574:in `each'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:574:in `block in process_connections'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:574:in `process_connections'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:316:in `block in run'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:307:in `loop'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:307:in `run'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/rpc/server/instance.rb:152:in `initialize'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/processes/executables/instance.rb:13:in `new'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/processes/executables/instance.rb:13:in `<top (required)>'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/processes/executables/base.rb:50:in `load'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/processes/executables/base.rb:50:in `<main>'
[2017-04-20 00:16:50 +0000] --------------------------------------------------------------------------------
[2017-04-20 00:16:50 +0000] [Net::ReadTimeout] Net::ReadTimeout
[2017-04-20 00:16:50 +0000] /opt/arachni/system/usr/lib/ruby/2.2.0/net/protocol.rb:158:in `rescue in rbuf_fill'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/usr/lib/ruby/2.2.0/net/protocol.rb:152:in `rbuf_fill'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/usr/lib/ruby/2.2.0/net/protocol.rb:134:in `readuntil'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/usr/lib/ruby/2.2.0/net/protocol.rb:144:in `readline'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/usr/lib/ruby/2.2.0/net/http/response.rb:39:in `read_status_line'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/usr/lib/ruby/2.2.0/net/http/response.rb:28:in `read_new'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/usr/lib/ruby/2.2.0/net/http.rb:1414:in `block in transport_request'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/usr/lib/ruby/2.2.0/net/http.rb:1411:in `catch'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/usr/lib/ruby/2.2.0/net/http.rb:1411:in `transport_request'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/usr/lib/ruby/2.2.0/net/http.rb:1384:in `request'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/usr/lib/ruby/2.2.0/net/http.rb:1377:in `block in request'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/usr/lib/ruby/2.2.0/net/http.rb:853:in `start'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/usr/lib/ruby/2.2.0/net/http.rb:1375:in `request'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/default.rb:103:in `response_for'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/default.rb:57:in `request'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/bridge.rb:653:in `raw_execute'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/bridge.rb:631:in `execute'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/bridge.rb:136:in `get'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/common/navigation.rb:32:in `to'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/browser.rb:334:in `block in goto'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/page/dom/transition.rb:151:in `call'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/page/dom/transition.rb:151:in `start'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/page/dom/transition.rb:106:in `initialize'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/browser.rb:329:in `new'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/browser.rb:329:in `goto'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/browser.rb:250:in `load'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/session.rb:339:in `login_from_configuration'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/session.rb:245:in `block in login'
[2017-04-20 00:16:50 +0000] Parent:
[2017-04-20 00:16:50 +0000] Arachni::RPC::Server::Plugin::Manager
[2017-04-20 00:16:50 +0000] Block:
[2017-04-20 00:16:50 +0000] #<Proc:0x000000032d52c8@/opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/plugin/manager.rb:68>
[2017-04-20 00:16:50 +0000] Cannot be executed while running as an RPC server.
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/components/plugins/autologin.rb:37:in `prepare'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/plugin/manager.rb:69:in `block (2 levels) in run'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/utilities.rb:425:in `call'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/utilities.rb:425:in `exception_jail'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/plugin/manager.rb:68:in `block in run'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/plugin/manager.rb:65:in `each'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/plugin/manager.rb:65:in `run'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/framework/parts/state.rb:348:in `prepare'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/rpc/server/framework.rb:257:in `prepare'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/rpc/server/framework.rb:148:in `run'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/rpc/server/instance.rb:594:in `block in scan'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:95:in `call'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:95:in `block in each'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:119:in `call'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:119:in `block (2 levels) in each'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/rpc/server/instance.rb:606:in `call'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/rpc/server/instance.rb:606:in `block (2 levels) in scan'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/rpc/server/framework/master.rb:88:in `call'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/rpc/server/framework/master.rb:88:in `block (2 levels) in enslave'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-rpc-0.2.1.4/lib/arachni/rpc/client/handler.rb:77:in `call'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-rpc-0.2.1.4/lib/arachni/rpc/client/handler.rb:77:in `receive_response'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-rpc-0.2.1.4/lib/arachni/rpc/client/handler.rb:137:in `receive_object'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-rpc-0.2.1.4/lib/arachni/rpc/protocol.rb:52:in `on_read'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/connection.rb:261:in `block in _read'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/connection/error.rb:26:in `call'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/connection/error.rb:26:in `translate'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/connection.rb:260:in `_read'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/connection/tls.rb:115:in `_read'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:574:in `each'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:574:in `block in process_connections'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:574:in `process_connections'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:316:in `block in run'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:307:in `loop'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:307:in `run'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/rpc/server/instance.rb:152:in `initialize'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/processes/executables/instance.rb:13:in `new'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/processes/executables/instance.rb:13:in `<top (required)>'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/processes/executables/base.rb:50:in `load'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/processes/executables/base.rb:50:in `<main>'
[2017-04-20 00:16:50 +0000] 
[2017-04-20 00:16:50 +0000] Parent:
[2017-04-20 00:16:50 +0000] Arachni::RPC::Server::Plugin::Manager
[2017-04-20 00:16:50 +0000] Block:
[2017-04-20 00:16:50 +0000] #<Proc:0x000000032d52c8@/opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/plugin/manager.rb:68>
[2017-04-20 00:16:50 +0000] Caller:
[2017-04-20 00:16:50 +0000] --------------------------------------------------------------------------------
[2017-04-20 00:16:50 +0000] Cannot be executed while running as an RPC server.
[2017-04-20 00:16:50 +0000] Caller:
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/utilities.rb:425:in `exception_jail'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/plugin/manager.rb:68:in `block in run'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/plugin/manager.rb:65:in `each'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/plugin/manager.rb:65:in `run'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/framework/parts/state.rb:348:in `prepare'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/rpc/server/framework.rb:257:in `prepare'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/rpc/server/framework.rb:148:in `run'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/rpc/server/instance.rb:594:in `block in scan'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:95:in `call'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:95:in `block in each'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:119:in `call'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:119:in `block (2 levels) in each'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/rpc/server/instance.rb:606:in `call'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/rpc/server/instance.rb:606:in `block (2 levels) in scan'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/rpc/server/framework/master.rb:88:in `call'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/rpc/server/framework/master.rb:88:in `block (2 levels) in enslave'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-rpc-0.2.1.4/lib/arachni/rpc/client/handler.rb:77:in `call'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-rpc-0.2.1.4/lib/arachni/rpc/client/handler.rb:77:in `receive_response'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-rpc-0.2.1.4/lib/arachni/rpc/client/handler.rb:137:in `receive_object'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-rpc-0.2.1.4/lib/arachni/rpc/protocol.rb:52:in `on_read'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/connection.rb:261:in `block in _read'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/connection/error.rb:26:in `call'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/connection/error.rb:26:in `translate'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/connection.rb:260:in `_read'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/connection/tls.rb:115:in `_read'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:574:in `each'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:574:in `block in process_connections'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:574:in `process_connections'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:316:in `block in run'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:307:in `loop'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:307:in `run'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/rpc/server/instance.rb:152:in `initialize'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/processes/executables/instance.rb:13:in `new'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/processes/executables/instance.rb:13:in `<top (required)>'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/processes/executables/base.rb:50:in `load'
[2017-04-20 00:16:50 +0000] /opt/arachni/system/gems/gems/arachni-1.5/lib/arachni/processes/executables/base.rb:50:in `<main>'
[2017-04-20 00:16:50 +0000] --------------------------------------------------------------------------------
[2017-04-20 00:16:50 +0000] Cannot be executed while running as an RPC server.
[2017-04-20 00:16:50 +0000] Cannot be executed while running as an RPC server.
[2017-04-20 00:16:50 +0000] Cannot be executed while running as an RPC server.
[Arachni::RPC::Exceptions::ConnectionError] Connection closed [Connection refused - connect(2) for 127.0.0.1:49423]
```

**Comment by Zapotek** [comment]
What plugins have you enabled?

**Comment by bossadvisors** [comment]
autologin, discovery, exec, header's collector, health map, metrics, and uncommon headers were enabled.

**Comment by Zapotek** [comment]
You need to disable the `exec` plugin, it can't be run over RPC.

**Comment by bossadvisors** [comment]
Thank you.
