### ISSUE TITLE
[Errno::E2BIG] Argument list too long

### ISSUE THREAD

**Issue by CashWilliams** [Arachni/arachni#887]
After running arachni repeatedly, I've started to get this error.
It might have to do with the AutoLogin plugin.

Running with:
```
arachni --checks=*,-file_inclusion,-ldap_injection,-no_sql_injection*,-path_traversal,-backdoors,-backup_directories,-backup_files,-common_admin_interfaces,-common_directories,-common_files,-directory_listing,-captcha,-cvs_svn_users,-emails,-private_ip,-ssn,-localstart_asp,-webdav --plugin 'proxy:port=9595,bind_address=192.168.25.8' --plugin autologin:url=http://local.secdemo.com/user/login,parameters='name=demo&pass=demo',check='Log out' --scope-extend-paths urls.txt --scope-exclude-pattern '.*\.css' --scope-exclude-pattern '\/devel\/.*' --scope-exclude-pattern '\/sites\/.*\/files\/.*' --scope-exclude-pattern 'user\/logout' --scope-auto-redundant=10 --audit-links --audit-forms --platforms 'linux,sql,mysql,apache,php,symfony' http://local.secdemo.com
```

Error output:
```
[*] Initializing...
 [*] Preparing plugins...
 [*] AutoLogin: Logging in, please wait.
 [-] [utilities#exception_jail:428] [Errno::E2BIG] Argument list too long - /home/vagrant/arachni-1.5.1-0.5.12/system/usr/bin/ruby
 [-] [utilities#exception_jail:428] /home/vagrant/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/processes/manager.rb:209:in `spawn'
 [-] [utilities#exception_jail:428] /home/vagrant/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/processes/manager.rb:209:in `spawn'
 [-] [utilities#exception_jail:428] /home/vagrant/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/processes/manager.rb:222:in `method_missing'
 [-] [utilities#exception_jail:428] /home/vagrant/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/browser.rb:1251:in `block (2 levels) in spawn_phantomjs'
 [-] [utilities#exception_jail:428] /home/vagrant/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/browser.rb:1195:in `call'
 [-] [utilities#exception_jail:428] /home/vagrant/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/browser.rb:1195:in `block in with_timeout'
 [-] [utilities#exception_jail:428] /home/vagrant/arachni-1.5.1-0.5.12/system/usr/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
 [-] [utilities#exception_jail:428] /home/vagrant/arachni-1.5.1-0.5.12/system/usr/lib/ruby/2.2.0/timeout.rb:32:in `block in catch'
 [-] [utilities#exception_jail:428] /home/vagrant/arachni-1.5.1-0.5.12/system/usr/lib/ruby/2.2.0/timeout.rb:32:in `catch'
 [-] [utilities#exception_jail:428] /home/vagrant/arachni-1.5.1-0.5.12/system/usr/lib/ruby/2.2.0/timeout.rb:32:in `catch'
 [-] [utilities#exception_jail:428] /home/vagrant/arachni-1.5.1-0.5.12/system/usr/lib/ruby/2.2.0/timeout.rb:103:in `timeout'
 [-] [utilities#exception_jail:428] /home/vagrant/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/browser.rb:1194:in `with_timeout'
 [-] [utilities#exception_jail:428] /home/vagrant/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/browser.rb:1245:in `block in spawn_phantomjs'
 [-] [utilities#exception_jail:428] /home/vagrant/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/browser.rb:1234:in `times'
 [-] [utilities#exception_jail:428] /home/vagrant/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/browser.rb:1234:in `spawn_phantomjs'
 [-] [utilities#exception_jail:428] /home/vagrant/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/browser.rb:1217:in `spawn_browser'
 [-] [utilities#exception_jail:428] /home/vagrant/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/browser.rb:1114:in `selenium'
 [-] [utilities#exception_jail:428] /home/vagrant/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/browser.rb:1337:in `start_webdriver'
 [-] [utilities#exception_jail:428] /home/vagrant/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/browser.rb:187:in `initialize'
 [-] [utilities#exception_jail:428] /home/vagrant/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/session.rb:443:in `new'
 [-] [utilities#exception_jail:428] /home/vagrant/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/session.rb:443:in `refresh_browser'
 [-] [utilities#exception_jail:428] /home/vagrant/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/session.rb:241:in `login'
 [-] [utilities#exception_jail:428] /home/vagrant/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/components/plugins/autologin.rb:37:in `prepare'
 [-] [utilities#exception_jail:428] /home/vagrant/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/plugin/manager.rb:69:in `block (2 levels) in run'
 [-] [utilities#exception_jail:428] /home/vagrant/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/utilities.rb:425:in `call'
 [-] [utilities#exception_jail:428] /home/vagrant/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/utilities.rb:425:in `exception_jail'
 [-] [utilities#exception_jail:428] /home/vagrant/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/plugin/manager.rb:68:in `block in run'
 [-] [utilities#exception_jail:428] /home/vagrant/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/plugin/manager.rb:65:in `each'
 [-] [utilities#exception_jail:428] /home/vagrant/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/plugin/manager.rb:65:in `run'
 [-] [utilities#exception_jail:428] /home/vagrant/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/framework/parts/state.rb:348:in `prepare'
 [-] [utilities#exception_jail:428] /home/vagrant/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/framework.rb:110:in `run'
 [-] [utilities#exception_jail:428] /home/vagrant/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/ui/cli/framework.rb:80:in `block in run'
 [-] [utilities#exception_jail:429]
 [-] [utilities#exception_jail:430] Parent:
 [-] [utilities#exception_jail:431] Arachni::Plugin::Manager
 [-] [utilities#exception_jail:432]
 [-] [utilities#exception_jail:433] Block:
 [-] [utilities#exception_jail:434] #<Proc:0x0000000499db68@/home/vagrant/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/plugin/manager.rb:68>
 [-] [utilities#exception_jail:435]
 [-] [utilities#exception_jail:436] Caller:
 [-] [utilities#exception_jail:437] /home/vagrant/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/utilities.rb:425:in `exception_jail'
 [-] [utilities#exception_jail:437] /home/vagrant/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/plugin/manager.rb:68:in `block in run'
 [-] [utilities#exception_jail:437] /home/vagrant/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/plugin/manager.rb:65:in `each'
 [-] [utilities#exception_jail:437] /home/vagrant/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/plugin/manager.rb:65:in `run'
 [-] [utilities#exception_jail:437] /home/vagrant/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/framework/parts/state.rb:348:in `prepare'
 [-] [utilities#exception_jail:437] /home/vagrant/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/framework.rb:110:in `run'
 [-] [utilities#exception_jail:437] /home/vagrant/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/ui/cli/framework.rb:80:in `block in run'
 [-] [utilities#exception_jail:438] --------------------------------------------------------------------------------
```

**Comment by Zapotek** [comment]
The error says it all, the argument list is too long, instead of disabling checks try enabling the ones you want, that should shorten the argument list.
Or, since you've excluded all passive checks, use `-passive/*` instead of excluding them one at a time.

**Comment by CashWilliams** [comment]
I found the problem just now as I was removing arguments one by one trying to find out what is too long.

`--scope-extend-paths urls.txt` - I'd re-generated urls.txt and now see that it is 1700 lines long. Looks like there is a limit on the number that can be brought in via this method.

**Comment by Zapotek** [comment]
I've misunderstood the situation, it was not argument list for arachni, it was an argument list arachni was using to spawn a helper process and the size of the `urls.txt` would indeed affect it.

I'm re-opening the issue and will sort it out.

**Comment by CashWilliams** [comment]
Thanks for the quick response! I'll test this soon.
(My backup plan was to loop through the file with wget via the proxy, which I'd rather not do)

**Comment by Zapotek** [comment]
I'll let you know once the nightlies are up so that you can test it.

**Comment by Zapotek** [comment]
Nightlies are up.
