### ISSUE TITLE
Proxy through and error

### ISSUE THREAD

**Issue by bgerardw** [Arachni/arachni#888]
I had configured the proxy for login and the login check passed.

> This is the deduced login form:
> 
> Found in: https://signup.leagueoflegends.co.kr/Member/Login.php?retUrl2=HTTPS://signup.leagueoflegends.co.kr/Customer/requestlist.php
> Action: https://signup.leagueoflegends.co.kr/Member/login_proc.php (method POST)
> 
>     "recaptcha_challenge_field" = "03AIezHSYg72-UWaRFahuk1rckwNN8U0wEhiTAYOPwHneNo6keZ0G7fZZucWAqbJJBgv8LwzhP1adbdiOr9dimfXY5dyyaphmdn9MU8zBJh4jswxblnP9QNoXAmM4qLzqLTDJOqcAO_PQsxdFRn0g1-jawz205FLLJFSc4brnAuHv0KuKX9LGj5q10caHaYy_2q9yExCBDUAlY"
>     "ret" = "/"
>     "ret2" = "HTTPS://signup.leagueoflegends.co.kr/Member/mypage01.php"
>     "isCaptcha" = "1"
>     "userID" = "user"
>     "userPW" = "password"
>     "recaptcha_response_field" = "5219 Public"

However, as it started its scan it threw this error.
``` 

2017-05-19 12:21:33 +0100 --------------------------------------------------------------------------------
ENV:
---
CPLUS_INCLUDE_PATH: "/home/brian/arachni-2.0dev-1.0dev/bin/../system/usr/include"
XDG_VTNR: '7'
NVM_RC_VERSION: ''
XDG_SESSION_ID: c2
NVM_IOJS_ORG_VERSION_LISTING: https://iojs.org/dist/index.tab
CLUTTER_IM_MODULE: xim
XDG_GREETER_DATA_DIR: "/var/lib/lightdm-data/brian"
rvm_bin_path: "/home/brian/.rvm/bin"
SESSION: ubuntu
GPG_AGENT_INFO: "/home/brian/.gnupg/S.gpg-agent:0:1"
GEM_HOME: "/home/brian/arachni-2.0dev-1.0dev/system/gems"
SHELL: "/bin/bash"
XDG_MENU_PREFIX: gnome-
VTE_VERSION: '4205'
TERM: xterm-256color
DERBY_HOME: "/usr/lib/jvm/java-8-oracle/db"
IRBRC: "/home/brian/arachni-2.0dev-1.0dev/bin/../system/usr/lib/ruby/.irbrc"
LIBRARY_PATH: "/home/brian/arachni-2.0dev-1.0dev/bin/../system/usr/lib:/usr/lib:/usr/local/lib"
QT_LINUX_ACCESSIBILITY_ALWAYS_ON: '1'
WINDOWID: '67108874'
GNOME_KEYRING_CONTROL: ''
UPSTART_SESSION: unix:abstract=/com/ubuntu/upstart-session/1000/2546
MY_RUBY_HOME: "/home/brian/arachni-2.0dev-1.0dev/bin/../system/usr/lib/ruby"
GTK_MODULES: gail:atk-bridge:unity-gtk-module
USER: brian
NVM_DIR: "/home/brian/.nvm"
LD_LIBRARY_PATH: "/home/brian/arachni-2.0dev-1.0dev/bin/../system/usr/lib:/usr/lib:/usr/local/lib"
QT_ACCESSIBILITY: '1'
LS_COLORS: 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
_system_type: Linux
XDG_SESSION_PATH: "/org/freedesktop/DisplayManager/Session0"
XDG_SEAT_PATH: "/org/freedesktop/DisplayManager/Seat0"
rvm_path: "/home/brian/.rvm"
SSH_AUTH_SOCK: "/run/user/1000/keyring/ssh"
DEFAULTS_PATH: "/usr/share/gconf/ubuntu.default.path"
SESSION_MANAGER: local/cluemaster:@/tmp/.ICE-unix/2871,unix/cluemaster:/tmp/.ICE-unix/2871
XDG_CONFIG_DIRS: "/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg"
rvm_prefix: "/home/brian"
FONTCONFIG_PATH: "/home/brian/arachni-2.0dev-1.0dev/bin/../system/home/arachni/.fonts"
PATH: "/home/brian/arachni-2.0dev-1.0dev/system/gems/bin:/home/brian/arachni-2.0dev-1.0dev/bin/../system/../bin:/home/brian/arachni-2.0dev-1.0dev/bin/../system/usr/bin:/home/brian/arachni-2.0dev-1.0dev/bin/../system/gems/bin:/home/brian/.rvm/gems/ruby-2.2.0/bin:/home/brian/.rvm/gems/ruby-2.2.0@global/bin:/home/brian/.rvm/rubies/ruby-2.2.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/brian/.rvm/bin"
DESKTOP_SESSION: ubuntu
QT_QPA_PLATFORMTHEME: appmenu-qt5
QT_IM_MODULE: ibus
C_INCLUDE_PATH: "/home/brian/arachni-2.0dev-1.0dev/bin/../system/usr/include"
NVM_NODEJS_ORG_MIRROR: https://nodejs.org/dist
JOB: unity-settings-daemon
PWD: "/home/brian/arachni-2.0dev-1.0dev/bin"
XDG_SESSION_TYPE: x11
JAVA_HOME: "/usr/lib/jvm/java-8-oracle"
XMODIFIERS: "@im=ibus"
ARACHNI_WEBUI_LOGDIR: "/home/brian/arachni-2.0dev-1.0dev/bin/../system/logs/webui"
LANG: en_IE.UTF-8
GNOME_KEYRING_PID: ''
MANDATORY_PATH: "/usr/share/gconf/ubuntu.mandatory.path"
GDM_LANG: en_US
NODE_PATH: "/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript"
ARACHNI_FRAMEWORK_LOGDIR: "/home/brian/arachni-2.0dev-1.0dev/bin/../system/logs/framework"
IM_CONFIG_PHASE: '1'
COMPIZ_CONFIG_PROFILE: ubuntu
_system_arch: x86_64
_system_version: '16.04'
GDMSESSION: ubuntu
GTK2_MODULES: overlay-scrollbar
SESSIONTYPE: gnome-session
rvm_version: 1.27.0 (latest)
XDG_SEAT: seat0
HOME: "/home/brian/arachni-2.0dev-1.0dev/bin/../system/home/arachni"
SHLVL: '1'
LANGUAGE: en_IE:en
RAILS_ENV: production
GNOME_DESKTOP_SESSION_ID: this-is-deprecated
UPSTART_INSTANCE: ''
LOGNAME: brian
XDG_SESSION_DESKTOP: ubuntu
UPSTART_EVENTS: xsession started
COMPIZ_BIN_PATH: "/usr/bin/"
QT4_IM_MODULE: xim
XDG_DATA_DIRS: "/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop"
J2SDKDIR: "/usr/lib/jvm/java-8-oracle"
DBUS_SESSION_BUS_ADDRESS: unix:abstract=/tmp/dbus-35SzVL7KPE
GEM_PATH: "/home/brian/arachni-2.0dev-1.0dev/bin/../system/gems"
LESSOPEN: "| /usr/bin/lesspipe %s"
NVM_IOJS_ORG_MIRROR: https://iojs.org/dist
UPSTART_JOB: unity7
INSTANCE: ''
DISPLAY: ":0"
XDG_RUNTIME_DIR: "/run/user/1000"
J2REDIR: "/usr/lib/jvm/java-8-oracle/jre"
GTK_IM_MODULE: ibus
XDG_CURRENT_DESKTOP: Unity
RUBYLIB: "/home/brian/arachni-2.0dev-1.0dev/system/gems/gems/bundler-1.14.6/lib:/home/brian/arachni-2.0dev-1.0dev/bin/../system/usr/lib/ruby:/home/brian/arachni-2.0dev-1.0dev/bin/../system/usr/lib/ruby/site_ruby/2.2.0:/home/brian/arachni-2.0dev-1.0dev/bin/../system/usr/lib/ruby/2.2.0:/home/brian/arachni-2.0dev-1.0dev/bin/../system/usr/lib/ruby/2.2.0/x86_64-linux:/home/brian/arachni-2.0dev-1.0dev/bin/../system/usr/lib/ruby/site_ruby/2.2.0/x86_64-linux"
LESSCLOSE: "/usr/bin/lesspipe %s %s"
RUBY_VERSION: ruby-2.2.3
_system_name: Ubuntu
XAUTHORITY: "/home/brian/.Xauthority"
BUNDLE_GEMFILE: "/home/brian/arachni-2.0dev-1.0dev/system/arachni-ui-web/Gemfile"
BUNDLER_ORIG_PATH: "/home/brian/arachni-2.0dev-1.0dev/bin/../system/../bin:/home/brian/arachni-2.0dev-1.0dev/bin/../system/usr/bin:/home/brian/arachni-2.0dev-1.0dev/bin/../system/gems/bin:/home/brian/.rvm/gems/ruby-2.2.0/bin:/home/brian/.rvm/gems/ruby-2.2.0@global/bin:/home/brian/.rvm/rubies/ruby-2.2.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/brian/.rvm/bin:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/brian/.rvm/bin:/home/brian/.rvm/bin"
BUNDLER_ORIG_GEM_PATH: "/home/brian/arachni-2.0dev-1.0dev/bin/../system/gems"
BUNDLE_BIN_PATH: "/home/brian/arachni-2.0dev-1.0dev/system/gems/gems/bundler-1.14.6/exe/bundle"
BUNDLER_VERSION: 1.14.6
RUBYOPT: "-rbundler/setup"
MANPATH: "/home/brian/arachni-2.0dev-1.0dev/system/gems/gems/kramdown-1.4.1/man"
--------------------------------------------------------------------------------
OPTIONS:
---
scope:
  redundant_path_patterns: {}
  dom_depth_limit: 5
  exclude_file_extensions: []
  exclude_path_patterns: []
  exclude_content_patterns: []
  include_path_patterns: []
  restrict_paths: []
  extend_paths: []
  url_rewrites: {}
browser_cluster:
  local_storage: {}
  wait_for_elements: {}
  pool_size: 6
  job_timeout: 10
  worker_time_to_live: 100
  ignore_images: false
  screen_width: 1600
  screen_height: 1200
datastore:
  report_path: 
input:
  values: {}
  default_values:
    name: arachni_name
    user: arachni_user
    usr: arachni_user
    pass: 5543!%arachni_secret
    txt: arachni_text
    num: '132'
    amount: '100'
    mail: arachni@email.gr
    account: '12'
    id: '1'
  without_defaults: false
  force: false
session:
  check_url: https://signup.leagueoflegends.co.kr
  check_pattern: "(?-mix:username)"
http:
  user_agent: Arachni/v2.0dev
  request_timeout: 10000
  request_redirect_limit: 5
  request_concurrency: 20
  request_queue_size: 100
  request_headers: {}
  response_max_size: 500000
  cookies: {}
  authentication_type: auto
audit:
  parameter_values: true
  exclude_vector_patterns: []
  include_vector_patterns: []
  link_templates: []
  links: true
  forms: true
  cookies: true
  ui_inputs: true
  ui_forms: true
  jsons: true
  xmls: true
checks:
- insecure_cross_domain_policy_access
- common_admin_interfaces
- http_put
- backup_files
- origin_spoof_access_restriction_bypass
- backdoors
- common_files
- password_autocomplete
- credit_card
- mixed_resource
- ssn
- html_objects
- cvs_svn_users
- form_upload
- http_only_cookies
- cookie_set_for_parent_domain
- insecure_cookies
- hsts
- unencrypted_password_forms
- captcha
- x_frame_options
- emails
- private_ip
- insecure_cors_policy
- insecure_client_access_policy
- insecure_cross_domain_policy_headers
- directory_listing
- common_directories
- backup_directories
- htaccess_limit
- webdav
- allowed_methods
- xst
- localstart_asp
- interesting_responses
- sql_injection_differential
- ldap_injection
- no_sql_injection_differential
- path_traversal
- xss_dom
- session_fixation
- xss_path
- unvalidated_redirect_dom
- file_inclusion
- xss_tag
- xss_script_context
- unvalidated_redirect
- xxe
- xss
- source_code_disclosure
- os_cmd_injection
- csrf
- rfi
- xss_event
- code_injection
- xss_dom_script_context
- code_injection_php_input_wrapper
- trainer
- sql_injection
- response_splitting
- sql_injection_timing
- no_sql_injection
- xpath_injection
- os_cmd_injection_timing
- code_injection_timing
platforms: []
plugins:
  proxy: {}
  rate_limiter:
    requests_per_second: '5'
no_fingerprinting: false
authorized_by: 
url: https://signup.leagueoflegends.co.kr/
--------------------------------------------------------------------------------
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] [EOFError] end of file reached
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/net/protocol.rb:153:in `read_nonblock'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/net/protocol.rb:153:in `rbuf_fill'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/net/protocol.rb:134:in `readuntil'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/net/protocol.rb:144:in `readline'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/net/http/response.rb:39:in `read_status_line'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/net/http/response.rb:28:in `read_new'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/net/http.rb:1414:in `block in transport_request'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/net/http.rb:1411:in `catch'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/net/http.rb:1411:in `transport_request'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/net/http.rb:1384:in `request'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/net/http.rb:1377:in `block in request'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/net/http.rb:853:in `start'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/net/http.rb:1375:in `request'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/gems/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/default.rb:103:in `response_for'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/gems/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/default.rb:57:in `request'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/gems/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/gems/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/bridge.rb:653:in `raw_execute'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/gems/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/bridge.rb:631:in `execute'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/gems/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/bridge.rb:136:in `get'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/gems/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/common/navigation.rb:32:in `to'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bd8871de010a/lib/arachni/browser.rb:334:in `block in goto'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bd8871de010a/lib/arachni/page/dom/transition.rb:151:in `call'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bd8871de010a/lib/arachni/page/dom/transition.rb:151:in `start'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bd8871de010a/lib/arachni/page/dom/transition.rb:106:in `initialize'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bd8871de010a/lib/arachni/browser.rb:329:in `new'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bd8871de010a/lib/arachni/browser.rb:329:in `goto'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bd8871de010a/lib/arachni/browser.rb:250:in `load'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bd8871de010a/lib/arachni/session.rb:339:in `login_from_configuration'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bd8871de010a/lib/arachni/session.rb:245:in `block in login'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bd8871de010a/lib/arachni/utilities.rb:425:in `call'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bd8871de010a/lib/arachni/utilities.rb:425:in `exception_jail'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bd8871de010a/lib/arachni/session.rb:244:in `login'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bd8871de010a/components/plugins/proxy.rb:260:in `block in request_handler'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bd8871de010a/lib/arachni/http/client.rb:263:in `call'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bd8871de010a/lib/arachni/http/client.rb:263:in `sandbox'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bd8871de010a/components/plugins/proxy.rb:258:in `request_handler'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bd8871de010a/lib/arachni/http/proxy_server/connection.rb:140:in `call'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bd8871de010a/lib/arachni/http/proxy_server/connection.rb:140:in `handle_request'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:428] /home/brian/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bd8871de010a/lib/arachni/http/proxy_server/connection.rb:91:in `block (3 levels) in initialize'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:429] 
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:430] Parent:
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:431] Arachni::Session
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:432] 
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:433] Block:
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:434] #<Proc:0x00000003dc0e80@/home/brian/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bd8871de010a/lib/arachni/session.rb:244>
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:435] 
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:436] Caller:
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:437] /home/brian/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bd8871de010a/lib/arachni/utilities.rb:425:in `exception_jail'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:437] /home/brian/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bd8871de010a/lib/arachni/session.rb:244:in `login'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:437] /home/brian/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bd8871de010a/components/plugins/proxy.rb:260:in `block in request_handler'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:437] /home/brian/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bd8871de010a/lib/arachni/http/client.rb:263:in `call'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:437] /home/brian/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bd8871de010a/lib/arachni/http/client.rb:263:in `sandbox'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:437] /home/brian/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bd8871de010a/components/plugins/proxy.rb:258:in `request_handler'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:437] /home/brian/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bd8871de010a/lib/arachni/http/proxy_server/connection.rb:140:in `call'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:437] /home/brian/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bd8871de010a/lib/arachni/http/proxy_server/connection.rb:140:in `handle_request'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:437] /home/brian/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-bd8871de010a/lib/arachni/http/proxy_server/connection.rb:91:in `block (3 levels) in initialize'
[2017-05-19 12:21:33 +0100] Session: [utilities#exception_jail:438] --------------------------------------------------------------------------------
```

**Comment by Zapotek** [comment]
Are you using any sort of utility that would proxy/tunnel Arachni's requests?

**Comment by bgerardw** [comment]
None

**Comment by Zapotek** [comment]
Is this consistently reproducible or intermittent?

**Comment by bgerardw** [comment]
I have seen twice or three times on this site only. I have not run much against this site.

**Comment by Zapotek** [comment]
Can you retry without the `rate_limiter` plugin please?

**Comment by bgerardw** [comment]
Sorry never got to reply to this. I need to limit the connections on this site in case I get blacklisted.

**Comment by Zapotek** [comment]
No worries.
