### ISSUE TITLE
Error or just ignore

### ISSUE THREAD

**Issue by bgerardw** [Arachni/arachni#897]
I got the following error but the scan is still running, Should I just Ignore it

```
[2017-06-27 14:49:53 +0100] Error while processing job: #<Arachni::BrowserCluster::Jobs::TaintTrace::EventTrigger:70336096265620 @resource=#<Arachni::Page::DOM:70335894589140 @url="blah" @transitions=33 @data_flow_sinks=0 @execution_flow_sinks=0> @event=:mouseup @element=<form name="logonForm" method="post" action="blah"> @forwarder=#<Arachni::BrowserCluster::Jobs::TaintTrace:70336096265820 @resource= @taint="window.top._%s_taint_tracer.log_execution_flow_sink()" @injector=nil time= timed_out=false> time= timed_out=false>
```

a previous scan threw this

```
[2017-06-27 12:10:23 +0100] Error while processing job: #<Arachni::BrowserCluster::Jobs::DOMExploration::EventTrigger:69885292745800 @resource=#<Arachni::Page::DOM:69885191281280 @url="blah @transitions=2 @data_flow_sinks=0 @execution_flow_sinks=0> @event=:mouseup @element=<form name="logonForm" method="post" action="blah"> time= timed_out=false>
> [2017-06-27 12:10:23 +0100] [EOFError] end of file reached
```

**Comment by Zapotek** [comment]
You can generally ignore these errors, they're like HTTP time-outs, they happen sometimes.
Seeing the backtrace would help determine what's going on though.

**Comment by bgerardw** [comment]
I trigger another, here is the back trace.

```--------------------------------------------------------------------------------
[2017-06-27 16:48:37 +0100] Error while processing job: #<Arachni::BrowserCluster::Jobs::DOMExploration::EventTrigger:42527820 @resource=#<Arachni::Page::DOM:42137400 @url="https://pre-prod.ff-etrans-dev/ole/" @transitions=9 @data_flow_sinks=0 @execution_flow_sinks=0> @event=:mouseup @element=<a href="/ole/home.do"> time= timed_out=false>
[2017-06-27 16:48:37 +0100] [EOFError] end of file reached
[2017-06-27 16:48:37 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/net/protocol.rb:153:in `read_nonblock'
[2017-06-27 16:48:37 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/net/protocol.rb:153:in `rbuf_fill'
[2017-06-27 16:48:37 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/net/protocol.rb:134:in `readuntil'
[2017-06-27 16:48:37 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/net/protocol.rb:144:in `readline'
[2017-06-27 16:48:37 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/net/http/response.rb:39:in `read_status_line'
[2017-06-27 16:48:37 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/net/http/response.rb:28:in `read_new'
[2017-06-27 16:48:37 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/net/http.rb:1414:in `block in transport_request'
[2017-06-27 16:48:37 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/net/http.rb:1411:in `catch'
[2017-06-27 16:48:37 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/net/http.rb:1411:in `transport_request'
[2017-06-27 16:48:37 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/net/http.rb:1384:in `request'
[2017-06-27 16:48:37 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/net/http.rb:1377:in `block in request'
[2017-06-27 16:48:37 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/net/http.rb:853:in `start'
[2017-06-27 16:48:37 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/net/http.rb:1375:in `request'
[2017-06-27 16:48:37 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/gems/selenium-webdriver-3.4.3/lib/selenium/webdriver/remote/http/default.rb:124:in `response_for'
[2017-06-27 16:48:37 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/gems/selenium-webdriver-3.4.3/lib/selenium/webdriver/remote/http/default.rb:78:in `request'
[2017-06-27 16:48:37 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/gems/selenium-webdriver-3.4.3/lib/selenium/webdriver/remote/http/common.rb:61:in `call'
[2017-06-27 16:48:37 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/gems/selenium-webdriver-3.4.3/lib/selenium/webdriver/remote/bridge.rb:170:in `execute'
[2017-06-27 16:48:37 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/gems/selenium-webdriver-3.4.3/lib/selenium/webdriver/remote/oss/bridge.rb:579:in `execute'
[2017-06-27 16:48:37 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/gems/selenium-webdriver-3.4.3/lib/selenium/webdriver/remote/oss/bridge.rb:52:in `get'
[2017-06-27 16:48:37 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/gems/selenium-webdriver-3.4.3/lib/selenium/webdriver/common/navigation.rb:32:in `to'
[2017-06-27 16:48:37 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-e9fa33dc6afb/lib/arachni/browser.rb:353:in `block in goto'
[2017-06-27 16:48:37 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-e9fa33dc6afb/lib/arachni/page/dom/transition.rb:151:in `call'
[2017-06-27 16:48:37 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-e9fa33dc6afb/lib/arachni/page/dom/transition.rb:151:in `start'
[2017-06-27 16:48:37 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-e9fa33dc6afb/lib/arachni/page/dom/transition.rb:106:in `initialize'
[2017-06-27 16:48:37 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-e9fa33dc6afb/lib/arachni/browser.rb:348:in `new'
[2017-06-27 16:48:37 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-e9fa33dc6afb/lib/arachni/browser.rb:348:in `goto'
[2017-06-27 16:48:37 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-e9fa33dc6afb/lib/arachni/page/dom.rb:146:in `restore'
[2017-06-27 16:48:37 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-e9fa33dc6afb/lib/arachni/browser.rb:285:in `load'
[2017-06-27 16:48:37 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-e9fa33dc6afb/lib/arachni/browser_cluster/jobs/dom_exploration/event_trigger.rb:34:in `run'
[2017-06-27 16:48:37 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-e9fa33dc6afb/lib/arachni/browser_cluster/job.rb:109:in `configure_and_run'
[2017-06-27 16:48:37 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-e9fa33dc6afb/lib/arachni/browser_cluster/worker.rb:80:in `run_job'
[2017-06-27 16:48:37 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-e9fa33dc6afb/lib/arachni/browser_cluster/worker.rb:244:in `block in start'
[2017-06-27 16:49:22 +0100] Error while processing job: #<Arachni::BrowserCluster::Jobs::TaintTrace:42860740 @resource=HTTP/1.1 200 OK
Date: Tue, 27 Jun 2017 15:47:57 GMT



[2017-06-27 16:49:22 +0100] [Errno::ECONNREFUSED] Connection refused - connect(2) for "127.0.0.1" port 30867
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/net/http.rb:879:in `initialize'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/net/http.rb:879:in `open'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/timeout.rb:98:in `call'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/timeout.rb:98:in `timeout'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/net/http.rb:878:in `connect'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/net/http.rb:1453:in `begin_transport'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/net/http.rb:1410:in `transport_request'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/net/http.rb:1384:in `request'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/net/http.rb:1377:in `block in request'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/net/http.rb:853:in `start'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/net/http.rb:1375:in `request'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/gems/selenium-webdriver-3.4.3/lib/selenium/webdriver/remote/http/default.rb:124:in `response_for'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/gems/selenium-webdriver-3.4.3/lib/selenium/webdriver/remote/http/default.rb:78:in `request'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/gems/selenium-webdriver-3.4.3/lib/selenium/webdriver/remote/http/common.rb:61:in `call'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/gems/selenium-webdriver-3.4.3/lib/selenium/webdriver/remote/bridge.rb:170:in `execute'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/gems/selenium-webdriver-3.4.3/lib/selenium/webdriver/remote/oss/bridge.rb:579:in `execute'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/gems/selenium-webdriver-3.4.3/lib/selenium/webdriver/remote/oss/bridge.rb:108:in `url'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/gems/selenium-webdriver-3.4.3/lib/selenium/webdriver/common/driver.rb:140:in `current_url'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-e9fa33dc6afb/lib/arachni/browser.rb:432:in `dom_url'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-e9fa33dc6afb/lib/arachni/browser.rb:1083:in `response'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-e9fa33dc6afb/lib/arachni/browser/javascript.rb:119:in `supported?'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-e9fa33dc6afb/lib/arachni/browser/javascript.rb:302:in `timeouts'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-e9fa33dc6afb/lib/arachni/browser.rb:1063:in `load_delay'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-e9fa33dc6afb/lib/arachni/browser.rb:1067:in `wait_for_timers'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-e9fa33dc6afb/lib/arachni/browser.rb:392:in `wait_till_ready'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-e9fa33dc6afb/lib/arachni/browser.rb:356:in `block in goto'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-e9fa33dc6afb/lib/arachni/page/dom/transition.rb:151:in `call'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-e9fa33dc6afb/lib/arachni/page/dom/transition.rb:151:in `start'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-e9fa33dc6afb/lib/arachni/page/dom/transition.rb:106:in `initialize'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-e9fa33dc6afb/lib/arachni/browser.rb:348:in `new'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-e9fa33dc6afb/lib/arachni/browser.rb:348:in `goto'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-e9fa33dc6afb/lib/arachni/browser.rb:273:in `load'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-e9fa33dc6afb/lib/arachni/browser_cluster/jobs/dom_exploration.rb:35:in `run'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-e9fa33dc6afb/lib/arachni/browser_cluster/jobs/taint_trace.rb:41:in `run'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-e9fa33dc6afb/lib/arachni/browser_cluster/job.rb:109:in `configure_and_run'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-e9fa33dc6afb/lib/arachni/browser_cluster/worker.rb:80:in `run_job'
[2017-06-27 16:49:22 +0100] /home/brian/shelob/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-e9fa33dc6afb/lib/arachni/browser_cluster/worker.rb:244:in `block in start'
```

**Comment by Zapotek** [comment]
Looks like one or more browsers crashed, it's not a problem as they'll get respawned as necessary.
Unless you're noticing any troublesome behavior there's no need to worry about it.

**Comment by bgerardw** [comment]
I did not notice any problem. Just wanted to flag it so you had a record of it.
