### ISSUE TITLE
Still  [ArgumentError] invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by oscommonjs** [Arachni/arachni#907]
```
[2017-08-05 08:30:18 +0800] [ArgumentError] invalid byte sequence in UTF-8
[2017-08-05 08:30:18 +0800] C:/Users/Administrator/Desktop/arachni/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/parser/nodes/with_value.rb:22:in `strip'
[2017-08-05 08:30:18 +0800] C:/Users/Administrator/Desktop/arachni/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/parser/nodes/with_value.rb:22:in `value='
[2017-08-05 08:30:18 +0800] C:/Users/Administrator/Desktop/arachni/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/parser/nodes/with_value.rb:18:in `initialize'
[2017-08-05 08:30:18 +0800] C:/Users/Administrator/Desktop/arachni/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/parser/sax.rb:58:in `new'
[2017-08-05 08:30:18 +0800] C:/Users/Administrator/Desktop/arachni/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/parser/sax.rb:58:in `text'
[2017-08-05 08:30:18 +0800] C:/Users/Administrator/Desktop/arachni/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/parser.rb:70:in `sax_html'
[2017-08-05 08:30:18 +0800] C:/Users/Administrator/Desktop/arachni/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/parser.rb:70:in `block in parse'
[2017-08-05 08:30:18 +0800] C:/Users/Administrator/Desktop/arachni/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/support/cache/base.rb:108:in `call'
[2017-08-05 08:30:18 +0800] C:/Users/Administrator/Desktop/arachni/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/support/cache/base.rb:108:in `fetch'
[2017-08-05 08:30:18 +0800] C:/Users/Administrator/Desktop/arachni/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/parser.rb:66:in `parse'
[2017-08-05 08:30:18 +0800] C:/Users/Administrator/Desktop/arachni/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/parser.rb:243:in `document'
[2017-08-05 08:30:18 +0800] C:/Users/Administrator/Desktop/arachni/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/parser.rb:423:in `paths'
[2017-08-05 08:30:18 +0800] C:/Users/Administrator/Desktop/arachni/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/page.rb:310:in `paths'
[2017-08-05 08:30:18 +0800] C:/Users/Administrator/Desktop/arachni/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/framework/parts/data.rb:207:in `push_paths_from_page'
[2017-08-05 08:30:18 +0800] C:/Users/Administrator/Desktop/arachni/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/framework/parts/audit.rb:98:in `audit_page'
[2017-08-05 08:30:18 +0800] C:/Users/Administrator/Desktop/arachni/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/framework/parts/audit.rb:228:in `audit_queues'
[2017-08-05 08:30:18 +0800] C:/Users/Administrator/Desktop/arachni/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/rpc/server/framework/multi_instance.rb:222:in `audit_queues'
[2017-08-05 08:30:18 +0800] C:/Users/Administrator/Desktop/arachni/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/framework/parts/audit.rb:202:in `block in audit'
[2017-08-05 08:30:18 +0800] C:/Users/Administrator/Desktop/arachni/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/framework/parts/audit.rb:177:in `loop'
[2017-08-05 08:30:18 +0800] C:/Users/Administrator/Desktop/arachni/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/framework/parts/audit.rb:177:in `audit'
[2017-08-05 08:30:18 +0800] C:/Users/Administrator/Desktop/arachni/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/framework.rb:117:in `block in run'
[2017-08-05 08:30:18 +0800] C:/Users/Administrator/Desktop/arachni/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/utilities.rb:425:in `call'
[2017-08-05 08:30:18 +0800] C:/Users/Administrator/Desktop/arachni/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/utilities.rb:425:in `exception_jail'
[2017-08-05 08:30:18 +0800] C:/Users/Administrator/Desktop/arachni/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/framework.rb:117:in `run'
[2017-08-05 08:30:18 +0800] C:/Users/Administrator/Desktop/arachni/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/rpc/server/framework.rb:156:in `block in run'
[2017-08-05 08:30:18 +0800] 
[2017-08-05 08:30:18 +0800] Parent:
[2017-08-05 08:30:18 +0800] Arachni::RPC::Server::Framework
[2017-08-05 08:30:18 +0800] 
[2017-08-05 08:30:18 +0800] Block:
[2017-08-05 08:30:18 +0800] #<Proc:0x00000009fef4d0@C:/Users/Administrator/Desktop/arachni/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/framework.rb:117>
[2017-08-05 08:30:18 +0800] 
[2017-08-05 08:30:18 +0800] Caller:
[2017-08-05 08:30:18 +0800] C:/Users/Administrator/Desktop/arachni/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/utilities.rb:425:in `exception_jail'
[2017-08-05 08:30:18 +0800] C:/Users/Administrator/Desktop/arachni/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/framework.rb:117:in `run'
[2017-08-05 08:30:18 +0800] C:/Users/Administrator/Desktop/arachni/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/rpc/server/framework.rb:156:in `block in run'
[2017-08-05 08:30:18 +0800] --------------------------------------------------------------------------------
```

**Comment by oscommonjs** [comment]
scan on site in xss mode always show this error

**Comment by Zapotek** [comment]
Any chance I can be given access to that website?

**Comment by Zapotek** [comment]
Closing due to lack of feedback, if you have a reproducible case please re-open.
