### ISSUE TITLE
error gems

### ISSUE THREAD

**Issue by l3d43r** [Arachni/arachni#908]
```
017-08-06 23:03:15 -0400 --------------------------------------------------------------------------------
ENV:
---
CPLUS_INCLUDE_PATH: "/Users/*******/Desktop/arachni-1.5.1-0.5.12/bin/../system/usr/include"
TERM_PROGRAM: Apple_Terminal
DYLD_FALLBACK_LIBRARY_PATH: "/Users/*******/Desktop/arachni-1.5.1-0.5.12/bin/../system/usr/lib:/usr/lib:/usr/local/lib"
GEM_HOME: "/Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems"
TERM: xterm-256color
SHELL: "/bin/bash"
IRBRC: "/Users/*******/Desktop/arachni-1.5.1-0.5.12/bin/../system/usr/lib/ruby/.irbrc"
TMPDIR: "/var/folders/n2/j2n2zdw968l1f25bvm_6f91h0000gn/T/"
LIBRARY_PATH: "/Users/*******/Desktop/arachni-1.5.1-0.5.12/bin/../system/usr/lib:/usr/lib:/usr/local/lib"
Apple_PubSub_Socket_Render: "/private/tmp/com.apple.launchd.QbifazPkLf/Render"
TERM_PROGRAM_VERSION: 388.1.1
MY_RUBY_HOME: "/Users/*******/Desktop/arachni-1.5.1-0.5.12/bin/../system/usr/lib/ruby"
TERM_SESSION_ID: A7298B6C-A594-452F-BCCD-964485F57689
USER: *******
LD_LIBRARY_PATH: "/Users/*******/Desktop/arachni-1.5.1-0.5.12/bin/../system/usr/lib:/usr/lib:/usr/local/lib"
MSF_DATABASE_CONFIG: "/usr/local/share/metasploit-framework/config/database.yml"
SSH_AUTH_SOCK: "/private/tmp/com.apple.launchd.wvcMYNTTNi/Listeners"
__CF_USER_TEXT_ENCODING: 0x1F5:0x0:0x52
FONTCONFIG_PATH: "/Users/*******/Desktop/arachni-1.5.1-0.5.12/bin/../system/home/arachni/.fonts"
PATH: "/Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/bin:/Users/*******/Desktop/arachni-1.5.1-0.5.12/bin/../system/../bin:/Users/*******/Desktop/arachni-1.5.1-0.5.12/bin/../system/usr/bin:/Users/*******/Desktop/arachni-1.5.1-0.5.12/bin/../system/gems/bin:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/opt/metasploit-framework/bin"
C_INCLUDE_PATH: "/Users/*******/Desktop/arachni-1.5.1-0.5.12/bin/../system/usr/include"
PWD: "/Users/*******/Desktop/arachni-1.5.1-0.5.12/bin"
ARACHNI_WEBUI_LOGDIR: "/Users/*******/Desktop/arachni-1.5.1-0.5.12/bin/../system/logs/webui"
LANG: en_CA.UTF-8
ARACHNI_FRAMEWORK_LOGDIR: "/Users/*******/Desktop/arachni-1.5.1-0.5.12/bin/../system/logs/framework"
XPC_FLAGS: '0x0'
XPC_SERVICE_NAME: '0'
HOME: "/Users/*******/Desktop/arachni-1.5.1-0.5.12/bin/../system/home/arachni"
SHLVL: '1'
RAILS_ENV: production
LOGNAME: *******
GEM_PATH: "/Users/*******/Desktop/arachni-1.5.1-0.5.12/bin/../system/gems"
DISPLAY: "/private/tmp/com.apple.launchd.auaIQ15bxD/org.macosforge.xquartz:0"
RUBYLIB: "/Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/bundler-1.14.6/lib:/Users/*******/Desktop/arachni-1.5.1-0.5.12/bin/../system/usr/lib/ruby:/Users/*******/Desktop/arachni-1.5.1-0.5.12/bin/../system/usr/lib/ruby/site_ruby/2.2.0:/Users/*******/Desktop/arachni-1.5.1-0.5.12/bin/../system/usr/lib/ruby/2.2.0:/Users/*******/Desktop/arachni-1.5.1-0.5.12/bin/../system/usr/lib/ruby/2.2.0/x86_64-darwin13:/Users/*******/Desktop/arachni-1.5.1-0.5.12/bin/../system/usr/lib/ruby/site_ruby/2.2.0/x86_64-darwin13"
RUBY_VERSION: ruby-2.2.3
RACK_ENV: development
BUNDLE_GEMFILE: "/Users/*******/Desktop/arachni-1.5.1-0.5.12/system/arachni-ui-web/Gemfile"
BUNDLER_ORIG_PATH: "/Users/*******/Desktop/arachni-1.5.1-0.5.12/bin/../system/../bin:/Users/*******/Desktop/arachni-1.5.1-0.5.12/bin/../system/usr/bin:/Users/*******/Desktop/arachni-1.5.1-0.5.12/bin/../system/gems/bin:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/opt/metasploit-framework/bin:/opt/metasploit-framework/bin"
BUNDLER_ORIG_GEM_PATH: "/Users/*******/Desktop/arachni-1.5.1-0.5.12/bin/../system/gems"
BUNDLE_BIN_PATH: "/Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/bundler-1.14.6/exe/bundle"
BUNDLER_VERSION: 1.14.6
RUBYOPT: "-rbundler/setup"
MANPATH: "/Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/kramdown-1.4.1/man"
BUNDLER_ORIG_MANPATH: "/Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/kramdown-1.4.1/man"
--------------------------------------------------------------------------------
OPTIONS:
audit:
  parameter_values: true
  exclude_vector_patterns: []
  include_vector_patterns: []
  link_templates: []
  links: true
  forms: true
  cookies: true
  jsons: true
  xmls: true
  ui_forms: true
  ui_inputs: true
browser_cluster:
  local_storage: {}
  wait_for_elements: {}
  pool_size: 6
  job_timeout: 10
  worker_time_to_live: 100
  ignore_images: false
  screen_width: 1600
  screen_height: 1200
datastore:
  token: c45bc7d8d171aa011c14905b94e2793d
http:
  user_agent: Arachni/v1.5.1
  request_timeout: 10000
  request_redirect_limit: 5
  request_concurrency: 20
  request_queue_size: 100
  request_headers: {}
  response_max_size: 500000
  cookies: {}
  authentication_type: auto
input:
  values:
    name: arachni_name
    user: arachni_user
    usr: arachni_user
    pass: 5543!%arachni_secret
    txt: arachni_text
    num: '132'
    amount: '100'
    mail: arachni@email.gr
    account: '12'
    id: '1'
  default_values:
  without_defaults: true
  force: false
scope:
  redundant_path_patterns: {}
  dom_depth_limit: 5
  exclude_file_extensions:
  - "[]"
  exclude_path_patterns: []
  exclude_content_patterns: []
  include_path_patterns: []
  restrict_paths: []
  extend_paths: []
  url_rewrites: {}
session: {}
checks:
- allowed_methods
- backdoors
- backup_directories
- backup_files
- captcha
- code_injection
- code_injection_php_input_wrapper
- code_injection_timing
- common_admin_interfaces
- common_directories
- common_files
- cookie_set_for_parent_domain
- credit_card
- csrf
- cvs_svn_users
- directory_listing
- emails
- file_inclusion
- form_upload
- hsts
- htaccess_limit
- html_objects
- http_only_cookies
- http_put
- insecure_client_access_policy
- insecure_cookies
- insecure_cors_policy
- insecure_cross_domain_policy_access
- insecure_cross_domain_policy_headers
- interesting_responses
- ldap_injection
- localstart_asp
- mixed_resource
- no_sql_injection
- no_sql_injection_differential
- origin_spoof_access_restriction_bypass
- os_cmd_injection
- os_cmd_injection_timing
- password_autocomplete
- path_traversal
- private_ip
- response_splitting
- rfi
- session_fixation
- source_code_disclosure
- sql_injection
- sql_injection_differential
- sql_injection_timing
- ssn
- trainer
- unencrypted_password_forms
- unvalidated_redirect
- unvalidated_redirect_dom
- webdav
- x_frame_options
- xpath_injection
- xss
- xss_dom
- xss_dom_script_context
- xss_event
- xss_path
- xss_script_context
- xss_tag
- xst
- xxe
platforms: []
plugins:
  autothrottle: {}
  discovery: {}
  healthmap: {}
  timing_attacks: {}
  uniformity: {}
no_fingerprinting: false
authorized_by: 
url: http://site.com/login.php
[2017-08-06 23:03:15 -0400] Could not merge plugin results for plugin 'healthmap', will only use local ones: undefined local variable or method `h' for Arachni::Plugins::HealthMap:Class
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/components/plugins/defaults/healthmap.rb:67:in `block in merge'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/components/plugins/defaults/healthmap.rb:67:in `each'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/components/plugins/defaults/healthmap.rb:67:in `sort_by'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/components/plugins/defaults/healthmap.rb:67:in `merge'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/data/plugins.rb:68:in `block in merge_results'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/data/plugins.rb:64:in `each'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/data/plugins.rb:64:in `merge_results'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/rpc/server/plugin/manager.rb:47:in `merge_results'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/rpc/server/framework.rb:203:in `block in clean_up'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:182:in `call'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:182:in `block in map'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:227:in `call'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:227:in `block in inject'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:95:in `call'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:95:in `block in each'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:119:in `call'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:119:in `block (2 levels) in each'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:213:in `call'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:213:in `block (2 levels) in inject'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:168:in `call'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:168:in `block (2 levels) in map'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/rpc/server/framework.rb:198:in `call'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/rpc/server/framework.rb:198:in `block (3 levels) in clean_up'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-rpc-0.2.1.4/lib/arachni/rpc/client/handler.rb:77:in `call'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-rpc-0.2.1.4/lib/arachni/rpc/client/handler.rb:77:in `receive_response'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-rpc-0.2.1.4/lib/arachni/rpc/client/handler.rb:137:in `receive_object'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-rpc-0.2.1.4/lib/arachni/rpc/protocol.rb:52:in `on_read'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/connection.rb:261:in `block in _read'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/connection/error.rb:26:in `call'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/connection/error.rb:26:in `translate'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/connection.rb:260:in `_read'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/connection/tls.rb:115:in `_read'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:574:in `each'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:574:in `block in process_connections'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:574:in `process_connections'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:316:in `block in run'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:307:in `loop'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:307:in `run'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/rpc/server/instance.rb:152:in `initialize'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/processes/executables/instance.rb:13:in `new'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/processes/executables/instance.rb:13:in `<top (required)>'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/processes/executables/base.rb:50:in `load'
[2017-08-06 23:03:15 -0400] /Users/*******/Desktop/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/processes/executables/base.rb:50:in `<main>'
```

**Comment by Zapotek** [comment]
The fix is in the nightlies, scan results aren't affected by this error.

Thanks for the heads up.
