### ISSUE TITLE
 Arachni ruby files Bugs:Not running 

### ISSUE THREAD

**Issue by Tikam02** [Arachni/arachni#909]
## ScreenShot:
![screenshot from 2017-08-10 20-44-15](https://user-images.githubusercontent.com/10548085/29184632-e3fefe24-7dd4-11e7-8604-97d862812a35.png)

```
[*] DATE=2017-08-10_20_29_50
[*] 
[*] [*] Running: /usr/share/arachni/bin/arachni --http-user-agent="Mozilla/5.0 (X11; Linux i686; rv:6.0) Gecko/20100101 Firefox/6.0" --http-request-concurrency=20 --report-save-path="arachni_report2017-08-10_20_29_50.afr" --http-proxy=127.0.0.1:8008 https://juice-shop.herokuapp.com/#/search
[*] /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- concurrent (LoadError)
[*] from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
[*] from /usr/share/arachni/lib/arachni.rb:11:in `<top (required)>'
[*] from /usr/share/arachni/ui/cli/framework.rb:9:in `require_relative'
[*] from /usr/share/arachni/ui/cli/framework.rb:9:in `<top (required)>'
[*] from /usr/share/arachni/bin/arachni:10:in `require_relative'
[*] from /usr/share/arachni/bin/arachni:10:in `<main>'
[*] 
[*] [*] Running: /usr/share/arachni/bin/arachni_reporter --reporter="html:outfile=arachni_report2017-08-10_20_29_50.html.zip" --reporter="txt:outfile=arachni_report2017-08-10_20_29_50.txt" --reporter="json:outfile=arachni_report2017-08-10_20_29_50.json" --reporter="ap:outfile=arachni_report2017-08-10_20_29_50.ap" --reporter="xml:outfile=arachni_report2017-08-10_20_29_50.xml" "/root/Desktop/pentest/owtf_review/targets/https__juice-shop.herokuapp.com__search/partial/Arachni_Unauthenticated/active/arachni_report2017-08-10_20_29_50.afr"
[*] /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- concurrent (LoadError)
[*] from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
[*] from /usr/share/arachni/lib/arachni.rb:11:in `<top (required)>'
[*] from /usr/share/arachni/ui/cli/reporter.rb:9:in `require_relative'
[*] from /usr/share/arachni/ui/cli/reporter.rb:9:in `<top (required)>'
[*] from /usr/share/arachni/bin/arachni_reporter:10:in `require_relative'
[*] from /usr/share/arachni/bin/arachni_reporter:10:in `<main>'
[*] unzip:  cannot find or open arachni_report2017-08-10_20_29_50.html.zip, arachni_report2017-08-10_20_29_50.html.zip.zip or arachni_report2017-08-10_20_29_50.html.zip.ZIP.
[*] [*] Removing potential binary garbage from text report ..
[*] strings: 'arachni_report2017-08-10_20_29_50.txt': No such file
```

**Comment by Zapotek** [comment]
Please use the official packages rather than working with the code and it should work fine.
