### ISSUE TITLE
Always facing this error at any website scan

### ISSUE THREAD

**Issue by hamzaijaz94** [Arachni/arachni#920]
```
2017-10-10 17:09:33 +0500 --------------------------------------------------------------------------------
ENV:
---
CPLUS_INCLUDE_PATH: "/home/hamza/arachni-1.2.1-0.5.7.1/bin/../system/usr/include"
XDG_VTNR: '7'
XDG_SESSION_ID: c2
XDG_GREETER_DATA_DIR: "/var/lib/lightdm-data/hamza.ijaz"
CLUTTER_IM_MODULE: xim
SESSION: ubuntu
GEM_HOME: "/home/hamza/arachni-1.2.1-0.5.7.1/system/gems"
GPG_AGENT_INFO: "/home/hamza/.gnupg/S.gpg-agent:0:1"
VTE_VERSION: '4205'
XDG_MENU_PREFIX: gnome-
SHELL: "/bin/bash"
TERM: xterm-256color
IRBRC: "/home/hamza/arachni-1.2.1-0.5.7.1/bin/../system/usr/lib/ruby/.irbrc"
LIBRARY_PATH: "/home/hamza/arachni-1.2.1-0.5.7.1/bin/../system/usr/lib"
QT_LINUX_ACCESSIBILITY_ALWAYS_ON: '1'
WINDOWID: '81788938'
GNOME_KEYRING_CONTROL: ''
UPSTART_SESSION: unix:abstract=/com/ubuntu/upstart-session/149000059/1603
MY_RUBY_HOME: "/home/hamza/arachni-1.2.1-0.5.7.1/bin/../system/usr/lib/ruby"
GTK_MODULES: gail:atk-bridge:unity-gtk-module
USER: hamza.ijaz
LD_LIBRARY_PATH: "/home/hamza/arachni-1.2.1-0.5.7.1/bin/../system/usr/lib"
QT_ACCESSIBILITY: '1'
LS_COLORS: 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
XDG_SESSION_PATH: "/org/freedesktop/DisplayManager/Session0"
XDG_SEAT_PATH: "/org/freedesktop/DisplayManager/Seat0"
SSH_AUTH_SOCK: "/run/user/149000059/keyring/ssh"
DEFAULTS_PATH: "/usr/share/gconf/ubuntu.default.path"
SESSION_MANAGER: local/des-0017.ebryx.local:@/tmp/.ICE-unix/1950,unix/des-0017.ebryx.local:/tmp/.ICE-unix/1950
XDG_CONFIG_DIRS: "/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg"
DESKTOP_SESSION: ubuntu
PATH: "/home/hamza/arachni-1.2.1-0.5.7.1/system/gems/bin:/home/hamza/arachni-1.2.1-0.5.7.1/bin/../system/../bin:/home/hamza/arachni-1.2.1-0.5.7.1/bin/../system/usr/bin:/home/hamza/arachni-1.2.1-0.5.7.1/bin/../system/gems/bin:/home/hamza/bin:/home/hamza/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/puppetlabs/bin"
QT_QPA_PLATFORMTHEME: appmenu-qt5
QT_IM_MODULE: ibus
C_INCLUDE_PATH: "/home/hamza/arachni-1.2.1-0.5.7.1/bin/../system/usr/include"
PWD: "/home/hamza/arachni-1.2.1-0.5.7.1/bin"
JOB: dbus
XDG_SESSION_TYPE: x11
XMODIFIERS: "@im=ibus"
ARACHNI_WEBUI_LOGDIR: "/home/hamza/arachni-1.2.1-0.5.7.1/bin/../system/logs/webui"
LANG: en_US.UTF-8
GNOME_KEYRING_PID: ''
MANDATORY_PATH: "/usr/share/gconf/ubuntu.mandatory.path"
GDM_LANG: en_US
ARACHNI_FRAMEWORK_LOGDIR: "/home/hamza/arachni-1.2.1-0.5.7.1/bin/../system/logs/framework"
COMPIZ_CONFIG_PROFILE: ubuntu
IM_CONFIG_PHASE: '1'
GDMSESSION: ubuntu
KRB5CCNAME: KEYRING:persistent:149000059
GTK2_MODULES: overlay-scrollbar
SESSIONTYPE: gnome-session
SHLVL: '1'
HOME: "/home/hamza/arachni-1.2.1-0.5.7.1/bin/../system/home/arachni"
XDG_SEAT: seat0
LANGUAGE: en_US
RAILS_ENV: production
GNOME_DESKTOP_SESSION_ID: this-is-deprecated
DYLD_LIBRARY_PATH: "/home/hamza/arachni-1.2.1-0.5.7.1/bin/../system/usr/lib"
LOGNAME: hamza.ijaz
XDG_SESSION_DESKTOP: ubuntu
GEM_PATH: "/home/hamza/arachni-1.2.1-0.5.7.1/bin/../system/gems"
DBUS_SESSION_BUS_ADDRESS: unix:abstract=/tmp/dbus-LBxQQzNfbw
XDG_DATA_DIRS: "/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop"
QT4_IM_MODULE: xim
LESSOPEN: "| /usr/bin/lesspipe %s"
INSTANCE: ''
DISPLAY: ":0"
XDG_RUNTIME_DIR: "/run/user/149000059"
GTK_IM_MODULE: ibus
XDG_CURRENT_DESKTOP: Unity
RUBYLIB: "/home/hamza/arachni-1.2.1-0.5.7.1/system/gems/gems/bundler-1.10.6/lib:/home/hamza/arachni-1.2.1-0.5.7.1/bin/../system/usr/lib/ruby:/home/hamza/arachni-1.2.1-0.5.7.1/bin/../system/usr/lib/ruby/site_ruby/2.2.0:/home/hamza/arachni-1.2.1-0.5.7.1/bin/../system/usr/lib/ruby/2.2.0:/home/hamza/arachni-1.2.1-0.5.7.1/bin/../system/usr/lib/ruby/2.2.0/x86_64-linux:/home/hamza/arachni-1.2.1-0.5.7.1/bin/../system/usr/lib/ruby/site_ruby/2.2.0/x86_64-linux"
RUBY_VERSION: ruby-2.2.2
LESSCLOSE: "/usr/bin/lesspipe %s %s"
XAUTHORITY: "/home/hamza/.Xauthority"
RACK_ENV: development
BUNDLE_GEMFILE: "/home/hamza/arachni-1.2.1-0.5.7.1/system/arachni-ui-web/Gemfile"
_ORIGINAL_GEM_PATH: "/home/hamza/arachni-1.2.1-0.5.7.1/bin/../system/gems"
BUNDLE_BIN_PATH: "/home/hamza/arachni-1.2.1-0.5.7.1/system/gems/gems/bundler-1.10.6/bin/bundle"
RUBYOPT: "-rbundler/setup"
MANPATH: "/home/hamza/arachni-1.2.1-0.5.7.1/system/gems/gems/kramdown-1.4.1/man"
BUNDLE_ORIG_MANPATH: "/home/hamza/arachni-1.2.1-0.5.7.1/system/gems/gems/kramdown-1.4.1/man"
--------------------------------------------------------------------------------
OPTIONS:
---
input:
  values:
    "(?i-mx:name)": arachni_name
    "(?i-mx:user)": arachni_user
    "(?i-mx:usr)": arachni_user
    "(?i-mx:pass)": 5543!%arachni_secret
    "(?i-mx:txt)": arachni_text
    "(?i-mx:num)": '132'
    "(?i-mx:amount)": '100'
    "(?i-mx:mail)": arachni@email.gr
    "(?i-mx:account)": '12'
    "(?i-mx:id)": '1'
  default_values:
    "(?i-mx:name)": arachni_name
    "(?i-mx:user)": arachni_user
    "(?i-mx:usr)": arachni_user
    "(?i-mx:pass)": 5543!%arachni_secret
    "(?i-mx:txt)": arachni_text
    "(?i-mx:num)": '132'
    "(?i-mx:amount)": '100'
    "(?i-mx:mail)": arachni@email.gr
    "(?i-mx:account)": '12'
    "(?i-mx:id)": '1'
  without_defaults: true
  force: false
datastore:
  token: 5b81d679b86c72c7505f8a757616dc2c
browser_cluster:
  wait_for_elements: {}
  pool_size: 6
  job_timeout: 25
  worker_time_to_live: 100
  ignore_images: false
  screen_width: 1600
  screen_height: 1200
http:
  user_agent: Arachni/v1.2.1
  request_timeout: 10000
  request_redirect_limit: 5
  request_concurrency: 20
  request_queue_size: 100
  request_headers: {}
  response_max_size: 500000
  cookies: {}
session: {}
scope:
  redundant_path_patterns: {}
  dom_depth_limit: 5
  exclude_path_patterns: []
  exclude_content_patterns: []
  include_path_patterns: []
  restrict_paths: []
  extend_paths: []
  url_rewrites: {}
audit:
  parameter_values: true
  exclude_vector_patterns: []
  include_vector_patterns: []
  link_templates: []
  links: true
  forms: true
  cookies: true
  jsons: true
  xmls: true
checks:
- allowed_methods
- backdoors
- backup_directories
- backup_files
- captcha
- code_injection
- code_injection_php_input_wrapper
- code_injection_timing
- common_admin_interfaces
- common_directories
- common_files
- cookie_set_for_parent_domain
- credit_card
- csrf
- cvs_svn_users
- directory_listing
- emails
- file_inclusion
- form_upload
- hsts
- htaccess_limit
- html_objects
- http_only_cookies
- http_put
- insecure_client_access_policy
- insecure_cookies
- insecure_cors_policy
- insecure_cross_domain_policy_access
- insecure_cross_domain_policy_headers
- interesting_responses
- ldap_injection
- localstart_asp
- mixed_resource
- no_sql_injection
- no_sql_injection_differential
- origin_spoof_access_restriction_bypass
- os_cmd_injection
- os_cmd_injection_timing
- password_autocomplete
- path_traversal
- private_ip
- response_splitting
- rfi
- session_fixation
- source_code_disclosure
- sql_injection
- sql_injection_differential
- sql_injection_timing
- ssn
- trainer
- unencrypted_password_forms
- unvalidated_redirect
- unvalidated_redirect_dom
- webdav
- x_frame_options
- xpath_injection
- xss
- xss_dom
- xss_dom_inputs
- xss_dom_script_context
- xss_event
- xss_path
- xss_script_context
- xss_tag
- xst
- xxe
platforms: []
plugins:
  autothrottle: {}
  discovery: {}
  healthmap: {}
  timing_attacks: {}
  uniformity: {}
no_fingerprinting: false
authorized_by: 
url: http://webscantest.com/
--------------------------------------------------------------------------------
[2017-10-10 17:09:33 +0500] Could not spawn browser process.
[2017-10-10 17:09:33 +0500] Fontconfig error: Cannot load default config file

[2017-10-10 17:09:33 +0500] [Arachni::Browser::Error::Spawn] Could not start the browser process.
[2017-10-10 17:09:33 +0500] /home/hamza/arachni-1.2.1-0.5.7.1/system/gems/gems/arachni-1.2.1/lib/arachni/browser.rb:1090:in `spawn_browser'
[2017-10-10 17:09:33 +0500] /home/hamza/arachni-1.2.1-0.5.7.1/system/gems/gems/arachni-1.2.1/lib/arachni/browser.rb:1001:in `selenium'
[2017-10-10 17:09:33 +0500] /home/hamza/arachni-1.2.1-0.5.7.1/system/gems/gems/arachni-1.2.1/lib/arachni/browser.rb:181:in `initialize'
[2017-10-10 17:09:33 +0500] /home/hamza/arachni-1.2.1-0.5.7.1/system/gems/gems/arachni-1.2.1/lib/arachni/browser_cluster/worker.rb:59:in `initialize'
[2017-10-10 17:09:33 +0500] /home/hamza/arachni-1.2.1-0.5.7.1/system/gems/gems/arachni-1.2.1/lib/arachni/browser_cluster.rb:418:in `new'
[2017-10-10 17:09:33 +0500] /home/hamza/arachni-1.2.1-0.5.7.1/system/gems/gems/arachni-1.2.1/lib/arachni/browser_cluster.rb:418:in `block in initialize_workers'
[2017-10-10 17:09:33 +0500] /home/hamza/arachni-1.2.1-0.5.7.1/system/gems/gems/arachni-1.2.1/lib/arachni/browser_cluster.rb:417:in `times'
[2017-10-10 17:09:33 +0500] /home/hamza/arachni-1.2.1-0.5.7.1/system/gems/gems/arachni-1.2.1/lib/arachni/browser_cluster.rb:417:in `initialize_workers'
[2017-10-10 17:09:33 +0500] /home/hamza/arachni-1.2.1-0.5.7.1/system/gems/gems/arachni-1.2.1/lib/arachni/browser_cluster.rb:122:in `initialize'
[2017-10-10 17:09:33 +0500] /home/hamza/arachni-1.2.1-0.5.7.1/system/gems/gems/arachni-1.2.1/lib/arachni/framework/parts/browser.rb:33:in `new'
[2017-10-10 17:09:33 +0500] /home/hamza/arachni-1.2.1-0.5.7.1/system/gems/gems/arachni-1.2.1/lib/arachni/framework/parts/browser.rb:33:in `block in browser_cluster'
[2017-10-10 17:09:33 +0500] /home/hamza/arachni-1.2.1-0.5.7.1/system/usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
[2017-10-10 17:09:33 +0500] /home/hamza/arachni-1.2.1-0.5.7.1/system/gems/gems/arachni-1.2.1/lib/arachni/framework/parts/browser.rb:28:in `browser_cluster'
[2017-10-10 17:09:33 +0500] /home/hamza/arachni-1.2.1-0.5.7.1/system/gems/gems/arachni-1.2.1/lib/arachni/framework/parts/audit.rb:168:in `audit'
[2017-10-10 17:09:33 +0500] /home/hamza/arachni-1.2.1-0.5.7.1/system/gems/gems/arachni-1.2.1/lib/arachni/framework.rb:120:in `block in run'
[2017-10-10 17:09:33 +0500] /home/hamza/arachni-1.2.1-0.5.7.1/system/gems/gems/arachni-1.2.1/lib/arachni/utilities.rb:408:in `call'
[2017-10-10 17:09:33 +0500] /home/hamza/arachni-1.2.1-0.5.7.1/system/gems/gems/arachni-1.2.1/lib/arachni/utilities.rb:408:in `exception_jail'
[2017-10-10 17:09:33 +0500] /home/hamza/arachni-1.2.1-0.5.7.1/system/gems/gems/arachni-1.2.1/lib/arachni/framework.rb:120:in `run'
[2017-10-10 17:09:33 +0500] /home/hamza/arachni-1.2.1-0.5.7.1/system/gems/gems/arachni-1.2.1/lib/arachni/rpc/server/framework.rb:154:in `block in run'
[2017-10-10 17:09:33 +0500] 
[2017-10-10 17:09:33 +0500] Parent:
[2017-10-10 17:09:33 +0500] Arachni::RPC::Server::Framework
[2017-10-10 17:09:33 +0500] 
[2017-10-10 17:09:33 +0500] Block:
[2017-10-10 17:09:33 +0500] #<Proc:0x00000004104c18@/home/hamza/arachni-1.2.1-0.5.7.1/system/gems/gems/arachni-1.2.1/lib/arachni/framework.rb:120>
[2017-10-10 17:09:33 +0500] 
[2017-10-10 17:09:33 +0500] Caller:
[2017-10-10 17:09:33 +0500] /home/hamza/arachni-1.2.1-0.5.7.1/system/gems/gems/arachni-1.2.1/lib/arachni/utilities.rb:408:in `exception_jail'
[2017-10-10 17:09:33 +0500] /home/hamza/arachni-1.2.1-0.5.7.1/system/gems/gems/arachni-1.2.1/lib/arachni/framework.rb:120:in `run'
[2017-10-10 17:09:33 +0500] /home/hamza/arachni-1.2.1-0.5.7.1/system/gems/gems/arachni-1.2.1/lib/arachni/rpc/server/framework.rb:154:in `block in run'
[2017-10-10 17:09:33 +0500] --------------------------------------------------------------------------------
```

**Comment by Zapotek** [comment]
Your version of Arachni is really old, please try the current one.
