### ISSUE TITLE
Healthmap error

### ISSUE THREAD

**Issue by Viss** [Arachni/arachni#922]
I attempted to scan another customer site, and this error was displayed, and the scan stopped. Not entirely sure what I can do about it, if anything.

```
2017-10-13 14:09:46 -0400 --------------------------------------------------------------------------------
ENV:
---
CPLUS_INCLUDE_PATH: "/root/tools/arachni/bin/../system/usr/include"
XDG_SESSION_ID: '3'
rvm_bin_path: "/usr/local/rvm/bin"
GEM_HOME: "/root/tools/arachni/system/gems"
TERM: screen
SHELL: "/bin/bash"
IRBRC: "/root/tools/arachni/bin/../system/usr/lib/ruby/.irbrc"
LIBRARY_PATH: "/root/tools/arachni/bin/../system/usr/lib:/usr/lib:/usr/local/lib"
BYOBU_CONFIG_DIR: "/root/.byobu"
BYOBU_TTY: "/dev/pts/0"
MY_RUBY_HOME: "/root/tools/arachni/bin/../system/usr/lib/ruby"
SSH_TTY: "/dev/pts/0"
BYOBU_READLINK: readlink
USER: root
LD_LIBRARY_PATH: "/root/tools/arachni/bin/../system/usr/lib:/usr/lib:/usr/local/lib"
LS_COLORS: 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
BYOBU_RUN_DIR: "/dev/shm/byobu-root-9jxoFhuR"
_system_type: Linux
MSF_DATABASE_CONFIG: "/root/tools/msf/database.yml"
rvm_path: "/usr/local/rvm"
BYOBU_DISTRO: Ubuntu
BYOBU_DATE: "%Y-%m-%d "
TMUX: "/tmp/tmux-0/default,1952,1"
rvm_prefix: "/usr/local"
BYOBU_BACKEND: tmux
BYOBU_SED: sed
FONTCONFIG_PATH: "/root/tools/arachni/bin/../system/home/arachni/.fonts"
MAIL: "/var/mail/root"
PATH: "/root/tools/arachni/system/gems/bin:/root/tools/arachni/bin/../system/../bin:/root/tools/arachni/bin/../system/usr/bin:/root/tools/arachni/bin/../system/gems/bin:/usr/local/rvm/gems/ruby-2.1.6/bin:/usr/local/rvm/gems/ruby-2.1.6@global/bin:/usr/local/rvm/rubies/ruby-2.1.6/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/rvm/bin"
C_INCLUDE_PATH: "/root/tools/arachni/bin/../system/usr/include"
BYOBU_DARK: "#333333"
PWD: "/root/tools/arachni/bin"
BYOBU_ULIMIT: ulimit
ARACHNI_WEBUI_LOGDIR: "/root/tools/arachni/bin/../system/logs/webui"
LANG: en_US.UTF-8
ARACHNI_FRAMEWORK_LOGDIR: "/root/tools/arachni/bin/../system/logs/framework"
_system_arch: x86_64
TMUX_PANE: "%11"
_system_version: '16.04'
BYOBU_PYTHON: python2
BYOBU_CHARMAP: UTF-8
BYOBU_WINDOW_NAME: "-"
rvm_version: 1.26.11 (latest)
SHLVL: '3'
HOME: "/root/tools/arachni/bin/../system/home/arachni"
RAILS_ENV: production
BYOBU_LIGHT: "#EEEEEE"
LOGNAME: root
GEM_PATH: "/root/tools/arachni/bin/../system/gems"
BYOBU_PAGER: sensible-pager
BYOBU_ACCENT: "#75507B"
LESSOPEN: "| /usr/bin/lesspipe %s"
GOPATH: "/root/go"
BYOBU_PREFIX: "/usr"
XDG_RUNTIME_DIR: "/run/user/0"
BYOBU_HIGHLIGHT: "#DD4814"
RUBYLIB: "/root/tools/arachni/system/gems/gems/bundler-1.14.6/lib:/root/tools/arachni/bin/../system/usr/lib/ruby:/root/tools/arachni/bin/../system/usr/lib/ruby/site_ruby/2.2.0:/root/tools/arachni/bin/../system/usr/lib/ruby/2.2.0:/root/tools/arachni/bin/../system/usr/lib/ruby/2.2.0/x86_64-linux:/root/tools/arachni/bin/../system/usr/lib/ruby/site_ruby/2.2.0/x86_64-linux"
RUBY_VERSION: ruby-2.2.3
LESSCLOSE: "/usr/bin/lesspipe %s %s"
_system_name: Ubuntu
BYOBU_TIME: "%H:%M:%S"
RACK_ENV: development
BUNDLE_GEMFILE: "/root/tools/arachni/system/arachni-ui-web/Gemfile"
BUNDLER_ORIG_PATH: "/root/tools/arachni/bin/../system/../bin:/root/tools/arachni/bin/../system/usr/bin:/root/tools/arachni/bin/../system/gems/bin:/usr/local/rvm/gems/ruby-2.1.6/bin:/usr/local/rvm/gems/ruby-2.1.6@global/bin:/usr/local/rvm/rubies/ruby-2.1.6/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/rvm/bin"
BUNDLER_ORIG_GEM_PATH: "/root/tools/arachni/bin/../system/gems"
BUNDLE_BIN_PATH: "/root/tools/arachni/system/gems/gems/bundler-1.14.6/exe/bundle"
BUNDLER_VERSION: 1.14.6
RUBYOPT: "-rbundler/setup"
MANPATH: "/root/tools/arachni/system/gems/gems/kramdown-1.4.1/man"
BUNDLER_ORIG_MANPATH: "/root/tools/arachni/system/gems/gems/kramdown-1.4.1/man"
--------------------------------------------------------------------------------
OPTIONS:
datastore:
  token: 8c5c3df53d1ae976132809e3b3342f18
audit:
  parameter_values: true
  exclude_vector_patterns: []
  include_vector_patterns: []
  link_templates: []
  links: true
  forms: true
  cookies: true
  headers: false
  with_both_http_methods: false
  cookies_extensively: false
  jsons: true
  xmls: true
  ui_forms: true
  ui_inputs: true
session: {}
scope:
  redundant_path_patterns: {}
  dom_depth_limit: 5
  exclude_file_extensions:
  - "[]"
  exclude_path_patterns: []
  exclude_content_patterns: []
  include_path_patterns: []
  restrict_paths: []
  extend_paths: []
  url_rewrites: {}
  include_subdomains: false
  exclude_binaries: false
  https_only: false
input:
  values:
    "(?i-mx:name)": arachni_name
    "(?i-mx:user)": arachni_user
    "(?i-mx:usr)": arachni_user
    "(?i-mx:pass)": 5543!%arachni_secret
    "(?i-mx:txt)": arachni_text
    "(?i-mx:num)": '132'
    "(?i-mx:amount)": '100'
    "(?i-mx:mail)": arachni@email.gr
    "(?i-mx:account)": '12'
    "(?i-mx:id)": '1'
  default_values:
    name: arachni_name
    user: arachni_user
    usr: arachni_user
    pass: 5543!%arachni_secret
    txt: arachni_text
    num: '132'
    amount: '100'
    mail: arachni@email.gr
    account: '12'
    id: '1'
  without_defaults: true
  force: false
http:
  user_agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like
    Gecko) Chrome/45.0.2454.93 Safari/537.36
  request_timeout: 10000
  request_redirect_limit: 5
  request_concurrency: 20
  request_queue_size: 100
  request_headers: {}
  response_max_size: 500000
  cookies: {}
  authentication_type: auto
browser_cluster:
  local_storage: {}
  wait_for_elements: {}
  pool_size: 6
  job_timeout: 10
  worker_time_to_live: 100
  ignore_images: false
  screen_width: 1600
  screen_height: 1200
checks:
- code_injection
- code_injection_php_input_wrapper
- code_injection_timing
- csrf
- file_inclusion
- ldap_injection
- no_sql_injection
- no_sql_injection_differential
- os_cmd_injection
- os_cmd_injection_timing
- path_traversal
- response_splitting
- rfi
- session_fixation
- source_code_disclosure
- sql_injection
- sql_injection_differential
- sql_injection_timing
- trainer
- unvalidated_redirect
- unvalidated_redirect_dom
- xpath_injection
- xss
- xss_dom
- xss_dom_script_context
- xss_event
- xss_path
- xss_script_context
- xss_tag
- xxe
- allowed_methods
- backdoors
- backup_directories
- backup_files
- captcha
- common_admin_interfaces
- common_directories
- common_files
- cookie_set_for_parent_domain
- credit_card
- cvs_svn_users
- directory_listing
- emails
- form_upload
- hsts
- htaccess_limit
- html_objects
- http_only_cookies
- http_put
- insecure_client_access_policy
- insecure_cookies
- insecure_cors_policy
- insecure_cross_domain_policy_access
- insecure_cross_domain_policy_headers
- interesting_responses
- localstart_asp
- mixed_resource
- origin_spoof_access_restriction_bypass
- password_autocomplete
- private_ip
- ssn
- unencrypted_password_forms
- webdav
- x_frame_options
- xst
platforms: []
plugins:
  autothrottle: 
  discovery: 
  healthmap: 
  timing_attacks: 
  uniformity: 
no_fingerprinting: false
authorized_by: 
url: xxxxxx
[2017-10-13 14:09:46 -0400] Could not merge plugin results for plugin 'healthmap', will only use local ones: undefined local variable or method `h' for Arachni::Plugins::HealthMap:Class
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-1.5.1/components/plugins/defaults/healthmap.rb:67:in `block in merge'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-1.5.1/components/plugins/defaults/healthmap.rb:67:in `each'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-1.5.1/components/plugins/defaults/healthmap.rb:67:in `sort_by'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-1.5.1/components/plugins/defaults/healthmap.rb:67:in `merge'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-1.5.1/lib/arachni/data/plugins.rb:68:in `block in merge_results'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-1.5.1/lib/arachni/data/plugins.rb:64:in `each'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-1.5.1/lib/arachni/data/plugins.rb:64:in `merge_results'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-1.5.1/lib/arachni/rpc/server/plugin/manager.rb:47:in `merge_results'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-1.5.1/lib/arachni/rpc/server/framework.rb:203:in `block in clean_up'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:182:in `call'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:182:in `block in map'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:227:in `call'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:227:in `block in inject'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:95:in `call'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:95:in `block in each'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:119:in `call'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:119:in `block (2 levels) in each'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:213:in `call'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:213:in `block (2 levels) in inject'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:168:in `call'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:168:in `block (2 levels) in map'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-1.5.1/lib/arachni/rpc/server/framework.rb:198:in `call'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-1.5.1/lib/arachni/rpc/server/framework.rb:198:in `block (3 levels) in clean_up'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-rpc-0.2.1.4/lib/arachni/rpc/client/handler.rb:77:in `call'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-rpc-0.2.1.4/lib/arachni/rpc/client/handler.rb:77:in `receive_response'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-rpc-0.2.1.4/lib/arachni/rpc/client/handler.rb:137:in `receive_object'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-rpc-0.2.1.4/lib/arachni/rpc/protocol.rb:52:in `on_read'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/connection.rb:261:in `block in _read'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/connection/error.rb:26:in `call'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/connection/error.rb:26:in `translate'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/connection.rb:260:in `_read'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor/connection/tls.rb:115:in `_read'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:574:in `each'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:574:in `block in process_connections'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:574:in `process_connections'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:316:in `block in run'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:307:in `loop'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:307:in `run'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-1.5.1/lib/arachni/rpc/server/instance.rb:152:in `initialize'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-1.5.1/lib/arachni/processes/executables/instance.rb:13:in `new'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-1.5.1/lib/arachni/processes/executables/instance.rb:13:in `<top (required)>'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-1.5.1/lib/arachni/processes/executables/base.rb:50:in `load'
[2017-10-13 14:09:46 -0400] /root/tools/arachni/system/gems/gems/arachni-1.5.1/lib/arachni/processes/executables/base.rb:50:in `<main>'
```

**Comment by Zapotek** [comment]
This bug has been fixes in the nightlies.
Also, you may want to avoid using multiple instances for single scans, I'm re-evaluating this feature's stability and for this reason it will be removed from the new engine.
