### ISSUE TITLE
arachni scan failing - ECONNREFUSED to 127.0.0.1

### ISSUE THREAD

**Issue by mgoins01** [Arachni/arachni#929]
Have installed arachni on a machine running in AWS, based on the kali Linux ami & am seeing the scan hang when attempting to kick off a base scan.  The scan hangs attempting to start the browser cluster.  Security groups in AWS are wide-open outbound, and restricted to ssh from a specific IP address.  As a test, we added the loopback address to the security group, to no effect.  Scan times out at 10 minutes.  Have a similar setup running on a laptop, under VMPlayer that runs fine.  Am ideas what's hanging it up?

Thanks.

Arachni version info:  Arachni 1.5.1 (ruby 2.3.3p222) [x86_64-linux-gnu]

From the command line:
---------------------------
root@kali:/# arachni http://<website.com>
 [~] No checks were specified, loading all.
 [~] No element audit options were specified, will audit links, forms, cookies, UI inputs, UI forms, JSONs and XMLs.

 [*] Initializing...
 [*] Preparing plugins...
 [*] ... done.
 [*] BrowserCluster: Initializing 6 browsers...

Contents of the log file:
--------------------------------------------------------------------------------
[2017-10-31 12:43:21 +0000] [utilities#exception_jail:428] [Errno::ECONNREFUSED] Failed to open TCP connection to 127.0.0.1:10710 (Connection refused - connect(2) for "127.0.0.1" port 10710)
[2017-10-31 12:43:21 +0000] [utilities#exception_jail:428] /usr/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect'
[2017-10-31 12:43:21 +0000] [utilities#exception_jail:428] /usr/lib/ruby/2.3.0/net/http.rb:879:in `block in connect'
[2017-10-31 12:43:21 +0000] [utilities#exception_jail:428] /usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
[2017-10-31 12:43:21 +0000] [utilities#exception_jail:428] /usr/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
[2017-10-31 12:43:21 +0000] [utilities#exception_jail:428] /usr/lib/ruby/2.3.0/net/http.rb:878:in `connect'
[2017-10-31 12:43:21 +0000] [utilities#exception_jail:428] /usr/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
[2017-10-31 12:43:21 +0000] [utilities#exception_jail:428] /usr/lib/ruby/2.3.0/net/http.rb:852:in `start'
[2017-10-31 12:43:21 +0000] [utilities#exception_jail:428] /usr/lib/ruby/2.3.0/net/http.rb:1398:in `request'
[2017-10-31 12:43:21 +0000] [utilities#exception_jail:428] /usr/share/arachni/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/default.rb:103:in `response_for'
[2017-10-31 12:43:21 +0000] [utilities#exception_jail:428] /usr/share/arachni/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/default.rb:57:in `request'
[2017-10-31 12:43:21 +0000] [utilities#exception_jail:428] /usr/share/arachni/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
[2017-10-31 12:43:21 +0000] [utilities#exception_jail:428] /usr/share/arachni/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/bridge.rb:653:in `raw_execute'
[2017-10-31 12:43:21 +0000] [utilities#exception_jail:428] /usr/share/arachni/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/bridge.rb:124:in `create_session'
[2017-10-31 12:43:21 +0000] [utilities#exception_jail:428] /usr/share/arachni/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/bridge.rb:88:in `initialize'
[2017-10-31 12:43:21 +0000] [utilities#exception_jail:428] /usr/share/arachni/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/common/driver.rb:57:in `new'
[2017-10-31 12:43:21 +0000] [utilities#exception_jail:428] /usr/share/arachni/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/common/driver.rb:57:in `for'
[2017-10-31 12:43:21 +0000] [utilities#exception_jail:428] /usr/share/arachni/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver.rb:82:in `for'
[2017-10-31 12:43:21 +0000] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/browser.rb:1109:in `selenium'
[2017-10-31 12:43:21 +0000] [utilities#exception_jail:428] /usr/share/arachni/lib/arachni/browser.rb:1337:in `start_webdriver'

**Comment by Zapotek** [comment]
This is an env issue, please use the [official packages](http://www.arachni-scanner.com/download/).
