### ISSUE TITLE
Run in background without a TTY failed!

### ISSUE THREAD

**Issue by aiddroid** [Arachni/arachni#980]
command:
```shell
 /home/work/odp/webroot/arachni/bin/arachni_multi 'http://10.121.201.71/login.php?username=user&password=123456' '--checks' '*,-x_frame_options,-interesting_responses,-captcha,-credit_card,-unencrypted_password_forms,-trainer,-sql*' --http-request-redirect-limit 0 --http-request-concurrency 30 --scope-page-limit 1 --browser-cluster-pool-size 0 --browser-cluster-ignore-images --timeout  "00:30:00"  --report-save-path /tmp
```

Same command runs well on SecureCRT shell, but error in supervisord, error logs here:
```shell
[-] [ui/cli/rpc/client/instance#run:81] [Errno::EINVAL] Invalid argument
[-] [ui/cli/rpc/client/instance#run:81] /home/work/odp/webroot/arachni/system/gems/gems/arachni-1.5.1/lib/arachni/support/mixins/terminal.rb:45:in `winsize'
[-] [ui/cli/rpc/client/instance#run:81] /home/work/odp/webroot/arachni/system/gems/gems/arachni-1.5.1/lib/arachni/support/mixins/terminal.rb:45:in `empty_screen'
[-] [ui/cli/rpc/client/instance#run:81] /home/work/odp/webroot/arachni/system/gems/gems/arachni-1.5.1/ui/cli/rpc/client/instance.rb:93:in `print_progress'
[-] [ui/cli/rpc/client/instance#run:81] /home/work/odp/webroot/arachni/system/gems/gems/arachni-1.5.1/ui/cli/rpc/client/instance.rb:75:in `run'
[-] [ui/cli/rpc/client/instance#run:81] /home/work/odp/webroot/arachni/system/gems/gems/arachni-1.5.1/ui/cli/rpc/client/local.rb:54:in `initialize'
[-] [ui/cli/rpc/client/instance#run:81] /home/work/odp/webroot/arachni/system/gems/gems/arachni-1.5.1/bin/arachni_multi:18:in `new'
[-] [ui/cli/rpc/client/instance#run:81] /home/work/odp/webroot/arachni/system/gems/gems/arachni-1.5.1/bin/arachni_multi:18:in `<top (required)>'
[-] [ui/cli/rpc/client/instance#run:81] /home/work/odp/webroot/arachni/bin/../system/arachni-ui-web/bin/arachni_multi:17:in `load'
[-] [ui/cli/rpc/client/instance#run:81] /home/work/odp/webroot/arachni/bin/../system/arachni-ui-web/bin/arachni_multi:17:in `<main>'
```

**Comment by aiddroid** [comment]
cannot call in background with out TTY, error messages here:
```shell
[2018-05-23 10:33:37 +0800] [ui/cli/rpc/client/instance#run:81] [Errno::ENOTTY] Inappropriate ioctl for device
[2018-05-23 10:33:37 +0800] [ui/cli/rpc/client/instance#run:81] /home/work/odp/webroot/arachni/system/gems/gems/arachni-1.5.1/lib/arachni/support/mixins/terminal.rb:45:in `winsize'
[2018-05-23 10:33:37 +0800] [ui/cli/rpc/client/instance#run:81] /home/work/odp/webroot/arachni/system/gems/gems/arachni-1.5.1/lib/arachni/support/mixins/terminal.rb:45:in `empty_screen'
[2018-05-23 10:33:37 +0800] [ui/cli/rpc/client/instance#run:81] /home/work/odp/webroot/arachni/system/gems/gems/arachni-1.5.1/ui/cli/rpc/client/instance.rb:93:in `print_progress'
[2018-05-23 10:33:37 +0800] [ui/cli/rpc/client/instance#run:81] /home/work/odp/webroot/arachni/system/gems/gems/arachni-1.5.1/ui/cli/rpc/client/instance.rb:75:in `run'
[2018-05-23 10:33:37 +0800] [ui/cli/rpc/client/instance#run:81] /home/work/odp/webroot/arachni/system/gems/gems/arachni-1.5.1/ui/cli/rpc/client/remote.rb:77:in `initialize'
[2018-05-23 10:33:37 +0800] [ui/cli/rpc/client/instance#run:81] /home/work/odp/webroot/arachni/system/gems/gems/arachni-1.5.1/bin/arachni_rpc:18:in `new'
[2018-05-23 10:33:37 +0800] [ui/cli/rpc/client/instance#run:81] /home/work/odp/webroot/arachni/system/gems/gems/arachni-1.5.1/bin/arachni_rpc:18:in `<top (required)>'
[2018-05-23 10:33:37 +0800] [ui/cli/rpc/client/instance#run:81] /home/work/odp/webroot/arachni/bin/../system/arachni-ui-web/bin/arachni_rpc:17:in `load'
[2018-05-23 10:33:37 +0800] [ui/cli/rpc/client/instance#run:81] /home/work/odp/webroot/arachni/bin/../system/arachni-ui-web/bin/arachni_rpc:17:in `<main>'
```
