### ISSUE TITLE
Create profile to save the times error

### ISSUE THREAD

**Issue by wanglei409** [Arachni/arachni#993]
**We're sorry, but something went wrong.**

log:

Completed 500 Internal Server Error in 593ms (ActiveRecord: 3.4ms)

ActionView::Template::Error (incompatible character encodings: ASCII-8BIT and UTF-8):
    21:             <div style="height: 0px;" id="<%= shortname %>" class="accordion-body collapse">
    22:                 <div class="accordion-inner">
    23:                     <div class="markdown">
    24:                         <%= m info[:description] %>
    25:                     </div>
    26:                 </div>
    27: 
  app/views/shared/_components_accordion_form.html.erb:24:in `block in _app_views_shared__components_accordion_form_html_erb___1437635184087118229_70323213890200'
  app/views/shared/_components_accordion_form.html.erb:2:in `each'
  app/views/shared/_components_accordion_form.html.erb:2:in `_app_views_shared__components_accordion_form_html_erb___1437635184087118229_70323213890200'
  app/views/shared/_components_twin_accordion_form.html.erb:17:in `_app_views_shared__components_twin_accordion_form_html_erb__2567399386315752510_70323213912220'
  app/views/profiles/_form.html.erb:500:in `block in _app_views_profiles__form_html_erb___4565235717641897762_52336520'
  app/views/profiles/_form.html.erb:1:in `_app_views_profiles__form_html_erb___4565235717641897762_52336520'
  app/views/profiles/new.html.erb:15:in `_app_views_profiles_new_html_erb__2605606699131849020_42311700'
  app/controllers/profiles_controller.rb:118:in `block (2 levels) in create'
  app/controllers/profiles_controller.rb:111:in `create'

**Comment by wanglei409** [comment]
why?
