### ISSUE TITLE
 This scan has the logged the following errors (if something looks like a bug feel free to report it)

### ISSUE THREAD

**Issue by vanessah24** [Arachni/arachni#997]
2018-07-09 15:42:25 +0200 --------------------------------------------------------------------------------
ENV:
---
ALLUSERSPROFILE: C:\ProgramData
APPDATA: C:\Users\honfov\AppData\Roaming
ARACHNI_FRAMEWORK_LOGDIR: Q:\arachni-1.5.1-0.5.12-windows-x86_64\system\\logs\framework
ARACHNI_WEBUI_LOGDIR: Q:\arachni-1.5.1-0.5.12-windows-x86_64\system\\logs\webui
BUNDLER_ORIG_GEM_PATH: Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0;C:/Users/honfov/.gem/ruby/2.2.0
BUNDLER_ORIG_MANPATH: Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/kramdown-1.4.1/man
BUNDLER_VERSION: 1.14.6
BUNDLE_BIN_PATH: Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/exe/bundle
BUNDLE_GEMFILE: Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/arachni-ui-web/Gemfile
CATALINA_HOME: D:\workspaces\tomcat\apache-tomcat-8.5.31
CommonProgramFiles: C:\Program Files\Common Files
CommonProgramFiles(x86): C:\Program Files (x86)\Common Files
CommonProgramW6432: C:\Program Files\Common Files
COMPUTERNAME: DK14-P-1101
ComSpec: C:\WINDOWS\system32\cmd.exe
ENV_ROOT: Q:\arachni-1.5.1-0.5.12-windows-x86_64\system\
ENV_RUBY_BIN: Q:\arachni-1.5.1-0.5.12-windows-x86_64\system\ruby\bin
ENV_WEBUI_BIN: Q:\arachni-1.5.1-0.5.12-windows-x86_64\system\arachni-ui-web\bin
ENV_WEBUI_ROOT: Q:\arachni-1.5.1-0.5.12-windows-x86_64\system\arachni-ui-web
FP_NO_HOST_CHECK: 'NO'
GEM_HOME: Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0
GEM_PATH: Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0;C:/Users/honfov/.gem/ruby/2.2.0
HOME: C:/Users/honfov
HOMEDRIVE: 'C:'
HOMEPATH: "\\Users\\honfov"
JAVA_HOME: C:\Program Files\Java\jdk1.8.0_144
LOCALAPPDATA: C:\Users\honfov\AppData\Local
LOGONSERVER: "\\\\P-W8-DCO-001-P"
MANPATH: Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/kramdown-1.4.1/man
NUMBER_OF_PROCESSORS: '2'
OS: Windows_NT
Path: Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/bin;Q:\arachni-1.5.1-0.5.12-windows-x86_64\system\ruby\bin;C:\Applis\Oracle\12.1.0.2\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program
  Files\Java\jdk1.6.0_45\bin;C:\Program Files\Java\jdk1.6.0_45\jre\bin;C:\Program
  Files (x86)\Java\jdk1.6.0_45\bin;C:\Program Files (x86)\Java\jdk1.6.0_45\jre\bin;C:\Applis\Perl64\site\bin;C:\Applis\Perl64\bin;C:\Perl64\site\bin;C:\Perl64\bin;C:\Applis\site\bin;C:\Applis\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\C:\Program
  Files\Java\jdk1.7.0_80\jre\bin;C:\Program Files\Java\jdk1.7.0_80\bin;C:\Program
  Files\Java\jdk1.7.0_80\jre\bin;;C:\Program Files (x86)\GNU\GnuPG\pub;C:\Program
  Files\TortoiseSVN\binC:\Program Files\Java\jdk1.7.0_80\jre\bin
pathExists: '0 '
PATHEXT: ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC"
PROCESSOR_ARCHITECTURE: AMD64
PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
PROCESSOR_LEVEL: '6'
PROCESSOR_REVISION: 3c03
ProgramData: C:\ProgramData
ProgramFiles: C:\Program Files
ProgramFiles(x86): C:\Program Files (x86)
ProgramW6432: C:\Program Files
PROMPT: "$P$G"
PSModulePath: C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\
PUBLIC: C:\Users\Public
RACK_ENV: development
RAILS_ENV: production
RUBYLIB: Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib
RUBYOPT: "-rbundler/setup"
SESSIONNAME: Console
SystemDrive: 'C:'
SystemRoot: C:\WINDOWS
TEMP: C:\Users\honfov\AppData\Local\Temp
TMP: C:\Users\honfov\AppData\Local\Temp
UATDATA: C:\Windows\CCM\UATData\D9F8C395-CAB8-491d-B8AC-179A1FE1BE77
USER: honfov
USERDNSDOMAIN: PARTECIS.LAN
USERDOMAIN: PARTECIS
USERNAME: honfov
USERPROFILE: Q:\arachni-1.5.1-0.5.12-windows-x86_64\system\home
windir: C:\WINDOWS
--------------------------------------------------------------------------------
OPTIONS:
---
audit:
  parameter_values: true
  exclude_vector_patterns: []
  include_vector_patterns: []
  link_templates: []
  links: true
  forms: true
  cookies: false
  headers: false
  with_both_http_methods: false
  cookies_extensively: false
  jsons: false
  xmls: false
  ui_forms: true
  ui_inputs: true
browser_cluster:
  local_storage: {}
  wait_for_elements: {}
  pool_size: 6
  job_timeout: 10
  worker_time_to_live: 100
  ignore_images: false
  screen_width: 1600
  screen_height: 1200
datastore:
  token: 34f910f9439bf2b938a9affd74d34faf
http:
  user_agent: Arachni/v1.5.1
  request_timeout: 10000
  request_redirect_limit: 5
  request_concurrency: 2
  request_queue_size: 100
  request_headers: {}
  response_max_size: 500000
  cookies: {}
  authentication_type: auto
input:
  values: {}
  default_values:
    name: arachni_name
    user: arachni_user
    usr: arachni_user
    pass: 5543!%arachni_secret
    txt: arachni_text
    num: '132'
    amount: '100'
    mail: arachni@email.gr
    account: '12'
    id: '1'
  without_defaults: true
  force: false
scope:
  redundant_path_patterns: {}
  dom_depth_limit: 5
  exclude_file_extensions: []
  exclude_path_patterns: []
  exclude_content_patterns: []
  include_path_patterns:
  - https://dev1-mon5.partecis.lan/proxya/login.*
  restrict_paths: []
  extend_paths: []
  url_rewrites: {}
  include_subdomains: false
  exclude_binaries: false
  https_only: true
session:
  check_url: https://dev1-mon5.partecis.lan/proxya/sortie.do
  check_pattern: "(?-mix:\\/proxya\\/sortie.do)"
checks:
- xss
platforms: []
plugins:
  autologin:
    url: https://dev1-mon5.partecis.lan/proxya/login.jsp
    parameters: username=Serv_securityscan&password=M3nt@l1st3
    check: 'href="/proxya/sortie.do" '
no_fingerprinting: false
authorized_by: 
url: https://dev1-mon5.partecis.lan/proxya/
--------------------------------------------------------------------------------
[2018-07-09 15:42:25 +0200] [Arachni::Session::Error::FormNotFound] Login form could not be found with: {:url=>"https://dev1-mon5.partecis.lan/proxya/login.jsp", :inputs=>{"username"=>"Serv_securityscan", "password"=>"M3nt@l1st3"}}
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/session.rb:356:in `login_from_configuration'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/session.rb:245:in `block in login'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/utilities.rb:425:in `call'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/utilities.rb:425:in `exception_jail'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/session.rb:244:in `login'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/components/plugins/autologin.rb:37:in `prepare'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/plugin/manager.rb:69:in `block (2 levels) in run'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/utilities.rb:425:in `call'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/utilities.rb:425:in `exception_jail'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/plugin/manager.rb:68:in `block in run'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/plugin/manager.rb:65:in `each'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/plugin/manager.rb:65:in `run'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/framework/parts/state.rb:348:in `prepare'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/rpc/server/framework.rb:257:in `prepare'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/rpc/server/framework.rb:148:in `run'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/rpc/server/instance.rb:594:in `block in scan'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:95:in `call'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:95:in `block in each'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:106:in `call'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:106:in `block in each'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:241:in `call'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:241:in `block in spawn_workers'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.2/lib/arachni/reactor/tasks/base.rb:52:in `call'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.2/lib/arachni/reactor/tasks/base.rb:52:in `call_task'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.2/lib/arachni/reactor/tasks/one_off.rb:23:in `call'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.2/lib/arachni/reactor/tasks.rb:96:in `block in call'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.2/lib/arachni/reactor/tasks.rb:96:in `each'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.2/lib/arachni/reactor/tasks.rb:96:in `call'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:309:in `block in run'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:307:in `loop'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:307:in `run'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/rpc/server/instance.rb:152:in `initialize'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/processes/executables/instance.rb:13:in `new'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/processes/executables/instance.rb:13:in `<top (required)>'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/processes/executables/base.rb:50:in `load'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/processes/executables/base.rb:50:in `<main>'
[2018-07-09 15:42:25 +0200] 
[2018-07-09 15:42:25 +0200] Parent:
[2018-07-09 15:42:25 +0200] Arachni::Session
[2018-07-09 15:42:25 +0200] 
[2018-07-09 15:42:25 +0200] Block:
[2018-07-09 15:42:25 +0200] #<Proc:0x000000076f3f68@Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/session.rb:244>
[2018-07-09 15:42:25 +0200] 
[2018-07-09 15:42:25 +0200] Caller:
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/utilities.rb:425:in `exception_jail'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/session.rb:244:in `login'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/components/plugins/autologin.rb:37:in `prepare'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/plugin/manager.rb:69:in `block (2 levels) in run'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/utilities.rb:425:in `call'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/utilities.rb:425:in `exception_jail'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/plugin/manager.rb:68:in `block in run'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/plugin/manager.rb:65:in `each'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/plugin/manager.rb:65:in `run'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/framework/parts/state.rb:348:in `prepare'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/rpc/server/framework.rb:257:in `prepare'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/rpc/server/framework.rb:148:in `run'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/rpc/server/instance.rb:594:in `block in scan'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:95:in `call'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:95:in `block in each'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:106:in `call'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:106:in `block in each'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:241:in `call'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.2/lib/arachni/reactor/iterator.rb:241:in `block in spawn_workers'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.2/lib/arachni/reactor/tasks/base.rb:52:in `call'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.2/lib/arachni/reactor/tasks/base.rb:52:in `call_task'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.2/lib/arachni/reactor/tasks/one_off.rb:23:in `call'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.2/lib/arachni/reactor/tasks.rb:96:in `block in call'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.2/lib/arachni/reactor/tasks.rb:96:in `each'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.2/lib/arachni/reactor/tasks.rb:96:in `call'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:309:in `block in run'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:307:in `loop'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.2/lib/arachni/reactor.rb:307:in `run'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/rpc/server/instance.rb:152:in `initialize'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/processes/executables/instance.rb:13:in `new'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/processes/executables/instance.rb:13:in `<top (required)>'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/processes/executables/base.rb:50:in `load'
[2018-07-09 15:42:25 +0200] Q:/arachni-1.5.1-0.5.12-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/lib/arachni/processes/executables/base.rb:50:in `<main>'
[2018-07-09 15:42:25 +0200] --------------------------------------------------------------------------------
[2018-07-09 15:42:25 +0200] Could not find a form suiting the provided parameters.

**Comment by cagdaskarabag** [comment]
I have the same problem; arachni was using too much CPU (100%) and RAM (90%) 
and forced me to reboot my system. Actually I had to reboot it; because it was irresponsive.

**Comment by vanessah24** [comment]
Hello. Thanks for your answer. And how did you do finally?
Thanks.

**Comment by cagdaskarabag** [comment]
Hello, 

I was struggling with the same error and I guess I've found a temporary solution. (for my situation at least.)

I haven't inspected your logs throughly but in my case; I've found this line below. The healthmap plugin was the culprid. I've disabled it and scans are running without an issue.
My suggestion would be checking your plugin configurations. 

I hope this helps.

Cheers.

_[2018-07-10 14:43:54 +0200] Could not merge plugin results for plugin '**healthmap**', will only use local ones: undefined local variable or method `h' for Arachni::Plugins::HealthMap:Class
[2018-07-10 14:43:54 +0200] C:/Users/10056935/Documents/Workspace/arachni/arachni/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-1.5.1/components/plugins/defaults/healthmap.rb:67:in `block in merge'_
